### ISSUE TITLE
Indexing a datetime column is SLOW and makes performance 8x worse

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1005]
Clone this repo:

https://www.dolthub.com/repositories/dolthub/pa_mail_ballots_2020

Then add an index on the Date_of_Birth column;

`create index pa_dob on pa (Date_of_Birth);`

This takes a LONG time. Much longer than a full import of the table.

Here's the query I want to run: `select count(*) from pa where date_of_birth < '1935-11-05' and ballot_returned_date is not null;`

Timing before and after creating the index:

```
time dolt.exe sql -q "select count(*) from pa where date_of_birth < '1935-11-05' and ballot_returned_date is not null;"
+----------+
| COUNT(*) |
+----------+
| 126766   |
+----------+
dolt.exe sql -q   0.00s user 0.00s system 0% cpu 2.840 total
```

```
time dolt.exe sql -q "select count(*) from pa where date_of_birth < '1935-11-05' and ballot_returned_date is not null;"
+----------+
| COUNT(*) |
+----------+
| 126766   |
+----------+
dolt.exe sql -q   0.00s user 0.02s system 0% cpu 15.460 total
```

**Comment by zachmu** [comment]
I thought maybe parallelism was making this much worse, but nope. Parallelism turned off and it's slightly worse.

**Comment by KIC** [comment]
actually, I have a composed PK with varchar, date components and an insert is just not finishing.

**Comment by timsehn** [comment]
We've made a ton of changes here. Resolving. Reopen as a new issue.
