### ISSUE TITLE
Remove tag info from EXTRA in dolt SQL schema

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1023]
This breaks compatibility with standard mysql's info schema tables, and conflicts with AUTO_INCREMENT columns.

See https://github.com/dolthub/dolt/pull/1022

Main barrier to just ripping it out is current implementation of `dolt schema tags`

**Comment by Hydrocharged** [comment]
How does this break compatibility with standard MySQL's infoschema tables? From reading [the docs](https://dev.mysql.com/doc/refman/8.0/en/information-schema-columns-table.html) it seems like `EXTRA` is meant to hold additional information that doesn't belong in the other columns, which would include our tags. There can be multiple values in `EXTRA`.

**Comment by zachmu** [comment]
Makes it so we can't write information_schema tests that run on both Dolt and other implementation of go-mysql-server. Also the possibility that a client will read the EXTRA column and not know what to do with it.

**Comment by Hydrocharged** [comment]
We could have our tests check for `contains` rather than `equals`, but we can change it if we're worried about clients getting confused seeings an unknown `tags`.

**Comment by VinaiRachakonda** [comment]
So if we want to remove tags from the extra column does it make sense to add it to a different column in the information_schema?

**Comment by Hydrocharged** [comment]
From previous conversations that we've had, I think we were wanting to get rid of it from SQL world altogether, and just have `dolt schema tags` for when one wants tags.

As a general rule of thumb though, for the built in tables like those under `information_schema`, their schema should mimic what MySQL has. Adding additional columns may cause clients to break as they may expect a specific number of columns.

**Comment by VinaiRachakonda** [comment]
Should I go ahead and close this?

**Comment by VinaiRachakonda** [comment]
Closed!
