### ISSUE TITLE
`dolt version` needs --verbose flag that includes commit hash and timestamp

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1035]
Also the --help option does nothing for the `version` command.

**Comment by zachmu** [comment]
For SQL, this should be a single-row static system table `dolt_version`

**Comment by oscarbatori** [comment]
@zachmu is that the commit hash of the build?

**Comment by zachmu** [comment]
Yes, this needs the commit commit hash that dolt was built at, as well as the timestamp of that commit.

**Comment by Hydrocharged** [comment]
Just the commit hash of the most recently released version, or dev builds as well?

**Comment by zachmu** [comment]
I'm not sure what my original intent was here, you can get the commit hash from the release number since it's a tag on the repo. This doesn't add much of anything. It would be cool for development builds, but that's also where it's hardest to implement. Closing this.
