### ISSUE TITLE
[Bug Report] Segfault When Running LS From Self-Compiled Dolt

### ISSUE THREAD

**Issue by alexis-evelyn** [dolthub/dolt#1055]
Attempting to use Dolt on the Raspberry Pi causes a segfault both in the latest commit.

These are pretty much the same instructions from issue #1028, but slightly modified.

Instructions to Compile
---
CWD: /home/alexis
---
```zsh
# Install Go
wget https://golang.org/dl/go1.15.5.linux-armv6l.tar.gz
tar xvf go1.15.5.linux-armv6l.tar.gz
mv go /usr/local/
# This extracts go to ~/go/
# $GOPATH = /home/alexis/go
# $GOROOT = /usr/local/go

# Install Dolt
git clone https://github.com/dolthub/dolt
cd dolt/go/
git checkout v0.22.0 # I've tested both with this and skipping it (with a full reset and reinstall each time)
env CGO_ENABLED=0 go install ./cmd/dolt

# Test Clone
cd ~/test/existing/ # This repo was copied from my laptop
dolt ls
```

I performed these commands on my RPI 3 with the version `Linux Data 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux` as stated by `uname -a`.

# Latest Commit - Commit b555e9569cfc48130c1f5b55c4fc6dc311cc7479

The log can be found at https://hastebin.com/aroqizeguc.yaml

# Interesting Notes

I decided to try out my hand at debugging go executables and I've got this for you. So, I know the RPi 3 is a armhf type processor. I suspect this may be the same issue as #1028, but so far, the debugger doesn't seem to want to let me step into the method.

Edit: Here's the starting line for the crash with `dolt ls` on a Raspberry Pi 3 running Raspian. https://github.com/dolthub/dolt/blob/f6d7fdc75bdd4a935587030e1a70daaed073daa8/go/store/nbs/store.go#L429

These screenshots are in order of execution of the code.

### First
![Screen Shot 2020-11-28 at 08 35 16](https://user-images.githubusercontent.com/6305346/100516846-b5ad9d00-3154-11eb-9561-df8eecae31e6.png)

### Second
![Screen Shot 2020-11-28 at 08 24 58](https://user-images.githubusercontent.com/6305346/100516800-67000300-3154-11eb-81ee-8af6a88fe155.png)

### Third
![Screen Shot 2020-11-28 at 08 24 47](https://user-images.githubusercontent.com/6305346/100516799-66676c80-3154-11eb-8bd6-06981426f6c0.png)

**Comment by alexis-evelyn** [comment]
The debugger instance I setup with https://kupczynski.info/2020/05/17/remote-debug-go-code.html and this fork of Delve (https://github.com/puppywang/delve/commit/d75633f5b1e444a876ede6ef99b77d845c98f443)

Using `go build -gcflags="all=-N -l" ./cmd/dolt`

**Comment by alexis-evelyn** [comment]
I believe this is the reason this bugs out. https://github.com/golang/go/issues/23345 and the 3rd bug in the bugs section of https://golang.org/pkg/sync/atomic/

**Comment by alexis-evelyn** [comment]
As I couldn't sleep. I decided to comment out the line in the Atomic file just to see what happens and it magically works.

### Commented Out Line
![Screen Shot 2020-11-28 at 11 55 18](https://user-images.githubusercontent.com/6305346/100521289-b0f6e200-3170-11eb-9890-60e87eaeebfb.png)

### Demo of Dolt on RPi 3
![Screen Shot 2020-11-28 at 11 54 42](https://user-images.githubusercontent.com/6305346/100521307-cec44700-3170-11eb-8268-6197ea7469b3.png)

```go
*(*int)(nil) = 0 // crash on unaligned uint64
```

**Comment by VinaiRachakonda** [comment]
Dolt now works on a RPI as per this fun blog! https://www.dolthub.com/blog/2021-05-17-dolt-powered-bartender/
