### ISSUE TITLE
Support dolt commit -a

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1067]
This flag automatically stages all files (tables) in the working set before the commit.

**Comment by VinaiRachakonda** [comment]
To be clear, you are expecting this logic in the SQL side as well right?

**Comment by timsehn** [comment]
I think it may already exist in the CLI...but definitely yes

**Comment by zachmu** [comment]
Not in the CLI yet. Easy to add though.

**Comment by VinaiRachakonda** [comment]
Adding as a note to myself here that I need to update relevant docs (including --author)
