### ISSUE TITLE
Session variables need to be lower cased in config

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1091]
Ex SET @@myDB_head would not be loaded properly.

**Comment by VinaiRachakonda** [comment]
Bad session variables also result in an awful segfault.

**Comment by zachmu** [comment]
Segfault in https://github.com/dolthub/dolt/issues/1424. Should not happen.

**Comment by VinaiRachakonda** [comment]
Closed in https://github.com/dolthub/dolt/issues/1091
