### ISSUE TITLE
LIKE returns bad results

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1114]
https://www.dolthub.com/repositories/dolthub/us-president-precinct-results/query/master?q=SELECT+*%0AFROM+%60precincts%60+where+county+not+like+jurisdiction+%2B%27%25%27%0ALIMIT+200%3B%0A%0A%0A%0A%0A%0A%0A&active=Tables

Shows no results, which is not correct as seen by this group by:

https://www.dolthub.com/repositories/dolthub/us-president-precinct-results/query/master?q=SELECT+precinct%2C+state%2C+county%2C+count%28*%29+as+jur_count%0AFROM+%60precincts%60+%0Agroup+by+precinct%2C+state%2C+county%0AORDER+BY+COUNT%28*%29+desc%0A%0A%0A%0A%0A%0A%0A&active=Tables

**Comment by zachmu** [comment]
This now gives a different error: 

`unable to cast "PALM BEACH" of type string to float64`

**Comment by timsehn** [comment]
Looks like '+' is not a MySQL concept. This works though:

https://www.dolthub.com/repositories/dolthub/us-president-precinct-results/query/master?q=SELECT+*%0AFROM+%60precincts%60+where+county+not+like+concat%28jurisdiction%2C%27%25%27%29%3B&active=Tables

**Comment by timsehn** [comment]
Resolving.
