### ISSUE TITLE
Prevent multiple Dolt SQL servers starting for the same database

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#1122]
It is currently possible to start two Dolt SQL server processes for a single database, which could lead to lots of unpleasantness. We should use file system handles, or some other mechanism, to prevent this:
![Screen_Shot_2020-12-16_at_3 44 55_PM](https://user-images.githubusercontent.com/1596348/102420064-11ca4b00-3fb6-11eb-8895-27196fe0a06d.png)

**Comment by timsehn** [comment]
Resolved with the lock file.
