### ISSUE TITLE
Weird Index bug

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1131]
Repo: https://www.dolthub.com/repositories/dolthub/us-president-precinct-results

```
PS C:\Users\timse\dolthub\dolt\us-president-precinct-results> dolt branch -va
  alexis-evelyn-master                                  e6igatjb053c7g8nh9u3qcp4aoqv46co
* master                                                s71coggcibb1bgs6im4pforkff4dqq6h
  washington-2016                                       l7dln8ad3udkqtb98mbrlge4j3dhaohr
PS C:\Users\timse\dolthub\dolt\us-president-precinct-results> dolt sql -q "select * from precincts where county='WAKE COUNTY' and state='NORTH CAROLINA'"
unable to find field with index 1 in row of 0 columns
PS C:\Users\timse\dolthub\dolt\us-president-precinct-results> dolt sql -q "select count(*) from precincts where county='WAKE COUNTY'"
+----------+
| COUNT(*) |
+----------+
| 271      |
+----------+
```

All 271 rows should match.

**Comment by zachmu** [comment]
Small dolt repo to reproduce the issue:

https://www.dolthub.com/repositories/dolthub/dolt-issue-1131/

The saved query "Broken index lookup" will demonstrate the bug.

To trigger it, the following needs to be true:
1) There's an index lookup applied to the query
2) A column is selected that isn't part of the index used

Three working queries and one broken one are in the query catalog.

I think this has something to do with the recent change to allow covering indexes, but it isn't triggered by projection pushdown itself. Turning off projection pushdown in the analyzer rules still triggers the bug.

It's also possible that this has been broken for longer than the covering index changes, but I think that's less likely.

**Comment by zachmu** [comment]
Confirmed that this works correctly as of the last release, 4bad22669d2687691776c313a95683da23f5acfa.

Brian to investigate.

**Comment by zachmu** [comment]
This works now, but needs a regression test.
