### ISSUE TITLE
Match MySQL on execution order when missing ORDER BY clause

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#1135]
`UPDATE` is order dependent, so for a table:
```
+---+
| x |
+---+
| 1 |
| 2 |
| 3 |
+---+
```
The query `UPDATE tbl SET x = x + 1 ORDER BY x ASC` will cause duplicate key errors. Originally, dolt did not do key checks for `UPDATE` statements, only `INSERT` statements, so we'd never run into these issues.

As of https://github.com/dolthub/dolt/pull/1123, we now check for previous keys during `UPDATE`, which means a previously-working query can now fail. Normally this would be fine if the previous behavior were wrong and it was corrected, but this now raises a different issue. An example can be found in the `go-mysql-server` engine test [multiple triggers before and after insert, with precedes / follows](https://github.com/dolthub/go-mysql-server/blob/9b5cda56c9343c34230ae5ef076a2d4feef29861/enginetest/trigger_queries.go#L874):

```sql
CREATE TABLE a (x INT PRIMARY KEY);
CREATE TABLE b (y INT PRIMARY KEY);
INSERT INTO b VALUES (1), (3);
CREATE TRIGGER a1 BEFORE INSERT ON a FOR EACH ROW SET new.x = New.x + 1;
CREATE TRIGGER a2 BEFORE INSERT ON a FOR EACH ROW PRECEDES a1 SET new.x = New.x * 2;
CREATE TRIGGER a3 BEFORE INSERT ON a FOR EACH ROW PRECEDES a2 SET new.x = New.x - 5;
CREATE TRIGGER a4 BEFORE INSERT ON a FOR EACH ROW FOLLOWS a2 SET new.x = New.x * 3;
CREATE TRIGGER a5 AFTER INSERT ON a FOR EACH ROW UPDATE b SET y = y + 1;
CREATE TRIGGER a6 AFTER INSERT ON a FOR EACH ROW PRECEDES a5 UPDATE b SET y = y * 2;
CREATE TRIGGER a7 AFTER INSERT ON a FOR EACH ROW PRECEDES a6 UPDATE b SET y = y - 5;
CREATE TRIGGER a8 AFTER INSERT ON a FOR EACH ROW FOLLOWS a6 UPDATE b SET y = y * 3;
INSERT INTO a VALUES (1), (3);
```

This works in MySQL, as it interprets the `UPDATE` statements as though they had `ORDER BY y ASC` appended. Dolt, however, processes these in a non-deterministic order, so sometimes this will error, and other times it will not.

**Comment by zachmu** [comment]
This isn't something we can easily fix, because we're processing the update in parallel by design. We might need to enable this via a compatibility mode at some point to match the MySQL behavior exactly, but it will necessarily be a lot slower.
