### ISSUE TITLE
sql: querying repo tags from a system table

### ISSUE THREAD

**Issue by lucab** [dolthub/dolt#1137]
I'm running latest version of `dolt` (`0.22.7`) and scouting through `dolt ls --all` I didn't find hints about this.

It would nice to have some way, possibly via a system table, to introspect details about repository tags. In particular, I'd like to query:
 * tag<->commit linkage
 * latest tag as of given timestamp
 * tag changes over time

**Comment by timsehn** [comment]
Great idea. We'll get this in.

**Comment by zachmu** [comment]
System table should be called `dolt_tags` and have a schema similar to `dolt_log`

**Comment by theetrain** [comment]
May I humbly request to add a stored procedure that emulates `dolt tag`? That way I can add, list, or delete tags via SQL.

i.e.

```mysql
CALL DOLT_TAG("20220705-1"); --create tag for today
```

**Comment by timsehn** [comment]
This is in the current release by #3774
