### ISSUE TITLE
Import path writes types.Null to the storage layer

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1138]

**Comment by andrew-wm-arthur** [comment]
The bug _was_ that we were writing explicit Null values to the storage map, instead of doing Null compaction. `types.Null` should never show up in the storage map for non-primary key columns, instead we omit that tag:value pair from the tuple.

This line seems to indicate that we're still writing Nulls on the import path, but I haven't confirmed this by inspecting the resulting Map.
https://github.com/dolthub/dolt/blob/53c6723197f6b6fb1dde1b5be6c74133ba03a657/go/libraries/doltcore/table/untyped/csv/reader.go#L172

**Comment by zachmu** [comment]
@bheni can you fix this while you're in the import path? We should never be writing types.Null to databases

**Comment by timsehn** [comment]
Resolving due to staleness.
