### ISSUE TITLE
catch interrupts in dolt sql during query execution / output

### ISSUE THREAD

**Issue by rickducott** [dolthub/dolt#1155]
Setup:

```
dolt clone dolthub/us-president-precinct-results
cd us-president-precinct-results
dolt sql
```

I was exploring this dataset from the `dolt sql` shell and accidentally ran: `select * from precinct;`. While the query was executing and the output buffering, I hit `ctrl+c` to kill the query. This caused my `dolt sql` shell to exit. 

When you enter the `dolt sql` shell it is configured to catch interrupts, it must just not be configured to catch them while it is buffering output.

**Comment by zachmu** [comment]
Confirmed this is still a problem. SIGINT during query execution should kill the query, not the entire shell.
