### ISSUE TITLE
Dolt autoincrement table loses last autoincrement value

### ISSUE THREAD

**Issue by chrisfw** [dolthub/dolt#1197]
Dolt (v 0.22.9) table created with autoincrement seems to have reset the last value so a new insert attempt fails with duplicate primary key error.  I am not sure how/when this occurred, nor how to reset the current value so a new insert without id specified is correct.  Inserts with a specified value for id continue to work ok. 
```
ocimodel> insert into boot_volume_attachment_lifecycle_state(displayname) values('Testing');
duplicate primary key given: (1)
```
```
ocimodel> SHOW CREATE TABLE boot_volume_attachment_lifecycle_state;
+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                                  | Create Table                                                                                                                                                                               |
+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| boot_volume_attachment_lifecycle_state | CREATE TABLE `boot_volume_attachment_lifecycle_state` (
  `id` tinyint NOT NULL AUTO_INCREMENT,
  `displayname` varchar(100),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
```

**Comment by andrew-wm-arthur** [comment]
Do you mind sharing the contents of the table, and description of what operations you ran? I'll try to repro

**Comment by chrisfw** [comment]
I can actually give you the repo if you want.  Regardless, I can definitely provide the scripts to create and populate it.

**Comment by andrew-wm-arthur** [comment]
Both would be helpful!

**Comment by chrisfw** [comment]
[ocimodel.tar.gz](https://github.com/dolthub/dolt/files/5784405/ocimodel.tar.gz)

CREATE TABLE boot_volume_attachment_lifecycle_state (id tinyint PRIMARY KEY AUTO_INCREMENT, displayname VARCHAR(100));
insert into boot_volume_attachment_lifecycle_state(displayname) values('UnknownEnumValue');
insert into boot_volume_attachment_lifecycle_state(displayname) values('Attached');
insert into boot_volume_attachment_lifecycle_state(displayname) values('Attaching');
insert into boot_volume_attachment_lifecycle_state(displayname) values('Detached');
insert into boot_volume_attachment_lifecycle_state(displayname) values('Detaching');

**Comment by chrisfw** [comment]
Hi @andrew-wm-arthur 
Is there anything additional you would like me to provide in order to troubleshoot this issue?
Thanks,
Chris

**Comment by andrew-wm-arthur** [comment]
Hey @chrisfw 
I haven't been able to reproduce locally. From looking at the `.sqlhistory` log, I'm wondering if it might be a Foreign Key issue. Do you have the full sql script that you used to create the database?

**Comment by chrisfw** [comment]
Sure thing @andrew-wm-arthur.  Here you go.  I can _sort of_ understand this dupe key error when doing an insert on a table with an auto_increment pk on a new branch (which happened to me this morning), but for this issue submission everything was done on master.  Can you point me to any docs regarding the design of auto_increment and how the curr value is maintained?  Can it be set/reset via sql similar to the way auto increment works in SQL Server or sequences in Oracle or Postgres?     

[sql.txt](https://github.com/dolthub/dolt/files/5799109/sql.txt)

**Comment by andrew-wm-arthur** [comment]
@chrisfw `AUTO_INCREMENT` was designed to mimic MySQL's semantics. The current sequence value is persisted and updated with each change to a table with an `AUTO_INCREMENT` key. 
You can directly change the value of the `AUTO_INCREMENT` sequence with `ALTER TABLE boot_volume_attachment_lifecycle_state AUTO_INCREMENT = 42;`.
We currently don't have any docs for `AUTO_INCREMENT`, but this [blog post](https://www.dolthub.com/blog/2020-11-06-mysql-auto-increment/) does describe their design.

**Comment by andrew-wm-arthur** [comment]
Regarding multi-branch `AUTO_INCREMENT`, we don't have a good story for this yet. The intended design is for the state of the auto sequence to be replicated on a new branch. This leaves the problem of parallel inserts on each branch conflicting on merge. We've discussed potential designs for conflict-free merges, but haven't moved on implementing them yet.

**Comment by chrisfw** [comment]
@andrew-wm-arthur, thanks a lot for this info!  It is very helpful.
Regards,
Chris

**Comment by andrew-wm-arthur** [comment]
@chrisfw Ultimately the issue was that the `AUTO_INCREMENT` sequence was being reset during some schema changes. The issue is now patched.

**Comment by chrisfw** [comment]
Thanks Andy!  Glad to hear you identified it and it is resolved.  Much appreciated.

Regards,
Chris
