### ISSUE TITLE
"index already exists" when creating an index inside `CREATE TABLE IF NOT EXISTS` clause

### ISSUE THREAD

**Issue by tybug** [dolthub/dolt#1275]
repro using doltpy (normal dolt usage with `dolt sql -q` also reproduces though)

```python
from pathlib import Path

from doltpy.core import Dolt

dolt = Dolt.init(Path(__file__).parent)

for _ in range(2):
    dolt.sql("""
        CREATE TABLE IF NOT EXISTS some_table (
            id INT PRIMARY KEY,
            data INT NOT NULL,
            INDEX data_idx (data)
        );
    """)
```

error:
```
`data_idx` already exists as an index for this table
```

**Comment by oscarbatori** [comment]
Isn't the issue here that you are creating the same table twice?

**Comment by tybug** [comment]
the `IF NOT EXISTS` guard should mean that the index doesn't get created the second time around, though. It should see that the table doesn't exist and then not try to create the index again (note: I am no sql expert). If you run this query twice in a normal mysql database, it runs fine.

**Comment by oscarbatori** [comment]
I'm sorry, I totally missed that the first time out. This is Dolt issue I will move it to that queue and get it looked at. Thanks for bringing this to our attention.

**Comment by VinaiRachakonda** [comment]
After some testing this now looks solved. Marking as closed
