### ISSUE TITLE
dolt gc breaks sql-server inserts until restarted

### ISSUE THREAD

**Issue by eff917** [dolthub/dolt#1300]
server: dolt version 0.22.14
client: mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for Linux (x86_64) using readline 5.1

If `dolt gc` is run on the repository while `dolt sql-server` is running, insertions after `dolt gc` will fail until `sql-server` is restarted.

Steps to reproduce:

1. create repository
2. start sql-server
3. create tables, insert some data thorugh an sql client
4. disconnect client
5. on a separate terminal run `dolt gc` against the repository
6. try to insert data

Expected output is one of the following three:
1. `dolt gc` should fail while sql-server is running
2. It should issue a warning to restart any sql-servers pointed at this repository
3. trigger a reload for the sql-server

For now i think option 2 is the simplest, as the repository doesn't have to know if there is a sql-server serving the repo.

Actual output:
client:
```
mysql example_repo -h 127.0.0.1 -u root < insert.sql 
ERROR 1105 (HY000) at line 1: unknown error: corrupt manifest
```
server:
```
INFO: NewConnection: client 2
INFO: audit trail
TRACE: received query insert into books values (10903, 'XBRL in Nutshell 2',125, 109.99)
DEBUG: executing query
TRACE: returning OK result &{[] 1 0  [] <nil>}
INFO: ConnectionClosed: client 2
```
After sql-server restart the same insert works without any problems.

**Comment by oscarbatori** [comment]
That is currently a limitation of `dolt gc`, it's an offline operation, that is an operation where the results do not make it into a running Dolt SQL instance.

Your issue raises a product question for us around how communicate to our users the semantics of online/offline operations. Our current roadmap includes making versions of the CLI functions available in SQL (`DOLT_*`), but that doesn't do much to help here as it's not quite ready yet.

**Comment by timsehn** [comment]
Our solution here will be to lock out `dolt gc` from working when a `dolt sql-server` is running.

**Comment by zachmu** [comment]
We now prevent commands like `dolt gc` from executing when the server is running. There's an equivalent procedure `call dolt_gc()` you can run on a running server (currently in alpha release).
