### ISSUE TITLE
Foreign Keys don't travel with working set on `dolt checkout`

### ISSUE THREAD

**Issue by andy-wm-arthur** [dolthub/dolt#1310]
https://github.com/dolthub/dolt/blob/9c8ae0de518f2de0c44dcc697cc82d1c226d3cc1/bats/foreign-keys.bats#L1217

**Comment by timsehn** [comment]
@zachmu is this fixed with: #5732?

**Comment by zachmu** [comment]
No, but I'll go ahead and fix it while I'm in there.
