### ISSUE TITLE
When checking out via SQL, views don't automatically update

### ISSUE THREAD

**Issue by alexis-evelyn** [dolthub/dolt#1318]
From commit d71d37fc48bd93384dd80819e60eed3eb06c4666

```
➜  presidential-tweets git:(master) ✗ dolt version
dolt version 0.22.8
```

Commands

```
select dolt_checkout('test');
show tables;
-- Still see existing views from previous branch even though checked out initial commit with no tables (or views)
```

![Screen Shot 2021-02-09 at 20 42 26](https://user-images.githubusercontent.com/6305346/107452486-52a69200-6b17-11eb-8980-5979ec117dca.png)

**Comment by zachmu** [comment]
The right way to fix this is to not register views with the engine explicitly, but look them up with the database at analysis time like tables. Will fix this problem, and be better for other reasons.
