### ISSUE TITLE
You can delete every branch in Dolt from SQL

### ISSUE THREAD

**Issue by alexis-evelyn** [dolthub/dolt#1319]
From commit d71d37fc48bd93384dd80819e60eed3eb06c4666

```
➜  presidential-tweets git:(master) ✗ dolt version
dolt version 0.22.8
```

```
delete from dolt_branches;  -- Delete all branches
select * from dolt_branches;  -- See no branches
```

```
select dolt_checkout('master'); -- or (dolt checkout master) brings back the branch of choice
```

No real harm is done by clearing all branches (so long as you remember a branch's name). Just a funny bug. There may be more bugs as a result of trying to manipulate data while off a branch, but since Dolt claims to have already checked out said branch when you add it back, it may just be harmless (untested).

![Screen Shot 2021-02-09 at 20 48 31](https://user-images.githubusercontent.com/6305346/107453067-45d66e00-6b18-11eb-90c8-7a83403ca8e0.png)

**Comment by zachmu** [comment]
Thanks for the report, this is now fixed with a test.
