### ISSUE TITLE
wrong error message for query

### ISSUE THREAD

**Issue by saewitz** [dolthub/dolt#1330]
This query: `select if(election_year=2016, sum(votes), 0)-if(election_year=2020, sum(votes), 0)  from vote_tallies group by state` run on [this](https://www.dolthub.com/repositories/dolthub/us-president-precinct-results) database returns the error:

> table "vote_tallies" does not have column "election_year"

This error is not right because there is a column `election_year` in the database.

**Comment by timsehn** [comment]
Gonna resolve this. We have better names handling now.
