### ISSUE TITLE
Dolt Insert eating up all the memory on host via SQL Server but not CLI

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1343]
Repro:

I have updated everything here for reproducibility: https://git.nomics.world/cbenz/tests-benchmarks in particular:

- the script: https://git.nomics.world/cbenz/tests-benchmarks/-/blob/main/git-to-dolt.py
- the explanation with logs/mem profile: https://git.nomics.world/cbenz/tests-benchmarks/-/blob/main/git-to-dolt.md

**Comment by cbenz** [comment]
I modified my script to use the Dolt CLI via doltpy instead a `DoltSQLServerContext`, and the memory consumption stays low. Cf [this commit](https://git.nomics.world/cbenz/tests-benchmarks/-/commit/2f2468a6edf8496bd12514c53a0daf9e5c14bf2a) and the [updated explanation](https://git.nomics.world/cbenz/tests-benchmarks/-/blob/main/git-to-dolt.md#using-dolt-cli) with new mem profile.

**Comment by timsehn** [comment]
Interesting. Thanks for the repro. We'll get on it soon.

**Comment by zachmu** [comment]
We never dug into this memory problem, but memory usage in general (especially being able to configure max usage) is on our radar. I'm going to leave this open since you provided excellent profiles for us to dig into. Thanks for the report!

**Comment by timsehn** [comment]
Resolving this as we've made a ton of progress on memory usage
