### ISSUE TITLE
Dolt : SQL queries : via a JavaScript library!

### ISSUE THREAD

**Issue by ghost** [dolthub/dolt#1388]
Would you be able to develop a client-end (in browser) access-only JavaScript SQL library to work with Dolt.
Could pave the way for single-page web applications hosted via GitHub Pages accessing data using Dolt.

**Comment by timsehn** [comment]
What exactly do you want? You can access Dolt through a standard MySQL client. Here's the example Javascript code:

https://github.com/dolthub/dolt/blob/master/mysql-client-tests/node/index.js

**Comment by mayureshkathe** [comment]
I am requesting a JavaScript client library in access-only mode to facilitate issuing of SQL statements via a single-page webapp.

**Comment by mayureshkathe** [comment]
> What exactly do you want? You can access Dolt through a standard MySQL client. Here's the example Javascript code:
> https://github.com/dolthub/dolt/blob/master/mysql-client-tests/node/index.js

Also, you could extend the requested JavaScript web-client library to provide full (read-write-access) via a single-page webapp on your site authenticating GitHub users via GitHub OAuth, thereby providing not just a CLI client but also a web client to access your Dolt databases stored on GitHub/DoltHub.

**Comment by mayureshkathe** [comment]
Also, I'm not so sure about the performance metrics, but from a code reuse perspective; migrating your whole client code-base to JavaScript with options to produce versions for the Web and CLI (via Node.js) might become beneficial in the long-run.

**Comment by mayureshkathe** [comment]
And, if you do decide to go the full JavaScript path, remember to write it in TypeScript which provides conditional compilation to JavaScript modules (either for the Web or CLI via Node.js).

**Comment by zachmu** [comment]
Since the original requestor is not with us anymore to ask about this feature request, I'm going to close this out.
