### ISSUE TITLE
stray characters in `dolt diff` output

### ISSUE THREAD

**Issue by tybug** [dolthub/dolt#1389]
`dolt diff` is erroneously inserting the string `(MISSING)` in some columns of some rows.

* clone https://www.dolthub.com/repositories/tybug/national-course-catalog-us/doc/stray-characters-repro
* `dolt diff HEAD HEAD^1 > diff.diff`
* look for lines like `Blended/Hybrid up to 49%!W(MISSING)eb` - the actual content of this line is `Blended/Hybrid up to 49% Web`, as you can see with eg the following query: `select * from sections where section='82591' and course_id='ACCT 225'`.

**Comment by timsehn** [comment]
Huh. We had another bug report of that this and I thought @Brian Hendriks
<brian@dolthub.com> fixed it. Thanks for the repro. We'll get this fixed
for the next release.
