### ISSUE TITLE
document the format of s3 remote strings

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1390]
From discourse:

on the readme making it more clear that you need a dynamodb table and that you seem to need [].
and showing that you will likely need the --region flag

**Comment by bregydoc** [comment]
Hi, first, Dolt is an awesome project!

I'm trying to set a s3 bucket as remote for my dolt repository, but I cannot match the correct URL s3 format, I tried:

- aws://bucket.s3.amazonaws.com/database
- aws://dynamo-table:bucket/database
- aws://bucket/database

As @zachmu says above, the documentation isn't clear.

**Comment by timsehn** [comment]
We wrote this to cover this topic:

https://www.dolthub.com/blog/2021-07-19-remotes/

**Comment by addisonklinke** [comment]
Are nested prefixes supported? For example `aws://[dolt_dynamo_table:dolt_remotes_s3_storage]/menus/dinner`. I tried setting something like that up and I get

```
cloning aws://[dolt_dynamo_table:dolt_remotes_s3_storage]/menus/dinner`
error: failed to get remote db
cause: invalid database name
```

My company has several different remote repositories that should be logically grouped together, so we'd like to nest them under common prefix "folders" in S3

**Comment by reltuk** [comment]
@addisonklinke Thanks for the report! In looking at the code path and the history of the code, it looks like this restriction is an unintentional hold over from a previous implementation of AWS remotes. I just opened a PR (#2946) to remove the check.

I'll land it once it's reviewed and tested and this hopefully be supported in the next version of dolt :).

**Comment by addisonklinke** [comment]
@timsehn Did you still want a separate issue to track @reltuk's PR?

**Comment by timsehn** [comment]
No. We're good. 

Just next time, open a new issue. It's easy to miss comments on closed issues. I happen to keep a hawk-eye on my GitHub emails looking for names that are not us.
