### ISSUE TITLE
Option to use PostgreSQL Dialect (instead of MySQL)?

### ISSUE THREAD

**Issue by karlhorky** [dolthub/dolt#1396]
Hi there, first of all, thanks for Dolt, looks pretty cool! I've been toying with ideas of versioning database data with Git or similar for a while now, but my plans are all very fledgling still, nothing nearly as advanced as what you have here.

Do you have any plans to support SQL dialects other than MySQL for interacting with Dolt? Eg. would a PostgreSQL flavor be a possibility?

**Comment by ptman** [comment]
You should be able to sync from postgres https://docs.dolthub.com/guides/sql-sync#postgres

**Comment by timsehn** [comment]
So, to be clear, Dolt is built on a new storage engine. We support the
MySQL SQL standard but we have implemented it on our server. We don't use
any MySQL code in Dolt. What this effectively means is that existing MySQL
clients work with Dolt. You can see those tested in most languages here:

https://github.com/dolthub/dolt/tree/master/mysql-client-tests

So what we're talking about here is supporting a specific flavor of the SQL
dialect. We don't have plans to support multiple SQL dialects as the
benefits far outweigh the costs. We would love to build easy migration
paths from other databases which is what Paul is pointing at.

**Comment by 00LT00** [comment]
hi @timsehn ,do you want to support sync between dolt and databses(mysql,oracle,postgresql...) by golang? Look like it just have python API now.

**Comment by 00LT00** [comment]
Thanks @timsehn @oscarbatori . I'm just used to using golang. I don't mean anything.

**Comment by oscarbatori** [comment]
Closing this out.
