### ISSUE TITLE
Switching from current branch to current branch causes changes to appear lost

### ISSUE THREAD

**Issue by zennetizen** [dolthub/dolt#1399]
If I set @@dolttest_head to the current branch, all uncomitted changes are lost on the current connection, and it is reset to the head of the current branch until I reconnect.

What Happens:

```
MySQL [dolttest]> CREATE TABLE `my_test` (
    ->   `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    ->    PRIMARY KEY (`id`)
    -> );
Empty set (0.021 sec)

MySQL [dolttest]> show tables;
+---------+
| Table   |
+---------+
| my_test |
+---------+
1 row in set (0.001 sec)

MySQL [dolttest]> select @@dolttest_head;
+----------------------------------+
| @@dolttest_head                  |
+----------------------------------+
| b152b8ucihtos25pk8s5u1cfrjaetp5d |
+----------------------------------+
1 row in set (0.001 sec)

MySQL [dolttest]> SET @@dolttest_head = 'b152b8ucihtos25pk8s5u1cfrjaetp5d';
Query OK, 1 row affected (0.001 sec)

MySQL [dolttest]> show tables;
Empty set (0.001 sec)
```

Expected behaviour:

'show tables;' returns 'my_test'.

-----

DDL of my_test:
```
CREATE TABLE `my_test` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (`id`)
);
```

**Comment by zachmu** [comment]
Brian, I believe you figured out the issue here in Discord. Can you follow up here for posterity?

**Comment by bheni** [comment]
This really is an issue with the documentation.  We don't have this covered in any of our docs and we need to resolve that, but I'll give a quick overview here.

@@dbname_working is a hash that points to a root value.  It can hold changes that are not committed, and this is what gets updated when write queries modify the session.

@@dbname_head points to the latest commit hash.  You can set it to be a known commit hash.  You can set it from the value of the dolt_branches table, or you can set it using HASHOF('branch_name').  Setting the value of @@dbname_head has a side effect in that it also changes the value of @@dbname_working to be equal to the root value for the given commit.  This will overwrite changes to the working set. It is equivalent to doing a `dolt checkout branch_name` followed by `dolt reset --hard`.

From the code snippet in this issue:
```
MySQL [dolttest]> select @@dolttest_head;
+----------------------------------+
| @@dolttest_head                  |
+----------------------------------+
| b152b8ucihtos25pk8s5u1cfrjaetp5d |
+----------------------------------+
1 row in set (0.001 sec)

MySQL [dolttest]> SET @@dolttest_head = 'b152b8ucihtos25pk8s5u1cfrjaetp5d';
Query OK, 1 row affected (0.001 sec)
```

capturing the hash of @@dolttest_head and then using that to set the value of @@dolttest_head captures the hash of the current commit, and then set the current commit to be that same value.  The side effect of doing this is @@dolttest_working is overwritten with hash of the root value @@dolttest_head and the changes are lost.

If you really want to save the value of @@dolttest_working somewhere to be used later you can do that.  The one thing to look out for is that calls to `dolt gc` will delete data that isn't referenced in any commits.
