### ISSUE TITLE
Make dbeaver work with Dolt

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1404]
https://dbeaver.io/

According to user @ptman Dolt you can't connect to Dolt using dbeaver. We need to support the SQL statements it uses to connect.

**Comment by VinaiRachakonda** [comment]
Just tried this and dbeaver works on my end. @ptman can you tell me what error you are getting?

**Comment by ptman** [comment]
Tested using dbeaver 21.0.0 and dolt 0.24.1

**Comment by seralf** [comment]
HI I have the same issue as @ptman. 

The configuration used for testing is:
* dbeaver 21.0.0 
* dolt 0.24.1
* windows 10

**Comment by VinaiRachakonda** [comment]
@ptman @seralf I will take a look today and get back by EOD!

**Comment by VinaiRachakonda** [comment]
@ptman @seralf There are some missing queries the dbeaver runs that i'll implement today but I think you should still be able to get dbeaver up and running. Can you try running the sql-server with this config? It looks like dbeaver use multiple connections to run queries whereas dolt's default is to accept 1 at max.

**Comment by seralf** [comment]
Hi thank you, I tried with your configuration, with still no luck.

From the terminal, even with the "trace" level you provided, I see:

```bash
$ .dolt sql-server --config=config.yaml
Starting server with Config HP="localhost:3307"|U="root"|P=""|T="30000"|R="false"|L="info"
INFO: NewConnection: client 1
INFO: audit trail

```

**Comment by seralf** [comment]
I did again the same thing, in order to be sure I didn't miss something, maybe for copy+paste.

Anyway, same result:

```sh
$ dolt sql-server --config=config.yaml
Starting server with Config HP="localhost:3307"|U="root"|P=""|T="30000"|R="false"|L="trace"
INFO: NewConnection: client 1
INFO: audit trail
```

**Comment by VinaiRachakonda** [comment]
Making a mental note of the some queries that need to be implemented here:

SHOW VARIABLES
SHOW FULL TABLES w/ pattern
SHOW TABLE STATUS w/ pattern

**Comment by VinaiRachakonda** [comment]
Hi @seralf I just pushed in some changes into master that allows basic functionality with Dbeaver and Dolt sql-server. We usually do releases on Monday if you want to wait for that.

For dbeaver you'll need to have multiple connections running so that sample config I sent you earlier will be needed. If any thing breaks feel free to let us know!

**Comment by seralf** [comment]
Thank you @VinaiRachakonda I'll try it as soon as possible!

**Comment by VinaiRachakonda** [comment]
Hi @seralf, I'm going to close this issue for now. If any bug comes up please feel free to file a new issue.

**Comment by seralf** [comment]
> Hi @seralf, I'm going to close this issue for now. If any bug comes up please feel free to file a new issue.

HI @VinaiRachakonda I've tested it now on dbeaver, and the connection works!
If I double click on a table, I see the results as expected (I used the example IPtoCountry data), but if I try to execute the same SQL qery by the editor by myself, the connection seems to be freezed, without return any result back.

**Comment by VinaiRachakonda** [comment]
Hi @seralf, did you run it with the config I linked you above? Dbeaver uses multiple connection whereas Dolt uses one connection out of the box. Could you also posts the logs you received when executed the command? 
Thanks!

**Comment by seralf** [comment]
Hi you are right, for some reason in this test I was using the wrong configuration: I probably messed up the good one during some experiments when it did not work before... I replace the config again with the one attached in this thread and now it seems to work! :-)

I'll try it with some data, probably also from jdbc with java/scala and let you know in case of other problems.

thank you very much!
Alfredo

**Comment by VinaiRachakonda** [comment]
Glad to hear that Alfredo! I appreciate you taking the time to list out all of these problems. It's extremely valuable for us.
