### ISSUE TITLE
Dolt SQL shell backspace weirdness

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#141]
Repro: 

1. Make a sql query that spans more than one line
2. Execute the query
3. Hit up to go back to the query
4. Backspace over the line break
5. It starts to eat the results above and not actually backspace

**Comment by oscarbatori** [comment]
@zachmu do we have any intention to do anything about this?

**Comment by zachmu** [comment]
Yes, we need to fix this. It's a bug in the readline library we're using. Fix is to replace the readline library to one that doesn't have the bug, but that means rewriting large parts of our shell. There's a TODO in the code for this as well.

https://github.com/cockroachdb/cockroach/issues/15460

**Comment by zachmu** [comment]
The dolt SQL shell still could use some work, but this bug is no longer relevant (we remove newlines from queries before putting them in the query history)
