### ISSUE TITLE
Implement merge --squash

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1423]
Also via SQL with the `merge()` function.

This lets customers keep long-running user session branches, then merge them back to `master` while only generating a single `master` commit.

**Comment by zachmu** [comment]
I missed that this already exists on the command line. So we need two more things:

1) squash support in `MERGE()`
2) squash support in `DOLT_MERGE()`

**Comment by VinaiRachakonda** [comment]
This is due by end of month?

**Comment by zachmu** [comment]
Yup

**Comment by VinaiRachakonda** [comment]
on the docket

**Comment by VinaiRachakonda** [comment]
DOLT_MERGE already has squash parameter.

Will see what it is like for MERGE()
