### ISSUE TITLE
Selfhosted server?

### ISSUE THREAD

**Issue by brasilikum** [dolthub/dolt#1437]
Hey, I am exploring dolt. 
I was wondering if there is a way to selfhost the server?
Is the protocol documented somewhere?

**Comment by VinaiRachakonda** [comment]
Hi @brasilikum! Can you elaborate a little on what you mean by selfhost the server. Dolt comes in with a MySQL compatible Server built in with the command `dolt sql-server`

**Comment by timsehn** [comment]
So you can run a dolt SQL server as @VinaiRachakonda mentions. Here is the documentation for that:

https://docs.dolthub.com/interfaces/sql

We do not support running Dolt as a "remote" in the Git context. But we do support S3, GCS, and Filesystem based remotes as well as DoltHub. See documentation here:

https://docs.dolthub.com/interfaces/cli#dolt-remote

**Comment by brasilikum** [comment]
@timsehn Thank you, that was what I was looking for!

**Comment by d-sanderson** [comment]
Is dolt compatible with https://github.com/jeremydaly/serverless-mysql?

**Comment by oscarbatori** [comment]
@d-sanderson I am not sure, you're welcome to pop on our [Discord](https://discord.com/invite/RFwfYpu) and ask questions that arise if you're willing to give it a try. It's not something we have looked at though.
