### ISSUE TITLE
Implement EXISTS() function

### ISSUE THREAD

**Issue by zennetizen** [dolthub/dolt#1439]
As it stands, EXISTS() doesn't seem to work or exist in this specific case:

```
General error: 1105 unknown error: unsupported syntax: exists 
```

```
select exists(select * from `my_table` where `my_col` = 'my_value') as `exists`
```

**Comment by timsehn** [comment]
Thanks for the report. 

Moreover, it's not even listed as a possible function in our docs: 

https://docs.dolthub.com/interfaces/sql/sql-support/expressions-functions-operators

**Comment by timsehn** [comment]
Duplicate of https://github.com/dolthub/dolt/issues/2164 and it is fixed!
