### ISSUE TITLE
UUID function support

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1447]
Add support for the UUID functions in this blog post:

https://mysqlserverteam.com/mysql-8-0-uuid-support/

**Comment by Hydrocharged** [comment]
Easy starting point: https://pkg.go.dev/github.com/google/uuid#NewUUID

@VinaiRachakonda tag me for review when it’s ready

**Comment by VinaiRachakonda** [comment]
In pr in gms @Hydrocharged

**Comment by VinaiRachakonda** [comment]
Add support here: https://github.com/dolthub/go-mysql-server/pull/340
