### ISSUE TITLE
Requesting JavaScript client library

### ISSUE THREAD

**Issue by mayureshkathe** [dolthub/dolt#1460]
Would you consider developing a client library for Dolt written in JavaScript and released for usage via a web page?
This might seem like an extreme use-case, but consider the fact that if users are provided with a mechanism to access their data stored on GitHub/DoltHub in read-only mode, it could lead to an unforeseen jump in the usage of Dolt databases via single-page web-apps.
The more the number of people find value in using your technology and service via multiple methods, the more the number of people will gravitate toward using your service.

**Comment by VinaiRachakonda** [comment]
Hi @mayureshkathe! What type of functionality are you thinking that this client library would have? Dolt is a mysql database so any js orm should work with it fine. 

If you want to specific queries to something hosted on Dolthub we do have a remote api seen here: https://docs.dolthub.com/dolthub/getting-started#api-alpha Are you looking for additional functionality built on top of that?

**Comment by timsehn** [comment]
I'm pretty sure he wants a wrapper around this:

https://www.dolthub.com/blog/2020-08-21-dolthub-repository-apis/

You make a URI request and get back JSON. What sort of other Dolt goo would you like?

**Comment by mayureshkathe** [comment]
@timsehn your example is magical, and fits perfectly with my use-case. Also, @VinaiRachakonda the API when fully ready is what would be amazing. Hope it get's done soon enough. Thanks. 👍🏽

**Comment by VinaiRachakonda** [comment]
Glad to see this what you're lookin for @mayureshkathe. We're still a pretty small team so we ship features as users request. If you experiment with the api as is right now and find some functionality that you are looking for please let us know! For now, I think you should be able to get started with the current api
