### ISSUE TITLE
CREATE TABLE ... AS SELECT ... supports DISTINCT

### ISSUE THREAD

**Issue by ajbouh** [dolthub/dolt#1478]
The AST nodes returned by the latest version of `github.com/dolthub/vitess/go/vt/sqlparser` do not seem to properly capture the `SELECT` part of a `CREATE TABLE ... AS SELECT ...` statement.

Concretely, if you try to parse:

`CREATE TABLE items AS SELECT distinct item_id FROM orders;`

you seem to only see nodes for

`CREATE TABLE items`

Accordingly, the AST node formatter code I found in that same repository does not try to print the `AS SELECT ...` subexpression either.

Note that if it's a `VIEW` instead of a `TABLE`, the statement is parsed without losing information.

So this has a chance of working:
`CREATE VIEW items AS SELECT distinct item_id FROM orders;`

But this does not:
`CREATE TABLE items AS SELECT distinct item_id FROM orders;`

Apologies if this is not the right place to file this. The dolthub repo for its vitess fork does not have GitHub issues enabled.

**Comment by VinaiRachakonda** [comment]
Hi @ajbouh! This a great catch and flaw in our parser. We'll also need to make changes in go-mysql-server to implement the necessary functionality.

Do you need this fix implemented in the parser only? Or are you looking to run queries with this syntax as well?

**Comment by ajbouh** [comment]
Right now I'm just trying to use the parser directly.

My goal is to compute a (table-based) dependency graph of a set of SQL
statements so I can schedule them in a reasonable order.

There aren't many good (complete) options for golang SQL parsers out there.
:)

**Comment by VinaiRachakonda** [comment]
Got it, that makes sense. I can add to this the roadmap, it should be a pretty quick fix, but I'm not sure when we'll get to it. We'd also welcome contributions as well if that's something you'd like to do.

**Comment by ajbouh** [comment]
I've got something that works right now atop a different parser, so I'm not
blocked directly by this.

I don't have the bandwidth right now to extend the current dolthub
implementation, but I'm happy to test a PR and continue to provide test
cases and feedback  :)

I only recently discovered dolt while looking for a golang SQL parser.
Seems like a very interesting tool and is something I'll keep in mind for
my project's future roadmap.

**Comment by ajbouh** [comment]
@VinaiRachakonda you mentioned this being a quick fix. Can you give a short outline of what it would be?

**Comment by VinaiRachakonda** [comment]
Hi @ajbouh 

You'll need to submit a pull request to this repo -> https://github.com/dolthub/vitess

Look for our sqlparser in this file -> https://github.com/dolthub/vitess/blob/master/go/vt/sqlparser/sql.y

Then you'll need to

- Edit and compile to include your parsing logic
- Update ast.go to include that logic
- Add tests to parse_tests.go to ensure it compile properly

LMK if you have anymore questions

**Comment by zachmu** [comment]
This partially works now.

This works:

`create table counties2 as select * from counties;`

But this fails with a bad error message:

```
create table counties3 as select distinct name from counties;
attempted to resolve CREATE LIKE, expected `ResolvedTable` but received `*plan.Distinct`
```

**Comment by swaldman** [comment]
(i've hit this too, trying to build relations without duplicates from temporary tables using "create table ... as select distinct * from ...", getting "Error 1105: attempted to resolve CREATE LIKE, expected `ResolvedTable` but received `*plan.Distinct`")

**Comment by timsehn** [comment]
We'll look at this now.

**Comment by swaldman** [comment]
(i've worked around it with "create view tmpview_xxx as select distinct * from ...", then "create table xxx as select * from tmpview_xxx" then "drop tmpview_xxx". not ideal perhaps, but it works!)

**Comment by zachmu** [comment]
This is fixed in the latest release. Thanks for the report!

**Comment by swaldman** [comment]
(Thanks!)
