### ISSUE TITLE
Can I just config dolt just as git?

### ISSUE THREAD

**Issue by dongwangdw** [dolthub/dolt#1490]
There are some many commands for dolt. I want to have some simple aliases just like i did in git, like  checkout=co .etc.

I found a config file under .dolt. Not sure what is that? And I did not find such config in the repos.

**Comment by VinaiRachakonda** [comment]
Hi @dongwangdw your terminal should support aliasing commands themselves, we don't do that directly.

For example, I use zsh and I have a set of aliases that I exported to its config. So something like this works.

```alias dolt checkout = dolt co`. This can be saved in a .zsh file for zsh or .bash_rc for bash. 

We will support these types of cli shortcuts in the future, but it's not on our immediate roadmap.

**Comment by dongwangdw** [comment]
@VinaiRachakonda 
Thanks for response.
GOt this.
