### ISSUE TITLE
Can not use stored procedure with arguments

### ISSUE THREAD

**Issue by cipharius** [dolthub/dolt#1496]
Given the example setup:

```mysql
CREATE TABLE items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  item TEXT NOT NULL
);

CREATE PROCEDURE add_item (IN txt TEXT) MODIFIES SQL DATA
INSERT INTO items (item) VALUES (txt);

CALL add_item('A test item');
```

Dolt throws an error:
```
error on line 6 for query 

CREATE PROCEDURE add_item (IN txt TEXT) MODIFIES SQL DATA
INSERT INTO items (item) VALUES (txt): column "txt" could not be found in any table in scope
Error processing batch
```

I didn't get to test this on MySQL, but the documentation examples does not have any special syntax for accessing procedure parameters.
Did I miss something or is this a dolt bug?

**Comment by Hydrocharged** [comment]
This is definitely a Dolt bug! We do parameter name resolution for stored procedures in an analysis step that's independent from column name resolution. It looks like we're accidentally not looking into the `VALUES` of `INSERT` and `REPLACE` during the param name resolution. I'll get it fix out by the next release!

**Comment by Hydrocharged** [comment]
@cipharius This is fixed in the above PR!
