### ISSUE TITLE
Long term assurance and insurance against liquidation

### ISSUE THREAD

**Issue by kathe** [dolthub/dolt#1506]
I haven't understood Dolthub fully, so pardon my stupidity; where evident or otherwise.

The way I've understood it, the code for Dolt (the client) and DoltHub (the server) is fully open sourced.

Dolt users host their databases on DoltHub which is a privately owned environment, completely dependent upon the status of your business, just like GitHub.

But, GitHub is owned and operated by Microsoft, an organization with very deep pockets with an interest in using the public code repositories to feed their machine learning division which in turn provides the required algorithmic improvements to Microsoft's development environment tooling subsystems.

I don't think any of the above is true for the organization operating DoltHub and supporting it's development.
Given the same, even though I am working on a non-profit, non-government, open source project which cannot afford to host it's own infrastructure, I can very well rely on the longevity of GitHub's Pages (free static-page web hosting) offering but not on DoltHub.

There's been a history of open source projects backed by innovative businesses going bust and taking with them the entire layer of the stack that depended on them.

Is there any insurance that DoltHub could provide to prevent such an incident from occurring at any time in the future?
I guess not, then considering that Dolt is such a fantastic concept (and implementation) and since it's already open source, would your parent organization please consider rebuilding your hosting service (DoltHub) using a modular approach to provide hosting (public and private) of databases on GitHub, managed through a layer and API (written as a Node.JS application) hosted on your organization's infrastructure to prevent a user's application stack from going haywire (by allowing them to re-host that layer and API on a low-cost server of their choice) in case you go belly-up?

Then comes the issue of how your organization could generate revenues, because I guess currently you are only generating revenues from the private repositories above 1GB in size.

The business model could be slightly altered to providing mechanism to authenticate users accounts on DoltHub with GitHub accounts (probably OAuth) as the only way to access the Dolt databases stored on GitHub through your layer. You could then have tiers (free and commercial) based on permitted number of transactions being done through your layer. Yes, then there's nothing preventing people from just hosting their own servers, but isn't that the case currently true too?

**Comment by oscarbatori** [comment]
If you don't like DoltHub, you can host your Dolt database on AWS or GCP, or any machine of your choice. DoltHub is a collaboration and hosting platform for Dolt, and it's a way that DoltHub Inc. makes money. If you don't like DoltHub you can use Dolt, it's free and open source, and always will be, and figure out your own hosting solution.
