### ISSUE TITLE
Dolt should provide a way to ignore unsupported-but-known SQL commands instead of returning an error.

### ISSUE THREAD

**Issue by reltuk** [dolthub/dolt#151]
Lots of off-the-shelf SQL tools like data dumpers and import tools can be pointed at `dolt sql-server` and make credible progress. But they often fail when they try to use MySQL features that are currently unsupported by dolt, including things like:

* `BEGIN` / `COMMIT` / `ROLLBACK`
* `FOREIGN KEY`

Other unsupported syntax does seem to be silently ignored, including a `UNIQUE` column constraint in a `CREATE TABLE` and a `COLLATE` directive in a column constraint.

It seems like we should have two behaviors:
1. some things that are syntactically understood but not yet implemented are ignored, instead of erroring.
1. all things that are not implemented yet cause an error.

Mode 1 is useful for things like imports and interfacing with third-party tools, whereas mode 2 is useful when interacting with dolt intentionally and coming to know if the commands you are running are not having the effect you expect.

**Comment by OliverEvans96** [comment]
I'm trying to connect `dolt sql-server` to [Space Cloud](https://github.com/spaceuptech/space-cloud) to generate a GraphQL API. I believe it's trying to use `BEGIN` for some reason, and dolt is throwing an error:

```
$ dolt sql-server -u oliver -p potato -H 0.0.0.0 -l trace
Starting server with Config HP="0.0.0.0:3306"|U="oliver"|P="potato"|T="30000"|R="false"|L="trace"
INFO: NewConnection: client 1
INFO: audit trail
INFO: ConnectionClosed: client 1
INFO: NewConnection: client 2
INFO: audit trail
TRACE: received query START TRANSACTION
DEBUG: executing query
TRACE: Error running query START TRANSACTION: unsupported syntax: begin
INFO: ConnectionClosed: client 2
```

It would be great if this were somehow handled gracefully! In this particular case, I'm not sure what the `BEGIN` is for, so who knows whether it could really be safely ignored.
