### ISSUE TITLE
Support Compound `ALTER TABLE` statements

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1522]
This query does not parse:
```
ALTER TABLE circuits_circuittermination 
ADD COLUMN _cable_peer_type_id integer NULL , 
ADD CONSTRAINT circuits_circuitterm__cable_peer_type_id_bd122156_fk_django_co 
    FOREIGN KEY (_cable_peer_type_id) REFERENCES django_content_type(id)
```

**Comment by louisrigot** [comment]
I'm experiencing the same issue with Djagno

**Comment by Hydrocharged** [comment]
This is fixed in the tip of https://github.com/dolthub/go-mysql-server. https://github.com/dolthub/dolt/pull/1548 pulls in the latest `go-mysql-server` to Dolt, so this will be fixed as soon as the PR is merged.
