### ISSUE TITLE
Slow cloning from google storage

### ISSUE THREAD

**Issue by Focus** [dolthub/dolt#1530]
Hi there. Recently started experimenting with dolt in our ML pipelines, really enjoying the experience so far! Only issue I have noticed is that cloning a remote repository on google storage seems to take unreasonably long. Downloading the 100MB bucket with the dolt data takes a few seconds yet cloning the remote repository takes well over 10 minutes. Any ideas on how I can make this faster?

**Comment by VinaiRachakonda** [comment]
Thank you for your report @Focus! I will talk to my team member and get back to you on best practices. Feel free to hop in our discord if you want to get into more specifics -> https://discord.com/invite/RFwfYpu

**Comment by VinaiRachakonda** [comment]
Hi @Focus! This is a relatively untested/unoptimized path for us that we're eager to improve. Can you provide some additional details on you envision using Dolt and when you'll need faster support by? We can definitely make this faster we just need to schedule this into our roadmap. 

Thanks!

**Comment by bheni** [comment]
I've been running some tests this morning against aws, gcs, and dolthub remotes.  My test repo is a little over 600MB.

# GCS

```
time dolt clone gs://BUCKET gcs-test
cloning gs://BUCKET
156,487 of 156,487 chunks complete. 0 chunks being downloaded currently.

real    28m2.168s
user    0m21.606s
sys     0m15.104s
```

# AWS

```
time dolt clone aws://[DYNAMODB:S3_BUCKET]/irs-soi aws-test
cloning aws://[DYNAMODB:S3_BUCKET]/irs-soi
156,487 of 156,487 chunks complete. 0 chunks being downloaded currently.
real    17m32.72s 
user    0m15.60s 
sys     0m11.07s 
```

# Dolthub

```
~/datasets>time dolt clone https://doltremoteapi.beta.dolthub.com/Liquidata/irs-soi irs-soi2
cloning https://doltremoteapi.beta.dolthub.com/Liquidata/irs-soi
309,516 of 309,516 chunks complete. 0 chunks being downloaded currently.

real    0m43.057s
user    0m3.182s
sys     0m6.277s
```

**Comment by Focus** [comment]
Thanks @bheni for the fix. Can confirm now on master that the download time is lightning fast :)

**Comment by VinaiRachakonda** [comment]
@Focus We usually do releases every Monday so no need to build from Master past then.
