### ISSUE TITLE
Can I install dolt without sudo?

### ISSUE THREAD

**Issue by ws1088** [dolthub/dolt#1535]
I don't have root access and would like to try `dolt`...

**Comment by timsehn** [comment]
You can just download the appropriate binary and put `dolt` in your path.
Do you need specific instructions? Latest release binaries are at the
bottom of this page:

Release 0.25.1 · dolthub/dolt (github.com)
<https://github.com/dolthub/dolt/releases/tag/v0.25.1>

**Comment by ws1088** [comment]
thanks for the pointer. i was able to download it and at least print the help message. will now be able to test it out. thanks!
