### ISSUE TITLE
Django 3.2 MySQL backend fails with `function: 'convert_tz' not found`

### ISSUE THREAD

**Issue by louisrigot** [dolthub/dolt#1539]
Hi all! I started developing a Django application that uses Dolt as database (using the mysql backend). 

Django 3.1 worked OK, but after upgrading to Django 3.2 it fails with `function: 'convert_tz' not found`. This is due to the `mysql_server_data()`  function in `django.db.backends.mysql.base.DatabaseWrapper` that runs to check if certain MySQL are supported; which contains CONVERT_TZ, failing the query. The query also contains some SELECTS that return NULL and crash Django down the line. By subclassing the MySQL DatabaseWrapper and manually setting those values I got it to work again.

## Workaround:

`settings.py`
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'dolt': {
        'ENGINE': 'dolt_engine',
        'HOST': '127.0.0.1',
        'NAME': 'db',
        'USER': 'root',
        'PASSWORD': ''
    }
}
```

`dolt_engine/base.py`:
```python
from django.db.backends.mysql import base
from django.utils.functional import cached_property


class DatabaseWrapper(base.DatabaseWrapper):
    @cached_property
    def mysql_server_data(self):
        with self.temporary_connection() as cursor:
            cursor.execute("SELECT VERSION()")
            row = cursor.fetchone()
        return {
            'version': row[0],
            'sql_mode': None,
            'default_storage_engine': None,
            'sql_auto_is_null': False,
            'lower_case_table_names': False,
            'has_zoneinfo_database': False,
        }
```

**Comment by andrew-wm-arthur** [comment]
@louisrigot Thanks for the bug! Looks like we haven't implemented this function yet, but it should be straightforward

**Comment by zachmu** [comment]
@VinaiRachakonda, can you knock this out this week?

**Comment by VinaiRachakonda** [comment]
Ill get this in by Sunday

**Comment by VinaiRachakonda** [comment]
This was merged in about a month ago. Apologies for the last response
