### ISSUE TITLE
Possible Deadlock on Large Table Update

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1550]
Repro: `dolthub/hospital-price-transparency-v2` @ `p9v591drgp6ddpkiv9nhs632kdaenrp1`

Generate a CSV from `dolthub/hospital-price-transparency` @ `4ap6nlmiiidhjvne24obduebvamv9k5c` using:

`dolt sql -q "select code, npi_number, payer, 'UNSPECIFIED' as IP_OP, 'NONE' as caveat, 'NULL' as mode, price from prices" -r csv`

Import that CSV in `hospital-price-transparency-v2` using:

`dolt table import -pk code,npi_number,payer,IP_OP,caveat,mode -u prices ..\hospital-price-transparency\newprices.csv`

It deadlocked at 

`Rows Processed: 23134208, Additions: 23134208, Modifications: 0, Had No Effect: 0`

**Comment by zachmu** [comment]
Brian, can you attempt this with your new CSV import code to see if the problem has gone away or not?
