### ISSUE TITLE
CLI could remap www.dolthub.com to doloteremoteapi.dolthub.com during `dolt remote add` to improve usability

### ISSUE THREAD

**Issue by pramttl** [dolthub/dolt#1556]
### Issue

I cloned from a base repo initially. But I wanted to remap my origin to my fork of the repo. So I removed the existing origin with dolt remote remove and tried to add use `dolot remote add origin <url_of_the_fork_from_the_browser_tab>`. However, since the url in the browser is different from the API CNAME DOLT CLI uses (dolotremoteapi.) I ran into a bad url error when I tried to do a dolt push.

### Proposition / Potential Solution

dolt cli can remap if it sees a url with www.dolthub.com to doltremoteapi.dolthub.com, so that user does not see a bad url error if they accidentally use the repo url from their browser window.

**Comment by VinaiRachakonda** [comment]
@pramttl Thank you for this issue! This is a great suggestion and we will consider it for sure.

**Comment by timsehn** [comment]
If you just leave it off it is inferred. ie. just type `dolt clone dolthub/us-businesses`

**Comment by fulghum** [comment]
Great feature request @pramttl. 

@VinaiRachakonda just implemented support for DoltHub web URLs (https://github.com/dolthub/dolt/pull/3912), so I'll close out this issue. We also have another tracking issue with a slightly broader scope that also includes supporting web URLs for DoltLab databases (https://github.com/dolthub/dolt/issues/3874) in case that's interesting for you. 

Thanks again for taking the time to open this feature request. Please let us know if you have any other issues or feature requests for Dolt!
