### ISSUE TITLE
`INSERT IGNORE INTO` unsupported (Django 3.2 many-to-many)

### ISSUE THREAD

**Issue by louisrigot** [dolthub/dolt#1562]
When trying to save a many-to-many relation, Django 3.2 emits an `INSERT IGNORE INTO` statement that is unsupported by Dolt.

**Comment by VinaiRachakonda** [comment]
Thank you for letting us know @louisrigot! We'll jot this down and get back to you ASAP

**Comment by louisrigot** [comment]
A temporary workaround if [subclassing the built-in database backends](https://docs.djangoproject.com/en/3.2/ref/databases/#subclassing-the-built-in-database-backends) (not thoroughly tested):

```python
from django.db.backends.mysql import operations


class DatabaseOperations(operations.DatabaseOperations):
    def insert_statement(self, ignore_conflicts=False):
        return super().insert_statement(ignore_conflicts=False)
```

**Comment by VinaiRachakonda** [comment]
INSERT IGNORE INTO is now in master
