### ISSUE TITLE
Quickly find the latest commit that's touched a table

### ISSUE THREAD

**Issue by AmirAktify** [dolthub/dolt#1563]
So, let's say I have a table x that's gone through multiple commits and iterations in its life cycle. What would be the quickest way / query to find the _latest_ commit that's affected the table?

One can of course do a `git blame`, but anecdotally I've found that's slow to run and also possibly overkill for this case.

Now of course, this problem is trivial / near instance to solve if you have only a single table in your repository - just pick the most recent commit. But if you have multiple tables, it becomes not as immediately obvious.

**Comment by VinaiRachakonda** [comment]
You need to query one of our system tables cc: https://docs.dolthub.com/interfaces/sql/dolt-system-tables

For example if we have a table that we are tracking called `test`, we need to look at its edit history in the table `dolt_history_test`. -> https://docs.dolthub.com/interfaces/sql/dolt-system-tables#dolt_history_usdtablename

So the query will probably  something like this in your use case

```sql
SELECT commit_hash from dolt_history_test ORDER BY commit_date DESC LIMIT 1; 
```

**Comment by AmirAktify** [comment]
Thanks for looking into it! Manually testing, this doesn't work sadly. The commit hashes in `dolt_history_test` are a strict superset of those in `dolt blame test`. 

For instance, if your most recent commit U, you only changed `other_test`, but did not touch `test` at all. However, all the rows in `test` will still be appended to `dolt_history_test` for each row of `test`. (This also seems inefficient and can blow up table size if you have many tables in a repository, each with independent commits.....)
So if you run:
`select count(*) from dolt_history_test where commit_hash='U'`

You will get `len(test)` as the result, even though it wouldn't show up in `dolt blame test` at all.

**Comment by VinaiRachakonda** [comment]
Whoops @AmirAktify! You're correct. Sorry for leading you astray. Does `dolt blame test` not answer your question? I've also added this feature request that I think will be a better interface for adding this in the future #1564

**Comment by AmirAktify** [comment]
Thanks! 

`dolt blame test` does work, but it seems to take a very long time to run. Which I feel is unavoidable for what it does (a commit version history of every row).  

There's probably a faster way to do it for my use case - I tried looking at `dolt_diff_test` which grows much slower than `dolt_history_test`. 

Does this look right?

`SELECT to_commit from dolt_diff_test order by to_commit_date desc limit 1`

**Comment by VinaiRachakonda** [comment]
Yes this looks correct to me!

**Comment by AmirAktify** [comment]
Thanks! You may close this issue.
I guess one last random question I had off the top of my head, if you know and since it kind of came up in this discussion. Is `dolt_history_test` dynamically computed only when one queries it, or is it kept stored in the repository?

 If its the former, it doesn't concern me at all, but if its the latter I might need to squash my commit patterns to keep that table exploding our `gcp` backend repository size.

**Comment by VinaiRachakonda** [comment]
This table is dynamically generated!
