### ISSUE TITLE
Add commit hash functionality to dolt ls --verbose

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1564]
Currently `dolt ls --verbose` works as follows:

It lists the table name, the table hash, and the number of rows. We should add in the commit hash that most recently affected the table

**Comment by AmirAktify** [comment]
This would be great! One alternate way to do it that mirrors `git`'s syntax. In `git` you can do `git log -p filename`. In `dolt` speak, that would be `dolt log -p tablename`.

Whichever is more intuitive to implement or preferred by users would work for me. Either variant would be very useful.

**Comment by VinaiRachakonda** [comment]
@AmirAktify We recently merged this feature into master. You can do `dolt log <table-name>` to produce a log that defines which commits affected the particular table. To get the most recent one this is all you need to do

```bash
dolt log -n 1 <table_name>
```

We do release every Monday so you can either wait till then or build from master.

**Comment by zachmu** [comment]
This is in the latest release, closing out
