### ISSUE TITLE
Date column matching does not work properly

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#1572]
Date columns must be wrapped in a `date()` conversion to match date literals. This prevents them from being used in an index lookup.

https://www.dolthub.com/repositories/post-no-preference/options/query/master?q=explain+SELECT+*%0AFROM+%60option_chain%60%0Awhere+date%28%60date%60%29+%3D+date%28%272021-04-19%27%29%0ALIMIT+200%3B%0A%0A%0A%0A%0A%0A%0A&active=Tables

**Comment by post-no-preference** [comment]
Hi. Has any progress been made here?

**Comment by zachmu** [comment]
We're working on a fix now, thanks for the poke
