### ISSUE TITLE
dolt checkout to most recently updated branch

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1590]
As the amount of branches grow for a repo it would be nice to add a flag to dolt checkout to enable checkout to most recent used branch as well as the most recently updated branch.

Basically a flag that automates this query `select name from dolt_branches ORDER BY latest_commit_date DESC LIMIT 1;` for the most recently updated branch and something like `git checkout -` for the most recently used branch.

**Comment by zachmu** [comment]
We need something akin to a reflog to implement this

**Comment by zachmu** [comment]
No plans for this at the moment
