### ISSUE TITLE
Require SSL

### ISSUE THREAD

**Issue by drequivalent** [dolthub/dolt#1603]
Does Dolt support SSL/TLS with its SQL connection?

**Comment by timsehn** [comment]
No. Only raw TCP right now. Again, we can build it just need someone to want it :-)

**Comment by timsehn** [comment]
None of our current customers have asked for it. So, again, we'll eventually get to it but we need an enterprise support contract buyer to pull it up the priority stack.

**Comment by timsehn** [comment]
Added in https://github.com/dolthub/dolt/pull/2072
