### ISSUE TITLE
PhpMyAdmin, Adminer and any other general SQL client compatibility

### ISSUE THREAD

**Issue by drequivalent** [dolthub/dolt#1604]
Is Dolt compatible with SQL clients such as PMA, Adminer, Workbench, etc. etc?

Also in question, ProxySQL

**Comment by VinaiRachakonda** [comment]
Hi @drequivalent we've tested the following editors here ->. https://docs.dolthub.com/integrations/sql-editors

The only blocker for working with other MySQL editors like the one you mentioned is MySQL compatibility. If you try connecting a Dolt server with these editors and see a failing query (Dolt allows logging of all queries) then feel free to post an issue and we'll fix it.

Our goal is to definitely get compatible with every editor.

**Comment by drequivalent** [comment]
> Dolt allows logging of all queries

From what I see, Dolt is basically built around logging of all queries, which is why I want it :)

Hmmm... No phpmyadmin on the list...
Do I need to test it myself, then?

**Comment by VinaiRachakonda** [comment]
@drequivalent Yes

**Comment by timsehn** [comment]
It should work exactly like MySQL does :-) Our expectation is that it works. We just listed the ones we tested.

**Comment by geertdepuydt** [comment]
I don't want to open a new issue, neither hijack this one, only mention my user experience.
I experience some recurring trouble trying to get Dolt to work as a MySQL server with several products such as Metabase and NocoDB.
They seem to connect to Dolt just fine, but then either can't find the tables (NocoDB), or the table fields (metabase).
When you launch SQL queries from within these tools it is clear the tables are their and the data is accessible... just some background queries these tools use to fetch meta data from dolt seem to fail.

**Comment by oscarbatori** [comment]
@geertdepuydt thanks for sharing this, this is useful. Can you provide the queries/error messages so we can queue up implementation?

If you have a business need here we are more than happy to discuss prioritization. Just shoot us a note.

**Comment by zachmu** [comment]
Many of these database inspection tools rely on the `information_schema` database, which is not fully implemented. It's filled in enough to get several more common GUIs working, but there are known gaps.

In the long term we will support all such clients, but this isn't a top priority vs. other features. If you have specific clients we should focus on first, please let us know and we will evaluate them.

And as Tim has mentioned several times, we prioritize features for paying customers. If you think you would be a paying customer except your chosen tool doesn't work, that counts too.

**Comment by timsehn** [comment]
NocoDB should work now. I'm resolving this issue in favor of issues for specific tools.
