### ISSUE TITLE
Dolt: Throughput Test Fails Intermittently

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#1610]
https://github.com/liquidata-inc/ld/blob/master/dolt/go/libraries/utils/iohelp/read_test.go#L225

This test will unpredictably fail on Windows. On repeated runs, sometimes they all pass, sometimes they don't. In the meantime, I have a runtime check that skips this on Windows.

**Comment by zachmu** [comment]
This is skipped for unix too, the test is flakey.

**Comment by timsehn** [comment]
The above link no longer exists so I'll resolve.
