### ISSUE TITLE
Dolt: `SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())` Fails

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#1614]
When implementing dolt serve functionality, it was observed that Oracle's .NET MySQL connector would call `SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())` immediately when connecting to dolt. This is not currently a supported SQL function, and thus an exception was thrown by the .NET client.

Specifically, the exception states that `utc_timestamp` was not found.

**Comment by VinaiRachakonda** [comment]
This works now
