### ISSUE TITLE
GCP Authentication Fails on Google Colab

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1659]
There seems to be a bit of authentication bug that causes Dolt to not properly connect to a GCP remote from Google Colab.

**Comment by VinaiRachakonda** [comment]
@Focus Is this generally what your were referring to?

**Comment by Focus** [comment]
Hi @VinaiRachakonda . The bug I'm referring to (which I suspect is more to do with colab/gcp authentication than dolt) can be reproduced as follows.

1. Open up a new notebook and authenticate google tools using:
```
!gcloud auth login
!gcloud auth application-default login
!gcloud config set project blablabla
```

2. Install dolt:
```
!curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
!dolt config --global --add user.name "I am a cat"
!dolt config --global --add user.email "cat@catsunite.io"
```

3. Try to clone a private GS repo:
```
!dolt clone gs://my-super-secret-repo
```

The above clone fails, whereas the google tool is able access the GS directory fine. In particular I can copy it across using:
```
!gsutil cp -r gs://my-super-secret-repo ./
```

**Comment by VinaiRachakonda** [comment]
Hi @Focus! I think the problem is that Google Collab seems to initialize the notebook in `/content` vs `~` so the Golang Google Storage Client is unable to find the location of the application credentials. There are two quick solutions you can adopt

1. Right after step 1 you can add a python cell with the following code
```python
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/content/.config/application_default_credentials.json'
```
This code essentially sets the application credentials location to the path where the application default credentials are located. These credentials are generated after running `!gcloud auth application-default login`. This environment variable change will persist the entire session.

2. Right before you clone run this magic command. This will not persist the entire notebook but only in the cell

```python
%env GOOGLE_APPLICATION_CREDENTIALS=/content/.config/application_default_credentials.json
!dolt clone gs://vinai-test-bucket
```

I think solution 1 makes the most sense. In the long term Dolt probably needs a command line argument for a settings configuration file.

Let me know if this fixes your problem!

**Comment by Focus** [comment]
@VinaiRachakonda Awesome, thanks a bunch for this. Can confirm it working!

**Comment by oscarbatori** [comment]
@VinaiRachakonda can we just make a feature issue to pass the location of the config in the command line or whatever?
