### ISSUE TITLE
Name resolution bug for `LEFT OUTER JOIN`

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1661]
Engine fails to resolve `tenancy_tenantgroup.name`, but column [does exist](https://www.dolthub.com/repositories/dolthub/nautobot/query/master?q=describe+tenancy_tenantgroup%3B&active=Tables)

Error running query
```
SELECT `tenancy_tenant`.`id`,
    `tenancy_tenant`.`created`,
    `tenancy_tenant`.`last_updated`,
    `tenancy_tenant`.`_custom_field_data`,
    `tenancy_tenant`.`name`,
    `tenancy_tenant`.`slug`,
    `tenancy_tenant`.`group_id`,
    `tenancy_tenant`.`description`,
    `tenancy_tenant`.`comments`
FROM
    `tenancy_tenant`
LEFT OUTER JOIN
    `tenancy_tenantgroup`
ON
    (`tenancy_tenant`.`group_id` = `tenancy_tenantgroup`.`id`)
WHERE
    `tenancy_tenant`.`id` IN (NULL)
ORDER BY
    `tenancy_tenantgroup`.`name` ASC,
    `tenancy_tenant`.`name` ASC
LIMIT 21
```
: table "tenancy_tenantgroup" does not have column "name"

**Comment by andrew-wm-arthur** [comment]
Possible an issue with reserved words?
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by zachmu** [comment]
Can you post the schema of these tables?

**Comment by andrew-wm-arthur** [comment]
https://www.dolthub.com/repositories/dolthub/nautobot/query/master?q=describe+tenancy_tenantgroup%3B&active=Tables
