### ISSUE TITLE
`dolt table import -u` intermittently hangs during batch import

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#1693]
**Context**: I'm doing a lot of importing for the hospital bounty, millions of rows. 

My batch scripts look something like:

```
dolt table import payers -u --no-gc /home/ec2-user/SageMaker/cone/CONE_1326010273_payers.csv && echo 'COMPLETED: CONE-1326010273, FILE: PAYERS'
dolt table import procedures -u /home/ec2-user/SageMaker/cone/CONE_1326010273_procedures.csv && echo 'COMPLETED: CONE-1326010273, FILE: PROCEDURES' 
date >> log.txt
echo 'COMPLETED: CONE-1326010273, FILE: PROCEDURES' >> log.txt
dolt table import prices -u /home/ec2-user/SageMaker/cone/CONE_1326010273_prices_0.csv && echo 'COMPLETED: CONE-1326010273, FILE: 0'
(etc.)
```

and typically contain dozens of tables to import.

**Problem:** Since about 4 days ago I've been running into the following issue that I don't think I've seen before. 

While batch importing with `dolt table import -u`, importing tables of < 200k rows each, dolt stops importing and eventually hangs indefinitely until I hit Ctrl-C. 

I've been logging imports, so this is what it looks like. 

```
Thu May  6 17:27:11 UTC 2021
COMPLETED: CONE-1326010273, FILE: PROCEDURES
Thu May  6 17:59:16 UTC 2021
COMPLETED: CONE-1326010273, FILE: 0
Thu May  6 18:30:57 UTC 2021
COMPLETED: CONE-1326010273, FILE: 1
Thu May  6 19:04:37 UTC 2021
COMPLETED: CONE-1326010273, FILE: 2
... (edited down for clarity)
Fri May  7 12:01:00 UTC 2021
COMPLETED: CONE-1467082370, FILE: PROCEDURES
Fri May  7 12:55:53 UTC 2021
COMPLETED: CONE-1467082370, FILE: 0
Fri May  7 13:51:08 UTC 2021
COMPLETED: CONE-1467082370, FILE: 1
Fri May  7 14:41:51 UTC 2021
COMPLETED: CONE-1467082370, FILE: 2
```

**What to see**: Files continue importing successfully followed by a long pause. After this, a hang occurred that lasted 7 hours until I hit Ctrl-C.

You can reproduce the issue by cloning my repo and trying to import the following CSVs.

https://www.dolthub.com/repositories/spacelove/hospital-price-transparency-v2

https://send.ioiox.com/download/d82352e2412d0def/#J1Oa0LnpIbMuUKLe87KlIg (link lasts 15d from now)

**What I'm doing to resolve it**: seeing if going back to 26.1 solves the issue.

As a final thought -- although I don't have any evidence of it, it feels like `dolt import` is a lot slower than it used to be. I don't know if these are related issues.

Update: 5/7/21 10pm: Switching to 26.1 might have improved things somewhat, but I still get the same hang. I'm wondering if it's the increasing size of my database that's causing the problems. It's now around 14GB, and my VMs have 16GB of RAM. Experimenting with 32GB machines.

**Comment by alecstein** [comment]
Trying an older version of dolt and using 32GB of RAM did not resolve the issue. Now I am wondering if it's just the size of the db that is causing these problems. And it is pretty serious as well, I was not able to import a single table of 200k row on either of two 32GB machines over 8 hours.

**Comment by timsehn** [comment]
We are aware of this issue. It has something to do with garbage
collection. @bheni is looking into it. We apologize for the inconvenience.

**Comment by alecstein** [comment]
Running `dolt gc` after the hang kinda/sorta resolves the issue temporarily.

**Comment by alecstein** [comment]
Alright, a better workaround is cloning *only* the master branch of my repo and starting over from there. That reliably gets rid of the error.

**Comment by zachmu** [comment]
@bheni can you comment on whether this should be fixed with your latest changes?

**Comment by timsehn** [comment]
Gonna resolve this.
