### ISSUE TITLE
Feature request: show status during dolt sql edits

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#1708]
When you edit a large database it can be helpful to see how things are going. Often a command silently fails, and you don't know until you cancel and re-run it, or try something else.

Just like `dolt table import` shows # of rows imported, it would be nice if `dolt sql` showed something along the lines of:

`Applied query to X rows. Continuing...`

This could be implemented as a verbose option.

It would also be cool if you could see how long the query was taking, with a `-t` flag or something like that, which would output some time stats. Which might be useful for finding which ways of querying/editing the database are fastest.

**Comment by VinaiRachakonda** [comment]
Great feature request at @alecstein. I can add it to our feature queue. 

For the `-t` flag you can prepend all of your queries with the `time` command. For example,

```
time dolt sql -q "SELECT * FROM mytable"
```

will amount of the time the completed query took. 

We could do definitely output the running time of a query on our end but that's further down the line.

**Comment by zachmu** [comment]
We already periodically output bulk edit stats for sql imports, i.e. `dolt sql < mysql.dump` that show number of row inserted, updated, deleted.

This is about long-running update / insert / delete queries that touch many rows. Right now there's no feedback on the command line about the progress such queries are making. They just appear to hang.
