### ISSUE TITLE
Feature: Foreign Keys referencing system tables

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1754]
Allow foreign keys to reference system tables such as `dolt_branches`, `dolt_log`, `dolt_commits`, and `dolt_commit_ancestors`. Per-table system tables such as `dolt_diff_*` and `dolt_history_*` probably shouldn't be able to be referenced. 

Use case: adding contextual data to commit/branch data, such as which user created a branch

**Comment by Hydrocharged** [comment]
Shelved for now due to issues managing global state with foreign keys.
