### ISSUE TITLE
Should be a parse error

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1772]
```
hospital-price-transparency-v2 $ dolt sql -q "select code, npi_number, payer, price from prices natural join procedures where code = '00450' and (short_description is not NULL or long_description is not NULL)"
```

This parses and runs even though `code` is ambiguous.

**Comment by zachmu** [comment]
I think this is actually WAI, because the natural join automatically reduces the two code columns down to a single one before the filter gets applied.
