### ISSUE TITLE
write_file and write_pandas raise DoltException on Windows

### ISSUE THREAD

**Issue by PaulM5406** [dolthub/dolt#1774]
Hello,

write_file and write_pandas raise DoltException on Windows. Here is the traceback. I do not know which is this other process that locks the file. If I run the command `table import data_pisigma -c --pk=id temp.csv` directly from the terminal, I get no error.

`b'An error occurred moving data:\n\ncause: error garbage collecting the following files:\t.\\.dolt\\noms/4d3m60adthij431437g9v7l8uf4kigpg: remove .\\.dolt\\noms/4d3m60adthij431437g9v7l8uf4kigpg: The process cannot access the file because it is being used by another process.\n'
Traceback (most recent call last):
  File "C:\Users\paolo\Dev\data_pisigma\main.py", line 67, in <module>
    write_file(dolt,
  File "C:\ProgramData\Anaconda3\envs\data_pisigma\lib\site-packages\doltcli\utils.py", line 73, in write_file
    _import_helper(
  File "C:\ProgramData\Anaconda3\envs\data_pisigma\lib\site-packages\doltcli\utils.py", line 199, in _import_helper
    dolt.execute(args + [fname])
  File "C:\ProgramData\Anaconda3\envs\data_pisigma\lib\site-packages\doltcli\dolt.py", line 309, in execute
    output = _execute(args, self.repo_dir, outfile=outfile)
  File "C:\ProgramData\Anaconda3\envs\data_pisigma\lib\site-packages\doltcli\dolt.py", line 89, in _execute
    raise DoltException(str_args, out, err, exitcode)
doltcli.dolt.DoltException: ('table import data_pisigma -c --pk=id C:\\Users\\paolo\\AppData\\Local\\Temp\\tmpqcm7hpaz.csv', b'Rows Processed: 55, Additions: 55, Modifications: 0, Had No Effect: 0', b'An error occurred moving data:\n\ncause: error garbage collecting the following files:\t.\\.dolt\\noms/4d3m60adth
ij431437g9v7l8uf4kigpg: remove .\\.dolt\\noms/4d3m60adthij431437g9v7l8uf4kigpg: The process cannot access the file because it is being used by another process.\n', 1)`

**Comment by Hydrocharged** [comment]
We've just released a new version of Dolt that we think may fix this issue. Give it a spin and let us know if you still run into the problem!

**Comment by zachmu** [comment]
Going to close this out for the time being, because we have a solution for windows that we think is as good as we can do for now.

Basically: os.Rename() on Windows is error prone due to the OS preventing access to files sometimes, for reasons not even the golang authors understand. The best we can do for now is retry failed Rename operations, which we are now doing.

If anyone can demonstrate a reliable repro for this, or runs into this again in the wild, please do let us know.
