### ISSUE TITLE
dolt sql-server error when using PostgreSQL mysql_fdw against it

### ISSUE THREAD

**Issue by richardji7** [dolthub/dolt#1780]
Since dolt sql-server is MySQL compatible.  I am using PostgreSQL mysql_fdw to connect to Dolt as a remote database.
I am getting the following error.  When I connect to a real one MariaDB, it works fine.

dolt_agencies is a foreign table.

                 List of relations
 Schema |       Name        |     Type      | Owner 
--------+-------------------+---------------+-------
 public | dolt_agencies     | foreign table | rji

[local]:5432 rji@rji_pdap=# select * from dolt_agencies;
ERROR:  failed to execute the MySQL query: 
Commands out of sync; you can't run this command now

I am using PostgreSQL 13 with the latest mysql_fdw from their github repo.

**Comment by zachmu** [comment]
Hi @richardji7,

Our goal is for anything that works in MySQL to work in Dolt, but we're not there yet. It's likely that the postgres FDW is using features of MySQL that dolt implements incompletely, e.g. information schema tables or obscure parts of the wire protocol. It's hard to say exactly what's going on here without more debug info.

If you're interested in helping us debug this, you can turn on trace logging in your server, which will log every query the server receives. Use the `-l trace` option when starting the server. Additional instructions here:

https://docs.dolthub.com/interfaces/cli#dolt-sql-server

Let me know what else we can tell you,

Zach

**Comment by richardji7** [comment]
Trace file attached.
[dolt_server_trace.gz](https://github.com/dolthub/dolt/files/6601895/dolt_server_trace.gz)

**Comment by flinz** [comment]
I would also be interested in the same usecase. I could see dolt replacing some tables in postgres via the fdw.

**Comment by VinaiRachakonda** [comment]
@richardji7 I just tested the fdw with the dolt database you were using and I was able to select data without any problems. Looking at your logs I did not see any errors as well. Are you still able to repro with the latest version of dolt? 

We do have some small problems on the write side with the fdw. I'll address those fixes asap

**Comment by VinaiRachakonda** [comment]
@flinz You should at least be able to get started by creating a foreign table that reads from a dolt table.

**Comment by richardji7** [comment]
@VinaiRachakonda Yes, the problem still exists.

**Comment by richardji7** [comment]
What I am noticing is that here is the trace output for when I do "select * from dolt_source_types;" from PostgreSQL side.

```
INFO: NewConnection: client 3
INFO: audit trail
TRACE: connection 3: received query SET sql_mode='ANSI_QUOTES'
TRACE: connection 3: executing query
TRACE: connection 3 spooling result row []
TRACE: committing transaction Disabled transaction
TRACE: connection 3 returning result &{[] 1 0  [[]] <nil>}
TRACE: connection 3: received query SET sql_mode='ANSI_QUOTES'
TRACE: connection 3: executing query
TRACE: connection 3 spooling result row []
TRACE: committing transaction Disabled transaction
TRACE: connection 3 returning result &{[] 1 0  [[]] <nil>}
TRACE: connection 3: received query SELECT `id`, `name`, `description` FROM `pdap_datasets`.`source_types`
TRACE: connection 3: executing query
TRACE: connection 3 spooling result row [INT32(1) VARCHAR("court") VARCHAR("A Court is providing this data.")]
TRACE: connection 3 spooling result row [INT32(2) VARCHAR("direct") VARCHAR("A governing body or law enforcement agency is providing data directly.")]
TRACE: connection 3 spooling result row [INT32(3) VARCHAR("third party") VARCHAR("A third party is aggregating data from another type of source.")]
TRACE: committing transaction Disabled transaction
```

After this, no matter how many queries to Dolt server I tried, there is no more trace logs on Dolt side, as if that connection is dead.  I'd have to quit psql and reconnect.

**Comment by richardji7** [comment]
Here is the trace from a mysql client.  Compare to the trace generated by mysql_fdw, the difference is the above has "TRACE: committing transaction Disabled transaction".  This one doesn't.
```
TRACE: connection 1: received query select * from source_types
TRACE: connection 1: executing query
TRACE: connection 1 spooling result row [INT32(1) VARCHAR("court") VARCHAR("A Court is providing this data.")]
TRACE: connection 1 spooling result row [INT32(2) VARCHAR("direct") VARCHAR("A governing body or law enforcement agency is providing data directly.")]
TRACE: connection 1 spooling result row [INT32(3) VARCHAR("third party") VARCHAR("A third party is aggregating data from another type of source.")]
```

**Comment by VinaiRachakonda** [comment]
@richardji7 What configs are you running the server with? Is max-connections > 1? That could cause the hanging behavior. cc this [doc](https://docs.dolthub.com/reference/faq#why-does-my-connection-to-the-server-hang-time-out)

You can ignore the "TRACE: committing transaction Disabled transaction". It just means you have the transactions configs turned off. It shouldn't cause any problems

**Comment by VinaiRachakonda** [comment]
@richardji7 Can you post the steps you used to create the foreign table and the server object? 

I followed this [guide](https://github.com/EnterpriseDB/mysql_fdw)

**Comment by richardji7** [comment]
Yes, I used the same guide.  I git clone that repo and compiled it against the most recent PostgreSQL 13 build which is also compiled from source.  And yes, I am using the pdap/datasets Dolt repo.

**Comment by VinaiRachakonda** [comment]
As an update to this issue, the error the user was having seemed to be with an OS (Opensuse Leap) that we don't support yet.

I added a code sample here for the read path of mysql_fdw: https://github.com/dolthub/dolt/pull/1889

If anyone wants write path support comment here.
