### ISSUE TITLE
Quickstart install requires executing remote code as root

### ISSUE THREAD

**Issue by josiah-roberts** [dolthub/dolt#1795]
The quickstart install for Dolt requires `sudo bash -c 'curl -L someUrl | bash'`. Executing code over the network sight-unseen is one thing, but additionally handing root permissions to a remote script is really not something we should be encouraging users to do.

I understand there's some argument to be made for "the repo / Github would have to be compromised for this to expose anyone." However, I would really appreciate it if the quickstart at least offered some kind of alternative install approach for those who prefer to avoid piping curl into bash as root. Perhaps a link out to the [binary distributions](https://github.com/dolthub/dolt/releases) and/or an option to install Dolt for the current user without requiring root?

**Comment by oscarbatori** [comment]
@josiah-roberts good shout. We will add some language and a link to that effect.

**Comment by zachmu** [comment]
I updated the README with an alternative for people who don't want to run a script with sudo, thanks for the suggestion!
