### ISSUE TITLE
cat / diff leave output colored after SIGINT 

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#1838]
After killing a `dolt diff` or `dolt conflicts cat` output using SIGINT, the terminal remains the last color used. 
![image](https://user-images.githubusercontent.com/40151222/122301120-3d2ee380-cece-11eb-8018-fe8a2aa5f62f.png)

Tested on:

Microsoft Windows 10 Home, Version 10.0.19042 Build 19042
@timsehn [says](https://discord.com/channels/746150696465727668/746152112169287760/854844182228893706) he's seen it on MacOs

**Comment by VinaiRachakonda** [comment]
Closing since pr was merged in
