### ISSUE TITLE
dolt removes data on incremental schema update

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#1850]
Having a table and calling a `dolt schema import -u` with a new column - drops all data from this table.

Steps to reproduce:
create base table:
```
cd dolt-issue
dolt init

echo "key,val" > data.csv
echo "1,2" >> data.csv
cat data.csv

dolt table import -c atable --pk key data.csv

dolt diff

dolt commit -am "atable"
```

update table with new schema:
```
echo "key,val,another_val" > data.csv
echo "1,2," >> data.csv
cat data.csv

dolt schema import -u atable --pks key data.csv
```

see that the table gets empty:
```
>dolt diff
diff --dolt a/atable b/atable
--- a/atable @ bte2pp3jbo7q2frfmd176mi7b829dg0o
+++ b/atable @ u2lraefgka9p4apn9ir235a9b2ttusa3
  CREATE TABLE atable (
    `key` INT UNSIGNED NOT NULL
    `val` INT UNSIGNED NOT NULL
+   `another_val` LONGTEXT
     PRIMARY KEY (key)
  );

+-----+-----+-----+-------------+
|  <  | key | val |             |
|  >  | key | val | another_val |
+-----+-----+-----+-------------+
|  -  | 1   | 2   | NULL        |
+-----+-----+-----+-------------+

```

Expected behaviour:
Dolt adds new nullable column to the table, as per `dolt schema import --help` tells:
```
-u, --update
          Update a table to match the inferred schema of the <file> provided
```

Environment:
```
Ubuntu 20.04
> dolt version
dolt version 0.26.9
```

**Comment by timsehn** [comment]
This is not supported this way. We've really only used/tested `dolt schema --update` with empty tables.

We can add it but it may take a while.

You have a workaround to just add the column using `dolt sql`. In this case:

`dolt sql alter table atable add column another_val LONGTEXT`

**Comment by kretes** [comment]
I see.

I think it might be worth exiting from `dolt schema --update` with a clear message that it cannot work if the table is not empty. The contract would at least be clear.
