### ISSUE TITLE
dolt should update schema on table import --replace

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#1851]
I have a table, with not-null field.
I run `table update -r` to replace the table with new data, in which this column is nullable.
Dolt doesn't allow me to do that.

Steps to reproduce:
```
mkdir dolt-issue-2

cd dolt-issue-2
dolt init

echo "key,val" > data.csv
echo "1,2" >> data.csv
cat data.csv

dolt table import -c atable --pk key data.csv

dolt commit -am "atable"

echo "key,val,another_val" > data.csv
echo "1,,1" >> data.csv
cat data.csv

dolt table import -r atable --pk key data.csv
```
error:
```
Rows Processed: 0, Additions: 0, Modifications: 0, Had No Effect: 0
A bad row was encountered while moving data.
Bad Row: 
invalid column: val
These can be ignored using the '--continue'
```

This might not be that bad, as simply running a schema update before, would be enough:
```
dolt schema import -r atable --pks key data.csv
dolt table import -r atable --pk key data.csv
```

However - when using doltcli `write_pandas` API - this one is not called.

From the logical perspective - if `table import -c` creates both appropriate schema and data - the same should happen on `table import -r`

**Comment by zachmu** [comment]
This is WAI and documented, according to the help for `dolt table import`:

```
 If --replace-table | -r is given the operation will replace <table> with the contents of the file. The table's
        existing schema will be used, and field names will be used to match file fields with table fields unless a mapping
        file is specified.
```

Basically, `-r` is like `-u` except that it drops all existing rows first.

I think the bug here is that write_pandas needs to drop and recreate the table, rather than calling `table import -r`

Max, does that sound right to you?

**Comment by max-hoffman** [comment]
@zachmu Is this the behavior that we want for `--replace`? If yes, then I think it would be confusing if by default doltpy ran different (extra) commands for a file import. I can add a flag to add the additional drop beforehand (`drop=True`), or improve the documentation, or make better helper functions for dropping tables? If none of those sound like a good idea, maybe there should be a fourth import flag `--drop`?

**Comment by kretes** [comment]
Thanks for the explanation.
It sounds to me that this is, as frequently, the case of the right naming.
I expected `replace` to replace both schema and data. Alternative to adding a configuration flag for replace - you might consider introducing a different command for updating the schema and replacing the datawith

**Comment by timsehn** [comment]
The behavior you want is already supported with `--create`. 
```
