### ISSUE TITLE
support dolt clone file:///somepath-to-a-dolt-repo

### ISSUE THREAD

**Issue by AddictArts** [dolthub/dolt#1860]
```
$ dolt clone file:$HOME/box/dolt/ dolt2 

cloning file:$HOME/box/dolt
Retrieving remote information.
error: clone failed
cause: remote at that url contains no Dolt data
```

The remote has a ".dolt" and commits. This works with git. Maybe I am doing something wrong.

**Comment by timsehn** [comment]
I think if you put `.dolt` on there it works. Let me try and make sure.

**Comment by reltuk** [comment]
@AddictArts Thanks for the report. Looks like the current logic gets the expected location a little wrong. The following works:

`dolt clone file:$HOME/box/dolt/.dolt/noms dolt2`

So you need `.dolt/noms` appended. We will take a pass at getting the git-equivalent syntax supported.

**Comment by timsehn** [comment]
```
dolt $ dolt clone file:$HOME/liquidata/dolt/dolt-test/.dolt/noms dolt2 
cloning file:///Users/timsehn/liquidata/dolt/dolt-test/.dolt/noms
23 of 23 chunks complete. 0 chunks being downloaded currently.
```

For confirmation.

**Comment by timsehn** [comment]
It's a pretty easy fix to change this behavior. We're debating where to put it right now. @VinaiRachakonda will likely get to it next week.

**Comment by AddictArts** [comment]
Thanks, yes that worked. What is the "noms" I thought and then I looked at the architecture page and found the noms info.

**Comment by AddictArts** [comment]
It would be great if a

```
git dolt link file:.../.dolt/noms
```

Let you choose a destination name instead of noms in the git repo. Thanks

**Comment by timsehn** [comment]
Agreed. That's kinda gross. I don't think we had filesystem remotes when we
built `git-dolt`.

**Comment by bheni** [comment]
The intended use was not to be able to push/pull/clone from/to a directory.  As in:

```dolt init
... # do some stuff and commit it
dolt remote add origin file:///path/to/store/data
dolt push origin master```

That will put all the dolt files in that directory.  The use case I was looking to support is something like pushing to a mounted network directory.  Then someone else could run:

```dolt clone file:///path/to/store/data```

It was not expected for users to want to clone a repository they already have locally when we wrote file based remote storage.

**Comment by AddictArts** [comment]
Dolt advertises itself with git like semantics. So, this is very much a git thing, so intended or not, if you want to be like git, well then you might want to consider it seriously.

**Comment by zachmu** [comment]
Definitely agree with this. It's on our roadmap for sure.

**Comment by ckaran** [comment]
How far along is this?  While I agree that cloning a database that you already have seems weird, it's really handy when you're learning how dolt works.

**Comment by timsehn** [comment]
You can, you just have to point it at the Noms directory of another repo. It automatically sets it correctly if you push to it. Here's a good doc:

https://www.dolthub.com/blog/2021-07-19-remotes/

**Comment by ckaran** [comment]
Thank you.

**Comment by timsehn** [comment]
Resolving in favor of #5325
