### ISSUE TITLE
Multi Table Update does not work in Dolt

### ISSUE THREAD

**Issue by geertdepuydt** [dolthub/dolt#1862]
Trying to update one table column by joining with another table column.
I'm starting to suspect this fails silently (no errors are thrown) in Dolt.
The table is never updated with the expected values as far as I can tell.
Does multi-table update work in Dolt?

this is the query used (the join is valid):
`UPDATE  rds_dump.ResearchTopics t1, rds_dump.ResearchGroups t2
SET t1.academiclabs_research_group_id = t2.academiclabs_research_group_id
WHERE t1.rds_research_group_id = t2.rds_research_group_id`

BEFORE the update, dummy value of '123' should be updated with correct values.
`rds_dump> select t1.research_group, t1.academiclabs_research_group_id from ResearchTopics t1 join ResearchGroups t2 on t2.rds_research_group_id = t1.rds_research_group_id where t1.rds_research_group_id = '355569';

+----------------+--------------------------------+
| research_group | academiclabs_research_group_id |
+----------------+--------------------------------+
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
+----------------+--------------------------------+
rds_dump> UPDATE  rds_dump.ResearchTopics t1, rds_dump.ResearchGroups t2 SET t1.academiclabs_research_group_id = t2.academiclabs_research_group_id WHERE t1.rds_research_group_id = t2.rds_research_group_id and t1.rds_research_group_id = '355569';
**Query OK, 11 rows affected
Rows matched: 11  Changed: 11  Warnings: 0**

AFTER the update query:
rds_dump> select t1.research_group, t1.academiclabs_research_group_id from ResearchTopics t1 join ResearchGroups t2 on t2.rds_research_group_id = t1.rds_research_group_id where t1.rds_research_group_id = '355569';
+----------------+--------------------------------+
| research_group | academiclabs_research_group_id |
+----------------+--------------------------------+
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
| The Gordon Lab | 123                            |
+----------------+--------------------------------+`

The dummy value '123' should have been updated, as is indicated by the query OK message (11 Changed), but somehow these changes are not committed (dummy value '123' is unchanged???)

**Comment by timsehn** [comment]
@reltuk will look at this.

**Comment by zachmu** [comment]
Hi @geertdepuydt,

Multi-table updates / deletes don't work. This query should fail loudly rather than silently.

We'll get this fixed soon, it's been on our radar for a while.

**Comment by geertdepuydt** [comment]
Thank you for the info @zachmu

**Comment by VinaiRachakonda** [comment]
This is now in master
