### ISSUE TITLE
Dolt table export to csv's with Json fields is not json encoded strings.

### ISSUE THREAD

**Issue by AmirAktify** [dolthub/dolt#1868]
This makes further parsing of the csv's by downstream applications more annoying, because one has to use regexes and replaces to convert back, which cannot handle some edge cases easily.

 I could give examples in the ways its not json compatible, but first I wanted to inquire whether this is desired behavior.

**Comment by max-hoffman** [comment]
When this is merged, it should fix this bug.
https://github.com/dolthub/dolt/pull/1873

In the meantime, `dolt sql -q "select * from table" -r csv` is a functional workaround
