### ISSUE TITLE
dolt sql-server gives diffrent data than running commands on box

### ISSUE THREAD

**Issue by GoreNetwork** [dolthub/dolt#1896]
I run the command on the box
dhimes@ubuntu:~/dolt$ dolt sql -q "show tables"
+-----------+
| Table     |
+-----------+
| json_spew |

I run the command from python
`mysql.connector.errors.DatabaseError: 1146 (HY000): table not found: json_spew
`
When I tell the python code to build the table the python code can then update the table, however 
`
 dolt  revert --hard
`
Does not revert the changes
My python code
https://github.com/GoreNetwork/learning_scrap_work/blob/master/dolt_git_db/work_with_dolt_db.py

**Comment by timsehn** [comment]
We don't support `revert` yet. I think you want `reset`.

**Comment by GoreNetwork** [comment]
Sorry, that's what I meant :-(

**Comment by VinaiRachakonda** [comment]
Hi @GoreNetwork. I ran your script and it seems to work fine for me and show me the table. I did have to change line 84 to the following to get the json formatting correct.

```python
insert_statment = "INSERT INTO json_spew (json_feild) VALUES ('{}')".format(junk_json_data)
```

**Comment by VinaiRachakonda** [comment]
@GoreNetwork Are you sure you are connected to a Dolt server instead of a MySQL server? The running MySQL installation tends to use port 3307

**Comment by GoreNetwork** [comment]
I am not sure why, but this is working now.

Thank you all
