### ISSUE TITLE
Rebase?

### ISSUE THREAD

**Issue by tslocke** [dolthub/dolt#1915]
I notice the list of git-like commands in the main README doesn't include rebase.

Is this something that could be implemented in the application layer?

I believe the fundamental operation behind rebase is the ability to take a commit, and apply the changes in that commit to a table (or tables) in a *different state* than that of the original parent commit. In other words, diff/patch for tables.

Is that possible?

Thanks

**Comment by timsehn** [comment]
We don't have rebase yet. It's definitely on the backlog. 

If you want diff/patch for tables check out `dolt diff --sql`. This will give you the sql "patch" between two commits, you can then apply it anywhere. 

Is there a use case you have that does not cover?

**Comment by tslocke** [comment]
No it was more out of curiosity. With `dolt diff --sql` it wouldn't be that hard to implement rebase if the need arose.

Thanks very much.
