### ISSUE TITLE
Support OpenSUSE with Dolt

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1928]

**Comment by zachmu** [comment]
@VinaiRachakonda, can you provide a little more detail here? What's not working with OpenSUSE? What's the scope of the work?

**Comment by VinaiRachakonda** [comment]
This isn't a well written issue. There was an issue with Dolt on OpenSUSE working with the mysql_fdw read path. I assumed it to be an OS problem but haven't investigated. I'll go ahead and close
