### ISSUE TITLE
dolt sql cannot execute

### ISSUE THREAD

**Issue by csgorham** [dolthub/dolt#1943]
i just installed dolt version 0.27.0

I am cloning repositories and see that it is there with 'dolt ls' 

however when i try to use sql or sql-server  it says,

"Cannot execute 'dolt sql', repository format is out of date.
Run "dolt migrate" to update this repository to the latest format"

Then when i run dolt migrate 

"Cannot unmarshal from: Struct EncodedColumn {
  col_constraints: List<Struct EncodedConstraint {
    constraint_type: String,
    params: Map<>,
  }>,
  is_part_of_pk: Bool,
  name: String,
  tag: Float,
  typeinfo: Struct EncodedTypeInfo {
    params: Map<String, String>,
    type: String,
  },
} to: encoding.encodedColumn details: missing field "kind""

**Comment by VinaiRachakonda** [comment]
Hi @csgorham, do you mind letting me know which repo you cloned? i've tried with some older repos and haven't been able to replicate.

Thanks!

**Comment by csgorham** [comment]
I cloned two and both gave the error  - my dolt sql function seems to not
function irregardless

dolthub <https://www.dolthub.com/organizations/dolthub> /
cannabis-testing-wa
<https://www.dolthub.com/repositories/Liquidata/cannabis-testing-wa>
oscarbatori <https://www.dolthub.com/users/oscarbatori> /
holidays <https://www.dolthub.com/repositories/oscarbatori/holidays>

**Comment by VinaiRachakonda** [comment]
@csgorham Thanks for the headsup, we'll get this resolved ASAP.

**Comment by VinaiRachakonda** [comment]
@csgorham We have fixed the cannabis dataset you posted. We're going to keep probing for public datasets and migrate them
