### ISSUE TITLE
Shell completions for bash/zsh/fish

### ISSUE THREAD

**Issue by cmoog** [dolthub/dolt#1961]
This is a nice quality-of-life feature... especially as a new user learning the API surface.

I believe the implementation should be fairly straightforward given that [cobra supports it out-of-the-box](https://github.com/spf13/cobra/blob/master/shell_completions.md), but I could be mistaken. I'm willing to open a PR myself need-be.

**Comment by timsehn** [comment]
This is a good feature request. 

Obviously, we would accept a PR if you get the time. Otherwise, @VinaiRachakonda will get it on his roadmap of customer requests.

**Comment by cmoog** [comment]
After some poking around, I realized that the root `dolt` command doesn't use cobra... so this may be more effort than I initially expected.

**Comment by zachmu** [comment]
This is in the latest release. Run `dolt gen-zsh` to generate a completion file.

Enjoy!
