### ISSUE TITLE
Add support for LOAD_FILE()

### ISSUE THREAD

**Issue by wisn** [dolthub/dolt#1968]
Should be pretty clear. I need the `LOAD_FILE()` function so I can insert my picture as a blob.
I've tried converting the picture into a hex string and then paste it on my terminal.
Apparently, my terminal broke.
I've also tried to update the cell directly on Dolthub.
However, I got the `request header too large` or some sort of error.
Can't think of any alternative. Any input?

**Comment by VinaiRachakonda** [comment]
I think we'll just go ahead and implement LOAD_FILE. Seems like the best way to solve this.

**Comment by timsehn** [comment]
Vinai is gonna finish up ALTER for primary keys and then he's gonna tackle this. It could be really easy of more involved. We'll know more in a week or so.

A strategy in the meantime is to stick your images in cloud storage and then store the link as the key in dolt. Something like we do for logos:

https://www.dolthub.com/repositories/dolthub/logo-2k-extended/data/master/logos

**Comment by wisn** [comment]
Alright, thank you, @VinaiRachakonda @timsehn!

> A strategy in the meantime is to stick your images in cloud storage and then store the link as the key in dolt.

Ah, yes. I can do that too but I guess I will wait and see.

**Comment by VinaiRachakonda** [comment]
This is now in master! We will have a blog coming soon that runs into more detail on how it works

**Comment by wisn** [comment]
@VinaiRachakonda thank you! I will try it ASAP after the blog post is published.

**Comment by VinaiRachakonda** [comment]
Just posted our blog https://www.dolthub.com/blog/2021-08-23-dolt-and-images @wisn

**Comment by wisn** [comment]
@VinaiRachakonda awesome! many thanks
