### ISSUE TITLE
feature request: `dolt commit revert`

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1969]
Mirror the functionality of [`git commit revert`](https://git-scm.com/docs/git-revert#_description). This function should be available from both SQL and the CLI. 

Git commit revert is an interactive function. However, as a first pass, I think we should make `dolt commit revert` a non-interactive function. 
There's also an open question around conflicts and constraint-violations, as these could arise from a revert operation. We could materialize conflicts and constraints as we would with a merge, but again, as a first pass, I think it's fine to simply fail the operation if they occur. 

I'm interested to hear thoughts from others, @Hydrocharged in particular.

**Comment by Hydrocharged** [comment]
We also have to consider schema changes and table additions as well. Looking through the documentation for git's version, they may somehow use their merge logic, which would automatically give us conflicts and such if we followed that same path, but I don't think it's quite possible for us with our current implementation of merge.

**Comment by Hydrocharged** [comment]
In addition, `git revert` commits the result as a part of the workflow. Do we just want to update the working set, or also commit?

**Comment by andrew-wm-arthur** [comment]
I was also thinking that using the merge path would be the simplest/best approach. I think we could factor out a common "apply" algorithm that we can use for both paths. 

As far as commit semantics, we should mirror what Git does. I think parody is important, and it happens to be easier to integrate with applications this way

**Comment by Hydrocharged** [comment]
Implemented in https://github.com/dolthub/dolt/pull/2003
