### ISSUE TITLE
dolt blame come out in random order each time

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#197]
This makes it hard to compare two consecutive blame outputs.

Can we pick a consistent row ordering? Preferably the same ordering as we use in other sql tables?

**Comment by timsehn** [comment]
Was this fixed with your migration to the SQL path @druvv ?

**Comment by druvv** [comment]
This was fixed a while back. For keyless tables the order may be non-deterministic, but from my testing it's atleast consistent for a small number of rows.
