### ISSUE TITLE
Creating Boolean type field in table in dolthub UI fails.

### ISSUE THREAD

**Issue by AmirAktify** [dolthub/dolt#1977]
The following query fails in the `dolthub ui`. Whereas replacing Boolean with TinyInt(1) succeeds. This is however listed as supported in dolt's docs: https://docs.dolthub.com/interfaces/sql/sql-support/data-description

CREATE TABLE dev_company (
    company_id INT,
    company_name VARCHAR(255),
    is_buildable BOOLEAN, 
    PRIMARY KEY(company_id)
);

**Comment by timsehn** [comment]
We'll get on this right away. Thanks Amir.

**Comment by zachmu** [comment]
This bug appears to be specific to dolthub. You can work around it by using dolt on the command line until we push a fix.

**Comment by timsehn** [comment]
More specifically, it's a bug in the open source sql parser we use
on DoltHub. We're discussing whether we should just fork it and start
maintaining our own. There are a bunch of bugs with it today.

**Comment by tbantle22** [comment]
This should be fixed now
