### ISSUE TITLE
[Bug] Simple inserts sometimes not saved

### ISSUE THREAD

**Issue by bhigginsuk** [dolthub/dolt#2002]
Apologies for the vaguery around this issue, I don't know much about the inner workings of dolt or relational databases as a whole. This issue appears for me only very infrequently, and as such I don't have a set of reproducible steps.

Sometimes when I run an insert query, the result does not persist. The auto_increment column is incremented, and `select last_insert_id();` returns an incremented id, but the value is not in the table when queried.

When it happens, the table will no longer accept the specific values used. Repeatedly running the same insert query will appear successful, and the id will continue to increment, but the values will never end up in the table.

Other values can be inserted just fine. The issue is "fixed" by changing one of the values to something else, i.e. sticking an underscore on the end or something.

The best way to explain really is with a video demonstration: https://youtu.be/MjkNJGshn6k.

The create statement for the table shown in the video is as follows:
```sql
CREATE TABLE `product` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `genus_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `class_id` (`genus_id`),
  UNIQUE KEY `name` (`name`),
  CONSTRAINT `fk_product_genus_id` FOREIGN KEY (`genus_id`) REFERENCES `genus` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4
```

System info:
- Arch Linux
- dolt 0.26.0, built from [the AUR](https://aur.archlinux.org/packages/dolt/)

**Comment by VinaiRachakonda** [comment]
@bhigginsuk Thank you for your bug! 

Looking at our revision history, we made some changes to this behavior after version 0.26.0. Is it possible at all for you to upgrade and try again? 

We aren't maintaining Dolt distribution on Aur even though we should. I would recommend building from source.

**Comment by zachmu** [comment]
Definitely please try again with the latest revision. I can't offhand understand how this is happening, but 26.0 is actually quite old, especially as it relates the SQL shell.

If you can reproduce it with the latest version, we will be eager to dig in more from our side.

**Comment by bhigginsuk** [comment]
My apologies for submitting a bug on an out of date version, I submitted the issue right as I was logging off and posting the OS/version details only popped into my head right before I logged out; I didn't check for an updated version.

I have updated to 0.27.4.2, which appears to resolve the issue.

Whereas I initially thought the issue was with the insert failing, it would seem the issue is/was a little more complex than that. Even though my issue is now resolved I'll post some feedback just in case it's helpful.

If you look in my video, you can see that (unnoticed by me at the time) 'Chard' was actually already in my 'product' table, with id 196. Presumably that was the next available id the very first time I tried this insert.
The issue that arose at the time was that subsequent queries referencing '196' as a foreign key said that no such id existed, which is why I would have tried a few times, each time with the results shown in the video (id increments, appears successful, not actually there).
What is also confusing is that, with version 0.26.0, querying the table is inconsistent with whether it returns the entry or not. You can see it in the video, but it did not show when I ran the query again just now (with v0.26.0).
![image](https://user-images.githubusercontent.com/14295333/130295334-ace93583-0df7-4511-b21f-0839f75f622e.png)

Anyway, v0.27.4.2 correctly shows it in the query, and returns an error message, although it doesn't appear to quite be the right one. I would expect it to warn me of duplicate unique key 'Chard, but this may just be a semantics issue.
![image](https://user-images.githubusercontent.com/14295333/130295438-6f9858c9-8bce-4ae4-a37c-e597b8a76f5f.png)

If the problem reoccurs I'll reopen the issue.

**Comment by timsehn** [comment]
Thanks for the detailed feedback. @Hydrocharged how do you feel about that error message?

**Comment by Hydrocharged** [comment]
So on duplicate unique key errors, we're listing the primary keys that contain the existing duplicate key rather than the duplicate key itself. This was chosen as it was reasoned that the user already has the key itself (in this case we're inserting `Chard` so we already know that value), so it is more useful to state which row contains the duplicate value that is preventing the insertion of the user's value. We can update the error message to reflect this (such as `duplicate unique key given on row with pk: [x]`), list the full row, or we can reiterate the unique key that caused the duplicate issue.

Of note, MySQL lists the given key (the last option I mentioned), and leaves it up to the user to determine the conflicting row through a query if that information is desired.
