### ISSUE TITLE
Non-deterministic import behavior on `dolt table import`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2020]
Skipped bats test here:

https://github.com/dolthub/dolt/pull/2019

Repeating multiple rows in a CSV and using `--update --continue` should produce the same import every time.

**Comment by rishawsingh** [comment]
I want resolve this issue can you explain me how can I do it?

**Comment by timsehn** [comment]
Come on our Discord and we'll help you out.

https://discord.com/invite/RFwfYpu

**Comment by jennifersp** [comment]
in writeRow function, it checks for whether the row needs to be inserted or updated based on only initialData instead of currentData with previous insertion/update, so that it tries to insert all the rows with the first update command into empty table instead of updating.

**Comment by VinaiRachakonda** [comment]
This is fixed with #2426
