### ISSUE TITLE
diffs displayed incorrectly

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#2039]
This is an issue I encountered during the `us-schools` bounty.

To repro:

Start with the db from https://www.dolthub.com/repositories/dolthub/us-schools at commit 38j86l.

Export the table:
```
dolt table export schools master.csv
```
Then, in a notebook:
```
import pandas as pd

# replace the filename here
df = pd.read_csv('db/master.csv', dtype = {'zip': str})

# the cleaner way is to do with with a map/dict, 
# but this way gives you slightly more control
df['name'] = (df['name']
              .str.replace(' EL$', ' ELEMENTARY')
              .str.replace(' EL ', ' ELEMENTARY ')
              .str.replace(' ELEM$', ' ELEMENTARY')
              .str.replace(' ELEM ', ' ELEMENTARY ')
              .str.replace(' SCH$', ' SCHOOL')
              .str.replace(' SCH ', ' SCHOOL ')
              .str.replace(' SCHL$', ' SCHOOL')
              .str.replace(' SCHL ', ' SCHOOL ')
              .str.replace(' ES ', ' ELEMENTARY SCHOOL ')
              .str.replace(' ES$', ' ELEMENTARY SCHOOL')
              .str.replace(' MS$', ' MIDDLE SCHOOL')
              .str.replace(' MS ', ' MIDDLE SCHOOL ')
              .str.replace(' HS$', ' HIGH SCHOOL')
              .str.replace(' HS ', ' HIGH SCHOOL ')
              .str.replace(' H S ', ' HIGH SCHOOL ')
              .str.replace(' H S$', ' HIGH SCHOOL')
              .str.replace(' M S ', ' MIDDLE SCHOOL ')
              .str.replace(' M S$', ' MIDDLE SCHOOL')
              .str.replace(' E S ', ' ELEMENTARY SCHOOL ')
              .str.replace(' E S$', ' ELEMENTARY SCHOOL')
            )
df.to_csv('db/master_noabbrev.csv', index = False)
```
Try to import it with
```
dolt table import -r schools master_noabbrev.csv
```
followed by
```
dolt diff
```
In my case, I saw many rows appear in the diff whose cells were completely unchanged.

Notably, and irrespective of whether this is an issue on my end, it's apparent that dolt diffs can sometimes display rows as edited (with the green/red +/-) even when they are apparently the same as before.

**Comment by timsehn** [comment]
I tried repro-ing this with:
```
dolt sql -q "create table test(pk int, c1 int, primary key(pk))"
dolt sql -q "insert into test ('foo', 'bar', 'baz')"
dolt commit -am "Created table"
dolt table export test test.csv
dolt table import -r test test.cs
dolt diff
```
No diff. Something more subtle is going on.

**Comment by timsehn** [comment]
I'm gonna go out on a limb and blame pandas.

**Comment by timsehn** [comment]
This suggests there is something about the decoding and encoding of some of these string primary keys that causes them to not come back as they were put in:
us-schools $ dolt table export -f schools test.csv

Successfully exported data.
us-schools $ dolt table import -r schools test.csv
Rows Processed: 141792, Additions: 141792, Modifications: 0, Had No Effect: 0
Import completed successfully.
us-schools $ dolt diff --summary
diff --dolt a/schools b/schools
--- a/schools @ cmb8s96ah66c14s3ekqleh094ju9kqtt
+++ b/schools @ su1ba979u6hst1evpion7c8d1ui8q0j8
112,282 Rows Unmodified (79.19%)                                              
0 Rows Added (0.00%)
0 Rows Deleted (0.00%)
29,510 Rows Modified (20.81%)
0 Cells Modified (0.00%)
(141,792 Entries vs 141,792 Entries)

us-schools $

**Comment by timsehn** [comment]
Once it's exported and imported back, there is no diff:
```
us-schools $ dolt checkout -b tim/test-encoding
Switched to branch 'tim/test-encoding'
us-schools $ dolt commit -am "Trying again"
commit 3vg5ilvmmk6i5ec29pc43kle61qb3vj3
Author: Tim Sehn <tim@liquidata.co>
Date:   Thu Aug 19 15:58:20 -0700 2021

	Trying again

us-schools $ dolt table export -f schools test.csv

Successfully exported data.
us-schools $ dolt table import -r schools test.csv
Rows Processed: 141792, Additions: 141792, Modifications: 0, Had No Effect: 0
Import completed successfully.
us-schools $ dolt diff --summary
```

**Comment by alecstein** [comment]
Here's something to look into -- whether it's the source of this problem or not, it is a problem.

`dolt table export` exports floats to 5 decimal places. But some of the `lat`/`lon` are 10 decimal places or more. When they are reimported those cells should be truncated, and the cells should show a diff.

They do not show a diff. Dolt shows those cells as unchanged.

**Comment by timsehn** [comment]
I'll test float precision. Good thought.

**Comment by timsehn** [comment]
Testing the above right now.

**Comment by alecstein** [comment]
I'm testing it as well. I think I might be wrong -- it's hard to know what is truncating what. But we'll see.

**Comment by timsehn** [comment]
If it's float precision it's not reproducible on the command line easily:
```
bats-working $ dolt sql -q "create table test (pk int, num float, primary key(pk))"
bats-working $ dolt sql -q "insert into test values (0, 1.1111111111111111111111111)"
Query OK, 1 row affected
bats-working $ dolt sql -q "select * from test"
+----+-----------+
| pk | num       |
+----+-----------+
| 0  | 1.1111112 |
+----+-----------+
bats-working $ dolt commit -am "added table"
commit rf55mjuoejki7mmq6qh8207snltjrbtj
Author: Tim Sehn <tim@liquidata.co>
Date:   Thu Aug 19 16:30:31 -0700 2021

	added table

bats-working $ dolt table export test test.csv
test.csv already exists. Use -f to overwrite.
bats-working $ dolt table export -f test test.csv

Successfully exported data.
bats-working $ dolt table import -r test test.csv
Rows Processed: 1, Additions: 1, Modifications: 0, Had No Effect: 0
Import completed successfully.
bats-working $ dolt diff
bats-working $ cat test.csv 
pk,num
0,1.1111112
```

**Comment by alecstein** [comment]
![image](https://user-images.githubusercontent.com/16236421/130157159-b2d68733-7af9-4790-b728-3530e19db69e.png)

I believe it is float precision. Let me know what you think.

**Comment by alecstein** [comment]
![image](https://user-images.githubusercontent.com/16236421/130157504-09b616ac-1fea-4f46-a8e4-3ae2680e9641.png)

The previous image was of a row that erroneously appeared as diffed. 

This is one of the rows that didn't get diffed. Same float.

**Comment by timsehn** [comment]
Float precision as mangled by Pandas?

**Comment by alecstein** [comment]
Okay so for more good times on this, I thought I'd see if I could get around it by working directly with the connection stream. But that still reproduces the problem.

```
# On the command line, do
# dolt sql server

from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root@127.0.0.1:3306/db")
connection = engine.connect()
df = pd.read_sql_table('schools', connection)

df['name'] = (df['name']
              .str.replace(' EL$', ' ELEMENTARY')
            )

df = (df.drop_duplicates(subset = ['name', 'city', 'state'])
            .set_index(['name', 'city', 'state']
        )

# Before running the next command,
# open another terminal and manually truncate the table with
# dolt sql
# > truncate table schools;

df.to_sql('schools', con=connection, if_exists='append')
```

This reproduces the same error as in the original post. This tells me that it's not just csv export that's the issue, but potentially how dolt is storing/loading the floats.

**Comment by timsehn** [comment]
Brian's investigation seems to indicate it has nothing to do with float precision and something to do with `NULL`s in the `website` column.

**Comment by alecstein** [comment]
Oh great, Brian is such a genius.

But there does seem to be a problem with csv export regardless. See the video below.

The pandas csv comes from reading the dolt data directly through a sql connection and then exporting to csv. The dolt csv comes from `dolt table export schools testdlt.csv`. You can see the difference in precision. 

https://user-images.githubusercontent.com/16236421/130271555-ce265a49-3c8b-40e3-8037-37e206c12eaf.mov

**Comment by timsehn** [comment]
I think that's expected. Floats have to be truncated at some precision on export. Each client will handle that differently.
