### ISSUE TITLE
client version mismatch with aws remote

### ISSUE THREAD

**Issue by shirouto** [dolthub/dolt#2052]
I am trying to clone a aws remote set up by a coworker, and I am running into this:

```
14 of 14 chunks complete. 0 chunks being downloaded currently.
error: could not get the root value of master
cause: client (version: 0) is out of date and must upgrade to read this repo (version: 1).
       	visit https://github.com/dolthub/dolt/releases/latest/
```

For one thing, I am running the latest client version:

```
dolt version 0.24.1
```

The other thing that happened and left me a bit reeling is that by mistake I ran something like

```
dolt clone  aws://[table:bucket]/database .
```

in a directory where I had other stuff. It basically clobbered and wiped everything in the current directory. This is definitely not matter to pass around to our typical analysts. :-/

**Comment by VinaiRachakonda** [comment]
This is now fixed in master. A realease will be out shortly with the fix!

**Comment by timsehn** [comment]
Sorry. This was a nasty bug.

**Comment by shirouto** [comment]
That was quick. Thanks for fixing this. 

Just to make sure I understand. This will fix the issue on client versions starting with the next release, which means we must take care to having all users on clients with this version or newer. If the user is on an older client she may still have a nasty surprise. ;-)

Anyway, I intend to give it a spin off master. Thanks.
