### ISSUE TITLE
Dolt doesn't respect primary key for sort order

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2070]
If you declare a table like so:

```sql
create table test (a int, b int, c int, primary key (b,a))
```

Dolt's uses `(a,b)` as the key for internal sorting. This typically isn't visible to clients so it isn't a major bug, but should still be fixed.

This behavior is due to go-mysql-server's schema interface treating primary key as a boolean attribute of a column, when it should be a distinct top-level entity.

**Comment by bheni** [comment]
~/test>dolt init
Successfully initialized dolt data repository.

~/test>dolt sql -q 'CREATE TABLE test (pk BIGINT, c1 BIGINT, PRIMARY KEY(c1,pk));'

~/test>dolt sql -q 'INSERT INTO test VALUES (0,5),(1,4),(2,3),(3,2),(4,1),(5,0);'
Query OK, 6 rows affected

~/test>dolt table export test temp.csv -f
Successfully exported data.

~/test>cat temp.csv
pk,c1
0,5
1,4
2,3
3,2
4,1
5,0

**Comment by zachmu** [comment]
This is a major bug now that indexed lookups are better. Max to address.

**Comment by timsehn** [comment]
This is fixed:
```
test-pk-order $ dolt init --new-format
Successfully initialized dolt data repository.
test-pk-order $ dolt sql -q 'CREATE TABLE test (pk BIGINT, c1 BIGINT, PRIMARY KEY(c1,pk));'
test-pk-order $ dolt sql -q 'INSERT INTO test VALUES (0,5),(1,4),(2,3),(3,2),(4,1),(5,0);'
Query OK, 6 rows affected
test-pk-order $ dolt sql -q "select * from test";
+----+----+
| pk | c1 |
+----+----+
| 5  | 0  |
| 4  | 1  |
| 3  | 2  |
| 2  | 3  |
| 1  | 4  |
| 0  | 5  |
+----+----+
```
