### ISSUE TITLE
sql-server INSERT performance is unacceptable for reasonably sized data imports.

### ISSUE THREAD

**Issue by reltuk** [dolthub/dolt#2091]
From #2088

```r
library(nycflights13)
library(RMariaDB13)
conn <- dbConnect(RMariaDB::MariaDB(), host = "127.0.0.1", port = 3333,
                       username = "user", password = "pwd", dbname = "doltdb")
dbWriteTable(dolt_conn, "flights", nycflights13::flights, overwrite = TRUE)
```

Results in a stream of 336,776 `INSERT INTO flights VALUES (?, ?, ?, ...);` statements being sent to the server on a single prepared statement. Each write fully flushes the table editor, reifies the prolly tree map, and takes on the order of 5ms on average on my laptop. The end result is that the import takes ~ 25 minutes.

The data set is ~40MB in size and there are only a few hundred thousand rows.

`dolt sql` and `dolt table import` have special handling for the import case, and it is much more efficient to batch the inserts and flush the map edits in batches. We should consider whether we can add similar functionality to a given sql-server session so that it does not flush table and index editors until it needs to perform a read or commit a transaction.

**Comment by max-hoffman** [comment]
This behavior is documented in our benchmarks, and we have a tool to batch and speed up large volumes of individual INSERT queries:
https://github.com/dolthub/insert-batcher
