### ISSUE TITLE
Rename "master" to "main"

### ISSUE THREAD

**Issue by josh-chamberlain** [dolthub/dolt#2113]
The base branch should be "main", not "master", to remove [unnecessary problematic language](https://medium.com/idealo-tech-blog/inclusive-language-in-tech-82b19b34b7cf).

This could be the default base branch for repos moving forward, or it could be somehow applied retroactively.

You could also give people the ability to rename, but there's no advantage to sticking with `master`.

https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by timsehn** [comment]
This is done in version 0.30.0+

https://www.dolthub.com/blog/2021-09-29-dolt-and-dolthub-init-main/
