### ISSUE TITLE
dolt should invoke the pager for long output

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2122]
Commands like `dolt log` dump pages of text to the screen. Should be in a pager by default, as with git.

**Comment by rustiever** [comment]
Hi @zachmu, i would like to work on this. I'm beginner to Go and open source contributions. Is there any contribution guide and local setup guide so that i can refer. And i will appreciate your help when i get struck at any point. Thanks.

**Comment by timsehn** [comment]
Welcome!

This is the best contribution guide we have: 

https://www.dolthub.com/blog/2021-09-08-how-to-contribute-to-dolt/

It's about how to make a change to `go-mysql-server` but you should be able to port it well to a Dolt change. 

If you get stuck, come chat with us on Discord:

https://discord.com/invite/RFwfYpu
