### ISSUE TITLE
SQL method to examine schema diffs

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2145]
`dolt_diff_table` and friends are focused on the data diff between two commits. We need a similar way to examine schema diffs in the SQL context.

Current methods to inspect historical schema:

```sql
test> show create table `test/0i4vscdluqolq3p6p8qrq5te916sr7c4`.x;
+-------+-----------------------------------------------------------------------------------------------------------------+
| Table | Create Table
        |
+-------+-----------------------------------------------------------------------------------------------------------------+
| x     | CREATE TABLE `x` (
  `y` bigint NOT NULL,
  `z` bigint,
  PRIMARY KEY (`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+-------+-----------------------------------------------------------------------------------------------------------------+
test> desc `test/0i4vscdluqolq3p6p8qrq5te916sr7c4`.x;
+-------+--------+------+-----+---------+-------+
| Field | Type   | Null | Key | Default | Extra |
+-------+--------+------+-----+---------+-------+
| y     | bigint | NO   | PRI |         |       |
| z     | bigint | YES  |     |         |       |
+-------+--------+------+-----+---------+-------+
```

It would be nice if we also supported the following (currently syntax errors):

```sql
show create table foo as of 'HEAD~';
desc foo as of 'HEAD~';
```

But these just give you the schema at a point in time, not a diff.

Some ideas for structured schema diffs:

1) More system tables: dolt_schema_diff_tablename
2) Use the information_schema database or a custom dolt extension of it, similar to the above

**Comment by timsehn** [comment]
As we've discussed `as of` here is not in the SQL standard and will require a fork of Vitess.

**Comment by timsehn** [comment]
There is now the `dolt_patch()` stored procedure that should produce the alters statements between two diffs. Still need a bunch more ways. This is a hole for Dolt.

**Comment by tbantle22** [comment]
`dolt_patch('--schema')` that just shows sql statements that modify the schema would be cool/useful for the hosted workbench

**Comment by zachmu** [comment]
The `dolt_schema_diff` table function solves this for a human user, but the fact that its output is `create table` statements means it's going to be hard to consume in an application context.

**Comment by timsehn** [comment]
Resolving as we have: `dolt_schema_diff()` table function and `dolt_patch('--schema')`
