### ISSUE TITLE
Support `JSON_TABLE()` function

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2163]
MySQL 8.0.4 added support for the `JSON_TABLE()` function: https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html

I think this is a very cool feature and would be great to have in Dolt.

**Comment by zachmu** [comment]
This is probably going to be a little bit longer off. We can prioritize it if it's blocking something you need.

A little closer at hand is `VALUES`, which is a another way to easily specify static table data: https://dev.mysql.com/doc/refman/8.0/en/values.html

And of course, common table expressions and subqueries already work today.

**Comment by knutwannheden** [comment]
I see. I find `JSON_TABLE()` most useful when the database contains JSON documents in a column, as the data can then be used in queries. E.g. in a `FROM` clause it can be joined:
```sql
select pa.vorname, pa.nachname, x.name
from parlamentarier pa
join json_table(pa.parlament_interessenbindungen_json, '$[*]' columns (name varchar(1000) path '$."Name"')) x
```

**Comment by knutwannheden** [comment]
It will be exciting to test the `JSON_TABLE` function in the next release.

**Comment by JCOR11599** [comment]
`JSON_TABLE` functionality has made its way up to main. Feel free to pull if you want to try it out early!
Expect a release later today.

Just a heads up that we currently don't support `FOR ORDINALITY` or `NESTED` right now.
Here's a simple example of what it does in dolt
```
tmp> SELECT * FROM JSON_TABLE( '[{"a":1},{"a":2}]', "$[*]" COLUMNS( x varchar(100) path "$.a" ) ) as t;
+---+
| x |
+---+
| 1 |
| 2 |
+---+
```

Let us know how it works for you and comment any issues or feature requests you want us to prioritize.

**Comment by knutwannheden** [comment]
I can confirm that the example query works. If I find any more problems, I will report separate issues. I think this issue can be closed then. Thank you!
