### ISSUE TITLE
Support `EXISTS` predicates and expressions

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2164]
When I execute a query with an `EXISTS` predicate (see https://dev.mysql.com/doc/refman/5.7/en/exists-and-not-exists-subqueries.html) I get an error like: `[HY000][1105] unsupported syntax: exists (select 1 from dual)`.

Simple example:

```sql
select 1
from dual
where exists(select 1 from dual)
```

So unless I missed something, `EXISTS` predicates are at the moment not supported.

MySQL in fact also supports `EXISTS` expressions in the `SELECT` clause:

```sql
select exists(select null from dual)
from dual
```

Until Dolt supports this, it would probably be worth mentioning in the documentation, as I think this is a very frequent construct to be used (at least the predicate form).

**Comment by timsehn** [comment]
Agree it should be in the documentation.

**Comment by knutwannheden** [comment]
FWIW, this is the issue I would give most of my votes.

**Comment by zachmu** [comment]
Thanks for bringing this up.

Vinai is going to start on this today. Should be in next week's release.

**Comment by timsehn** [comment]
https://github.com/dolthub/go-mysql-server/pull/572

Just need to bump GMS and this will be fixed.

**Comment by VinaiRachakonda** [comment]
Merged in master
