### ISSUE TITLE
Bug: [HY000][1105] ambiguous column name

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2165]
The following query gives an error when running: `[HY000][1105] ambiguous column name "b", it's present in all these tables: t, t2`

```sql
select t.a a, count(distinct t2.b)
from (select 1 a, 2 b from dual) t
join (select 1 a, 3 b from dual) t2 on t2.a = t.a
group by 1
```

For some reason the query works fine when I remove the alias from the group by column:

```sql
select t.a, count(distinct t2.b)
from (select 1 a, 2 b from dual) t
join (select 1 a, 3 b from dual) t2 on t2.a = t.a
group by 1
```

**Comment by knutwannheden** [comment]
The `distinct` in the example given doesn't appear to have anything to do with the problem and I have also encountered other queries without aliases in the `SELECT` clause which have this problem. So far I have only seen it in `GROUP BY` queries, but I didn't do that much testing yet.

**Comment by zachmu** [comment]
Thanks for the report, we're investigating this today.

**Comment by timsehn** [comment]
This is resolved:
```
test-join-plan $ dolt sql -q "select t.a a, count(distinct t2.b)
> from (select 1 a, 2 b from dual) t
> join (select 1 a, 3 b from dual) t2 on t2.a = t.a
> group by 1"
+---+----------------------+
| a | count(distinct t2.b) |
+---+----------------------+
| 1 | 1                    |
+---+----------------------+
```
