### ISSUE TITLE
Missing indexes when join condition uses extra conditions

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2170]
I have a `GROUP BY` query with multiple `JOIN`s which runs quite slow in Dolt (~90 sec) compared to MySQL (~400 ms) when executed against the data in https://www.dolthub.com/repositories/knutwannheden/lobbywatch:

```sql
select rechtsform,
       count(1)                                                  anz,
       count(i.id)                                               anz_bind,
       count(distinct pa.id)                                     anz_parl,
       count(m.id)                                               anz_mand,
       count(distinct p.id)                                      anz_pers,
       count(case when i.id is null and m.id is null then 1 end) anz_ohne
from organisation o
         left join interessenbindung i
                   on o.id = i.organisation_id and now() between coalesce(i.von, now()) and coalesce(i.bis, now())
         left join parlamentarier pa
                   on pa.id = i.parlamentarier_id and now() between pa.im_rat_seit and coalesce(pa.im_rat_bis, now())
         left join mandat m on o.id = m.organisation_id and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
         left join person p on p.id = m.person_id and now() >= coalesce(p.zutrittsberechtigung_von, now())
group by rechtsform
order by 2 desc
;
```

Here is the link to the named query ("slow analytics query"): https://www.dolthub.com/repositories/knutwannheden/lobbywatch/query/master?q=select+rechtsform%2C++++++++count%281%29++++++++++++++++++++++++++++++++++++++++++++++++++anz%2C++++++++count%28i.id%29+++++++++++++++++++++++++++++++++++++++++++++++anz_bind%2C++++++++count%28distinct+pa.id%29+++++++++++++++++++++++++++++++++++++anz_parl%2C++++++++count%28m.id%29+++++++++++++++++++++++++++++++++++++++++++++++anz_mand%2C++++++++count%28distinct+p.id%29++++++++++++++++++++++++++++++++++++++anz_pers%2C++++++++count%28case+when+i.id+is+null+and+m.id+is+null+then+1+end%29+anz_ohne+from+organisation+o++++++++++left+join+interessenbindung+i++++++++++++++++++++on+o.id+%3D+i.organisation_id+and+now%28%29+between+coalesce%28i.von%2C+now%28%29%29+and+coalesce%28i.bis%2C+now%28%29%29++++++++++left+join+parlamentarier+pa++++++++++++++++++++on+pa.id+%3D+i.parlamentarier_id+and+now%28%29+between+pa.im_rat_seit+and+coalesce%28pa.im_rat_bis%2C+now%28%29%29++++++++++left+join+mandat+m+on+o.id+%3D+m.organisation_id+and+now%28%29+between+coalesce%28m.von%2C+now%28%29%29+and+coalesce%28m.bis%2C+now%28%29%29++++++++++left+join+person+p+on+p.id+%3D+m.person_id+and+now%28%29+%3E%3D+coalesce%28p.zutrittsberechtigung_von%2C+now%28%29%29+group+by+rechtsform+order+by+2+desc+%3B&active=Queries

**Comment by zachmu** [comment]
Not sure exactly why yet, but our analyzer is getting confused by your join condition, causing it to miss every join index. If I move the extra clauses (not used to join tables, but part of the join condition) to the `WHERE` clause, it can use the indexes.

```sql
select rechtsform,
       count(1)                                                  anz,
       count(i.id)                                               anz_bind,
       count(distinct pa.id)                                     anz_parl,
       count(m.id)                                               anz_mand,
       count(distinct p.id)                                      anz_pers,
       count(case when i.id is null and m.id is null then 1 end) anz_ohne
from organisation o
         left join interessenbindung i on o.id = i.organisation_id
         left join parlamentarier pa on pa.id = i.parlamentarier_id 
         left join mandat m on o.id = m.organisation_id 
         left join person p on p.id = m.person_id 
         where 
             now() between coalesce(i.von, now()) and coalesce(i.bis, now())
             and now() between pa.im_rat_seit and coalesce(pa.im_rat_bis, now())
             and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
             and now() >= coalesce(p.zutrittsberechtigung_von, now())
group by rechtsform
order by 2 desc;
```

The analyzer is supposed to do this on its own, but it's confused for some reason I haven't found yet, maybe coalesce?

**Comment by knutwannheden** [comment]
Moving the predicates from the `JOIN`'s `ON` clause into the query's `WHERE` clause is generally only equivalent in the case of inner joins. Here I do all outer joins, but the predicates all deal with `NULL`s except for one, but there may be a `NOT NULL` constraint on that column. So in this particular case it may be OK to move the predicates. Thanks for finding this workaround.

**Comment by knutwannheden** [comment]
I just tested the two queries (predicates in `JOIN`'s `ON` vs. predicates in `WHERE`) and they don't return the same result. This is due to what I said about outer joins and the fact that the predicates get applied as a filter on the joined rows when used in the `WHERE` clause. So in this case the workaround is not applicable.

**Comment by zachmu** [comment]
OK, it took me a little while to understand your schema and query well enough to figure out why the workaround gives different results. It's because the parlamentarier table's join clause doesn't coalesce like the other ones do. This returns (almost) the same result, and is much faster:

```sql
select rechtsform,
       count(1)                                                  anz,
       count(i.id)                                               anz_bind,
       count(distinct pa.id)                                     anz_parl,
       count(m.id)                                               anz_mand,
       count(distinct p.id)                                      anz_pers,
       count(case when i.id is null and m.id is null then 1 end) anz_ohne
from organisation o
         left join interessenbindung i on o.id = i.organisation_id
         left join parlamentarier pa on pa.id = i.parlamentarier_id
         left join mandat m on o.id = m.organisation_id
         left join person p on p.id = m.person_id
         where
             now() between coalesce(i.von, now()) and coalesce(i.bis, now())
             and now() between coalesce(pa.im_rat_seit, now()) and coalesce(pa.im_rat_bis, now())
             and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
             and now() >= coalesce(p.zutrittsberechtigung_von, now())
group by rechtsform
order by 2 desc;
```

This query produces the same output except for an entry in the `anz_ohne` column, which you can probably figure out how to correct faster than I can:

```
< ag    1773    467     140     242     105     1100  (modified query)
---
> ag    1772    467     140     242     105     1099   (original query)
```

**Comment by knutwannheden** [comment]
Thanks for the analysis. I will take a closer look at this tomorrow.

I would just like to point out that this is a more or less random ad-hoc query I found to run very slow compared to when run in MySQL. The query may not make much sense and I don't need a workaround to make it run fast in Dolt. I just provided it to help you find the "problem" in your optimizer. I am sorry for not pointing this out earlier.

**Comment by zachmu** [comment]
Not at all, we appreciate the report. I encountered several other bugs while looking into this one, it's always worthwhile.

And in fact this particular problem with the analyzer is impacting other customers as well, it's definitely something we need to fix in the general case. I'm working on this now so should have something to show for it relatively soon.

**Comment by knutwannheden** [comment]
> This query produces the same output except for an entry in the `anz_ohne` column, which you can probably figure out how to correct faster than I can.

This is interesting. Also the column `anz` shows a difference of 1. But I now also get the impression that Dolt returns wrong data, because I think the data returned by the two queries should in fact be quite different. I will try to narrow it down using a simpler example and report a separate issue for this.

Also, I was going to try to make the query a bit easier to understand by making an explicit tree of `JOIN`s and replace some of the `LEFT JOIN`s with normal `JOIN`s, but it turns out Dolt can't parse that. I know this is rather esoteric syntax, but if you like I can report a separate issue for this.
```sql
select rechtsform,
       count(distinct o.id)                                                  anz,
       count(distinct i.id)                                                  anz_bind,
       count(distinct pa.id)                                                 anz_parl,
       count(distinct m.id)                                                  anz_mand,
       count(distinct p.id)                                                  anz_pers,
       count(distinct case when i.id is null and m.id is null then o.id end) anz_ohne
from organisation o
         left join (
            interessenbindung i
            join parlamentarier pa
            on pa.id = i.parlamentarier_id and now() between pa.im_rat_seit and coalesce(pa.im_rat_bis, now())
         )
         on o.id = i.organisation_id and now() between coalesce(i.von, now()) and coalesce(i.bis, now())
         left join (
            mandat m
            join person p
            on p.id = m.person_id and now() >= coalesce(p.zutrittsberechtigung_von, now())
        )
        on o.id = m.organisation_id and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
group by rechtsform
order by 1
;
```

**Comment by zachmu** [comment]
> But I now also get the impression that Dolt returns wrong data, because I think the data returned by the two queries should in fact be quite different.

I don't quite understand the difference between these queries myself, but what I can tell you is that I tested both of them in Dolt and MySQL, and Dolt behaves identically to MySQL for these queries. 

I filed #2203 for the explicit join tree issue.

**Comment by knutwannheden** [comment]
Taking a simpler example I think the difference with the predicate in the `JOIN` vs in the query's `WHERE` clause becomes clear:

```sql
create table a(id int, val varchar(10));
create table b(id int, val varchar(10));
create table a_b(a_id int, b_id int);

insert into a(id, val) values (1, 'one'), (2, 'two'), (3, 'three');
insert into b(id, val) values (4, 'four'), (5, 'five'), (6, 'six');
insert into a_b(a_id, b_id) select a.id, b.id from a cross join b;
```

The query:
```sql
select *
from a_b
         left join a on a.id = a_b.a_id and a.val like '%t%'
         left join b on b.id = a_b.b_id and b.val like '%f%'
order by 1, 2
;
```

will return:
```
+----+----+----+-----+----+----+
|a_id|b_id|id  |val  |id  |val |
+----+----+----+-----+----+----+
|1   |4   |NULL|NULL |4   |four|
|1   |5   |NULL|NULL |5   |five|
|1   |6   |NULL|NULL |NULL|NULL|
|2   |4   |2   |two  |4   |four|
|2   |5   |2   |two  |5   |five|
|2   |6   |2   |two  |NULL|NULL|
|3   |4   |3   |three|4   |four|
|3   |5   |3   |three|5   |five|
|3   |6   |3   |three|NULL|NULL|
+----+----+----+-----+----+----+
```

Just moving the additional `JOIN` predicates into the `WHERE` clause is obviously wrong. In fact I can't think of a straightforward alternative of writing this query right now.

I will still take a look at what I think seems to be wrong with the data returned by Dolt for my original query.

**Comment by zachmu** [comment]
Smaller test case, from SHAQ dataset.

With an index on (first_name, last_name), this uses an index:

`select player_id from players where first_name = 'Mark' and last_name = 'Landsberger';`

but this does not:

`select player_id from players where first_name = 'Mark' and last_name = 'Landsberger' and player_id < 10;`

**Comment by knutwannheden** [comment]
I just retested this and can confirm that this performance problem still persists.

**Comment by timsehn** [comment]
@max-hoffman Can you take a look at this one?

**Comment by max-hoffman** [comment]
I am fixing the latest query zach posted above, I have an easy repro and the root cause is clear. After that I will loop back to the first query and see if anything else is holding that back.

**Comment by knutwannheden** [comment]
As commented earlier, the query in the issue description is just some "random" ad-hoc query I came up with when testing Dolt. I now ran it again and it doesn't work anymore with the latest version of Dolt. I am actually not sure why it apparently worked before, because there is an error in it.

FWIW, here is a corrected query running against the same data (takes around 35s to execute on my machine):
```sql
select rechtsform,
       count(1)                                                  anz,
       count(i.id)                                               anz_bind,
       count(distinct pa.id)                                     anz_parl,
       count(m.id)                                               anz_mand,
       count(distinct p.id)                                      anz_pers,
       count(case when i.id is null and m.id is null then 1 end) anz_ohne
from organisation o
         left join interessenbindung i
                   on o.id = i.organisation_id and now() between coalesce(i.von, now()) and coalesce(i.bis, now())
         left join parlamentarier pa
                   on pa.id = i.parlamentarier_id and now() between pa.im_rat_seit and coalesce(pa.im_rat_bis, now())
         left join mandat m on o.id = m.organisation_id and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
         left join zutrittsberechtigung p on p.person_id = m.person_id and now() >= coalesce(p.von, now())
group by rechtsform
order by 2 desc
;
```

**Comment by max-hoffman** [comment]
All of these queries expose issues regarding filtered ranged scans on an index. We don't handle ranges well, basically. Instead of choosing a subset of equality filters for index lookups, and hoisting the range filters in a parent operation, we exit indexing altogether. The correct behavior would be similar to the query zach posted, where the analyzer selects equality filters for indexed join conditions, and then passes the join result to the remaining filters. We have the same issue for standalone queries that drop an indexing condition when we add a range filter that cannot fold into the range scan.  There are several parts of the analyzer that do this incorrectly, and I am not sure how long these will take to fix. But if the join above has a 1-to-1 relationship for the table `id` columns, i imagine an indexed plan will be an order of magnitude faster when I am done.

**Comment by max-hoffman** [comment]
This fix should give a more reasonable response latency now https://github.com/dolthub/go-mysql-server/pull/1197

```SQL
time dolt sql -q "select rechtsform,
    count(1)                                                  anz,
    count(i.id)                                               anz_bind,
    count(distinct pa.id)                                     anz_parl,
    count(m.id)                                               anz_mand,
    count(distinct p.id)                                      anz_pers,
    count(case when i.id is null and m.id is null then 1 end) anz_ohne
        from organisation o
        left join interessenbindung i
            on o.id = i.organisation_id and now() between coalesce(i.von, now()) and coalesce(i.bis, now())
        left join parlamentarier pa
            on pa.id = i.parlamentarier_id and now() between pa.im_rat_seit and coalesce(pa.im_rat_bis, now())
        left join mandat m on o.id = m.organisation_id and now() between coalesce(m.von, now()) and coalesce(m.bis, now())
        left join zutrittsberechtigung p on p.person_id = m.person_id and now() >= coalesce(p.von, now())
            group by rechtsform
             order by 2 desc;"
+-----------------------------------+------+----------+----------+----------+----------+----------+
| rechtsform                        | anz  | anz_bind | anz_parl | anz_mand | anz_pers | anz_ohne |
+-----------------------------------+------+----------+----------+----------+----------+----------+
| Verein                            | 5571 | 5571     | 244      | 4272     | 577      | 0        |
| Parlamentarische Gruppe           | 4220 | 4220     | 242      | 1837     | 52       | 0        |
| Stiftung                          | 1347 | 1347     | 175      | 1000     | 136      | 0        |
| AG                                | 512  | 512      | 144      | 95       | 56       | 0        |
| Staatlich                         | 274  | 274      | 86       | 188      | 96       | 0        |
| Informelle Gruppe                 | 270  | 270      | 106      | 207      | 25       | 0        |
| Genossenschaft                    | 100  | 100      | 52       | 42       | 18       | 0        |
| Einfache Gesellschaft             | 77   | 77       | 34       | 51       | 19       | 0        |
| Oeffentlich-rechtlich             | 71   | 71       | 42       | 32       | 20       | 0        |
| GmbH                              | 68   | 68       | 54       | 16       | 16       | 0        |
| Einzelunternehmen                 | 28   | 28       | 26       | 1        | 1        | 0        |
| Ausserparlamentarische Kommission | 8    | 8        | 7        | 0        | 0        | 0        |
| KG                                | 2    | 2        | 2        | 1        | 1        | 0        |
+-----------------------------------+------+----------+----------+----------+----------+----------+

________________________________________________________
Executed in    1.47 secs   fish           external
   usr time    2.22 secs   50.55 millis    2.17 secs
   sys time    0.36 secs   12.21 millis    0.35 secs
   ```

**Comment by knutwannheden** [comment]
That looks great. Thanks for looking into this again!

**Comment by timsehn** [comment]
Keep finding slow queries! We're actually in a position to fix them quickly now.

**Comment by knutwannheden** [comment]
As soon as the next release is out I will run some more queries to test the performance

**Comment by knutwannheden** [comment]
I can confirm that the example query executes much faster now. If I find any more problems, I will report separate issues. I think this issue can be closed then. Thank you!
