### ISSUE TITLE
dolt diff output format

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2243]
Currently dolt only supports sql and stdout format. I Wonder if dolt diff cmd will support well-formated output such as json so that developers can ultilize the result more easily.

**Comment by bpf120** [comment]
@liuqianhong6007 Any interest in sharing more about your use case on a quick call with me and Tim? The calls really help us with our roadmap and we can usually give some advice on your Dolt implementation. My email is brianf@dolthub.com.

**Comment by timsehn** [comment]
We support this in `dolt sql` so it should be less than a day's work to put it in `dolt diff`.

```
PS C:\Users\timse\dolthub\dolt\demo> dolt diff
diff --dolt a/employees b/employees
--- a/employees @ aaof9v5tr3stqc825k59bl38ltmapkdq
+++ b/employees @ fadi3bjdfb31sdfmd9ulgh8ejprjvpe7
+---+----+---------+
|   | id | name    |
+---+----+---------+
| + | 5  | Tim     |
| + | 6  | neuriam |
+---+----+---------+
PS C:\Users\timse\dolthub\dolt\demo> dolt diff -r json
invalid output format: json
PS C:\Users\timse\dolthub\dolt\demo> dolt sql -r json -q "select * from employees"
{"rows": [{"id":1,"name":"Jane"},{"id":2,"name":"Jeff"},{"id":3,"name":"Jill"},{"id":4,"name":"Joe"},{"id":5,"name":"Tim"},{"id":6,"name":"neuriam"}]}
```
