### ISSUE TITLE
Any changes made in another branch will be lost if `dolt sql-server` isn't restarted after changing branches

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2244]
To reproduce, start an SQL server, then switch to another (new/existing) branch in a separate terminal/process. Any modifications made whilst in the second branch will be lost as soon as a reset to the original branch occurs. `dolt diff` does not show the changes even whilst in the second branch.

This appears to be related to #2092.

**Comment by zachmu** [comment]
Can you give a more detailed repro of this @abmyii ? I'm not sure I understand the steps exactly.

**Comment by timsehn** [comment]
This is resolved.
