### ISSUE TITLE
`dolt checkout` will stomp uncommitted changes on another branch

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2246]
`dolt checkout` emulates git behavior by taking working set changes with you to the newly checked out branch. This is fine in a command line only world, but in the context of a SQL server, there can be uncommitted working set changes on the destination branch. The current behavior is to overwrite any such changes on the destination branch. Instead, we should detect this condition and refuse to process the checkout until the working set changes are committed or rolled back.

**Comment by timsehn** [comment]
We no longer take changes along with `dolt_checkout()` in the SQL context to resolve this.
