### ISSUE TITLE
`dolt pull` is trying to do a commit for a ff merge

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#2249]
I am doing a `dolt pull` to get new commits from the remote.
There are no local changes/new commits in local branch.
Expected result:
  I expect my branch will be fast-forwarded.
Actual result:
  dolt complains about no committer data set (which is true), however this shouldn't be relevant as I am not doing any commit.

```
dolt-db# dolt status
On branch 210921_updates
nothing to commit, working tree clean
dolt-db# dolt log -n 3 origin/210921_updates | grep commit
commit 7cbh5up1umffe41p9k4lnuakpok6onqb
commit n24jt2vd7rv8mcsmtsuuao70qnb405l2
commit 9voc9iofm5i5bkk9akdgt37tu27vj1td
dolt-db# dolt log -n 1 | grep commit
commit 9voc9iofm5i5bkk9akdgt37tu27vj1td
dolt-db# dolt pull

Aborting commit due to empty committer name. Is your config set?
```

After I set the committer data it goes ok with ff:
```
dolt-db# .... setting committer data

dolt-db# dolt pull

Updating 9voc9iofm5i5bkk9akdgt37tu27vj1td..7cbh5up1umffe41p9k4lnuakpok6onqb
Fast-forward
dolt-db# dolt log -n 3 | grep commit
commit 7cbh5up1umffe41p9k4lnuakpok6onqb
commit n24jt2vd7rv8mcsmtsuuao70qnb405l2
commit 9voc9iofm5i5bkk9akdgt37tu27vj1td
```

`dolt version 0.30.3`

**Comment by timsehn** [comment]
Nevermind. Different bug that I inferred from the title. Dolt doesn't really let you do much without a committer set. We can audit some of the paths and move the check lower in the call stack.
