### ISSUE TITLE
piping large `.sql` files requires significant memory

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#226]
I created a large `.sql` file (7.5gb, 10million rows, 11 columns) and piped it into dolt with the following command:
`$ dolt sql < giant.sql`

About half way through the piping process at ~5 million rows inserted, `dolt` was consuming 22gb of memory and climbing.

**Comment by andrew-wm-arthur** [comment]
@zachmu I believe piping files to the sql server is not batched?

**Comment by zachmu** [comment]
No, the server is never batched. Command line sql command is though.

I don't know whether this problem still exists. A repro (upload the giant problematic file to s3)? would help figure that out.

**Comment by ptman** [comment]
Can stuff be wrapped in transactions to batch?

**Comment by andrew-wm-arthur** [comment]
@ptman what's the use case you're interested in? Generally the fastest write path is `dolt import ...`

**Comment by ptman** [comment]
Right now I have a golang mysql client doing inserts and mem keeps growing. I should probably insert to postgres and import from there, but would like to get rid of the extra step. Also space usage without gc is quite bad. Can sql-server do automatic GCs every now and then like git does?

**Comment by zachmu** [comment]
We've done a lot of work on SQL inserts from the command line, and it's unlikely this bug still exists in its original form.

Tracking sql server garbage collection here:

https://github.com/dolthub/dolt/issues/1987
