### ISSUE TITLE
Dolt Add Commit Statements not working in the MySQL Connector .Net

### ISSUE THREAD

**Issue by AlistairAutonomation** [dolthub/dolt#2262]
I got the .Net example working with the MySQL Connector
Select Statements work but when I try DOLT Add and DOLT Commit ...I see the following errors on the Server 

2021-10-15T08:59:21+10:00 INFO [conn 22] ConnectionClosed {}
2021-10-15T09:00:25+10:00 INFO [conn 23] NewConnection {}
2021-10-15T09:01:19+10:00 WARN [conn 23] error running query {connectTime=2021-10-15T09:00:25+10:00, error=nothing to commit, query=SELECT DOLT_COMMIT('-a', '-m', 'My Commit')}
2021-10-15T09:01:40+10:00 ERROR [conn %!d(<nil>)] Error reading packet from client 23 (127.0.0.1:60451): read tcp 127.0.0.1:3306->127.0.0.1:60451: wsarecv: An existing connection was forcibly closed by the remote host.
io.ReadFull(header size) failed {}
2021-10-15T09:01:40+10:00 INFO [conn 23] ConnectionClosed {}
2021-10-15T09:02:32+10:00 INFO [conn 24] NewConnection {}
2021-10-15T09:02:38+10:00 ERROR [conn %!d(<nil>)] Error reading packet from client 24 (127.0.0.1:63428): read tcp 127.0.0.1:3306->127.0.0.1:63428: wsarecv: An existing connection was forcibly closed by the remote host.
io.ReadFull(header size) failed {}
2021-10-15T09:02:38+10:00 INFO [conn 24] ConnectionClosed {}
2021-10-15T09:04:14+10:00 INFO [conn 25] NewConnection {}
2021-10-15T09:04:25+10:00 ERROR [conn %!d(<nil>)] Error reading packet from client 25 (127.0.0.1:60438): read tcp 127.0.0.1:3306->127.0.0.1:60438: wsarecv: An existing connection was forcibly closed by the remote host.
io.ReadFull(header size) failed {}
2021-10-15T09:04:25+10:00 INFO [conn 25] ConnectionClosed {}
2021-10-15T09:04:47+10:00 INFO [conn 26] NewConnection {}
2021-10-15T09:04:59+10:00 ERROR [conn %!d(<nil>)] Error reading packet from client 26 (127.0.0.1:60439): read tcp 127.0.0.1:3306->127.0.0.1:60439: wsarecv: An existing connection was forcibly closed by the remote host.
io.ReadFull(header size) failed {}
2021-10-15T09:04:59+10:00 INFO [conn 26] ConnectionClosed {}
2021-10-15T09:05:12+10:00 INFO [conn 27] NewConnection {}
2021-10-15T09:08:26+10:00 ERROR [conn %!d(<nil>)] Error reading packet from client 27 (127.0.0.1:56786): read tcp 127.0.0.1:3306->127.0.0.1:56786: wsarecv: An existing connection was forcibly closed by the remote host.
io.ReadFull(header size) failed {}
2021-10-15T09:08:26+10:00 INFO [conn 27] ConnectionClosed {}

----------------------------

The Code I am executing is as follows - I have adapted the code on your git hub .Net example. (Query test works, Commit Test does not):

using System;
using MySqlConnector;

namespace MySqlConnectorTest
{
    class TestException : Exception
    {
        public TestException(string message)
        {
            Console.WriteLine(message);
        }
    }

    class Program
    {
        static int Main(string[] args)
        {
            using (var conn = new MySqlConnection($"server=127.0.0.1;user=root;database=loci;port=3306;SslMode=none"))
            {
                try
                {
                    conn.Open();
                    CommitTest(conn);
                    //QueryTest(conn);

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    return 1;
                }

                conn.Close();
            }

            return 0;
        }

        public static void CommitTest(MySqlConnection conn)
        {
            string sql1 = "SELECT DOLT_ADD('-A')";
            string sql2 = "SELECT DOLT_COMMIT('-a', '-m', 'My Commit')";

            using (var cmd = new MySqlCommand(sql1, conn))
                try
                {
                    object result = cmd.ExecuteNonQuery();
                    if (result != null)
                    {
                        int r = Convert.ToInt32(result);
                        if (r != 1)
                        {
                            TestException ex = new TestException($"Expected 1, Recieved {r}");
                            throw ex;
                        }
                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }

            using (var cmd = new MySqlCommand(sql2, conn))
                try
                {
                    object result = cmd.ExecuteNonQuery();
                    if (result != null)
                    {
                        int r = Convert.ToInt32(result);
                        if (r != 1)
                        {
                            TestException ex = new TestException($"Expected 1, Recieved {r}");
                            throw ex;
                        }
                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
        }

        public static void SetupTest(MySqlConnection conn)
        {
            using var cmd = new MySqlCommand();
            cmd.Connection = conn;

            cmd.CommandText = @"CREATE TABLE test (pk int, `value` int, primary key(pk))";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "INSERT INTO test(pk, `value`) VALUES(0,0)";
            cmd.ExecuteNonQuery();
        }

        public static void QueryTest(MySqlConnection conn)
        {
            string sql = "Select * from State_populations";
            using (var cmd = new MySqlCommand(sql, conn))
                try
                {
                    var reader = cmd.ExecuteReader();
                    if (reader != null)
                    {
                        while (reader.Read())
                        {
                            Console.WriteLine(reader.GetString("state"));
                        }

                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
        }
    }

}

**Comment by timsehn** [comment]
@VinaiRachakonda will look into this. He wrote those functions.

**Comment by zachmu** [comment]
What error are you getting from the call to `dolt_commit()?`

**Comment by zachmu** [comment]
Oh, I see it now:

`error=nothing to commit`

You need to make some changes to a table, or use the `--allow-empty` flag:

https://docs.dolthub.com/interfaces/cli#dolt-commit

**Comment by AlistairAutonomation** [comment]
i thought i did....i added a state value...i will try again

**Comment by AlistairAutonomation** [comment]
I added a new row...tried the commit and add, and it failed again.
My Insert Statement is as follows. When I interrrogate the table I can see the value is in the table. 

The Insert statement I use is as as follows:

public static void InsertTest(MySqlConnection conn)
        {
            string sql = "INSERT INTO state_populations(state,population) VALUES('Qld', 10001)";
            using (var cmd = new MySqlCommand(sql, conn))
                try
                {
                    object result = cmd.ExecuteNonQuery();
                    if (result != null)
                    {
                        int r = Convert.ToInt32(result);
                        if (r != 1)
                        {
                            TestException ex = new TestException($"Expected 1, Recieved {r}");
                            throw ex;
                        }
                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
        }

**Comment by AlistairAutonomation** [comment]
Does Dolt Commit and Add, Only pick up changes to the database structure...not added row values?

**Comment by VinaiRachakonda** [comment]
Added more dot net tests in #2303 that test Dolt SQL functions. Seeing no issues, I'm closing this
