### ISSUE TITLE
golang go-sql-driver/mysql does't work with Multiple HEADs

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2275]
When I try to connect dolt server using golang's go-sql-driver/mysql driver in multiple heads mode,  It seems that  go-sql-driver/mysql driver does't support database with  a sub name. DSN string format in go-sql-driver/mysql like [username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]. When dbname is "mydb", It works, but not work when dbname is "mydb/feature-branch".  And it does't work when I use SQL statement "use mydb/feature-branch" after connecting to default main branch to switch to feature-branch. Finally I have to use "select DOLT_CHECKOUT('mydb/feature-branch')" after successfully connecting to default main branch. I wonder if it is a problem

**Comment by zachmu** [comment]
Thanks for the report, @liuqianhong6007, this not working out of the box is definitely a problem.

The connection string method is relatively new, and might need some tweaking to get right. It works for the mysql shell, i.e.

`mysql --host 127.0.0.1 --port 3306 -uroot corona_virus/master`

Sounds like we need some additional tests of this behavior for the various connectors to see where it's not supported.

**Comment by liuqianhong6007** [comment]
If you switch feature branch after connecting to db, there is a trap of golang's database pool that the newly connection will point to default main but not feature branch. So maybe the best way of connecting to feature branch is to connect it by exact feature branch dsn in the beginning.

**Comment by timsehn** [comment]
We have done a ton of work on these database specs recently. I'm closing. Please open a new issue if you have trouble connecting to specific branches using connection strings.
