### ISSUE TITLE
Overwriting an existing table using import -c -f does not remove foreign key constraints

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#2281]
Added skipped bats tests here: https://github.com/dolthub/dolt/pull/2280

Noticed during file upload on dolthub that if you overwrite (`dolt table import -c -f`) an existing table that has foreign key constraints, the constraints are not removed and `dolt schema show` results in an error similar to `cannot find column for tag 16307 in table details used in foreign key 06cu76j3`

**Comment by stephkyou** [comment]
Bug is resolved, behavior working correctly in the bats test.
