### ISSUE TITLE
First Unique Key in a keyless table should be represented as a primary key

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#2289]
The following create table statement should parse

`create table t(pk int not null auto_increment, UNIQUE KEY pk (pk));`

**Comment by VinaiRachakonda** [comment]
We can parse this statement but we are still treating pk as `UNIQUE` key instead of a `PRIMARY` key. 

Skipped bats here #4014.

**Comment by jycor** [comment]
Update: This PR https://github.com/dolthub/go-mysql-server/pull/2467 fixes many issues related to this.

However, due to the way we store/retrieve indexes there are still some edge cases.

**Comment by jycor** [comment]
closing in favor of: https://github.com/dolthub/dolt/issues/7932
