### ISSUE TITLE
The database fields are case-sensitive?

### ISSUE THREAD

**Issue by chenjpu** [dolthub/dolt#2295]
```
CREATE TABLE `test_t` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
1.Field is as lowercase as the definition 
![image](https://user-images.githubusercontent.com/1785778/138981033-bcc22399-1e90-464d-bb0c-b023382229a9.png)

2.The fields are in capital 
![image](https://user-images.githubusercontent.com/1785778/138981076-75565306-6dbd-4de5-90ac-ee995a2023ea.png)

**Comment by zachmu** [comment]
This is fixed in the latest release. Let us know if you have any trouble.
