### ISSUE TITLE
confusing error message when selecting from conflict tables with `@@autocommit = true`

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2305]
When I merge feature branch, some conflicts occurs. Then I can use **select * from dolt_conflicts_mycolor** to get the conflicts just as the following
![image](https://user-images.githubusercontent.com/31907732/139248180-955d4e57-f231-461d-b14e-a539400cc480.png)

 Next the problem appears.
I use **SELECT DOLT_MERGE('test2')** to merge feature branch and an error of conflicts is expected. Then **select * from dolt_conflicts_mycolor** should get the same output as above. But this time followed by an unexpected error of **merge has unresolved conflicts. please use the dolt_conflicts table to resolve**
![image](https://user-images.githubusercontent.com/31907732/139249281-d1ec63dc-baf9-4f6e-a831-52feadb3e701.png)

And in golang test, I also get the error when I try to find out the conflicts
![image](https://user-images.githubusercontent.com/31907732/139249857-f814c9e4-112d-42f9-b722-660121bf2f4d.png)

If this is not a bug, hava any idea to advance my work ?

**Comment by timsehn** [comment]
This error message is fixed in recent releases.
