### ISSUE TITLE
Querying large tables using order by uses up memory and doesn't complete

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#231]
```
(base) Taylors-MBP:wikipedia-ngrams taylor$ dolt sql -q 'select * from trigram_counts order by total_count desc limit 15'
Killed: 9
(base) Taylors-MBP:wikipedia-ngrams taylor$ dolt sql -q 'select * from bigram_counts order by total_count desc limit 15'
Killed: 9
```

**Comment by cristiansteib** [comment]
@tbantle22  How large is that table? any logs and system specs? Thanks

**Comment by timsehn** [comment]
@cristiansteib Taylor works for the company that builds this. The bug report is self-explanatory to us. Are you offering to help?

**Comment by cristiansteib** [comment]
@timsehn  I want to use Dolt for a project, but I need to rely on it, probably I could help if it were usable for us. Do we have some channel for a talk?

**Comment by timsehn** [comment]
That would be awesome. Email me at tim@liquidata.co.

**Comment by eff917** [comment]
I also ran into this:
Table: ~62mill records.
Query: `DELETE FROM table WHERE id IN (SELECT id FROM table ORDER BY RAND() LIMIT 1);`

The embedded in itself query maxes out around 30GB RAM used, and completed in ~5 minutes.
The full query was killed with OOM on a 432GB VM in ~15 minutes. The memory usage went up in ~30GB increments (used up +30GB in ~15-30sec, then another 15-30sec +1-2GB memory used, then repeat) until it was killed.

**Comment by VinaiRachakonda** [comment]
Closing since, table performance has changes a lot since 2019. Best to file a new issue if memory spikes again
