### ISSUE TITLE
[Feature Request/Bug] Add processlist to information_schema table

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#2310]
Attempting to kill a running query while using TablePlus results in 
`
WARN [conn 2] error running query {connectTime=2021-10-29T09:19:55-04:00, error=syntax error at position 45 near 'processlist', query=select * from information_schema.processlist where db = 'us_businesses' AND info <> ''}
`

https://dev.mysql.com/doc/refman/8.0/en/information-schema-processlist-table.html

**Comment by zachmu** [comment]
In the meantime, we support:

`SHOW PROCESSLIST`
`KILL <ID>`

**Comment by jennifersp** [comment]
`information_schema.processlist` is added in https://github.com/dolthub/go-mysql-server/pull/832
