### ISSUE TITLE
Tableplus can't detect Table

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#2311]
### Steps to reproduce:
1. `dolt sql-server`
2. Connect to server with TablePlus
3. Run a select query
4. Attempt to edit returned row(s)

I attempted it with the debug log level and nothing was displayed. I can confirm that it works with a normal MySQL database however, so it's an issue here.

### Screenshot:
![image](https://user-images.githubusercontent.com/40151222/139444012-9b5647c5-97bd-4a17-bd2e-bdee381f4857.png)

**Comment by VinaiRachakonda** [comment]
Investigating this found the following error:

```
 error running query {connectTime=2022-03-04T11:03:23-08:00, error=table not found: COLLATION_CHARACTER_SET_APPLICABILITY, query=SELECT CCSA.character_set_name as charset,T.table_collation as collation,T.engine as engine,T.table_name AS name,T.table_rows AS estimated_row FROM information_schema.TABLES T,information_schema.COLLATION_CHARACTER_SET_APPLICABILITY CCSA WHERE CCSA.collation_name=T.table_collation AND T.TABLE_SCHEMA='dsimple'}
 ```

We need to implement the information schema `COLLATION_CHARACTER_SET_APPLICABILITY` table

**Comment by jennifersp** [comment]
information_schema.COLLATION_CHARACTER_SET_APPLICABILITY table is added in https://github.com/dolthub/go-mysql-server/pull/851

**Comment by VinaiRachakonda** [comment]
Let's not close this issue yet. Still some testing left to make sure editing works

**Comment by timsehn** [comment]
I tested and editing table in table plus now works.
