### ISSUE TITLE
DOLT_MERGE should return detailed error

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2315]
The CLI **dolt merge** works well as shown
![image](https://user-images.githubusercontent.com/31907732/139646091-dedc2f9f-9d44-4c7e-9f3c-490337cc2679.png)

However,  **SELECT DOLT_MERGE('feature1', '-no-ff', '-m', 'Merge branch feature1 into main')** does't work. The repo main branch is not clean
![image](https://user-images.githubusercontent.com/31907732/139646317-04735cc7-6dea-47dc-b31a-8f18cbd25f0a.png)

It indicetes that I should use **dolt commit to conclude merge**.
I think maybe variable  **@@autocommit** affects,  so I print the value which has been set default true
![image](https://user-images.githubusercontent.com/31907732/139647091-8f8f674a-528a-49f2-8abb-ca05a4f0d3ad.png)

Then I notice that it returns "1"  that indicates something wrong. But I get no result by quering dolt_conflicts_$db table
So where can I get the detail error ?

**Comment by VinaiRachakonda** [comment]
This is confusing on our part. `dolt_merge` returning 1 means there are no conflicts. I'm going to clean up the return syntax and appropriately update the documentation

**Comment by timsehn** [comment]
The error messages and workflow have been updated in many recent releases. This should work better now.
