### ISSUE TITLE
writeable `dolt_remotes`

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#2320]
INSERT/UPDATE/DELETE into `dolt_remotes` system table.

[series of bats tests for unsupported behavior](https://github.com/dolthub/dolt/blob/280bbb42f91a595cd3ad4de4bce0552d0d0cd57f/integration-tests/bats/system-tables.bats#L165)

**Comment by timsehn** [comment]
This was implemented as `dolt_remote()` stored procedure instead.
