### ISSUE TITLE
Merging schemas that look the same in the CLI drops error if NOT NULL constraints were defined slightly differently.

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2324]
1. Clone `dolthub/SHAQ`
2. `dolt remote add saewitz saewitz/SHAQ`
3. `dolt fetch saewitz`
4. `dolt merge --no-ff remotes/saewitz/nba_season_stats`

We both ran the same alter table statements to drop the primary key, add a league_id column, and readd the primary key with league_id in it.

**Comment by andrew-wm-arthur** [comment]
The schemas appear to be the same from the CLI, but they actually differ at the storage layer. This bit of [code](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/schema/column.go#L125) makes them look the same

**Comment by andrew-wm-arthur** [comment]
When we store Dolt schemas, we should enforce that `schema.Column.IsPartOfPK == true` implies that the column has a NotNull Constraint

**Comment by zachmu** [comment]
James, I had originally thought my most recent PR would address this as well, but it doesn't. The bug is we need to add a NOT NULL constraint to any primary key columns.
