### ISSUE TITLE
Custom escape characters are not supported? 

### ISSUE THREAD

**Issue by chenjpu** [dolthub/dolt#2334]
1.Can query the data that meets the conditions 
```
SELECT * from test_t t where t.NAME like '%\\_%' ESCAPE '\\';
```
2.Can not query the data that meets the conditions 
```
SELECT * from test_t t where t.NAME like '%$_%' ESCAPE '$';
```

**Comment by zachmu** [comment]
Thanks for the report.

Looks like we are not actually processing the escape characters for LIKE comparisons. This is a bug.

James, please take this on as your next task.
