### ISSUE TITLE
Resolving conflicts without committing does not allow you to continue to modify the working set

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2336]
I think I may have the same problem. Here's an easier repro.

1. Create a conflict on a merge.
2. Mark the conflict as resolved either using `dolt conflicts resolve` or deleting from the `dolt_conflicts` table
3. Try to do additional modifications before you commit. They fail with: `merge has unresolved conflicts. please use the dolt_conflicts table to resolve`

In real life:
```
SHAQ $ dolt merge --no-ff remotes/renatolopes771/main
Updating 1d3da54mavdrn3tr4gf4db6p503b26kf..cst9v4isb1i0ohu7q1i5qn78mmfs2lq8
players | 1384 ++++++++++++++++++++++++++++++
1 tables changed, 1384 rows added(+), 0 rows modified(*), 0 rows deleted(-)
Auto-merging leagues
CONFLICT (content): Merge conflict in leagues
Automatic merge failed; fix conflicts and then commit the result.
SHAQ $ dolt conflicts cat leagues
+-----+--------+-----------+------------------------------------------+
|     |        | league_id | name                                     |
+-----+--------+-----------+------------------------------------------+
|  +  | ours   | 5         | NBA G League                             |
|  +  | theirs | 5         | Ciutat De L'Hospitalet Tournament (ANGT) |
+-----+--------+-----------+------------------------------------------+
SHAQ $ dolt conflicts resolve --ours leagues
SHAQ $ dolt sql -q "insert into leagues values (6, 'Ciutat De L\'Hospitalet Tournament (ANGT)')" 
Query OK, 1 row affected
merge has unresolved conflicts. please use the dolt_conflicts table to resolve
SHAQ $ dolt conflicts cat leagues
+-----+--------+-----------+------+
|     |        | league_id | name |
+-----+--------+-----------+------+
+-----+--------+-----------+------+
```

**Comment by timsehn** [comment]
This is tested by this:

https://github.com/dolthub/dolt/blob/281551f46f79548433fa659f087f40db86e4213d/integration-tests/bats/conflict-detection-2.bats#L502****

Can I get this prioritized?

Fixing it will allow me to fix bounty contributors PRs and not screw up attribution.

**Comment by zachmu** [comment]
I think this is WAI, but we need a little design work here.

By default, dolt SQL won't let you commit a working set with conflicts. But that's probably not the right call when running `dolt sql -q`, or from the shell.

Workaround is `set dolt_force_transaction_commit = 1` in every session.

**Comment by zachmu** [comment]
Another bug here is that resolving every conflict doesn't clear the conflict state in the working set. In SQL, deleting every row in the conflicts table will mark the working set as conflict free, and the same needs to happen with `dolt conflicts resolve`

**Comment by timsehn** [comment]
As discussed in office, this is a little clearer then what Zach wrote.

If I make a merge with conflicts and resolve the conflicts, I should be able to continue to modify that working set. With this bug, I cannot.
