### ISSUE TITLE
`dolt commit --amend` to amend commit messages

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2338]
Being able to amend the previous commit's message would be a very useful feature to have. I will usually use `git commit --amend -m "<new message>"` rather than amending in an editor as I find that much faster, and I think that's sufficient for this issue.

**Comment by timsehn** [comment]
In the meantime you can do it this way:
```
dolt reset --soft HEAD~1
dolt reset HEAD
dolt commit -am "<message>"
```

**Comment by tanyongzhi** [comment]
I would like to work on this issue!

**Comment by timsehn** [comment]
That would be great! Our contributor guide is here:

https://docs.dolthub.com/guides/contributing

@fulghum can point you in the right direction when he comes online.

**Comment by fulghum** [comment]
Hey @tanyongzhi, that's awesome! The contributor guide is a great place start. Also feel free to [drop by our Discord](https://discord.com/invite/RFwfYpu) and ping me (JasonF) or ask questions in the `#dolt` channel if you get stuck on anything or just want to discuss design/implementation direction before you get too deep. We're happy to help get you pointed in the right direction. Checking out [the implementation for `dolt commit`](https://github.com/dolthub/dolt/blob/main/go/cmd/dolt/commands/commit.go) is a good place to get started.
