### ISSUE TITLE
Not able to change column data type on existing data set

### ISSUE THREAD

**Issue by namdnguyen** [dolthub/dolt#234]
Hi, very cool project. I'm having difficulty figuring out how to change column data types after importing a CSV. All columns were inferred to be `LONGTEXT` type. I tried to alter the data type with the following command:

```
dolt sql -q "ALTER TABLE table_name MODIFY 'column_name' (INTEGER)"
```

And received the message: 

> Error altering table: Unsupported alter table statement: 'ALTER TABLE table_name MODIFY 'column_name' (INTEGER)'

I also checked out `dolt schema` but didn't see a modify option there, aside from renaming columns. Is the best way to set up column data types to do it in the schema JSON to create the table before importing?

**Comment by timsehn** [comment]
First, thanks for trying Dolt.

You can have Dolt infer the schema from your CSV usind ```dolt schema import```. The ```--dry-run``` option will tell you what it's inferring.

Unfortunately, we haven't supported alter table commands to change column types because column type changes are forking operations for the backing store, unlike a traditional database. We have some technical details to work out before we support those. To change a type you have to export the schema using ```dolt schema show```, modify the SQL that comes out to what you want, drop the table, and create the table with the new SQL. Then, re-import the data back in.

This is a workflow we're actively working on.

**Comment by timsehn** [comment]
Also, you can do this chicanery:
```doltsql> select * from my_users;
+----+
| id |
+----+
| 1  |
| 2  |
| 3  |
| 4  |
| 5  |
| 6  |
| 7  |
| 8  |
| 9  |
| 10 |
+----+
doltsql> alter table my_users add column age longtext;
doltsql> update my_users set age = "1";
+---------+---------+
| matched | updated |
+---------+---------+
| 10      | 10      |
+---------+---------+
doltsql> select * from my_users;
+----+-----+
| id | age |
+----+-----+
| 1  | 1   |
| 2  | 1   |
| 3  | 1   |
| 4  | 1   |
| 5  | 1   |
| 6  | 1   |
| 7  | 1   |
| 8  | 1   |
| 9  | 1   |
| 10 | 1   |
+----+-----+
doltsql> alter table my_users add column new_age int;
doltsql> update my_users set new_age = int(age);
function: 'int, maybe you mean min?' not found
doltsql> update my_users set new_age = age;
+---------+---------+
| matched | updated |
+---------+---------+
| 10      | 10      |
+---------+---------+
doltsql> select * from my_users;
+----+-----+---------+
| id | age | new_age |
+----+-----+---------+
| 1  | 1   | 1       |
| 2  | 1   | 1       |
| 3  | 1   | 1       |
| 4  | 1   | 1       |
| 5  | 1   | 1       |
| 6  | 1   | 1       |
| 7  | 1   | 1       |
| 8  | 1   | 1       |
| 9  | 1   | 1       |
| 10 | 1   | 1       |
+----+-----+---------+
doltsql> alter table my_users drop column age;
doltsql> alter table my_users rename column new_age to age;
doltsql> select * from my_users;
+----+-----+
| id | age |
+----+-----+
| 1  | 1   |
| 2  | 1   |
| 3  | 1   |
| 4  | 1   |
| 5  | 1   |
| 6  | 1   |
| 7  | 1   |
| 8  | 1   |
| 9  | 1   |
| 10 | 1   |
+----+-----+```

**Comment by namdnguyen** [comment]
Thanks for the quick response, @timsehn! I like the first option for the initial table definition and the second option for subsequent changes. I'm glad you shared both and gave a sneak peek of the future implementation.

**Comment by namdnguyen** [comment]
Actually, Dolt did a really nice job with inferring the schema from the CSV. I skipped the step of importing the schema last time, and just imported the CSV as a new table, so all columns were defined as `LONGTEXT`. 

Dropping that table, importing the schema, and then updating the table with the CSV resulted in the data type definitions that I expected. No need to modify.

Thanks again for the help!

**Comment by timsehn** [comment]
We'll leave this bug open until we implement ```alter table modify```. Thanks for using (and contributing to) Dolt :-)

**Comment by namdnguyen** [comment]
Absolutely! Really digging it!
