### ISSUE TITLE
Feature Request: Make git log a table so that we can perform SQL queries on it

### ISSUE THREAD

**Issue by RenatoLopes771** [dolthub/dolt#2353]
Also show it on dolthub!

**Comment by timsehn** [comment]
This exists:

https://docs.dolthub.com/interfaces/sql/dolt-system-tables#dolt_log

and you can run `select * from dolt_log` on DoltHub:

https://www.dolthub.com/repositories/dolthub/SHAQ/query/main?q=SELECT+*%0AFROM+dolt_log%0ALIMIT+5%3B%0A%0A&active=Tables
