### ISSUE TITLE
CLI supports param for different working directory

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2359]
I wonder whethe dolt CLI will support different working directory by passing a param like "--work-dir" ?

**Comment by timsehn** [comment]
We need a DOLT_ROOT environment variable for other use cases. @zachmu is working on this right now.

**Comment by timsehn** [comment]
We have a `--data-dir` option for `dolt sql-server` now. I think we're fine with matching git semantics of only operating on the $CWD for the CLI.
