### ISSUE TITLE
unsupported  CURRENT_TIMESTAMP(3)

### ISSUE THREAD

**Issue by xuybin** [dolthub/dolt#2368]
CREATE TABLE IF NOT EXISTS `t` (
  `id` VARCHAR(45) NOT NULL,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
);

---
unsupported syntax: CURRENT_TIMESTAMP(3)

**Comment by zachmu** [comment]
Hi @xuybin,

Thanks for the report! We will get this fixed.

In the meantime, you can just use `current_timestamp()` as your default, but this will get you nanosecond precision. Do you need reduced precision of timestamp to millisecond precision? Or do you just need the syntax to work?
