### ISSUE TITLE
Dolt dump to parquet

### ISSUE THREAD

**Issue by noamross** [dolthub/dolt#2381]
I really like `dolt dump` for "data releases".  Would it be possible to also dump tables to parquet formats?  My workflow will typically involve another step moving the CSVs or JSON to parquet.  I understand the challenge of supporting many formats but parquet is a pretty widely used and interoperable format these days.

**Comment by zachmu** [comment]
Thanks for the feature request, this is a good one.

We'll start on this soon.

**Comment by zachmu** [comment]
Should also support this for `dolt table export`
