### ISSUE TITLE
Precision of int-typed columns lost in information schema

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2395]
When creating a table with an `int` column specifying a precision, this precision is lost in the information schema (it appears to work for `numeric` typed columns).

Example:
```sql
create table foo(x int(3))
;
show create table foo
;
```

The result of the latter shows this DDL:
```sql
CREATE TABLE `foo` (
  `x` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

For comparison see what MySQL does (https://www.db-fiddle.com/f/rCtpEG8ymjET6NjxG2DhyK/0):

```sql
CREATE TABLE `foo` ( `x` int(3) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

The type with the precision is in MySQL retained in the `information_schema.columns.column_type` column (here as `int(3)`).

**Comment by timsehn** [comment]
So we added this for tinyint here: https://github.com/dolthub/dolt/pull/6688

It looks like "as of MySQL 8.1.0, the display width setting is ONLY retained for signed TINYINT fields and ONLY when the display width is set to 1." Resolving as we will not fix this to match the latest MySQL.
