### ISSUE TITLE
Support `dolt_branch()` SQL function

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2408]
Inserting into the `dolt_branches` table using `HASHOF()` syntax is not as user friendly.

**Comment by jennifersp** [comment]
Creating a new branch and making a copy of existing branch are supported in https://github.com/dolthub/dolt/pull/2530 .
Currently, deleting and renaming branches are not supported for `dolt_branch()` function in sql.

**Comment by fulghum** [comment]
As part of this work, we also need to add reference documentation for the `DOLT_BRANCH` function from the Dolt SQL Functions page:
https://docs.dolthub.com/reference/sql/dolt-sql-functions

**Comment by jennifersp** [comment]
Supports for deleting and renaming branches are added in https://github.com/dolthub/dolt/pull/3487

**Comment by jennifersp** [comment]
Supports for deleting and renaming branches are added in https://github.com/dolthub/dolt/pull/3487 by @fulghum
