### ISSUE TITLE
Use of dependency vulnerable to hijacking

### ISSUE THREAD

**Issue by TcM1911** [dolthub/dolt#2416]
The [buzhash](https://github.com/dolthub/dolt/blob/33fdbb8b3c484d05bfc223717b68eacac3e2f53c/go/go.mod#L44) dependency used by Dolt is vulnerable to be hijacked. This can allow a malicious person to inject their own code that is consumed by this project the next time this dependency is updated. The new location of this code is located at https://github.com/silvasur/buzhash. Github redirects the old URL to this new URL until someone registers the old username.

For more information about how this attack works, please read our report on chain jacking: https://www.intezer.com/blog/malware-analysis/chainjacking-supply-chain-attack-puts-popular-admin-tools-at-risk/

Checkmarks has open sourced a tool that can run as a GitHub action to check for these types of vulnerabilities in the future: https://github.com/checkmarx/chainjacking

**Comment by reltuk** [comment]
@TcM1911 Thank you for this report. Greatly appreciated :).
