### ISSUE TITLE
[Readme improvement] - we need better migrate explanation.

### ISSUE THREAD

**Issue by stuk88** [dolthub/dolt#2427]
migrate - Executes a repository migration to update to the latest format.

What defines 'latest format'? should be added here.

**Comment by timsehn** [comment]
Thanks. We have only ever done one migration and it was very early, like 1.5 years ago.

We're going to be doing another one, maybe two. This is good feedback and @andrew-wm-arthur will handle it.

**Comment by andrew-wm-arthur** [comment]
@stuk88 I updated the CLI documentation to clarify `dolt migrate`. 

https://github.com/dolthub/dolt/pull/2428

The format that `dolt migrate` changes over time. As Tim said, we have a few migrations planned over the next two quarters that are oriented towards performance.

In general, Dolt's data format is unique to Dolt. We share a format with any other database or serialization format.
