### ISSUE TITLE
Intra-column diff for text / JSON fields

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2429]
Customers who store large payloads in text / JSON columns could benefit from seeing the diff within each column, rather than treating the value as opaque. This could be a separate non-default diff mode.

**Comment by timsehn** [comment]
JSON diffs will be on DoltHub soon: https://github.com/dolthub/dolthub-issues/issues/294

We can use that interface for CLI interface ideas.

For SQL interface we need a way to trim out the data as well.

**Comment by timsehn** [comment]
This functionality is on DoltHub diffs if anyone discovers this issue and is looking for a workaround.

**Comment by timsehn** [comment]
This PR adds text diff functionality for stored procedures. https://github.com/dolthub/dolt/pull/5335

We can use the same functionality and the `text-diff-mode` switch to do for other tables or certain column types as well.

**Comment by timsehn** [comment]
This is fixed with https://github.com/dolthub/dolt/pull/5365.
