### ISSUE TITLE
Dolt should reuse column on `drop` then `add`

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2430]
If you have a table and drop a column then add it back with the same definition, dolt will consider it a new column w.r.t. schema and row storage.

```sql
create table a (a int primary key, b int);
insert into a values (1, 1), (2, 2);
select dolt_commit('-am', 'first commit');
alter table a drop b;
alter table a add column b int;
```

Then when you run `dolt diff`, you see this:

```
+-----+---+------+------+
|  <  | a |      | b    |
|  >  | a | b    |      |
+-----+---+------+------+
|  <  | 1 | NULL | 1    |
|  >  | 1 | NULL | NULL |
|  <  | 2 | NULL | 2    |
|  >  | 2 | NULL | NULL |
+-----+---+------+------+
```

This happens because the second `b` column gets a different tag in schema. The correct behavior is the diff should show a single column `b` with all values set to `NULL`.

There are two ways we could do this:

1) Delete in storage when we drop a column, then reuse the column tag. We don't do this now, which makes drop column fast. We can't reuse the tag without also zeroing out storage.
2) Make diff match on column names and do something more intelligent.

**Comment by zachmu** [comment]
The diff output bug is fixed in main, but further testing is needed to make sure that the table storage is actually equivalent after dropping and recreating the column with the same data for all rows.

**Comment by timsehn** [comment]
@druvv you fixed this right with the tag change?

**Comment by druvv** [comment]
Missing in the above repro is the following:
```
update a set b = 1 where a = 1;
update a set b = 2 where a = 2;
```

As of Dolt (v0.40.21)[https://github.com/dolthub/dolt/releases/tag/v0.40.21] this issue is fixed.
