### ISSUE TITLE
read-only flag not being respected in config.yaml file

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2442]
Need a test in `sql-server.bats` to confirm this prevents modifying statements from executing.

**Comment by timsehn** [comment]
Has this been fixed?

**Comment by JCOR11599** [comment]
Yes: https://github.com/dolthub/dolt/blob/main/integration-tests/bats/sql-server.bats#L81

**Comment by JCOR11599** [comment]
This is merged into main and will be fixed in the next release
