### ISSUE TITLE
Support `-a` in `dolt tag` command

### ISSUE THREAD

**Issue by addisonklinke** [dolthub/dolt#2462]
First off thanks for this awesome tool - it's super helpful for machine learning datasets! 

I'm new to Dolt and playing around with a local repository to get familiar. The working tree is clean as shown by `dolt status` and I'm trying to add a tag at the current commit. Based on mirroring [git syntax](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_annotated_tags), I would expect the proper Dolt equivalent to be `dolt tag -a v1.4 -m "my version 1.4"`. However based on the command's help, I can see `-a` is not an option. I've tried the following variations all without success

```
# All the below match command synopsis "dolt tag [-m <message>] <tagname> [<ref>]"
# But still result in "failed to create tag cause: Invalid dataset ID: refs/tags/v1.4"
dolt tag -m "my version 1.4" v1.4  
dolt tag -m "my version 1.4" v1.4 HEAD 
dolt tag v1.4

# The remainder also fail (which isn't surprising since they don't match the synopsis) 
# failed to create tag cause: not a valid user tag name
dolt tag -m "v1.4" HEAD

# must specify a tag name to create
dolt tag -m "v1.4"
```

Can anyone clarify the proper usage and/or explain why a dataset ID is expected?

Unfortunately the [docs](https://docs.dolthub.com/interfaces/cli#dolt-tag) are out of date (specifying options that don't match the latest version 0.34.7) and the formatting of the synopsis code seems mangled, so overall I haven't had much luck there

**Comment by timsehn** [comment]
Hey Addison. Sorry for the misaligned docs. Tags don't get much use internally. 

We'll do a bug and test pass on them. 

I'm researching right now the command that will work for you.

**Comment by addisonklinke** [comment]
Apologies for missing this when opening the issue, but I just figured out it's a case of https://github.com/dolthub/dolt/issues/1144. I'd still really like to see dots supported in tags since semantic versioning is the most common naming schema. In that regard, perhaps this should get changed to a feature request?

Another thought (which might help new users getting through the docs) - can the `dolt tag` syntax be updated to match `git tag`? I recall reading somewhere that the design goal was to have Dolt follow git so that user's didn't have to learn a new syntax

**Comment by timsehn** [comment]
Those are two good feature requests:

1. Make `dolt tag` match `git tag`. I need to know more here because it sort of does without all the options. `git tag tagname` creates a tag at the current ref. Adding a ref at the end creates it at that ref. `git tag` w/ no options lists the tags. So what exactly is the request? More options?
2. Support `.` in tagnames. We already have a bug for that.

**Comment by timsehn** [comment]
I see you want support for `-a`. I'm not sure what the difference between a regular tag and an "unsigned, annotated tag object" and a regular git tag are.
```
       -a, --annotate
           Make an unsigned, annotated tag object
```

I'll change the title of this one to that.

**Comment by timsehn** [comment]
I'll also get the docs updated on the docs site.

**Comment by addisonklinke** [comment]
My understanding from [here](https://stackoverflow.com/a/4971817/7446465) is that annotated tags provide additional metadata (author, date, etc) that can be distributed with the repo. Perhaps Dolt is already doing that behind the scenes? I always use annotated tags in git since I've heard that's best practice, so out of habit that's what I tried when it came to Dolt

Maybe the annotated vs. not is unrelated to these, but some features missing in Dolt are
* Displaying tags in parentheses next to their commit in `dolt log`
* Being able to `dolt checkout tagname` - from the command help I see that this is probably unsupported for the moment

**Comment by timsehn** [comment]
Can you make additional issues for those two? I can do it but it's better for us optics-wise if you make them. It makes our repo look more active :-)

I'll have either @JCOR11599 or @jennifersp do a tag pass in the next couple weeks and crank through them.

**Comment by zachmu** [comment]
Both these are pretty easy to support, we'll get fixes out soon. But please do file issues :)

I'm fixing the docs problem for `tag` now.

**Comment by addisonklinke** [comment]
Of course, here are the new issues
* https://github.com/dolthub/dolt/issues/2463
* https://github.com/dolthub/dolt/issues/2464
* https://github.com/dolthub/dolt/issues/2465 (another one I thought of)

In terms of annotated tags, is the conclusion that dolt is already behaving this way by default so it's not worth changing the syntax of `dolt tag`?

**Comment by andrew-wm-arthur** [comment]
@addisonklinke thanks for this issue. Seems like the punchline here is that we're out-of-sync with Git's API. 

You're correct that we don't support "lightweight" tags. All tags include tag-specific metadata such as tagger, tag time, etc. For now, the only option is whether to include a message

**Comment by zachmu** [comment]
Docs for the `tag` command are now correct, thanks for the find.

https://docs.dolthub.com/interfaces/cli#dolt-tag

**Comment by addisonklinke** [comment]
Summary of `dolt tag` discussion before closing in favor of new issues opened above
* Currently doesn't support the `.` character.  Eventually the team plans to support this, and comments should be tracked in the original [issue](https://github.com/dolthub/dolt/issues/1144) (which should get re-opened)
* Does not have a distinction between lightweight vs. annotated tags like git, which is okay
* Correct syntax for a tag with message is `dolt tag -m "foo" v1`
