### ISSUE TITLE
Missing features in `dolt log`

### ISSUE THREAD

**Issue by addisonklinke** [dolthub/dolt#2463]
Some functionality that is present in git but not yet with dolt
* Display branch(es) and tag(s) associated with each commit (both local and remote). I think this has to do with the default behavior of `--decorate` discussed in the git [docs](https://git-scm.com/docs/git-log#Documentation/git-log.txt---decorateshortfullautono)
* Option for `--oneline` compact display
* Line number specification via `-L`. This would enable fancier aliases like `git follow` proposed [here](https://stackoverflow.com/a/19757441/7446465). I'm not sure if dolt supports alias configuration yet, but if not line numbers would still be a helpful manual option

Feel free to add others onto the list, these are just what I've noticed

**Comment by JCOR11599** [comment]
In main, I just merged functionality for these methods
 - `dolt log --decorate=<auto/short/full/no`
 - `dolt log --oneline`

(the combination of `decorate` and `oneline` also works similar to git)

So `dolt log` now displays HEAD, branches, remote branches, and tags next to the commits (in color too).
Hopefully these will come in handy.

**Comment by andrew-wm-arthur** [comment]
Regarding a the `-L` option, it might be more ergonomic to use the [`dolt_diff_$tablename`](https://docs.dolthub.com/reference/sql/dolt-system-tables#dolt_diff_usdtablename) system table to inspect these changes. The query would look like:
```sql
SELECT * FROM dolt_diff_my_table WHERE pk BETWEEN 100 AND 200; 
```
This would return a list of diffs for each commit for the primary key range (100,200)

**Comment by addisonklinke** [comment]
@JCOR11599 Many thanks for the `decorate` and `oneline` additions, they look great in Dolt 0.37.4!

@andrew-wm-arthur Your SQL equivalent for `-L` makes a lot of sense, could we still access this from the `dolt` CLI?

**Comment by timsehn** [comment]
Yes.

`dolt sql -q "SELECT * FROM dolt_diff_my_table WHERE pk BETWEEN 100 AND 200;"`

The -r option has output formats like CSV and JSON as well as traditional table view.

**Comment by addisonklinke** [comment]
With that query, I get an error 

`column "pk" could not be found in any table in scope`

I also tried substituting `id` for `pk` since `my_table` has its primary key column named that way, but still a similar error. In either case, `dolt diff` is displaying output fine

**Comment by timsehn** [comment]
@andrew-wm-arthur ?

**Comment by addisonklinke** [comment]
Sure added here https://github.com/dolthub/dolt/issues/3040
