### ISSUE TITLE
Dolt diff misses some rows

### ISSUE THREAD

**Issue by An0n3m0us** [dolthub/dolt#2478]
(In this instance I am separating the full names of teams into a prefix and a nickname)
After running `dolt diff` to check changes, I noticed that there was an issue; (I've added diff highlighting and labels for readability)
Notice that the row for `2008 Bellarmine Knights` only has the deletion row shown and not the addition row.

```diff
-|  <  | 29 | 4 | 2021 | Baylor Bears       | NULL    |
+|  >  | 29 | 4 | 2021 | Baylor             | Bears   |
-|  <  | 30 | 4 | 2003 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2003 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2006 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2006 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2008 | Bellarmine Knights | NULL    | <--- HERE
-|  <  | 30 | 4 | 2009 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2009 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2010 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2010 | Bellarmine         | Knights |
```

It's supposed to show up like this:
```diff
-|  <  | 29 | 4 | 2021 | Baylor Bears       | NULL    |
+|  >  | 29 | 4 | 2021 | Baylor             | Bears   |
-|  <  | 30 | 4 | 2003 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2003 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2006 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2006 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2008 | Bellarmine Knights | NULL    | <--- HERE
+|  >  | 30 | 4 | 2008 | Bellarmine         | Knights | <--- HERE
-|  <  | 30 | 4 | 2009 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2009 | Bellarmine         | Knights |
-|  <  | 30 | 4 | 2010 | Bellarmine Knights | NULL    |
+|  >  | 30 | 4 | 2010 | Bellarmine         | Knights |
```

Here's another example (correcting team abbreviation):
![image](https://user-images.githubusercontent.com/49789044/145244721-3fa7ba68-db60-4ca6-9b9c-d5fc34ecd021.png)
Notice how the row for `2015` only shows the deletion.

**Comment by zachmu** [comment]
Thanks for the report, @An0n3m0us

Can you give us a dolt repo and a set of insert / update statements that reproduce the problem?

**Comment by An0n3m0us** [comment]
https://www.dolthub.com/repositories/mysequel/issue2478/data/main

(First commit to add the initial data) `6k8hr69qqr7ttjdqlii87kbcti1cp4c5`;
`INSERT IGNORE INTO do1tdiff(id, col0, col1, col2, col3, col4, col5) VALUES (0, 0, 0, 0, 0, 0, 0);`
[ Insert statements for 1 through 998 ]
`INSERT IGNORE INTO do1tdiff(id, col0, col1, col2, col3, col4, col5) VALUES (999, 999, 999, 999, 999, 999, 999);`

(Second commit to update `col2`) `n6070j65moqc9i4821fuku7bvjmvq46k`;
`UPDATE do1tdiff SET col2="abc";`

Running `dolt diff` and searching through the output;
![image](https://user-images.githubusercontent.com/49789044/145308124-ddc9cc09-c402-415c-8986-dabccd634258.png)

On `dolthub` it shows up correctly;
![image](https://user-images.githubusercontent.com/49789044/145308509-6fe1281c-8301-4980-9a6d-0f6e3ece3cf3.png)

**Comment by zachmu** [comment]
@jennifersp will look into this next, thanks for the report
