### ISSUE TITLE
Feature Request: datediff sql function

### ISSUE THREAD

**Issue by n8layman** [dolthub/dolt#2519]
Hey all,

It would be great to be able to easily calculate the days between two dates or datetimes. Right now I'm using:
`FLOOR((UNIX_TIMESTAMP(DATE(end_date)) - UNIX_TIMESTAMP(DATE(start_date))) / 86400)` which works but is a bit cumbersome.

Thanks and awesome project!

**Comment by andrew-wm-arthur** [comment]
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff

**Comment by jennifersp** [comment]
DATEDIFF() is added in https://github.com/dolthub/go-mysql-server/pull/701
