### ISSUE TITLE
Support regular files (with regular Git semantics)

### ISSUE THREAD

**Issue by danbst** [dolthub/dolt#252]
Looks like dolt doesn't know about files:
```
$ touch README.md

$ ls -la
total 12
drwxr-xr-x 3 danbst users 4096 гру 15 13:15 .
drwxr-xr-x 4 danbst users 4096 гру 15 13:11 ..
drwxr-xr-x 4 danbst users 4096 гру 15 12:55 .dolt
-rw-r--r-- 1 danbst users    0 гру 15 13:15 README.md

$ dolt status
On branch master
nothing to commit, working tree clean
```
My wannabe usecase is to have README and import scripts published alongside with data.

-----

It is actually easy to create Git repo in same Dolt repo. Just add `.dolt` to `.gitignore` and publish to github. Not sure if this workaround is a solution or hack. Either way, it may be referenced in documentation.

**Comment by timsehn** [comment]
We are implementing LICENSE and README files right now. We should have those in the next release. 

We've discussed having other files like import scripts versioned along with the data itself. One of the proposed solutions is to have a ```dolt-git``` where you can put a git repo inside a dolt repo as you suggest. We'll keep this issue updated as we move along.
