### ISSUE TITLE
Feature Request: timestampdiff sql function

### ISSUE THREAD

**Issue by n8layman** [dolthub/dolt#2520]
Hello!

Would it be possible to add the timestampdiff sql function? That would make it easier to calculate time differences between two datetimes.

Thanks again and awesome work!

**Comment by andrew-wm-arthur** [comment]
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampdiff

**Comment by jennifersp** [comment]
TIMESTAMPDIFF() function is added, https://github.com/dolthub/go-mysql-server/pull/717
