### ISSUE TITLE
dolt 0.12.0 push error: invalid cross-device link

### ISSUE THREAD

**Issue by danbst** [dolthub/dolt#253]
```
$ dolt push --set-upstream origin master
Tree Level: 2 has 2 new chunks of which 0 already exist in the database. Buffering 2 chunks.
Tree Level: 2. 100.00% of new chunks buffered.
Tree Level: 1 has 2 new chunks of which 0 already exist in the database. Buffering 2 chunks.
Tree Level: 1. 100.00% of new chunks buffered.

error: push failed
cause: rename /run/user/1000/c4a538e2-8e02-4a64-b0be-dd4885ec6c30.tf .dolt/temptf/2087s0j7op35jpsrh213pr85rfmse8bg: invalid cross-device link
```
Which seems to be because of https://stackoverflow.com/a/43967659/1190453 (my TMPDIR is on tmpfs)

**Comment by timsehn** [comment]
We're discussing this one in the office right now. Thanks for the report.

**Comment by timsehn** [comment]
This one is a little tricky to fix so we are going to backburner it. The workaround is to set your tmpdir to something not tmpfs. Thanks for the report.

**Comment by tomdottom** [comment]
Would if be possible to configure `dolt` to use a different `/tmp` directory.  For those of us using `tmpfs` this would be easier that messing with our mount config

**Comment by tomdottom** [comment]
Quick workaround for others that are running into this:

1. Create a new directory on _the same mounted file system_ to server as the `tmp`
2. `export TMPDIR=/path/to/new/dir`
3. `dolt push --set-upstream origin master`

**Comment by timsehn** [comment]
Thanks for the workaround! Another user just ran into this so we should prioritize fixing it :-)

**Comment by Lakitna** [comment]
Ran into the same issue today.

If it helps, I'm running Dolt in Windows Subsystem for Linux.

It's a real bummer, I was trying to explore Dolt for the first time.

**Comment by timsehn** [comment]
Did the workaround not work for you? Set tmpdir to something on the same
mounted filesystem as your Dolt repo?

**Comment by timsehn** [comment]
And thank you for the shame. I'm bumping this up in the priority stack :-)

**Comment by Lakitna** [comment]
Haha, don't feel too ashamed. We've all had this happen at some point :)

The workaround does work as long as you make sure the temp folder actually exists. It will not make it for you if it doesn't.

In any case, it now works well enough for me to poke around this super interesting concept.

**Comment by timsehn** [comment]
We're targeting end of next week for a fix for this meaning it will likely
be in Dolt 0.18. Thanks for trying Dolt.

**Comment by bheni** [comment]
https://github.com/liquidata-inc/dolt/pull/671

Will be in next week's release.  I believe it will be 0.17.
