### ISSUE TITLE
Feature request: lag

### ISSUE THREAD

**Issue by n8layman** [dolthub/dolt#2531]
Any chance of implementing the lag sql function?

**Comment by andrew-wm-arthur** [comment]
@n8layman thanks for this issue

Currently our window function support is minimal, @max-hoffman is in the process of improving support. I'll let him reply with an estimate. 

https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_lag

**Comment by max-hoffman** [comment]
I am out for 2 weeks but this will take about 1 day to PR, test and merge. Will fold into the first January Dolt release.

**Comment by max-hoffman** [comment]
https://github.com/dolthub/go-mysql-server/pull/715
