### ISSUE TITLE
mysql client connection gets disconnected from shell when running queries

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#2539]
dolt sql-server connection gets disconnected when using mysql client from terminal after release of v0.34.9

skipped bats test:
https://github.com/dolthub/dolt/blob/jennifer/mysql-shell-test/integration-tests/bats/sql-server.bats#L1420

**Comment by zachmu** [comment]
@jennifersp this is fixed now, right?

**Comment by jennifersp** [comment]
yes, closing the issue.
