### ISSUE TITLE
Broken Link in hint text

### ISSUE THREAD

**Issue by doInfinitely** [dolthub/dolt#2544]
Steps to reproduce:

Attempt to import doltpy without dolt in path and it sends you here:
https://www.dolthub.com/docs/tutorials/installation/

Instead of here:
https://docs.dolthub.com/introduction/installation

**Comment by max-hoffman** [comment]
This fixes the link displayed alongside `dolt` install instructions.

https://github.com/dolthub/doltpy/pull/171
