### ISSUE TITLE
dolt table import --pk option, dolt schema import --pks option

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#257]
These should support the same argument for primary keys, or support both ```--pk``` and ```--pks```.

**Comment by danbst** [comment]
I'd also like to have "no pks" import, as I have CSVs to import without meaningful identifiers

**Comment by timsehn** [comment]
"No pks" is a bigger feature as the underlying storage requires a pk. We know primary keyless tables are a somewhat required use case.

There are workarounds right now:
1. Make every column a primary key. This prevents duplicate rows but otherwise will work as you expect.
2. Add an id column. We can add a --pks auto which does this for you if you would like. Then when you update a table you would need it sorted in the same order with new stuff at the bottom for us to do the right thing.

Long term:
We would structure a table with no primary keys as having every column be the primary key and have an column called count in the Dolt storage layer. When we queried that table, we would expose the count column as duplicate rows.
