### ISSUE TITLE
REGEXP_REPLACE() has a read-X in the docs

### ISSUE THREAD

**Issue by Luuk34** [dolthub/dolt#2588]
In the docs at: https://docs.dolthub.com/reference/sql/support/expressions-functions-operators
Is a red-**X**  after the function REGEXP_REPLACE

In this answer on Stackoverflow you can see that this function seems to work, using Dolt 0.35.3

https://stackoverflow.com/a/70643526/724039

P.S. Sorry I am tooo lazy to copy that answer here...

**Comment by timsehn** [comment]
@zachmu @JCOR11599 

https://github.com/dolthub/dolt/issues/2345

Please update the docs.

**Comment by JCOR11599** [comment]
Updated docs.
