### ISSUE TITLE
Does dolt support stateless interaction with remote?

### ISSUE THREAD

**Issue by dylanwilder** [dolthub/dolt#2589]
Is the only way to use dolt via cloning a local copy (ie local state)? Is there a way to operate on branches remotely? This makes it difficult to deploy as a backend for stateless services.

**Comment by timsehn** [comment]
The way we recommend doing this is through starting a `dolt sql-server`. Then, you have your applications connect to the server with MySQL clients and perform operations.

Here's a pretty detailed example using Django as the application framework.

https://www.dolthub.com/blog/2021-06-09-running-django-on-dolt/

**Comment by timsehn** [comment]
Also:

https://docs.dolthub.com/reference/sql/branches
