### ISSUE TITLE
Changes, made by "before insert" trigger do not rollback when insert fails

### ISSUE THREAD

**Issue by evyalyy** [dolthub/dolt#2613]
I have table `seq_table`, which keeps max sequence value, and a trigger for table, which replaces specific field with current value from sequence table and increments sequence.
But if insert fails (due to PK duplication for example), changes made by trigger in `seq_table` are still there and not rolled back.
Here is full repro:
```
create table seq_table (max_id integer primary key);

create table test_table(id integer primary key, secondary_id integer default 0, sometext text);

create trigger default_id_test_table before insert on test_table
for each row
begin
    set new.secondary_id = (select coalesce(max_id,1) from seq_table);
    update seq_table set max_id = max_id + 1;
end;


insert into seq_table values (1);

insert into test_table values (1, 0, 'first');

insert into test_table values (1, 0, 'error');
```

**Comment by JCOR11599** [comment]
The fix for this has been merged to main and will be available next release. Is this a blocker for you?
If so, let me know here and I'll cut a release. Otherwise, it will go out sometime next week.
