### ISSUE TITLE
`dolt table import -u <table>` shows incorrect processing information for `us-housing-prices`

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2615]
All rows show up under `Modifications`, regardless of if they were added or had no effect.

To reproduce:
```
dolt clone abmyii/us-housing-prices-mini
cd us-housing-prices-mini
echo """sale_date,property_id,city,property_type,physical_address,sale_price,state,county,source_url
> 2021-12-03 00:01:00,R128381380,OKLAHOMA CITY,1½ STORY FIN,11300 AUTUMN RD,0,OK,OKLAHOMA COUNTY,https://docs.oklahomacounty.org/AssessorWP5/DefaultSearch.asp
> 2021-12-03 00:01:00,R122312360,OKLAHOMA CITY,RANCH 1 STORY,11313 CIMARRON DR,190000,OK,OKLAHOMA COUNTY,https://docs.oklahomacounty.org/AssessorWP5/DefaultSearch.asp""" > import.csv
dolt table import -u sales import.csv
```
The import shows the following information:
```
$ dolt table import -u sales import.csv
Rows Processed: 2, Additions: 0, Modifications: 2, Had No Effect: 0
Import completed successfully.
```
Whereas running `dolt diff` will show the two rows as being added.

**Comment by VinaiRachakonda** [comment]
The semantics for update are `INSERT ON DUPLICATE UPDATE` which is essentially represented as a modification given our query planner. 

I can definitely take a pass at making a distinction that more clear.

You also mentioned that `had no effect` is not correctly being updated? Do you have a repro for? In this example it is correct that Had No Effect should be 0.

**Comment by abmyii** [comment]
I see - clarification would be great! I don't have a repro for the second scenario. It was being discussed on the `#dolt` channel earlier today as someone else had run into the same issue.
