### ISSUE TITLE
AS OF queries do not support TIMESTAMP

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2628]
`SELECT * FROM employee_hourly AS OF TIMESTAMP('2022-01-16 06:35:30');`

Throws a branch not found error.

All our bats tests use this syntax:

`select pk,c1 from one_pk as of CONVERT('2020-03-01 12:00:00', DATETIME)`

Our documentation uses TIMESTAMP:

https://docs.dolthub.com/reference/sql/querying-history

**Comment by tbantle22** [comment]
Should work on dolthub now https://www.dolthub.com/repositories/av16/demo/query/main?q=SELECT+*+FROM+employee_hourly+AS+OF+TIMESTAMP%28%272022-01-16+06%3A35%3A30%27%29%3B%0A&active=Tables

Also added AS OF tests to dolthubapi
