### ISSUE TITLE
can we deploy my own dolthub likes gitlab, or gerrit in my server?

### ISSUE THREAD

**Issue by dyexlzc** [dolthub/dolt#2703]
i had searched the whole network and can't find a solution to deploy a dolthub in my server.

**Comment by bpf120** [comment]
This will help you get started. We are calling it DoltLab. 
https://www.dolthub.com/blog/2022-01-14-announcing-doltlab/

**Comment by timsehn** [comment]
This is the repo for doltlab:

https://github.com/dolthub/doltlab-issues

Hit us up there if you have any issues.
