### ISSUE TITLE
Strange behavior of DOLT_MERGE()

### ISSUE THREAD

**Issue by prodoelmit** [dolthub/dolt#2705]
DOLT_MERGE() doesn't behave the same way as expected based on what we're used to in git

### Preparation:
There are two branches: `main` and `test_ff` 
```
UPDATE dolt_branches SET hash = HASHOF("main^") WHERE name='test_ff'
SELECT DOLT_CHECKOUT("test_ff")
```

Check hashes: 
```
SELECT 
  HASHOF("main") as main, 
  HASHOF("main^") as main_prev,
  HASHOF("test_ff") as test_ff,
  HASHOF("HEAD") as head,
  @@dolt_head as session_head
```

Result is as expected:
```
main,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
main_prev,8h0itn1vjps4ndsgp88oc6djlgg21si0
test_ff,8h0itn1vjps4ndsgp88oc6djlgg21si0
head,8h0itn1vjps4ndsgp88oc6djlgg21si0
session_head,8h0itn1vjps4ndsgp88oc6djlgg21si0
```

### Merge
After it I run
```
SELECT DOLT_MERGE("main")
```

### Expected result
Expected result should be: `dolt_status` is empty, hashed are as followed:
```
main,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
main_prev,8h0itn1vjps4ndsgp88oc6djlgg21si0
test_ff,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
head,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
session_head,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
```

### Actual result
`SELECT * FROM dolt_status` tells that there are modifications staged (Looks like bug #2679)

hashes: 
```
main,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
main_prev,8h0itn1vjps4ndsgp88oc6djlgg21si0
test_ff,dmqpls64i3s1u0f9udrvtl4g7dvl1hgt
head,8h0itn1vjps4ndsgp88oc6djlgg21si0
session_head,8h0itn1vjps4ndsgp88oc6djlgg21si0
```

**Comment by VinaiRachakonda** [comment]
@prodoelmit Do you mind letting us know whether autocommit was on or off?

**Comment by prodoelmit** [comment]
I haven't touched it, running `SELECT @@autocommit` gives `1`

**Comment by VinaiRachakonda** [comment]
@prodoelmit I am unable to reproduce your bug against our main branch. That being said the `UPDATE dolt_branches` semantics that you are using are not clearly defined with regards to our transactional layer. I would recommend using `DOLT_RESET` too set a branch to an earlier hash. 

I am merging some improvements too DOLT_MERGE soon to make the process of using it much smoother.
