### ISSUE TITLE
[Feature Request] Oh my Zsh support for local dolt folders

### ISSUE THREAD

**Issue by camilogarciabotero** [dolthub/dolt#2711]
Hi all,

I have recently opened a [Feature Request](https://github.com/ohmyzsh/ohmyzsh/issues/10635) on the official repo of `omz` so that dolt folders can get some support (theme or plugin) that expanses the experience of using `dolt` from the command line. 

If anyone got ideas of how this support can get better, they are welcomed. My initial idea was basically to have a prompt that tells us the state of the dolt folder (staged files/ commit)

<img width="754" alt="Screen Shot 2022-01-29 at 8 10 36 AM" src="https://user-images.githubusercontent.com/25586362/151662250-0d2f4340-03bd-475c-8530-281a290e3489.png">

Something that already is supported for git, but for dolt.

**Comment by zachmu** [comment]
Hi @camilogarciabotero,

Thanks for the feature request, that would be really cool!

I left a comment on your omz feature request with my ideas. Please tag me there if you want any other ideas, happy to follow up. In the meantime I'm going to close this, as it's not really a feature request for dolt itself.

Zach
