### ISSUE TITLE
dolt push: invalid or corrupt table file

### ISSUE THREAD

**Issue by SamDM** [dolthub/dolt#2713]
After executing an 'alter table' statement (adding an index to a column), I cannot longer push to a remote.
(I am using a file-based remote).

Even when adding a brand new (empty) remote, I get the same error.
```
mkdir /tmp/tmp_dolt_remote/
dolt remote add tmp 'file:///tmp/tmp_dolt_remote'
dolt push tmp
```
```
error: push failed
cause: invalid or corrupt table file
```

Unfortunately, I cannot share the database on which I am working.

What would be the first step to debug this? I can't find anything online that mentions this error.

**Comment by SamDM** [comment]
Update: the failed push operation seems to have corrupted the remote as well.
```
dolt clone 'file:///path/to/remote'
```
```
cloning file:///path/to/remote
error: failed to get remote db
cause: invalid or corrupt table file
```

**Comment by SamDM** [comment]
Update: it seems like removing **all** remotes and adding them again one by one fixed the problem.

The original issue was caused by a push on a network mounted drive that failed half-way (the drive was full).
Not something that should be solved by 'dolt' of course, but the error message could be improved.

**Comment by timsehn** [comment]
Would you like us to keep this issue open or make a new issue for the bad error message?

**Comment by bpf120** [comment]
@SamDM We'd love to hear about how you are using Dolt. Would you be up for a 15-minute call with me and Tim to share?

**Comment by SamDM** [comment]
> Would you like us to keep this issue open or make a new issue for the bad error message?

Either is fine for me. My main motivation for posting here was to get some pointers on how to debug the issue. And also to provide an answer for people googling 'invalid or corrupt table file' in the future.

I am not familiar with Go, so I don't plan to hack into the Dolt source code myself. But feel free to re-open this issue if you wish to improve the error message.

**Comment by SamDM** [comment]
> @SamDM We'd love to hear about how you are using Dolt. Would you be up for a 15-minute call with me and Tim to share?

The project I'm working with is, unfortunately, private company information. What I can share is that I'm using Dolt through the [sqlmodel api](https://sqlmodel.tiangolo.com/) and it is working really well.

**Comment by timsehn** [comment]
I'll leave it closed then :-)

**Comment by bpf120** [comment]
@SamDM That's great to hear it's working well. I'm on the business side so just curious about the use case, how you found us, etc.  All of that helps us with marketing and roadmap. You wouldn't need to share any of your private data..  Feel free to email me brianf@dolthub.com or Tim at tim@dolthub.com if you want to share.  Anyway, glad you are using Dolt, and keep us posted on how it's going.
