### ISSUE TITLE
[Feature Request] Support `with recursive`

### ISSUE THREAD

**Issue by post-no-preference** [dolthub/dolt#2719]
It would be nice to have access to `with recursive`. It's not a dealbreaker as the `with recursive` part can be done in code instead.

MySQL docs: https://dev.mysql.com/doc/refman/8.0/en/with.html

**Comment by max-hoffman** [comment]
@post-no-preference can you give an example of the kind of queries you are trying to run? just to confirm you don't need anything like correlated CTE's or nested CTE's

**Comment by max-hoffman** [comment]
It would also be helpful to know if you need insert, update and delete recursive CTEs on a first pass.

**Comment by post-no-preference** [comment]
I'm not doing anything too complex. If I have a table:

```sql
create table profit_loss
(
  date date,
  profit_loss decimal
);
```

I'd like to see over time what has happened with the profit/loss. So some query like:

```sql
with recursive cumulative_profit_loss(cur_date, cur_profit_loss) as (
  select
    date,
    profit_loss
  from
    profit_loss
  where
    date = (select min(date) from profit_loss)
  union all
  select
    date,
    profit_loss + cur_profit_loss
  from
    cumulative_profit_loss
  join
    profit_loss
  on
    date_sub(date, interval 1 day) = cur_date
)
select
  *
from
  cumulative_profit_loss;
```

No need to do inserts or updates from these queries.

**Comment by max-hoffman** [comment]
Working on execution runtime for recursive CTEs, hopefully will get something working before the end of the week.

In the meantime (and in general for time series aggregations), you might find window functions useful:

```SQL
tmp> create table profit_loss (date date, profit_loss decimal);
tmp> insert into profit_loss values ('2022-02-01', 1), ('2022-02-02', 3.0), ('2022-02-03', 1.0), ('2022-02-04', -1.0);
tmp> select date, sum(profit_loss) over (order by date) as cur_profit_loss from profit_loss order by date;
+-------------------------------+-----------------+
| date                          | cur_profit_loss |
+-------------------------------+-----------------+
| 2022-02-01 00:00:00 +0000 UTC | 1               |
| 2022-02-02 00:00:00 +0000 UTC | 4               |
| 2022-02-03 00:00:00 +0000 UTC | 5               |
| 2022-02-04 00:00:00 +0000 UTC | 4               |
+-------------------------------+-----------------+
```

**Comment by post-no-preference** [comment]
Indeed, that would have done the trick. Thanks for pointing that out.

**Comment by max-hoffman** [comment]
When merged, this PR will support a subset of recursive CTE behavior:  https://github.com/dolthub/go-mysql-server/pull/783

Nested recursive CTEs and some nested subqueries are not supported. If you need additional features or discover resolver errors for unsupported expressions that I missed just let me know and I will fix.

The query you gave above works now (with a few edits to accommodate our aliasing rules):

```SQL
with recursive cumulative_profit_loss(cur_date, cur_profit_loss) as (
  select
    date,
    p1.profit_loss
  from
    profit_loss as p1
  where
    date = (select min(date) from profit_loss)
  union all
  select
    date,
    p2.profit_loss + cur_profit_loss
  from
    cumulative_profit_loss
  join
    profit_loss as p2
  on
    date_sub(date, interval 1 day) = cur_date
)
select
  *
from
  cumulative_profit_loss;
+-------------------------------+-----------------+
| cur_date                      | cur_profit_loss |
+-------------------------------+-----------------+
| 2022-02-01 00:00:00 +0000 UTC | 1               |
| 2022-02-02 00:00:00 +0000 UTC | 4               |
| 2022-02-03 00:00:00 +0000 UTC | 5               |
| 2022-02-04 00:00:00 +0000 UTC | 4               |
+-------------------------------+-----------------+
```
