### ISSUE TITLE
`DOLT_CHECKOUT('-b', 'newbranch)` should take working set changes to new branch

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#2723]
For example doing `DOLT_MERGE('--squash')` leaves the state with a dirty working set. We should be able to do a DOLT_CHECKOUT from there.

**Comment by zachmu** [comment]
There's currently no way to stash session changes before changing branches. This would let customers move them to a new branch and commit them there.

**Comment by timsehn** [comment]
We decided that in the SQL context DOLT_CHECKOUT() does not take working set changes.
