### ISSUE TITLE
Allow duplicate indexes to be created

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2729]
Dolt currently errors out on the creation of an index that has the same columns, in the same order, as another index. This is a problem for compatibility, as this is allowed by MySQL and required by naïve conversion from other database formats such as Postgres, which treat `UNIQUE` as a constraint rather than an index type, as MySQL does.

Work items:

1) Remove this constraint, e.g. https://github.com/dolthub/dolt/tree/zachmu/allow-duplicate-indexes
2) Verify that duplicate indexes don't mess up index selection in engine (new tests)
3) Fix bats tests that verify duplicate indexes can't be created, add new bats tests demonstrating they can

**Comment by timsehn** [comment]
@JCOR11599 will fix this one soon.

**Comment by JCOR11599** [comment]
Fix is merged into GMS main and Dolt main
