### ISSUE TITLE
set  root `password` in SQL session without removing administrator password

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#2756]
After users/grants are added, the `password` value used to initialize a SQL-server may be editable.

This will be more useful if we differentiate between `administrator` and `root` passwords, only one of which is editable to help avoid locking admins out of SQL-servers.

**Comment by max-hoffman** [comment]
https://github.com/dolthub/dolt/issues/2753

**Comment by timsehn** [comment]
This is resolved. You can edit passwords using grants but if you start a SQL server with `config.yaml` or the `-u` command line argument that user is created for you with `GRANT ALL`.
