### ISSUE TITLE
Expose remote branches same as Git

### ISSUE THREAD

**Issue by Salad-King** [dolthub/dolt#2763]
While working on dolt, the remote references are not updated in local in the same way git does.

Example:
1. dev1 creates a new branch on git
2. dev2 creates another branch on git
3. dev1 issues fetch/pull command to only update the remote refs 
4. dev 1 can now see that there are new branches created

Go in general, git does a better job of exposing active remote branches. It also supports --track. Please align Dolt to the same behavior.

**Comment by timsehn** [comment]
--track is now supported.
