### ISSUE TITLE
Support: is there a query to extract file content on a specific date?

### ISSUE THREAD

**Issue by aborruso** [dolthub/dolt#2785]
Hi to all,
imagine I have repo in which I update a txt file day by day.

Is there a way to run a query as `SELECT nameFile from repo where datetime LIKE 2021-12-27`?

Thank you

**Comment by timsehn** [comment]
https://docs.dolthub.com/reference/sql/querying-history

Specifically:

`SELECT * FROM myTable AS OF TIMESTAMP('2020-01-01');`

Let us know if that works for you.

**Comment by aborruso** [comment]
First of all thank you very much!

> Let us know if that works for you.

I need some info about first steps. I have installed dolt in my debian, running

```
sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'
```

Now I want to extract the `2021-12-27` version of my `input.txt` file. Before running the SQL query, do I must create a dolt db or to init something?
Do I need to import my `input.txt` file or dolt will query simply the git history?

I have read you great documentation, but I did not understand what are the right steps to take in this simple case of mine.

**Comment by timsehn** [comment]
So, you have dolt installed. Here are the steps:

1. type `dolt` on your shell and make sure you see a command list. This indicates dolt is in your path.
2. dolt commands are exactly like git commands (if you use it that way). So make a directory called `doltdb`, cd into that directory and run `dolt init`. That creates a new database. 
3. So, now, it matters what is in `input.txt`. Is it just a flat text file you want to version over time? If so, dolt really isn't for that. Git will do better. Dolt is a SQL database that has git-style versioning. Dolt versions Tables. So, I assume it's a CSV or some sort of tabular data. If it is, you need to run `dolt table import`. But here's where I get stuck. I need to know what is in input.txt and how it maps to the tables you want in your dolt database.

**Comment by aborruso** [comment]
Hi @timsehn and thank you.

My file is a CSV. From what I read, I understand that I can track it from the import onwards. I cannot use dolt, on external files. So to use it for past variations, I just use git.
Did I get it right?

**Comment by timsehn** [comment]
You

**Comment by aborruso** [comment]
> This document goes into your use case, pretty well.
> 
> https://docs.dolthub.com/introduction/getting-started/git-for-data

Thank you again.

So to use it for past variations, I just use git.
Did I get it right?

**Comment by timsehn** [comment]
If you want to version a text file, use git.

If you want to version a SQL table, use Dolt. Import the text file as a csv into Dolt.

**Comment by bpf120** [comment]
@aborruso Our Discord is pretty active if you need more help too. All of the team hangs out there. Tim and I are happy to jump on a call to walk through your Dolt use case if you are looking at using it at your company.

Here's our Discord
https://discord.com/invite/RFwfYpu
