### ISSUE TITLE
Every SQL Commit is a Dolt Commit

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2802]
There is a use case where a user does not control over their client code and wants to use Dolt with a remote.

For this case, the user wants some version of the following:

* On each SQL Commit:
  * dolt commit
  * dolt push to branch specified in connection string/use to the remote configured

This is the next evolution of "push on write". It's "dolt commit/push on write".

This should be supported in the Dolt configuration.

**Comment by avaitla** [comment]
This would allow truly drop in dolt as a 3306 port to an existing application, whereas currently you cannot since you'd need to modify your application to do dolt add, dolt commit, dolt push - even if it already uses vanilla mysql crud.

**Comment by zachmu** [comment]
Hi @avaitla,

We have a mode that does this but it's not obvious.

```sql
set @@dolt_transaction_commit = 1
```

Apparently the docs for this system variable are missing. I'll fix that.

Then set up push on write to push every commit to your remote, as described here:

https://docs.dolthub.com/reference/sql/replication#push-on-write-from-sources

More info on the remote system variable here:

https://docs.dolthub.com/reference/sql/dolt-sysvars#dolt_replicate_to_remote

If any of this doesn't work or is difficult to use in a hosted solution, let us know ASAP and we'll get it working.

**Comment by timsehn** [comment]
He is currently using deploy tab, so I don't think it lets you set up custom configuration.

**Comment by zachmu** [comment]
Regardless of the server config, you can change this setting for all sessions like so:

```sql
set @@GLOBAL.dolt_transaction_commit = 1
```

**Comment by avaitla** [comment]
Odd connected to Dolthub Hosted Instance:

```
mysql> set @@GLOBAL.dolt_transaction_commit = 1;
ERROR 1105 (HY000): Variable 'dolt_transaction_commit' is a SESSION variable and can't be used with SET GLOBAL
```

**Comment by zachmu** [comment]
That's a bug, we'll get that fixed this week.

https://github.com/dolthub/dolt/issues/2806

**Comment by zachmu** [comment]
Docs for system variable are here:

https://docs.dolthub.com/reference/sql/dolt-sysvars#dolt_transaction_commit

**Comment by JCOR11599** [comment]
In the dolt config, you need to have every SQL transaction commit be made into a dolt commit and then push to origin.
You can modify the config like so:
```shell
$ dolt config --local --add sqlserver.global.dolt_transaction_commit 1
$ dolt config --local --add sqlserver.global.dolt_replicate_to_remote origin
```

**Comment by timsehn** [comment]
We're on it.
