### ISSUE TITLE
Using `--continue` flag for `dolt table import -u` doesn't add any rows

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2820]
This may be Windows-only. The version used was `0.37.0`. The output info showed that the rows were added and `Import successful`, but the changes didn't persist.

**Comment by VinaiRachakonda** [comment]
Can you provide a repro?

**Comment by abmyii** [comment]
OK, this isn't Windows-only, but it seems to be specific to the setup of the `us-housing-prices` database (perhaps the constraints?). To test, run `dolt table import -u sales test.csv` on the master branch. Both rows are valid except that I have changed the hour to 99 for the first `sale_date`.
[test.csv](https://github.com/dolthub/dolt/files/8088282/test.csv)

**Comment by VinaiRachakonda** [comment]
1. The attached schema in the csv file is very different from the table schema. Several of the column do not align with the schema, making it possible you are not actually updating a row to its new value.
2. This issue helped me identify a bug in our import statistics calculator that needs to get fixed.

**Comment by abmyii** [comment]
> * The attached schema in the csv file is very different from the table schema. Several of the column do not align with the schema, making it possible you are not actually updating a row to its new value.

I believe it is valid, as it worked once I removed the rows being skipped manually. I removed the additional rows and tried again, with result being the same, so I do think it is a bug in the importer.

[test.csv](https://github.com/dolthub/dolt/files/8116493/test.csv)

> 2\. This issue helped me identify a bug in our import statistics calculator that needs to get fixed.

Great!

**Comment by VinaiRachakonda** [comment]
Leaving as a note to myself. There is improper handling with --skip and violated check constraints.

**Comment by VinaiRachakonda** [comment]
Merged in master
