### ISSUE TITLE
Add details to information_schema.statistics table.

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#2856]
This is causing us to not display important information in relevant SQL Editors. For example, in the below Tableplus screenshot you cannot see the different index definitions.

![Screen Shot 2022-02-22 at 10 57 38 AM](https://user-images.githubusercontent.com/7027863/155200068-34928704-f7bd-42e5-a234-f9a684ad7359.png)

**Comment by jennifersp** [comment]
`information_schema.statistics` table is added in https://github.com/dolthub/go-mysql-server/pull/825
