### ISSUE TITLE
Hanging/memory leak on importing a single row to a specific branch

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2869]
To reproduce:
```bash
dolt clone abmyii/hospital-price-transparency-v3
dolt checkout Ascension
dolt table import -u hospitals hospitals.csv
```

Where `hospitals.csv` is:
[hospitals.csv](https://github.com/dolthub/dolt/files/8127781/hospitals.csv)

Note that out of the 16 rows being imported a some hang and others work. The single row below will also trigger the bug: 
```
cms_certification_num,chargemaster_url,homepage_url,last_edited_by_username
232034,https://healthcare.ascension.org/price-transparency/price-transparency-files,https://healthcare.ascension.org/Locations/Michigan/MIKAL/Kalamazoo-Ascension-Borgess-Hospital,abmyii
```

`UPDATE`s also hang:
```sql
UPDATE hospitals SET chargemaster_url="https://healthcare.ascension.org/price-transparency/price-transparency-files", homepage_url="https://healthcare.ascension.org/Locations/Michigan/MIKAL/Kalamazoo-Ascension-Borgess-Hospital", last_edited_by_username="abmyii" WHERE cms_certification_num="232034";
```

This bug only occurs on the `Ascension` branch, which leads me to thinking that I messed it up somehow. Earlier imports worked fine, though occasionally they were cancelled or killed (OOM).

**Comment by JCOR11599** [comment]
This appears to be an issue with foreign keys, I am working on a fix right now.
A workaround in the meantime is to set `foreign_key_checks = 0`.

**Comment by JCOR11599** [comment]
Fix for this is on main
