### ISSUE TITLE
dolt dump - Error with dumping

### ISSUE THREAD

**Issue by wilj** [dolthub/dolt#2874]
I'm getting the following error when I try to run "dolt dump" on my project:

```
Error with dumping voter_detail.
cause: typeinfo.VarStringTypeIdentifier is not types.String
```

Steps to reproduce:

```
dolt clone wilj/flvoters
cd flvoters
dolt dump
```

Both machines I've tried it on are Linux (one Ubuntu, one Debian), x64_64.

**Comment by zachmu** [comment]
Thanks for the report, we'll investigate this today.
