### ISSUE TITLE
can not exit after execute `dolt login`

### ISSUE THREAD

**Issue by JasonkayZK** [dolthub/dolt#2897]
it seems to be an endless loop:

```
Retrying in 4 
```

And `Command + C` won't work!

**Comment by timsehn** [comment]
This should be fixed in the latest version:

https://github.com/dolthub/dolt/pull/2775

Can you confirm you're on the latest Dolt?

**Comment by JasonkayZK** [comment]
I used the docker image:

https://gallery.ecr.aws/p1l9q4h7/dolt

which mentioned at:

https://github.com/dolthub/dolt/issues/1897

latest version worked, thanks❤️

**Comment by timsehn** [comment]
Great! Thanks for the report
