### ISSUE TITLE
Columns can have more than one not-null constraint in storage

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2927]
Discovered during schema merge: these two columns have the same definition, except that one has 2 not-null constraints and the other has 3:

![image](https://user-images.githubusercontent.com/474773/156825773-520f2674-d771-4893-9f21-5ff5ff6c03a9.png)

Repro: with US hospitals transparency database on dolthub, clone or add as a remote:

```bash
% dolt remote -v
spacelove https://doltremoteapi.dolthub.com/spacelove/hospital-price-transparency-v3
```

Create branches pointing to these commits:

```bash
% dolt branch -v
  sp-amg-take2                                          713h0qb2s7t3e4a7hpda987k7vi7mq46
* sp-main                                               itklav24s53hhrnlo1l5po6bgh9nvrhs
```

Then merge ps-amg-take2 into sp-main:

```bash
dolt merge --no-ff sp-amg-take2
Updating itklav24s53hhrnlo1l5po6bgh9nvrhs..713h0qb2s7t3e4a7hpda987k7vi7mq46
Unable to stage changes: add and commit to finish merge
error: Failed to commit changes.
cause: schema conflicts for table prices:
        different column definitions for our column cms_certification_num and their column cms_certification_num
        different column definitions for our column payer and their column payer
        different column definitions for our column code and their column code
        different column definitions for our column internal_revenue_code and their column internal_revenue_code
        different column definitions for our column inpatient_outpatient and their column inpatient_outpatient
        different column definitions for our column code_disambiguator and their column code_disambiguator
```

All the columns are un-equal because of a differing number of not-null constraints.

The action items for this bug:

1) Make it impossible for a column's definition to have more than one not-null constraint
2) Make column equality test used in schema merge ignore differing numbers of non-null constraints
3) When writing schemas to disk, collapse any duplicate non-null constraints down to a single one (for any repos already affected by this bug)
4) Write exhaustive tests that this can't happen. Trigger is unknown, but I believe it has to do with dropping and re-adding primary keys.

**Comment by JCOR11599** [comment]
Fix is merged into main. Schemas with columns with multiple NOT NULL constraints are trimmed down to just one when read from disk. We also throw an error if a schema with columns with multiple NOT NULL constraints is trying to be written to disk.
