### ISSUE TITLE
Schema merge should merge constraints more intelligently

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2928]
I make two branches. On one of them, I create some check constraints on a column. On another, I create a not-null constraint on that column. When I merge both back to main, they conflict and prevent the merge.

Non-overlapping constraint changes should merge together just like non-overlapping column changes in data.

This needs lots of tests.

**Comment by timsehn** [comment]
I think we decided this is a conflict. It's too hard to get this right and the fix is easy for the user to overcome.
