### ISSUE TITLE
Error altering table - high memory usage and process is killed

### ISSUE THREAD

**Issue by wilj** [dolthub/dolt#2939]
I'm getting an error when trying to alter a table.  It runs for a long while, steadily consuming memory, until it runs out of memory and I get the message "Killed".  The dolt repository is "wilj/flvoters".

```
gitpod /workspace $ dolt clone wilj/flvoters
cloning https://doltremoteapi.dolthub.com/wilj/flvoters
829,713 of 829,713 chunks complete. 0 chunks being downloaded currently.
gitpod /workspace $ cd flvoters/
gitpod /workspace/flvoters $ dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
flvoters> alter table voter_detail add name_first_search varchar(30);



Killed
```

I also have semi-related questions:

1) Are there plans for function indexes?  I'd like to create indexes on "lower(trim(column_name))", unformatted phone numbers, etc.

2) I was adding "search" versions of some columns, to work around the lack of function indexes.  For now I'll work around the memory issue by creating a separate table for the searchable values and populate it from the main table.  Are there any storage concerns if I regularly load/replace the searchable tables from the original table?

**Comment by timsehn** [comment]
I'm going to try and repro on my macbook. Stay tuned.

On (1), There are no plans but create a separate issue for this. Right now the best way is to add a column like you suggest and maybe populate it with a trigger. I think effectively on the backend this would be equivalent in storage to a function index but whereas the function index is hidden from standard view, the column is materialized in the table and can get in the way. Hence, the feature request :-)

On (2), you can definitely set up a trigger to do this. It will increase your storage but not in some non-linear way.

**Comment by timsehn** [comment]
It did finish on my 16GB machine.
```
flvoters $ dolt sql -q "alter table voter_detail add name_first_search varchar(30);"
flvoters $ dolt schema show
voter_detail @ working
CREATE TABLE `voter_detail` (
  `county_code` varchar(3) NOT NULL,
  `voter_id` varchar(10) NOT NULL,
  `name_last` varchar(30),
  `name_suffix` varchar(5),
  `name_first` varchar(30),
  `name_middle` varchar(30),
  `requested_public_records_exemption` varchar(1),
  `residence_address_line_1` varchar(50),
  `residence_address_line_2` varchar(40),
  `residence_city` varchar(40),
  `residence_state` varchar(2),
  `residence_zipcode` varchar(10),
  `mailing_address_line_1` varchar(40),
  `mailing_address_line_2` varchar(40),
  `mailing_address_line_3` varchar(40),
  `mailing_city` varchar(40),
  `mailing_state` varchar(2),
  `mailing_zipcode` varchar(12),
  `mailing_country` varchar(40),
  `gender` varchar(1),
  `race` varchar(1),
  `birth_date` varchar(10),
  `registration_date` varchar(10),
  `party_affiliation` varchar(3),
  `precinct` varchar(6),
  `precinct_group` varchar(3),
  `precinct_split` varchar(6),
  `precinct_suffix` varchar(3),
  `voter_status` varchar(3),
  `congressional_district` varchar(3),
  `house_district` varchar(3),
  `senate_district` varchar(3),
  `county_commission_district` varchar(3),
  `school_board_district` varchar(2),
  `daytime_area_code` varchar(3),
  `daytime_phone_number` varchar(7),
  `daytime_phone_extension` varchar(4),
  `email_address` varchar(100),
  `name_first_search` varchar(30),
  PRIMARY KEY (`voter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

voter_history @ working
CREATE TABLE `voter_history` (
  `county_code` varchar(3) NOT NULL,
  `voter_id` varchar(10) NOT NULL,
  `election_date` varchar(10) NOT NULL,
  `election_type` varchar(3) NOT NULL,
  `history_code` varchar(1),
  PRIMARY KEY (`voter_id`,`election_date`,`election_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

But it took 20 minutes. @druvv is investigating.

**Comment by bpf120** [comment]
@wilj we'd love to hear about your use case too. You can send me an email (brianf@dolthub.com) or swing by our discord.

https://discord.com/invite/RFwfYpu

**Comment by druvv** [comment]
@wilj This issue was fixed this morning if you build Dolt from main you can get this fix immediately. We may also release a hotfix version on Releases.
