### ISSUE TITLE
`dolt table import` cannot handle table names with `-` in them

### ISSUE THREAD

**Issue by geweldon** [dolthub/dolt#2949]
So diving into updating tables from a csv file via the dolt command line.  I imported and created a series of tables from some csv exports from another database, and then attempted to update using a comparable but unique csv.  However I keep running into this error "Error creating reader for csv file:partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv."  I have included the full set of commands and results below, but I am baffled as to what is going on here.  

I am able to to import the csv's in question using the dolthub ui, and I can import them using the create option in an empty branch, but trying to update a table just keeps giving me an error.

grantweldon@MacbookPros-MacBook-Pro Org-record-backup-3 % dolt ls  
Tables in working set:
	 partner_org___dep_train_3-backup-product2
	 partner_org___dep_train_3-backup-sbqq__customaction__c
	 partner_org___dep_train_3-backup-sbqq__priceaction__c
	 partner_org___dep_train_3-backup-sbqq__pricecondition__c
	 partner_org___dep_train_3-backup-sbqq__pricerule__c
	 partner_org___dep_train_3-backup-sbqq__productfeature__c
	 partner_org___dep_train_3-backup-sbqq__productoption__c
	 
grantweldon@MacbookPros-MacBook-Pro Org-record-backup-3 % dolt table import -u partner_org___dep_train_3-backup-sbqq__productoption__c partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv 

Error creating reader for csv file:partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv.
cause: syntax error at position 41 near 'partner_org___dep_train_3'
When attempting to move data from csv file:partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv to partner_org___dep_train_3-backup-sbqq__productoption__c, could not open a reader.

grantweldon@MacbookPros-MacBook-Pro Org-record-backup-3 % dolt table import -r partner_org___dep_train_3-backup-sbqq__productoption__c partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv 
Error creating reader for csv file:partner_org___dep_train_3-backup-sbqq__productoption__c-20220308222108.csv.

**Comment by timsehn** [comment]
Thanks for the report. That error message is bad.

Is the data and dolt database you're using public? Can you point us at the repository and provide a copy of the CSV?

**Comment by timsehn** [comment]
@VinaiRachakonda just changed this code so he is the best to start debugging.

**Comment by timsehn** [comment]
Looks like this is you:

https://www.dolthub.com/repositories/geweldon/Org-record-backup-3

All we need is the CSV to try and repro.

**Comment by geweldon** [comment]
Awesome, thanks for the quick response.  Here is the csv in question.  I renamed it with a shorter name for convenience, but I'm seeing the same error.
[productoption.csv](https://github.com/dolthub/dolt/files/8217286/productoption.csv)

**Comment by geweldon** [comment]
and yes, that is me

**Comment by bpf120** [comment]
Hi @geweldon, we'd love to hear about your use case. Feel free to email me (brianf@dolthub.com) or swing by our Discord. https://discord.com/invite/RFwfYpu

**Comment by geweldon** [comment]
I would love to do that.  You guys are certainly doing some exciting stuff.  I'll shoot you an email

**Comment by timsehn** [comment]
I'm trying to repro right now.

**Comment by timsehn** [comment]
Repro'ed:
```
Org-record-backup-3 $ dolt table import -u partner_org___dep_train_3-backup-sbqq__productoption__c productoption.csv
Error creating reader for csv file:productoption.csv.
cause: syntax error at position 41 near 'partner_org___dep_train_3'
When attempting to move data from csv file:productoption.csv to partner_org___dep_train_3-backup-sbqq__productoption__c, could not open a reader.
```

**Comment by timsehn** [comment]
The plot thickens:
```
Org-record-backup-3 $ grep partner_org___dep_train_3 productoption.csv 
Org-record-backup-3 $ 
```

**Comment by geweldon** [comment]
It always does....

**Comment by timsehn** [comment]
So i think the problem is the table name contains `-` s our importer is getting confused, probably not escape quoting them on the backend when turning the import into SQL. We just changed this code.

Can you try renaming the tables to something without `-` and see if it works?

**Comment by geweldon** [comment]
Sure thing, give me a sec.

**Comment by timsehn** [comment]
```
Org-record-backup-3 $ dolt sql -q "alter table \`partner_org___dep_train_3-backup-sbqq__productoption__c\` rename partner_org___dep_train_3_backup_sbqq__productoption__c" 
Org-record-backup-3 $ dolt table import -u partner_org___dep_train_3_backup_sbqq__productoption__c productoption.csv
Rows Processed: 2, Additions: 0, Modifications: 0, Had No Effect: 2
Import completed successfully.
```

**Comment by timsehn** [comment]
That's it. Will rename the bug.

**Comment by timsehn** [comment]
Simple repro:
```
tablename-dash-bug $ dolt table import -c this-is-a-table test.csv
Rows Processed: 1, Additions: 1, Modifications: 0, Had No Effect: 0
Import completed successfully.
tablename-dash-bug $ dolt ls
Tables in working set:
	 this-is-a-table

tablename-dash-bug $ dolt table import -u this-is-a-table test.csv
Error creating reader for csv file:test.csv.
cause: syntax error at position 20 near 'this'
When attempting to move data from csv file:test.csv to this-is-a-table, could not open a reader.
tablename-dash-bug $ cat test.csv 
pk, c1
0,0
```

Making a bats test.

**Comment by timsehn** [comment]
PR for skipped bats test: https://github.com/dolthub/dolt/pull/2950
