### ISSUE TITLE
Change README to be more OLTP-centric, less command line-centric

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2951]
I think it's time to change the main README to be more OLTP use case centered.

**Comment by timsehn** [comment]
Should be similar to:

https://docs.dolthub.com/introduction/getting-started/database

which isn't great.

**Comment by timsehn** [comment]
Goal should be by the end of this you get to a wow Dolt moment like:

1. Viewing the `dolt_diff` table
2. Discovering your changes are in Conflict and resolving

Or something...

**Comment by fulghum** [comment]
Instead of shifting totally towards SQL access... it would be nice to shift the focus in the readme from the CLI functionality to the core Dolt feature/capability itself, then show (or mention/link) that those features are equally accessible from the CLI or from SQL queries.

**Comment by timsehn** [comment]
Complete
