### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference error when cloning a Dolt repository

### ISSUE THREAD

**Issue by martaac16** [dolthub/dolt#2960]
Seeing this issue with the most recent dolt versions, when downgrading to a previous version it is able to clone the repository without any issues.

Full error here:
<img width="1430" alt="Screenshot_2022-03-07_at_12 45 13" src="https://user-images.githubusercontent.com/88975671/157868375-6bf0c6ee-0fcd-43a9-b76d-bd6eb3aff296.png">

**Comment by timsehn** [comment]
Thanks for the report! 

@druvv is becomeing a master in push/pull/clone.

What repo are you trying to clone? Is it a public one?

**Comment by bpf120** [comment]
@martaac16 Thanks for filing and using Dolt! We'd love to hear about your use case.  You email me (brianf@dolthub.com) or swing by our Discord if you'd like to share.

https://discord.com/invite/RFwfYpu

**Comment by druvv** [comment]
@martaac16 What URL are you cloning from? By any chance are you cloning with a `file://` url?

**Comment by martaac16** [comment]
Hey all, thank you for all your help! It is a private repo hosted in GCP, which I can clone with older versions of dolt

**Comment by druvv** [comment]
@martaac16 I was able to reproduce the issue. Will provide updates on a fix soon.

**Comment by druvv** [comment]
@martaac16 Dolt v0.37.5 has the fix for this issue. You can download it here: https://github.com/dolthub/dolt/releases/tag/v0.37.5 !
