### ISSUE TITLE
Use a helper function to handle errors returned by functions in a defer statement?

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#2964]
I think Dolt should consider using some kind of linter or helper function to handle errors returned by functions in a defer statement. Debugging error logic when using defers that also return errors is tricky and can lead to found bugs such as #2961.

Consider the following function, can you spot the bug?
```go
func BuggyErrorHandling() (err error) {
	h, err := os.Open("test")
	defer func() {
		err = h.close()
	}()
	return err
}
```

The value of the returned err will always be the result of `h.Close()` even if `os.Open("test")` returns an error. So if `Open` returns an error, the returned error by `BuggyErrorHandling` will be nil if `Close` has no error! This is the correct code:
```go
func CorrectErrorHandling() (err error) {
	h, err := os.Open("test")
	defer func() {
		closeErr := h.Close()
		if err == nil {
			err = closeErr
		}
	}()
	return err
}
```

In #2961, the if statement inside the defer was mistyped as `if err != nil` which always overrode `os.Open`'s error! This lead to errors being dropped. Spotting this was tricky for me.

I propose the following helper:
```go
// MergeErrOf merges the error returned by |f| with |out|.
// Specifically, if |*out| is nil, set |*out| to be the error returned by |f|.
func MergeErrOf(f func() error, out *error) {
	fErr := f()
	if *out == nil {
		*out = fErr
	}
}
```

And usage:
```go
func EasyErrorHandling() (err error) {
	var h *os.File
	h, err = os.Open("test")
	defer MergeErrOf(h.Close, &err)
	return err
}
```

`MergeErrOf` needs to take a pointer to an error because the parameters of a deferred function are captured at the time of defer.

**Comment by fulghum** [comment]
Thanks for thinking about how we could eliminate a whole class of tricky to catch bugs! Having a standard, reusable function that takes care of proper error handling in deferred functions is interesting. I'm curious to hear what the go-gurus like @zachmu think and if they've seen any similar patterns. It could also be interesting to grep through our repos for use of defer and see how well this pattern would easily slide in. On first glance in just the dolt repo, I see ~120 deferred functions in non-test code that aren't handling errors. I'm not sure how many represent real issues, but I bet there's at least one potential bug hiding in there. 🐞 

I'm also super curious about the linter idea you mentioned. I don't know much about golang linters (yet), but I'm wondering if there's anything out there that already covers deferred function error handling, or even some project we could contribute a linter check to.

**Comment by zachmu** [comment]
A simple prophylactic for this kind of error is to never name error return params `err`. Always use `rerr` for those.

Another layer of defense is the nil-checking inside the defer block, which you already mentioned. But that's error prone too, it's better to not shadow the return param var in the first place.

Not very familiar with golang's linter, but if we could codify these two things into rules I'd be happy to run them in CI.

**Comment by zachmu** [comment]
To be clearer here: I don't think the proposed helper function is something we should standardize on, unless the linter route can't be made to work. I would start there.
