### ISSUE TITLE
value out of range - insert 0x... into binary

### ISSUE THREAD

**Issue by milahu** [dolthub/dolt#2968]
i cannot insert \*large\* [binary](https://mariadb.com/kb/en/binary/) values, encoded as hex numbers

```sh
which dolt 
# /nix/store/8v2qqrzj27g9xxginzvrc94b9ccfi96v-dolt-0.32.1/bin/dolt

dolt init

dolt sql -q "create table releases (
  id int unsigned NOT NULL AUTO_INCREMENT,
  package_id int NOT NULL,
  version varchar(255) NOT NULL,
  sha256 binary(32),
  primary key (id)
)"

dolt sql -q "create index releases on releases (package_id, version)"

dolt sql -q "insert into releases (package_id, version, sha256) values
(1, '1.2.3', 0x148aa875c3cdb9af8919493926a3d7c6862fec7f330152f400c0aecb4467508a),
(1, '1.2.4', 0xed6e67f2e0f177cbe19c0dc4dd9a66c73e631cab9757f3d68f73369a3a824441)
"
# strconv.ParseUint: parsing "148aa875c3cdb9af8919493926a3d7c6862fec7f330152f400c0aecb4467508a": value out of range

dolt sql -q "select * from releases where package_id = 1"
```

the sha256 hashes were generated with

```sh
date | sha256sum -
# 04b019492e6f44fce27de2c649cef21699cce604d2ab57c13aa5e30cd620f8e7  -
```

32 bytes

```
printf 148aa875c3cdb9af8919493926a3d7c6862fec7f330152f400c0aecb4467508a | xxd -r -p | dd >/dev/null
# 32 bytes copied
```

also tried to insert base64 string

```sh
dolt sql -q "insert into releases (package_id, version, sha256) values
(1, '1.2.3', 'nPRmDyVPoRTJj00x9yS4yt5k0jr7nfrisTv1+33gKgg=')
"
# string is too large for column
```

maximum value for `binary(32)` is `0xffffffffffffffff`

```py
# python
format(0xffffffffffffffff, 'b') == '1111111111111111111111111111111111111111111111111111111111111111'
len(format(0xffffffffffffffff, 'b')) == 64 # 64 bit = 8 byte
```

first out-of-range vaue is `0x10000000000000000`

growing the `binary(32)` to `binary(128)` or `blob` does not help
so this is a bug in the query parser

### workaround

split the 256 bit value across 4 x 64 bit fields = `BIGINT UNSIGNED` type = uint64

### trace

the error is thrown in this call to `se.Query`

https://github.com/dolthub/dolt/blob/71ebab589710d5e68ad570c3030e80540e0ff719/go/cmd/dolt/commands/sql.go#L1032-L1033

leads to `strconv.ParseUint` in [go-mysql-server](https://github.com/dolthub/go-mysql-server/blob/main/sql/parse/parse.go#L3002) ...?

```go
func convertInt(value string, base int) (sql.Expression, error) {
        // ...
        ui64, err := strconv.ParseUint(value, base, 64)
        if err != nil {
                return nil, err
        }
```

`convertInt` is called by

```go

	case sqlparser.HexNum:
		v := strings.ToLower(string(v.Val))
		if strings.HasPrefix(v, "0x") {
			v = v[2:]
		} else if strings.HasPrefix(v, "x") {
			v = strings.Trim(v[1:], "'")
		}

		return convertInt(v, 16)
	case sqlparser.HexVal:
		val, err := v.HexDecode()
		if err != nil {
			return nil, err
		}
		return expression.NewLiteral(val, sql.LongBlob), nil
```

&rarr; `sqlparser.HexNum` vs `sqlparser.HexVal` = int vs binary
HexNum is limited by the CPU integer size, in my case 64 bit

`sqlparser.HexNum` leads to [sqlparser](https://github.com/dolthub/vitess/tree/main/go/vt/sqlparser) ...?

**Comment by timsehn** [comment]
Thanks for the bug report. We will dig in Monday. @JCOR11599 will dig in.

**Comment by bpf120** [comment]
Hi @milahu , thanks for filing and using Dolt! We'd love to hear about your use case. Feel free to email me (brianf@dolthub.com) or swing by our Discord. 

https://discord.com/invite/RFwfYpu

**Comment by timsehn** [comment]
Thanks for the deeper debugging. This might actually be a @Hydrocharged problem.

**Comment by Hydrocharged** [comment]
@milahu Thanks for the bug report!

Your trace gave me a good starting off point, so much so that I had an idea of what was going on before digging in myself, so I appreciate that very much! 😄

Regarding the first with the `BINARY` column, I just submitted a pull request to fix this issue, and should be in the next Dolt release. The other attempt that was demonstrated (attempting to use a base64 number) will not work, as there's no automatic way to see that the string represents a base64 number (unlike the `0x` prefix). The base64 attempt also fails in MySQL.
