### ISSUE TITLE
`CHARACTER SET` in `CREATE DATABASE` statement results in SQL parsing error

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#2971]
Encountered SQL Parsing Error when running the following on Mac using `dolt` version 0.37.5 :
```bash
$ dolt sql -q 'CREATE DATABASE metabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
Error parsing SQL
syntax error at position 35 near 'CHARACTER'
CREATE DATABASE metabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
                                   ^
syntax error at position 35 near 'CHARACTER'
```

This statement succeeds in MySQL (mysql  Ver 8.0.27 for macos11.6 on x86_64 (Homebrew)):
```
mysql> CREATE DATABASE metabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
Query OK, 1 row affected (0.00 sec)
```

**Comment by zachmu** [comment]
Closely related: https://github.com/dolthub/dolt/issues/2976

**Comment by VinaiRachakonda** [comment]
cc @jennifersp

**Comment by jennifersp** [comment]
https://github.com/dolthub/go-mysql-server/pull/884 added parsing of this statement is supported, and it gives warning when this query is ru. It will run as `CREATE DATABASE metabase` without any changes to schema setting.
