### ISSUE TITLE
Composite Primary Key doesn't seem to work

### ISSUE THREAD

**Issue by avaitla** [dolthub/dolt#2977]
Failed on composite primary keys:

```
CREATE TABLE `random_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `a` int NOT NULL,
  `b` int NOT NULL,
  PRIMARY KEY (`a`,`user_id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2999 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ERROR 1105 (HY000): there can be only one auto_increment column and it must be defined as a key
```

**Comment by avaitla** [comment]
This seems pretty minor to me though, but if you wanted to shoot for compatibility something to look at. I think just using single PK and then a UNIQUE constraint would work fine

**Comment by timsehn** [comment]
This is the same bug as #2981. We don't allow non-primary-key auto increment.

**Comment by timsehn** [comment]
Closing in favor of #2981
