### ISSUE TITLE
mysqldump of an empty database needs to work in Dolt

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2983]
This does not work now.

**Comment by timsehn** [comment]
Here's a MySQL dump with a table that fails:

[test-database-tables.dump.txt](https://github.com/dolthub/dolt/files/8268257/test-database-tables.dump.txt)

**Comment by jennifersp** [comment]
Added parsing for these queries with warnings as the functionalities are not supported:
- `CREATE DATABASE /*!32312 IF NOT EXISTS*/ test /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;` 
- `/*!40000 ALTER TABLE columns_priv DISABLE KEYS */;`
- `/*!40000 ALTER TABLE columns_priv ENABLE KEYS */;`

Added system variable, "innodb_stats_auto_recalc" for the query:
-  `/*!50606 SET @OLD_INNODB_STATS_AUTO_RECALC=@@INNODB_STATS_AUTO_RECALC */;`

Missing syntaxes that need parsing:
- `GENERATED ALWAYS AS ... VIRTUAL` syntax for columns
-  `mysql.innodb_index_stats` table needs to be supported in mysql db

**Comment by timsehn** [comment]
This works now.
