### ISSUE TITLE
Feature Request: Support FULLTEXT KEY

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2987]
FULLTEXT KEY not supported:
```
CREATE TABLE `another_random_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `body` text NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `idx_body` (`body`)
) ENGINE=InnoDB AUTO_INCREMENT=223 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ERROR 1105 (HY000): syntax error at position 135 near 'KEY'
```

**Comment by timsehn** [comment]
This came in again in a customer request.

**Comment by papastromboli** [comment]
I'd like to echo my desire for this feature to be supported.

**Comment by timsehn** [comment]
@Hydrocharged is working on this now.

**Comment by lhmzhou** [comment]
Is there a PR awaiting for reviews? On pins and needles for this feature!

**Comment by timsehn** [comment]
It's going to take at least a month :-)

**Comment by timsehn** [comment]
This is supported in 1.8.5. It's missing some functionality but people should open individual issues for things they want that are missing.
