### ISSUE TITLE
Support the EXTRACT function

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3006]
We should support the following function:

https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_extract

**Comment by VinaiRachakonda** [comment]
This is blocking the Peewee ORM tests

**Comment by florianlaws** [comment]
I'd like to add a vote for supporting the EXTRACT function.
It is one of the issues that prevent me from running my application on Dolt.

**Comment by timsehn** [comment]
@JCOR11599 is working on this right now.

**Comment by JCOR11599** [comment]
Hey @florianlaws, the fix for this has been merged to main, and a release for it will be out sometime this week.
