### ISSUE TITLE
Audit Error Codes

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3018]
Dolt does not do a good job of returning enough error codes for a wide variety of MySQL queries.

Consider the PyMYSQL Library and their relevant [error definitions](https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/err.py). What we can see is that many libraries use error codes for internal objects. This in turn compounds into incompatibility issues with ORMs who may case PyMySQL Error classes. 

1105 is no longer an acceptable return value.

**Comment by timsehn** [comment]
This is too broad to be a bug.
