### ISSUE TITLE
`column_default` column value of `information_schema.columns` table is incorrect

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#3045]
With wrong value in `column_default` column of `information_schema.columns` table, TablePlus includes the `DEFAULT` value when it generates ALTER TABLE statements

`NULL` value is referenced as string value of `'NULL'`
`EMPTY` value is referenced as string value of `''`

**Comment by VinaiRachakonda** [comment]
This should now be fixed. One thing to note in Tableplus is that we can select the expression drop down when working with complex function based expression values.
![Screen Shot 2022-04-12 at 10 07 06 AM](https://user-images.githubusercontent.com/7027863/163016515-96c6e85c-d897-40f0-8402-40efac5b3a72.png)
