### ISSUE TITLE
Adding/changing PK through TablePlus display fails

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#3046]
Add PK and drop PK works correctly on Dolt. But, when adding second PK, TablePlus generated query is:
```
CREATE testtable (pk int primary key, pk2 int);
ALTER TABLE testtable DROP PRIMARY KEY, ADD PRIMARY KEY (pk, pk2);
```

The last query drops the PK correctly, but the schema referenced in the second 'add pk' part of the query is not updated, so that it fails with error: `Multiple primary keys defined1`

**Comment by VinaiRachakonda** [comment]
Similar to #2325
