### ISSUE TITLE
Support the following SHOW statements

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3049]
- SHOW BINARY LOGS
- SHOW BINLOG EVENTS
- SHOW CREATE EVENT
- SHOW CREATE FUNCTION 
- SHOW CREATE PROCEDURE
- SHOW CREATE USER
- SHOW ERRORS
- SHOW FUNCTION CODE
- SHOW FUNCTION STATUS
- SHOW GRANTS
- SHOW MASTER STATUS
- SHOW OPEN TABLES
- SHOW PLUGINS
- SHOW PROCEDURE CODE
- SHOW PROFILE
- SHOW PROFILES
- SHOW RELAYLOG EVENTS:
- SHOW REPLICA STATUS
- SHOW STATUS

**Comment by timsehn** [comment]
`SHOW CREATE PROCEDURE` is complete. I'm going to close this in favor of individual bugs and refer people to here:

https://docs.dolthub.com/sql-reference/sql-support/supported-statements
