### ISSUE TITLE
Truncated time strings are not parsed correctly

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#3102]
MySQL allows you to specify a datetime such as `2000-01-01 00:00` and MySQL will assume the time is `00:00:00`. 

When you try to insert a datetime string like this (i.e. without the seconds explicitly specified), Dolt will return an error:
`value "2000-03-01 00:00" can't be converted to time.Time`

Dolt should treat that as a valid datetime string, since MySQL does. 

When used in filter expression in a query, Dolt does *not* error out and this can result in the query not being interpreted as customers expect and returning incorrect data. MySQL will recognize the date comparison and automatically fill in the missing seconds and treat this as a date. 

For example, the following query returns no results, even though two valid records exist:
`select * from prices where ts_start >= '2000-01-01 00:00'`

Note that if you explicitly use the `date` function, the query does execute as expected and returns the matching records. 
`select * from prices where ts_start >= date('2000-01-01 00:00');`

We should fix this case and review datetime handling to see if there are other similar cases we need to add tests for.

**Comment by JCOR11599** [comment]
Fix for dates is merged into main. I will do another pass over the `convert_value` error handling inconsistencies in another PR.

**Comment by fulghum** [comment]
Nice work @JCOR11599!
