### ISSUE TITLE
`dolt pull` should do `dolt fetch` under the hood

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#3113]
Git behaviour of `pull` is that it does `fetch` (fetching all remote branches) and then merge with upstream on a current branch.
Dolt, however is not doing `fetch` when `dolt pull` is issued.
For the sake of keeping same semantics - it should.

**Comment by timsehn** [comment]
I'm pretty sure this is the way it works. Did you notice refs not get updated on the non-pulled branches? Can you repro?

**Comment by timsehn** [comment]
@druvv will try and repro and make a bats test.

**Comment by timsehn** [comment]
Specifically, when a user issues a `dolt pull` command all remote refs should be "fetched" not just the pull branch. This is how Git works.

**Comment by bpf120** [comment]
@kretes Thanks for submitting. We'd love to hear about your use case. You can email me (brianf@dolthub.com) or swing by our Discord if you want to share. 

https://discord.com/invite/RFwfYpu

**Comment by druvv** [comment]
@kretes We'll modify the behavior and let you know when it's done.

**Comment by JCOR11599** [comment]
Fix for this has been merged to main, and will be available next release (probably Monday).
