### ISSUE TITLE
Allow AS OF strings to be naked identifers

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3116]
Currently you have to quote AS OF string identifiers, e.g.

```sql
show tables as of 'HEAD~';
select * from table as of '32asf213098sdfa';
```

It would be more ergonomic if we permitted naked (unquoted) strings for these tokens, as we do for various system variable assignments. E.g.:

```sql
set @@mydb_head_ref = a23098afds0asdf
```

**Comment by JCOR11599** [comment]
Fix is merged to gms main, will eventually make it dolt main
