### ISSUE TITLE
Unsupported `CREATE VIEW` syntax

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3117]
We should support the full range of CREATE VIEW` with a query like this

```
CREATE ALGORITHM=UNDEFINED DEFINER=`vinairachakonda`@`localhost` SQL SECURITY DEFINER VIEW `myview` AS select `parent`.`pk` AS `pk`,`parent`.`v1` AS `v1` from `parent`;
```

Specifically we are missing the 

- ALGORITHM Parameter
- SQL SECRUITY DEFINER parameter

**Comment by jennifersp** [comment]
Parsing the syntax is now supported, https://github.com/dolthub/go-mysql-server/pull/935
