### ISSUE TITLE
Bad error message for `string is too large for column`

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3148]
Consider the following table:

```
dsimple> create table t(val char(3));
dsimple> insert into t values ('dasdsa');
string is too large for column
```

Dolt should add to the error message the name of the offending column like mysql

```
mysql> insert into t values ('dasdsa');
ERROR 1406 (22001): Data too long for column 'val' at row 1
```

**Comment by aleclarson** [comment]
I'm getting similar error when using `dolt diff`

```
diff --dolt a/foo b/foo
--- a/foo @ v8f05butvl7q9n72kiidnqg5vvp4so66
+++ b/foo @ 9i9hs0ls3slb3cp0u70c275sn0akgmst
Failed transforming row
split_diffs
string '%!v(MISSING)' is too large for column '%!v(MISSING)'
```

Would be great to have something more helpful

**Comment by VinaiRachakonda** [comment]
@aleclarson Would it be possible to get a repro for your above error? 

The original issue is now fixes as we return something like this `string 'dsadas' is too large for column 'val'`

**Comment by VinaiRachakonda** [comment]
Resolved.
