### ISSUE TITLE
Upload units do not properly update

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3149]
![image](https://user-images.githubusercontent.com/40151222/161604050-43f85697-e5b2-43c0-8145-5fa23bd6b17f.png)

**Comment by fulghum** [comment]
@druvv – could you take a look at this one? It looks like this is reporting that the upload speed units is showing both `kB/s` and also `B/s`.

**Comment by druvv** [comment]
It seems like this occurs when the newly written line is shorter than the last written line. The newly written line is flushed and overwrites the old line, but doesn't overwrite any text after the old line.

**Comment by timsehn** [comment]
I just saw this on the CLI. @druvv is going to fix.

**Comment by timsehn** [comment]
This was actually a really small number bug fixed here: https://github.com/dolthub/dolt/pull/4467
