### ISSUE TITLE
Remove `db.Rebase()` from `dsess.StartTransaction`

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3162]
We originally added this functionality so that changes from the command line would be visible on a running server. See this bug for context:

https://github.com/dolthub/dolt/issues/2092

But this adds very significant overhead to short-lived transactions, including benchmarks such as point lookups.

Example: point lookups on primary key.

With `Rebase()` on every transaction start:

```
Latency (ms):
         min:                                    0.46
         avg:                                    0.56
         max:                                    1.61
         95th percentile:                        0.73
```

With this code disabled:

```
Latency (ms):
         min:                                    0.24
         avg:                                    0.35
         max:                                    5.17
         95th percentile:                        0.59
```

In order for this change to be safe, we need to lock the dolt database while the server is running, preventing any commands that update it from running. This can be accomplished with lock files. To avoid customers hitting dead locks from processes that died without cleaning up after themselves, the lock file should record the process ID so that we can disregard and clear the lock if the process doesn't exist.

We should also allow configuration in the server (via a system variable) that keeps the existing behavior, for customers that are running in single-user mode locally and want to run commands on their DB.

**Comment by timsehn** [comment]
I assume this bug is resolved via https://github.com/dolthub/dolt/pull/3755. But @max-hoffman and @zachmu can confirm.

**Comment by max-hoffman** [comment]
Yes this is fixed.
