### ISSUE TITLE
dolt clone progress: "chunks being downloaded currently" is broken

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#3163]
<img width="837" alt="Screen Shot 2022-04-05 at 4 54 40 PM" src="https://user-images.githubusercontent.com/14025711/161869856-db4e1333-d3ed-491d-9099-48f23f8e634e.png">

**Comment by fulghum** [comment]
@druvv – is this related to the issue about upload units not properly updating (https://github.com/dolthub/dolt/issues/3149)? Or do you think those separate issues?

**Comment by druvv** [comment]
Might be related to #3149 ?

**Comment by timsehn** [comment]
We rewrote this output.
