### ISSUE TITLE
`information_schema.columns` does not contain all associated view information

### ISSUE THREAD

**Issue by jycor** [dolthub/dolt#3168]
The columns `ordinal_position`,  `column_name`, `data_type`, `is_nullable`, `column_type` all return 0 or null, for views in the `information_schema.columns`.
Additionally, if a view selects multiple columns, there should be a row for each column.

This code for this is in GMS in `information_schema/information_schema.go`.
In order for this to work properly there needs to be significant changes to the ViewDefinition struct or we should parse it somehow, as currently we don't have the data to fill in these columns correctly

**Comment by VinaiRachakonda** [comment]
This is an open bug that is visible in Tableplus
