### ISSUE TITLE
Combining dolt and git repositories

### ISSUE THREAD

**Issue by ckaran** [dolthub/dolt#3179]
I have an odd use case; I want to be able to store dolt's database within a git repository.  Why?  Because I want to write something similar to [gitarena](https://github.com/mellowagain/gitarena) or [git-bug](https://github.com/MichaelMure/git-bug), but without having to manage a project's dolt database and git repository separately.  Ideally, I could use `git` to manage everything directly.

Alternatively, is there a way of storing a git repository within a dolt database?  If this can be done efficiently, with a single front-end set of tools handling it all, then that might be good enough.

**Comment by ckaran** [comment]
And... I just found `git-dolt`!  I'll mess with it for a bit and see if meets my needs.  Thank you!

**Comment by fulghum** [comment]
Hey @ckaran , glad you found `git-dolt`! Let us know if you have any questions or feature requests for us – we'd love to hear from you either on GitHub, or [on our Dolt Discord](https://discord.com/invite/RFwfYpu).
