### ISSUE TITLE
Is dolt's database format stabilized?

### ISSUE THREAD

**Issue by ckaran** [dolthub/dolt#3180]
Is Dolt's database format stabilized yet?  I'm a rust programmer, and would love to be able to have a pure rust implementation of dolt that I could embed within my code.  As a first step, I would like to read and write the database format directly.

**Comment by zachmu** [comment]
Hi @ckaran,

Thanks for the interest!

The database format is definitely not stable, and in fact we are in the middle of rewriting it for performance reasons. Cross-language compatibility is one of the goals of this rewrite, and we're using flatbuffers to make this feasible

https://google.github.io/flatbuffers/

After the rewrite we'll officially designate a 1.0 release, and with that release will come guarantees about the stability of the data format.

In the meantime we'd love to hear more about your use case for embedding dolt. This is something we're interested in as well, and we have plans for an embedding model similar to that used by SQLite, with a C-library API communicating with the database rather than having people read and write the format directly. Does that sound like something that could work for you?

**Comment by bpf120** [comment]
@ckaran Feel free to come by our Discord too with any questions. 

https://discord.com/invite/RFwfYpu

**Comment by ckaran** [comment]
@zachmu flatbuffers is perfect for me!  Are you also going to change the protocol message formats to all be in the flatbuffer format?  I'm thinking that if you do you could create something similar to the `git bundle` command relatively easily as the 'transport' is just going to be a file to pull from.

**Comment by zachmu** [comment]
Yes, everything will eventually be flatbuffers.

It's a lot of work to build a Rust library to work with dolt, even if you don't have to worry about parsing the storage format yourself. The architecture of dolt is that the query engine (also written in golang) sits on top of the storage layer. There's also a bunch of logic to traverse the prolly tree on both reads and writes that you really can't get wrong. Then of course there's a ton of business logic for things like branch, merge, commit, checkout etc.

It sounds like your main constraint is having a single binary you can give to customers. Is that about right? We haven't looked into this much yet, but that's definitely one of our goals with an embedded dolt as well. Does your integration require the SQL query engine, or are you strictly working with tables as datasets?

**Comment by ckaran** [comment]
I'm comfortable with using rust bindings to the dolt layer, but I've never done such a thing before, and my experience with go begins and ends with my compiling dolt on my machine the other day.  If you think that writing bindings would be fairly simple, I'm willing to evaluate it for performance and size.

As for what we need to give to customers, it basically boils down to 'smaller & faster == better'.  We're building software for robots and [IoT](https://en.wikipedia.org/wiki/Internet_of_things) like objects, all of which are heavily constrained in power, weight, and compute resources.  Anything that lets us get rid of unnecessary computation or code is a *good* thing.  That's the reason for microSD cards; they weigh about 250 micrograms, and the current generation supports up to 1 TB of storage, with future versions  planned to support 256 TB in the same form/weight/power factor.  If Dolt is fast enough (both read and write), we can reduce the amount of memory we use in exchange for more storage on board.

To give you a clearer understanding of 'why dolt?', it basically boils down to the computer equivalent of [Theory of Mind](https://en.wikipedia.org/wiki/Theory_of_mind).  Robots need to be able to model what other robots know and when they know it, in order to make guesses as to what the other robots will do in the future.  If network connectivity is perfect, you can always just ask the other robot what it's planning to do, but if you lose connectivity you need to use what information you have.  Dolt is perfect for this; a robot can consult not only the last known state, it can go back in time to see what the trajectory of its thoughts were.  E.g., let's consider a literal trajectory; it's just a set of positions over time.  Sounds like something that Dolt could handle well, yes?

Further, Dolt has the potential to efficiently synchronize different databases.  This is a **BIG** deal!  Our network connectivity might be over very low bandwidth networks (e.g., [LoRaWAN](https://lora-alliance.org/about-lorawan/) or [Zigbee](https://en.wikipedia.org/wiki/Zigbee)) in highly congested radio space, so anything that reduces the number of bits transmitted is *fantastic.*

Sorry about rambling a bit, I figured this would help you understand where I'm coming from.

**Comment by zachmu** [comment]
Yes, you totally get it. It's really exciting for us when people show up who really grok the vision. Tim wrote about something similar in this blog post:

https://www.dolthub.com/blog/2022-03-07-dolt-military/

What you're describing should be doable in principle, but it's definitely uncharted territory for us. We'd be very interested in exploring your use case as a pilot for embedded dolt, and we can offer at least advice and probably also some development work to make it happen. We can't promise a date for any of these deliverables until we have a better understanding of the work entailed. Probably the best way to make progress would be for you to hop on our discord so we can talk in real time about what you need.

https://discord.com/invite/RFwfYpu

**Comment by ckaran** [comment]
Interesting, because [this is what I was thinking about](https://iobt.illinois.edu/people/).  Maggie is one of my coworkers.

**Comment by timsehn** [comment]
Resolving since this reached a natural conclusion. Dolt's format will be stable in 1.0 which will release later this year.
