### ISSUE TITLE
Certain keys do not work on dolt sql cli

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3185]
Keys such as `f` do not work when using the sql cli (`dolt sql`) 

List of keys that do not work (on windows):
* `d`, `f`, `b`, `del`

Backspace also behaves as if you are pressing the control key (bulk delete)

**Comment by JCOR11599** [comment]
Is your ALT key stuck?

**Comment by fulghum** [comment]
@CaptainStabs – did you figure anything out here? We haven't seen the same behavior or heard any other reports. Let us know if you're still seeing this problem and if so, any other hints about your environment that might help.

**Comment by timsehn** [comment]
Resolving.
