### ISSUE TITLE
Unique constraint on table not preventing insert

### ISSUE THREAD

**Issue by geweldon** [dolthub/dolt#3188]
I am running into an issue with Unique constraints not seeming to function.  I am inserting values using an INSERT INTO SELECT statement, pulling the values from a table in a different branch using the AS OF keyword.  The Values consist of a generated UUID - using UUID() - and the Id field, and the column receiving the UUID is the primary key. 

Successive identical insert statements surprisingly don't result in any errors, even though the Id values being inserted are all duplicates (the UUIDs naturally are not).

<img width="1280" alt="Screen Shot 2022-04-07 at 7 39 09 PM" src="https://user-images.githubusercontent.com/1163819/162336389-218a9639-5ca2-4fa7-bb43-ef202848d172.png">

**Comment by geweldon** [comment]
The Repo is available at geweldon/VEID.  The attempted modifications were made in the UUID-SF branch on the UID_product2 table.  The values being inserted are present in the main branch in the Stg_product2 table.  I haven't pushed/commited any of the changes to the UUID-SF branch however.

**Comment by geweldon** [comment]
I also just confirmed that commiting the values first before repeating the  statement does not cause the constraint to work

**Comment by zachmu** [comment]
Thanks for the great bug report and repro, we will address this for the next release.

**Comment by JCOR11599** [comment]
I believe you are running into expected behavior.
Your `UID_product2` table has a unique key constraint defined over multiple columns
```
VEID> show create table UID_product2;
+--------------+------------------------------------------------------+        
| Table        | Create Table                                                                                                                                                                                                                                                                        |
+--------------+------------------------------------------------------+        
| UID_product2 | CREATE TABLE `UID_product2` (                                                                                                                                                                                                                                                
  `UUID` varchar(36) NOT NULL,                                                                                                                                                                                                                                                                
  `main` varchar(16383),                                                                                                                                                                                                                                                                      
  `Staging` varchar(16383),                                                                                                                                                                                                                                                                   
  `QA` varchar(16383),                                                                                                                                                                                                                                                                        
  `Dev` varchar(16383),
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `SF_Id` (`main`,`Staging`,`QA`,`Dev`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+--------------+------------------------------------------------------+
```

The rows you are inserting will populate the remaining columns with `NULL`, and evidently `NULL != NULL`, so the unique constraint is not violated.
The same thing happens in MySQL btw.

**Comment by geweldon** [comment]
I expected the behavior with the null columns.  However the 'main' column is allowing multiple duplicate values.  In the screenshot above, second result from the bottom, you can see where I returned 4 results for a single value in one of the columns.  Maybe I'm wrong, but I would expect a column with a unique constraint on it not to allow duplicate values in it.....

**Comment by andrew-wm-arthur** [comment]
@geweldon The behavior you're seeing is expected. A unique index defined over multiple columns only guarantees that the combination of values in a row is unique, not that each value is unique for it's column.

In order to guarantee that each of the columns (`main`, `staging`,`qa`, `dev`) contains unique values, you need a separate unique index on each column:

```diff
diff --dolt a/UID_product2 b/UID_product2
--- a/UID_product2 @ 30o9pq6babe2dl6tlqni6qpjkm7h2m7s
+++ b/UID_product2 @ c21miq0srcsvlk6ttd0334kij3uagq10
 CREATE TABLE `UID_product2` (
   `UUID` varchar(36) NOT NULL,
   `main` varchar(16383),
   `Staging` varchar(16383),
   `QA` varchar(16383),
   `Dev` varchar(16383),
   PRIMARY KEY (`UUID`),
-  UNIQUE KEY `SF_Id` (`main`,`Staging`,`QA`,`Dev`)
+  UNIQUE KEY `dev_uniq` (`Dev`),
+  UNIQUE KEY `main_uniq` (`main`),
+  UNIQUE KEY `qa_uniq` (`QA`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
I've confirmed this behavior on MySQL for both versions of the this table's schema. However, these is a small bug with how we display describe results. For the original schema, MySQL does not populate the `UNI` attribute for any of the columns (Dolt populates is for the first column `main`):
```sql
describe UID_product2;
+---------+-------------+------+-----+---------+-------+
| Field   | Type        | Null | Key | Default | Extra |
+---------+-------------+------+-----+---------+-------+
| UUID    | varchar(36) | NO   | PRI | NULL    |       |
| main    | varchar(32) | YES  | MUL | NULL    |       |
| Staging | varchar(32) | YES  |     | NULL    |       |
| QA      | varchar(32) | YES  |     | NULL    |       |
| Dev     | varchar(32) | YES  |     | NULL    |       |
+---------+-------------+------+-----+---------+-------+
5 rows in set (0.00 sec)
```
For the updated schema, both Dolt and MySQL show the following output for describe:
```sql
mysql> describe UID_product2;
+---------+-------------+------+-----+---------+-------+
| Field   | Type        | Null | Key | Default | Extra |
+---------+-------------+------+-----+---------+-------+
| UUID    | varchar(36) | NO   | PRI | NULL    |       |
| main    | varchar(32) | YES  | UNI | NULL    |       |
| Staging | varchar(32) | YES  | UNI | NULL    |       |
| QA      | varchar(32) | YES  | UNI | NULL    |       |
| Dev     | varchar(32) | YES  | UNI | NULL    |       |
+---------+-------------+------+-----+---------+-------+
5 rows in set (0.01 sec)
```
@VinaiRachakonda is currently working on improving schema introspection and will address this

**Comment by geweldon** [comment]
That makes sense!  Thanks so much
