### ISSUE TITLE
AUTO_INCREMENT changes integer column types from signed to unsigned

### ISSUE THREAD

**Issue by Jannick-v** [dolthub/dolt#3192]
This potential bug is introduced in `0.37.8` and is still present in the latest version (`0.37.9`)

The following table creation and data insertion used to work correctly in version `0.37.7`
```sql
create table `test_data` ( `pr_id` int NOT NULL AUTO_INCREMENT, `tech_id` int, `product_name` varchar(255), PRIMARY KEY (`pr_id`), UNIQUE KEY `tech_id` (`tech_id`));
insert into test_data (pr_id, tech_id, product_name) values (-10, 1, "test product");
```
In `0.37.8` and later, this results in the following error message:
```sql
-10 out of range for BIGINT UNSIGNED
```

Removing the `AUTO_INCREMENT` part for the `pr_id` column fixes the problem, but is obviously not desired
```sql
create table `test_data` ( `pr_id` int NOT NULL, `tech_id` int, `product_name` varchar(255), PRIMARY KEY (`pr_id`), UNIQUE KEY `tech_id` (`tech_id`));
insert into test_data (pr_id, tech_id, product_name) values (-10, Null, "test product");
```

Removing the `NOT NULL` part for the `pr_id` column has no effect.
___

Why assign (negative) values to an auto-increment column in the first place? Because this is a trivial way to indicate special cases :)

**Comment by zachmu** [comment]
Definitely a bug, thanks for the report.

This is related to a recent refactoring by @andrew-wm-arthur, and it looks like we didn't have a test case for inserting negative values into auto_increment columns.

**Comment by zachmu** [comment]
Actually, since Andy is out this week and you're working on something related, can you take this James?

**Comment by JCOR11599** [comment]
The fix for this has been merged into main and will available next release

**Comment by timsehn** [comment]
Would you like a patch release @Jannick-v?

**Comment by Jannick-v** [comment]
Hi all,
Thanks for the quick fix and follow-up.
Currently, the issue is causing our unit tests to fail but is currently non-blocking for general usage.
When is the next release planned? 
If you maintain +- weekly release freq, I think we can wait a little longer.
If it will take longer: patch release, please! :)

**Comment by timsehn** [comment]
We try to do once per week. We'll have one Friday or Monday with a fairly major Prepared Statement improvement. This one will get in there.

**Comment by Jannick-v** [comment]
Great news! I'll be out next week, so no need to rush :)
