### ISSUE TITLE
[REQUEST] Option to output sql generated by dolt diff

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3198]
Add an option to print the SQL query that `dolt diff` generates to make the diff table, to allow users to further tailor it beyond what `dolt diff` allows

Enclosing the value of the `where` statement with quotes causes diff to hang indefinetely:
```
dolt diff HPI multi-code-fix prices --limit 1 --where=cms_certification_num='673057'
```

**Comment by timsehn** [comment]
We aren't going to do this. Just learn the system table(s) if you want more customizable diff functionality.
