### ISSUE TITLE
QGIS plugin

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#3205]
Well, Dolt is great, we already know that, for spatial databases there is a needed option, this option open doors if you want enter in the development of spatial databases where geographers works too.

QGIS is an app to access, read and edit spatial databases, so, the best would be a plugin in QGIS to can manage the repository (branches, commits, etc, etc) and do Dolt easy to use for more ppl.

It can be made in python, so is very simple:
https://www.qgistutorials.com/en/docs/3/building_a_python_plugin.html

Thx!

**Comment by fulghum** [comment]
Thanks for the feature request @latot. QGIS looks like a very interesting project. @JCOR11599 has been working on our spatial db support and might enjoy poking around with QGIS and experimenting with how well the existing MySQL support works with Dolt and what gaps cause problems.

**Comment by timsehn** [comment]
Going to resolve in favor of more specific spatial types enhancements.

**Comment by latot** [comment]
@timsehn I understand the point of put other things in priority, I still think this issue should be open, even if can't be solved right now. Is key to can commit changes in a map, that is over the plugin it self, in the spatial world, even in this digital era, is pretty important the manual work, specially if you want quality data, so plis, lets search a way to keep a "save" button for spatial data.

Would be better an issue like..., "how to work with Dolt from QGIS?"

**Comment by timsehn** [comment]
We are committed to making Dolt work with the QGIS plug in. Don't take the resolution of this issue as us wavering on this commitment.

But in our issues, what we need is the specific spatial types functionality it uses as individual bugs like these:

https://github.com/dolthub/dolt/issues?q=is%3Aissue+label%3Aspatial-types+is%3Aopen

This issue as it stands is not actionable for us.

@JCOR11599 is working on #3638 right now for instance. Here is the PR: https://github.com/dolthub/go-mysql-server/pull/1309

**Comment by timsehn** [comment]
If this is a request for us to build a QGIS plug in, that is really far out on the roadmap and not worth tracking here. We don't even fully support spatial types now.

**Comment by latot** [comment]
You are right! sorry, I misunderstood the meanin of close the issue. step by step. Thx!
