### ISSUE TITLE
Potential memory leak with sql output

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3206]
While running a sql in a large table/with lots of results memory is rapidly used up to the point of slowing system down.
![image](https://user-images.githubusercontent.com/40151222/162998094-023eb065-7214-4d46-8fe6-7e3b4a455295.png)

**Comment by timsehn** [comment]
Which query on what database?

**Comment by timsehn** [comment]
I'm pretty sure Max fixed single in expressions. Checking this query now.

**Comment by timsehn** [comment]
Returns fine now and streams output immediately.
