### ISSUE TITLE
ORDER BY with several primary keys on a very large table takes too long ( almost does not load )

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#3207]
TablePlus displays tables using its primary keys to order the table, and so tables like `prices` from https://www.dolthub.com/repositories/dolthub/hospital-price-transparency-v3 database with very big amount of rows ( > 5M ) and 6 primary keys does not load/takes very long time to load.

**Comment by zachmu** [comment]
What query is being run?

**Comment by jennifersp** [comment]
The query generated from TablePlus that is being run is: 
```
SELECT * FROM `hospital_price_transparency_v3`.`prices` ORDER BY `cms_certification_num`,`code`,`inpatient_outpatient`,`internal_revenue_code`,`code_disambiguator`,`payer` LIMIT 1000 OFFSET 0;
```
