### ISSUE TITLE
Dolt sql csv output ignores filename case

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3227]
If file `abc.csv` already exists, and you tell dolt to write to file `ABC.csv`, it will overwrite `abc.csv`, and vice-versa 

```mysql
dolt sql -q "select * from <table>" -r csv > ABC.csv
```

**Comment by fulghum** [comment]
Can you confirm that you're using a case-sensitive file system? I see this same behavior because my disk is formatted with APFS and is not a case-sensitive file system, so this is expected in my case.
