### ISSUE TITLE
binary 'string' type needs to be resolved as geometry type

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#3231]
```
CREATE TABLE `address` (
  `address_id` smallint unsigned NOT NULL AUTO_INCREMENT,
  `location` geometry NULL,
  PRIMARY KEY (`address_id`)
)

INSERT INTO `address` VALUES (1,_binary '\0\0\0\0\0\0\0>\n2]c4\\ÀvÛ™\ÙH@')
```
(binary string above in mysqldump)
<img width="528" alt="Screen Shot 2022-04-14 at 2 35 16 PM" src="https://user-images.githubusercontent.com/44716627/163480693-ddbac6cf-d1ab-4436-bed1-8fe0cb620f3c.png">

error message : cannot insert string as point/geometry type

**Comment by VinaiRachakonda** [comment]
Let's make sure this gets translated to bats tests on dump.bats

**Comment by JCOR11599** [comment]
> Let's make sure this gets translated to bats tests on dump.bats

The changes in this PR https://github.com/dolthub/go-mysql-server/pull/957, allow dolt to read spatial types from `mysqldump` with the `--hex-blob` flag.; dumps that use binary still don't work. Currently, dolt doesn't support this flag, but I could add it?
