### ISSUE TITLE
Potential Compatibility issue with Knex

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3240]
Recently a user reported a Go `context canceled` when running Dolt server against the Knex ORM. The user mentioned that this was due to a malformed SQL query. The attempted repro was tried but I was unable to evoke the `context canceled` error. I am leaving this issue open in case anyone comes across it. 

```
 const knex = require('knex')({
    client: 'mysql',
    connection: {host: '127.0.0.1', port: 3307, user: 'root', database: 'dsimple'}
  });


async function testInsert() {
    await knex('keyed').insert({ pk: 1, val: 2 }).onConflict().merge()
    await knex.raw("daosdksaok")
    await knex('keyed').insert({ pk: 1, val: 2 }).onConflict().merge()
}

testInsert()
```

**Comment by VinaiRachakonda** [comment]
Update full repro is here: https://github.com/aleclarson/repro/tree/dolt-4-15-2022#readme

**Comment by aleclarson** [comment]
So excited for this bug to get fixed 😄 

Any chance we'll see it fixed this week? 🤞

**Comment by VinaiRachakonda** [comment]
Hey @aleclarson I've been hustling to figure out the cause of this bug. Trust me it is my #1 priority. We'll definitely get a fix in by EOW
