### ISSUE TITLE
MySQL database is only available in `sql-server` mode

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3258]
The following query with `dolt sql` fails

```
dolt sql -q "CREATE USER 'john.doe'@'localhost'"
```

with the error 

```
error on line 1 for query CREATE USER 'john.doe'@'localhost': database not found: mysql
database not found: mysql
```

**Comment by latot** [comment]
Check this, the db picks the name of the repository.

**Comment by VinaiRachakonda** [comment]
This issue is now fixed:

The command `dolt sql -q "CREATE USER 'john.doe'@'localhost'" --privilege-file='./file'` successfully executes
