### ISSUE TITLE
Color bug is back after latest release

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3292]
Issue #1838 has returned.
![image](https://user-images.githubusercontent.com/40151222/164815438-beadd00c-b798-41fa-96ca-dd1324784f60.png)

**Comment by fulghum** [comment]
Let us know if you have more details on how this was triggered – e.g. did you interrupt the process? If so, how? This is on Windows? 

As a workaround in the meantime, on unix systems, you should be able to use the `reset` command to get things back to normal if you get into this state again.
