### ISSUE TITLE
SQL REPLACE currently counts an INSERT-only as a REPLACE

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#330]
This can be replicated by running the following:
```bash
dolt init
dolt sql -q "CREATE TABLE test(pk BIGINT PRIMARY KEY, v BIGINT);"
dolt sql -q "REPLACE INTO test VALUES (1, 1);"
```

You'll receive the output:
```
+---------+
| updated |
+---------+
| 2       |
+---------+
```
This should read as `1`, since a row was not deleted. In `go/libraries/doltcore/sqle/table_editor.go::Delete`, we are not returning an error as we're storing operations to be performed during the `Close` function (for performance reasons). However, in the `go-mysql-server` package, in the function `sql/plan/insert.go::Execute`, we are looking for `Delete` to return `sql.ErrDeleteRowNotFound` which would never happen, thus not informing the package that no row was deleted.

**Comment by timsehn** [comment]
@Hydrocharged Can you write a skipped bats test for this? Seems like a simple repro.

**Comment by Hydrocharged** [comment]
Added a skipped bats test that should be unskipped when this is fixed: https://github.com/liquidata-inc/dolt/pull/361

**Comment by timsehn** [comment]
Resolved.
```
test-replace-count $ dolt init
Successfully initialized dolt data repository.
test-replace-count $ dolt sql -q "CREATE TABLE test(pk BIGINT PRIMARY KEY, v BIGINT);"
test-replace-count $ dolt sql -q "REPLACE INTO test VALUES (1, 1);"
Query OK, 1 row affected
```
