### ISSUE TITLE
dolt diff doesn't show data diff when table was added within the commit range

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#3300]
when doing a `dolt_diff` for a commit range that includes table creation and some data added - no diff is displayed for data, while it should be.

Steps to reproduce:
```
dolt_no_diff# dolt version
dolt version 0.39.2

dolt_no_diff# 
dolt_no_diff# dolt init
Successfully initialized dolt data repository.
dolt_no_diff# 
dolt_no_diff# dolt sql -q "create table a (x int);"
dolt_no_diff# 
dolt_no_diff# dolt status
On branch main
Untracked files:
  (use "dolt add <table|doc>" to include in what will be committed)
        new table:      a
dolt_no_diff# 
dolt_no_diff# dolt add a
dolt_no_diff# 
dolt_no_diff# dolt commit -m "table added"
commit 0at4ftmabs8tuhj2n9bbpf3lg2esi4s4 (HEAD -> main) 
Author: Tomasz Bartczak <email>
Date:  Tue Apr 26 10:30:15 +0000 2022

        table added

dolt_no_diff# 
dolt_no_diff# dolt diff HEAD~1
diff --dolt a/a b/a
added table
dolt_no_diff# 
dolt_no_diff# dolt sql -q "insert into a values (1);"
Query OK, 1 row affected
dolt_no_diff# dolt sql -q "insert into a values (2);"
Query OK, 1 row affected
dolt_no_diff# 
dolt_no_diff# dolt add a
dolt_no_diff# 
dolt_no_diff# dolt commit -m "data added"
commit kjo4u5jehcrd21329b7s7esiogk0195k (HEAD -> main) 
Author: Tomasz Bartczak <email>
Date:  Tue Apr 26 10:30:15 +0000 2022

        data added

dolt_no_diff# 
dolt_no_diff# dolt log -n 3
commit kjo4u5jehcrd21329b7s7esiogk0195k (HEAD -> main) 
Author: Tomasz Bartczak <email>
Date:  Tue Apr 26 10:30:15 +0000 2022

        data added

commit 0at4ftmabs8tuhj2n9bbpf3lg2esi4s4 
Author: Tomasz Bartczak <email>
Date:  Tue Apr 26 10:30:15 +0000 2022

        table added

commit 2800ho32o2pkgac3d6clvlsn4tifa7ff 
Author: Tomasz Bartczak <email>
Date:  Tue Apr 26 10:30:14 +0000 2022

        Initialize data repository

dolt_no_diff# 
dolt_no_diff# dolt diff HEAD~2 HEAD~1
diff --dolt a/a b/a
added table
dolt_no_diff# 
dolt_no_diff# dolt diff HEAD~1 HEAD
diff --dolt a/a b/a
--- a/a @ k8iuqjt9hq8050lsu2cgv8945manro8r
+++ b/a @ ecbacgulgaeca47u3jr6pb8h33ub22fq
+-----+---+
|     | x |
+-----+---+
|  +  | 1 |
|  +  | 2 |
+-----+---+
dolt_no_diff# 
dolt_no_diff# dolt diff HEAD~2
diff --dolt a/a b/a
added table
dolt_no_diff# ^C
dolt_no_diff# 
```

At the end I expect that the diff including both commits show both `table added` and the data diff that I see when navigate to a specific commit range.

**Comment by kretes** [comment]
And in an extreme situation where it was a single commit creating the table and adding the data, `dolt diff` cannot help to uncover the data at all:
```
dolt init

dolt sql -q "create table a (x int);"
dolt sql -q "insert into a values (1);"
dolt sql -q "insert into a values (2);"

dolt add a

dolt commit -m "table & data added"

dolt diff HEAD~1
```

I know there is a system table `dolt_diff_a` from which I can uncover the data added If I really need. However the diff should be there in the `dolt diff`

**Comment by timsehn** [comment]
Thanks for the bug report. 

We've modeled this behavior after git where adding file did not show the contents of the file in a diff. I've tested the newest version of git locally and now it shows the contents of the file as well as "added file".
```
show-diff $ git diff
show-diff $ git add test-file.txt 
show-diff $ git commit -m "Added file"
[master (root-commit) 90af068] Added file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test-file.txt
show-diff $ echo "Some text" > test-file.txt 
show-diff $ git diff
diff --git a/test-file.txt b/test-file.txt
index e69de29..01b51e6 100644
--- a/test-file.txt
+++ b/test-file.txt
@@ -0,0 +1 @@
+Some text
show-diff $ git add .
show-diff $ git commit -m "Some text"
[master b06953a] Some text
 1 file changed, 1 insertion(+)
show-diff $ git log
commit b06953a58733d1d104a7c7d95e80a8a69580f70b (HEAD -> master)
Author: Timothy Sehn <tim@dolthub.com>
Date:   Tue Apr 26 08:43:50 2022 -0700

    Some text

commit 90af0687cfe749603fd442ba4df06a811a29367d
Author: Timothy Sehn <tim@dolthub.com>
Date:   Tue Apr 26 08:43:00 2022 -0700

    Added file
show-diff $ git diff HEAD~1
diff --git a/test-file.txt b/test-file.txt
index e69de29..01b51e6 100644
--- a/test-file.txt
+++ b/test-file.txt
@@ -0,0 +1 @@
+Some text
```

@fulghum has been looking at diffs lately and we'll see if we can come up with a design that combines schema and data diffs.

**Comment by fulghum** [comment]
Thanks for reporting this @kretes. Glad you already know about the Dolt system tables as another way to get that information. You are absolutely correct that the same, consistent information must be accessible from the CLI. 

We did some work to clean up the various diff system tables a month or two ago, but the CLI still has a different code path for computing diffs. Eventually, we want to unify those to help make sure the experience is consistent. I'll go ahead and start poking around in the CLI diff code and see if there's a way to clean this up, without requiring the larger refactor to unify the codepaths. 

We're also starting to think about the right way to diff schema changes, so if you have any thoughts on what would be most helpful to you there, we'd love to hear it. Our initial idea is exposing a very simple textual diff of the `show create table as of <commit>` for each of the two commits being diffed. That would be fairly low hanging fruit, and easy for human readers, but not as easy to read programmatically.

**Comment by kretes** [comment]
> Our initial idea is exposing a very simple textual diff of the `show create table as of <commit>` for each of the two commits being diffed. That would be fairly low hanging fruit, and easy for human readers, but not as easy to read programmatically.

Looks fine from my perspective. The output of CLI should be first readable by humans, if someone intends to run a tooling on top of dolt - API should be used.

**Comment by fulghum** [comment]
I dug into this one and have a PR (https://github.com/dolthub/dolt/pull/3318) open to include the schema and data details in the diff. I still need to spend some time on the tests, but feel free to check out that PR if you want to see an example of the new output format.

**Comment by fulghum** [comment]
Merged into main. 🎉  This will go out in the next release, likely early next week. Just let us know if you need it sooner than that and we'll be happy to run a release.
