### ISSUE TITLE
Difficult to identify differences in `dolt_docs` when in conflict

### ISSUE THREAD

**Issue by goncinious** [dolthub/dolt#3337]
When stumbled into merge conflicts in `dolt_docs` files (e.g. on `README.md` file), I found it hard to identify the differences between the merging branches in the conflicted file. 

[`dolt conflicts cat dolt_docs`](https://docs.dolthub.com/reference/cli#dolt-conflicts-cat) just prints a dump of the file in both branches (see simple example below). If we imagine a longer README.md and with more overlapping changes, the differences will become quite hard to visualise.

```
dolt merge branch_a
Updating 8ilesjjhjbegi215rdkoabhsnieqlbp9..mr1i192aco3rb9vnba9958efikj9th9r
Auto-merging dolt_docs
CONFLICT (content): Merge conflict in dolt_docs
Automatic merge failed; fix conflicts and then commit the result.
dolt conflicts cat dolt_docs
+-----+--------+-----------+-----------------------------------------+
|     |        | doc_name  | doc_text                                |
+-----+--------+-----------+-----------------------------------------+
|  +  | ours   | README.md | this is a long text.
this is branch_b.
 |
|  +  | theirs | README.md | this is a long text.
this is branch_a.
 |
+-----+--------+-----------+---------------------------------------+
```

Ideally, I think a `git diff`-like interface would be useful to allow the user to quickly identify which lines are affected by the merge. Currently, `dolt diff` just shows the different commits:
```
dolt diff
diff --dolt a/dolt_docs b/dolt_docs
--- a/dolt_docs @ anr6bn2r6na4a8psup09fonfn3uq97or
+++ b/dolt_docs @ 36ejt9vf5qrvhjqh63tl72pjspldp752
```

## Steps to reproduce:
```
dolt init
dolt branch branch_a && dolt checkout branch_a
vim README.md
dolt add README.md
dolt commit -m "add README"
dolt checkout main && dolt branch branch_b && dolt checkout branch_b
vim README.md
dolt add README.md
dolt commit -m "add README"
dolt merge branch_a
```

**Comment by timsehn** [comment]
Yes. This could be better. The fact that LICENSE and README are rendered as files but are really tows in the `dolt_docs` table can be a bit confusing. Plus, conflict resolution is definitely not ergonomic, especially if two branches add a different README.

We're unlikely to get to this very quickly as we're focusing more on the OLTP database use case right now, rather than the data sharing use case. We'll discuss as a team whether there's an easy fix here.

**Comment by bpf120** [comment]
@goncinious Thanks for filing. We'd love to hear about your use case and how you found us. You can email me (brianf@dolthub.com) or swing by our Discord if you'd like to share.

https://discord.com/invite/RFwfYpu

**Comment by timsehn** [comment]
I'm going to merge this issue with #2429 as it is the same issue.
