### ISSUE TITLE
`dolt reset --hard` should clear merge state

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#3371]
From the git-reset man page:
>        Undo a merge or pull
> 
>                $ git pull                         (1)
>                Auto-merging nitfol
>                CONFLICT (content): Merge conflict in nitfol
>                Automatic merge failed; fix conflicts and then commit the result.
>                $ git reset --hard                 (2)
> 
>            1. Try to update from the upstream resulted in a lot of conflicts; you were not
>            ready to spend a lot of time merging right now, so you decide to do that later.
>            2. "pull" has not made merge commit, so git reset --hard which is a synonym for git
>            reset --hard HEAD clears the mess from the index file and the working tree.

If I try this out with git, git reset works as expected:
```
$ git merge to-merge
Auto-merging foo.txt
CONFLICT (content): Merge conflict in foo.txt
Automatic merge failed; fix conflicts and then commit the result.
$ git reset --hard
HEAD is now at 1b11c80 something too
$ git status
On branch main
nothing to commit, working tree clean
```

In dolt although:
```
$ dolt merge merge_branch
Updating 8ae5qrg1m4tn43lp893prqg91dn8oc6n..imjm64m5di9gclv6u2le3o0f8b0ai241
Auto-merging test1
CONFLICT (content): Merge conflict in test1
Automatic merge failed; 1 table(s) are unmerged.
Use 'dolt conflicts' to investigate and resolve conflicts.
$ dolt reset --hard
$ dolt status
On branch main
All conflicts and constraint violations fixed but you are still merging.
  (use "dolt commit" to conclude merge)
```

The merge is still "in-progress". Can we instead set the `WorkingSet`'s `MergeState` to nil when `dolt reset --hard` occurs? Are there any other cases where we might need to do this as well?

**Comment by timsehn** [comment]
Make it match git. If git aborts the merge on `git reset --hard` we should as well.
