### ISSUE TITLE
sql-client can't find knex-created table until show tables called

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#3402]
I am running `dolt sql-server`.
I am connecting to that via `dolt sql-client`.

In the client, I create a database:
```
mysql> create database dolt;
mysql> use dolt;
```

I then run a knex migration (`knex migrate:latest`) that creates a table. In the migration file:
```
exports.up = async function (knex) {
  await knex.schema.createTable('assets', (table) => {
          // fields populated here
  });
}
```

Then in the client, I try to query the (empty) table:
`mysql> select * from assets;`

Response:
`Error 1146: table not found: assets`

This response continues regardless of delay or repeated execution. However, showing the tables does show the table exists, and a subsequent query *after* `show tables;` does then succeed.

The full sequence:
```
mysql> create database dolt;
mysql> use dolt;      <----- after this statement but before the following select, the knex migration is run
mysql> select * from assets;
Error 1146: table not found: assets
mysql> show tables;
+----------------------+
| Tables_in_dolt       |
+----------------------+
| assets               |
| knex_migrations      |
| knex_migrations_lock |
+----------------------+
mysql> select * from assets;
mysql>  // no error, and no output as expected since table is empty
```
Note: This doesn't seem to be an issue for our application code accessing that table - that succeeds fine. It is also no an issue with a table created directly in the sql client.
It seems to be specifically an issue with tables created by a knex migration, and only in the dolt sql-client. It seems `show tables;` is doing something to bring the new table into "visibility" for subsequent `select` queries.

**Comment by timsehn** [comment]
This has something to do with the visibility of changes between multiple connected clients. @zachmu can elaborate. Might be a bug. It might be something we sort of intended.

**Comment by fulghum** [comment]
Thanks for reporting this @dphil . I was able to repro the behavior in Dolt, and it does look like MySQL's behavior is different (I couldn't repro it there). 

This might have to do with how Dolt is refreshing state for sql transactions. With client1 and client2 connected to a dolt sql-server instance, client1 can create a table, but client2 cannot immediately select from that table. After client2 executes any successful command (e.g. `select 1;`) it is then has visibility to the new table. However, it's weird that `show tables` executes correctly and includes the new table while the select statements fail. 

When I tried to repro this with MySQL, the second client was able to select from the new table immediately. 

I'll keep investigating more and will see if @zachmu has any ideas.

**Comment by zachmu** [comment]
I think this is a bug in how we initiate transactions. Specifically, there's an edge case where if you do a schema change on another session, other sessions won't see that change on their first auto-initialized transaction (with `@@autocommit = on`, mysql's default).

We're fixing this, but you can work around it for now by explicitly initiating a transaction (`start transaction;`) before running `select *`.

**Comment by fulghum** [comment]
Quick update on this one... I've got test cases that repro this, and I just got the fix working to make them pass. I still need to clean up the code a bit, and there are a few other areas of transaction initialization I want to look at while I'm in here, but I should have a PR out on Monday for the fix. 

Thanks for helping us find this issue!

**Comment by fulghum** [comment]
Alright, I just merged the fix for this into the main branch of the go-mysql-server repo. We'll pull that new version into Dolt and get a Dolt release out later today that includes this fix as well as a few others. 

Let us know if you find anything else strange and we'll hop on it asap!
