### ISSUE TITLE
Support Partial Clone

### ISSUE THREAD

**Issue by aleclarson** [dolthub/dolt#3403]
In cases where commit history is unnecessary, it'd be nice to avoid the wasted disk space.

```
dolt clone --depth 1 <repo> <dest>
```

From git docs:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1925840/168164185-a43d50fd-3858-417b-b605-8abb59e4104b.png">

**Comment by timsehn** [comment]
We've definitely discussed this and agree it's a good feature to add.

**Comment by burdiyan** [comment]
I think shallow clones and partial clones are a bit different features (although with some overlap). It's been discussed in pretty much any version control system implementation that ever existed, and sometimes they call them by different names (narrow clones, slices, etc.), but in the end it's all about the same.

Basically it all boils down to limit the clone in two dimensions: time and space.

So, time is what Git calls shallow clone, which lets you clone the repository without having to clone the full history.

And space, is what Git calls sparse checkout, which lets you checkout (and possible clone) only those parts of the repository that you are interested about. For example only a specific directory (or specific table in Dolt).

Both features are indeed very valuable to have in Dolt.

Do you have any plans, or maybe rough ideas on how could this be implemented in Dolt?

**Comment by alecstein** [comment]
Bumping this. This would be such a time saver for data bounties. These people don't need the history ever.

**Comment by timsehn** [comment]
Shallow clone is implemented:

https://www.dolthub.com/blog/2024-02-21-shallow-clone/

Partial clones are not. Changing the title of this issue to Partial :-)

**Comment by timsehn** [comment]
Good idea.

**Comment by bpf120** [comment]
@burdiyan , we'd love to learn about your Dolt use case sometime. Feel free to join our [Discord](https://discord.gg/gqr7K4VNKe) or shoot me an [email](mailto:brianf@dolthub.com) if you want to share.
