### ISSUE TITLE
(sql-client) shortcut to navigate cursor to next word

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#3405]
Quality of life feature for the dolt sql-client. Support cursor word-jumping. For example typically accomplished via ctrl-left/ctrl-right. Aids in navigating within parts of a long command to edit.

**Comment by JCOR11599** [comment]
I think the typical terminal keyboard shortcuts should apply here.
For the BASH terminal on my Windows machine, `alt + f` and `alt + b` move the cursor forward and back respectively. So, whatever your terminal's shortcuts are should work.
