### ISSUE TITLE
Bug: error: '*sql.ColumnDefaultValue' is not a valid value type for 'TINYINT'

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#3407]
I get an inscrutable error: `Bug: error: '*sql.ColumnDefaultValue' is not a valid value type for 'TINYINT'` when trying to import data into a table.

Repro:

Private repo: https://www.dolthub.com/repositories/dolthub/bug-test-1

Fire up `dolt sql` and do:
```
LOAD DATA INFILE 'test.csv'  INTO TABLE objects FIELDS TERMINATED BY ','  LINES TERMINATED BY '\n' IGNORE 1 LINES;
```

`test.csv` provided in chat.

**Comment by VinaiRachakonda** [comment]
This seems to be from an older version of Dolt. Upgrading 0.40 fixes the issue
