### ISSUE TITLE
Constraint Violations and Foreign Key Checks

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3414]
Consider this setup 

```SQL
CREATE TABLE colors (
    id INT NOT NULL,
    color VARCHAR(32) NOT NULL,

    PRIMARY KEY (id),
    INDEX color_index(color)
);
CREATE TABLE objects (
    id INT NOT NULL,
    name VARCHAR(64) NOT NULL,
    color VARCHAR(32),

    PRIMARY KEY(id),
    CONSTRAINT color_fk FOREIGN KEY (color) REFERENCES colors(color)
);
INSERT INTO colors (id,color) VALUES (1,'red'),(2,'green'),(3,'blue'),(4,'purple');
INSERT INTO objects (id,name,color) VALUES (1,'truck','red'),(2,'ball','green'),(3,'shoe','blue');
```

We make the following changes through the server

```
mysql> set foreign_key_checks = 0;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into objects values (4, 'laptop', 'gray');
Query OK, 1 row affected (0.01 sec)

mysql> set foreign_key_checks = 1;
Query OK, 0 rows affected (0.01 sec)

mysql> call dolt_commit('-a', '-m', 'dasdas');
+----------------------------------+
| hash                             |
+----------------------------------+
| f2sros3e237dcpa1glam79bthvaqt542 |
+----------------------------------+
1 row in set (0.01 sec)
```

The first issue here is **should we be allowed to even commit this state of the repo?** There is a foreign key violation with the color gray. 

Now let's exit the server mode and run 

`dolt constraints verify objects`

It does not output anything. That does not seem correct. I'm also not quite sure of the intended behavior when merging this state around

**Comment by zachmu** [comment]
We definitely need to support committing foreign key violations. They're possible to disable, they need to be committable as well.

The lack of output from `dolt constraints verify` seems like an error.

**Comment by druvv** [comment]
We can commit foreign key violations, `dolt_force_transaction_commit` needs to be set. This also allow you to commit conflicts.

**Comment by VinaiRachakonda** [comment]
dolt constraints verify acts only on the working set so all the behavior here is expected cc @druvv. Closing
