### ISSUE TITLE
Support EDITOR Configuration

### ISSUE THREAD

**Issue by pbronez** [dolthub/dolt#3415]
Dolt and git both have several operations (`commit`, `log`, etc.) that present text to the user via a text editor. Git allows the user to specify which editor program should be used for this, but dolt does not.

Git provides a couple ways for to provide the path to the preferred text editor:
1. Use `git config` to [set the `core.editor` parameter](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#_editor)
2. Set the [`GIT_EDITOR` environment variable](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables). If `GIT_EDITOR` is not set, git falls back to `EDITOR`. The `EDITOR` variable is a cross-application convention.

I have tried both methods with Dolt, but `dolt log` and `dolt commit` do not respect either configuration. I asked about this on Discord and was told to open an issue here.

System:
- MacOS 12.3.1
- dolt 0.40.0
- Terminal 2.12.5
- zsh 5.8

**Comment by VinaiRachakonda** [comment]
@jennifersp Mind following up? I know you looked at something similar before

**Comment by jennifersp** [comment]
Hi @pbronez, we don't support changing editors for Dolt at the moment.

**Comment by zachmu** [comment]
We definitely intend to support both `core.editor` as well as `$EDITOR`.

```go
func getCommitMessageFromEditor(ctx context.Context, dEnv *env.DoltEnv) (string, error) {
	var finalMsg string
	initialMsg, err := buildInitalCommitMsg(ctx, dEnv)
	if err != nil {
		return "", err
	}
	backupEd := "vim"
	if ed, edSet := os.LookupEnv("EDITOR"); edSet {
		backupEd = ed
	}
	editorStr := dEnv.Config.GetStringOrDefault(env.DoltEditor, backupEd)

	cli.ExecuteWithStdioRestored(func() {
		commitMsg, _ := editor.OpenCommitEditor(editorStr, initialMsg)
		finalMsg = parseCommitMessage(commitMsg)
	})
	return finalMsg, nil
}
```

I just tried this with `dolt commit` and it worked:

```
% dolt commit
Waiting for command to finish.
 commit e4o4kl3vbk8jncn4ajrlop9bfdrfcdk5 (HEAD -> main)
 Author: Zach Musgrave <zach@dolthub.com>
 Date:  Mon May 16 15:38:50 -0700 2022

     test
```

(my $EDITOR is set to emacs)

Can you give some more detail about what you're seeing here?

**Comment by timsehn** [comment]
Resolving as was not confirmed.
