### ISSUE TITLE
MOD function is missing

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#3423]
The modulo operator works in Dolt:
```
> SELECT 2 % 2;
+-------+
| 2 % 2 |
+-------+
| 0     |
+-------+
> SELECT 2 MOD 2;
+-------+
| 2 MOD 2 |
+-------+
| 0     |
+-------+
```

But the MOD function is missing:
```
> SELECT MOD(2, 2);
function: 'mod, maybe you mean mid or md5?' not found
```

MySQL reference:
https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_mod

**Comment by timsehn** [comment]
Indeed. From our docs.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/5376236/168662593-8c3ace52-da3b-4f3b-851a-15880a02ae73.png">

I don't think we need a ticket for every one of these. Why did you stumble on it?

**Comment by druvv** [comment]
The first google result when you search `take modulus sql` shows this link:
https://www.w3resource.com/sql/arithmetic-functions/mod.php#:~:text=SQL%20MOD()%20function%20is,the%20specified%20column%20or%20expression.

So I tried that.
