### ISSUE TITLE
Cannot create spatial table with CRS

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#3425]
Hi hi, more feedbacks related to spatial data, re-edit of all the issue.

```
../dolt sql -q 'CREATE TABLE geom (g GEOMETRY NOT NULL SRID 4326);'
Error parsing SQL
syntax error at position 44 near 'SRID'
CREATE TABLE geom (g GEOMETRY NOT NULL SRID 4326)
                                            ^
syntax error at position 44 near 'SRID'
```

https://dev.mysql.com/doc/refman/8.0/en/creating-spatial-indexes.html

Thx!

**Comment by timsehn** [comment]
@JCOR11599 Is this supposed to be supported?

**Comment by fulghum** [comment]
@jennifersp has the work for this one in flight already. Syntax support is ready and she's working on the go-mysql-server support next. We should have this one turned around for you quickly.

**Comment by fulghum** [comment]
@latot – let us know if you have any issues using the new SRID definition support when creating tables with spatial data types. Thanks again for reporting this one!

**Comment by latot** [comment]
@fulghum Okis!, I'll try in some time check the functions!

Thx implementing this :3
