### ISSUE TITLE
Support `dolt rebase`

### ISSUE THREAD

**Issue by mitar** [dolthub/dolt#3467]
I am exploring dolt but I am observing one feature missing: how to redact data already committed? How to change an existing commit to remove sensitive data which has been by accident pushed to it? Another problem is if you get GDPR "remove my data" request. Is there any plan to add that?

Also, if this would be added, my understanding is that also commit hashes of later commits would change, same as in git, yes?

Similarly, there is no `--amend` to `commit`.

**Comment by andrew-wm-arthur** [comment]
We currently support this through `dolt filter-branch`, here are the docs
https://docs.dolthub.com/reference/cli#dolt-filter-branch

**Comment by mitar** [comment]
Interesting. Does this work also for documentation files? And just to be sure, this changes commit hashes after rewriting, yes?

**Comment by andrew-wm-arthur** [comment]
Filter branch works on table data only, and yes, it rewrites each commit and creates a new commit

**Comment by aleclarson** [comment]
Does `filter-branch` allow for squashing past commits?

**Comment by zachmu** [comment]
No, `filter-branch` gives you a commit history 1:1 with the original one. There's no squash functionality.

True `rebase` functionality is coming, but is currently unscheduled. If this is stopping you from adopting dolt, please let us know.

**Comment by timsehn** [comment]
@fulghum is working on this now.

**Comment by fulghum** [comment]
As of [Dolt 1.30.5](https://github.com/dolthub/dolt/releases/tag/v1.30.5), we now support interactive rebases through the SQL interface. 

See our [announcement blog post for more details](https://www.dolthub.com/blog/2024-01-03-announcing-dolt-rebase/) and [let us know](https://github.com/dolthub/dolt/issues/new) if you'd like to see additional rebase features supported.
