### ISSUE TITLE
The column_key is empty in the information_schema.columns

### ISSUE THREAD

**Issue by sergeycherepanov** [dolthub/dolt#3469]
I still trying to use Dolt as database for the Directus CMS. But I facing with the issue related to determination of the primiry key in the schema. 

The directus logic based on the information_schema.columns.column_key values. 
But as I can see currently this column always empty.

To check it just need to create a table and select values from the INFORMATION_SCHEMA.COLUMNS table.

```sql
CREATE TABLE `about` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT "draft",
  `date_created` timestamp DEFAULT NULL,
  `date_updated` timestamp DEFAULT NULL,
  `url_key` varchar(255) NOT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `about_url_key_unique` (`url_key`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

SELECT
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.COLUMN_DEFAULT,
    C.IS_NULLABLE,
    C.COLUMN_TYPE,
    C.COLUMN_KEY,
    C.CHARACTER_MAXIMUM_LENGTH,
    C.EXTRA
FROM
    INFORMATION_SCHEMA.COLUMNS AS C
WHERE
        C.TABLE_NAME = 'about';
```

The current result:

table_name | column_name  | column_default | is_nullable | column_type  | column_key | character_maximum_length |
-----------|--------------|----------------|-------------|--------------|------------|--------------------------|
about      | id           | NULL           | NO          | int unsigned |            | NULL                     |
about      | uuid         | NULL           | NO          | char(36)     |            | NULL                     |
about      | status       | draft          | NO          | varchar(255) |            | NULL                     |
about      | date_created | NULL           | YES         | timestamp    |            | NULL                     |
about      | date_updated | NULL           | YES         | timestamp    |            | NULL                     |
about      | url_key      | NULL           | NO          | varchar(255) |            | NULL                     |

The expected result

table_name | column_name  | column_default | is_nullable | column_type  | column_key | character_maximum_length |
-----------|--------------|----------------|-------------|-------------|------------|--------------------------|
about       | id           | NULL           | NO          | int unsigned        | UNI       | NULL                     |
about       | uuid         | NULL           | NO          | char(36)        | PRI       | 36                       |
about       | status       | draft           | NO          | varchar(255)        |        | 255                      |
about       | date_created | NULL           | YES         | timestamp        |        | NULL                     |
about       | date_updated | NULL           | YES         | timestamp        |       | NULL                     |
about       | url_key      | NULL           | NO          | varchar(255)        | UNI       | 255                      |

**Comment by fulghum** [comment]
Hey @sergeycherepanov, thanks for opening this one. Using Dolt as the backing datastore for Directus CMS sounds like an awesome idea! Adding `column_key` seems like it should be pretty straightforward. I'll poke around to see if there's anything tricky with populating that column and see if it's something we can knock out quickly for you.

**Comment by bpf120** [comment]
Hi @sergeycherepanov, thanks again for making this issue. We'd love to learn more about how you're using Dolt with Directus. Feel free to email me (brianf@dolthub.com) or swing by our Discord. 

https://discord.com/invite/RFwfYpu

**Comment by fulghum** [comment]
I mentioned this one to @jennifersp yesterday and she was interested to pick it up, since she's done some work in information_schema already. Moving this one into assigned; we'll get this knocked out for you.

**Comment by jennifersp** [comment]
Fixed in https://github.com/dolthub/go-mysql-server/pull/1029
