### ISSUE TITLE
Indexing data inside JSON fields

### ISSUE THREAD

**Issue by mitar** [dolthub/dolt#3472]
It seems it is not possible to create indices on data inside JSON-typed fields?

**Comment by timsehn** [comment]
Thanks for all the great feature requests @mitar!

@andrew-wm-arthur this isn't possible right?

@max-hoffman maybe we can implement it in the new format?

**Comment by zachmu** [comment]
This is on the roadmap: "Virtual columns and json indexing"

https://docs.dolthub.com/other/roadmap

Currently unscheduled but we give priority requests from paying customers.

**Comment by zachmu** [comment]
Virtual columns are supported in the latest release. There are still some sharp edges (merges don't work correctly in some cases), so I'm going go leave this open until they're fixed. But you can try it out now.

**Comment by timsehn** [comment]
An example of how to use them to index JSON columns is in this blog:

https://www.dolthub.com/blog/2023-11-03-virtual-columns/

**Comment by zachmu** [comment]
Going to resolve this in favor of the more scoped bug here:

https://github.com/dolthub/dolt/issues/6945
