### ISSUE TITLE
Does aws remote work with assume role?

### ISSUE THREAD

**Issue by yummydum** [dolthub/dolt#3501]
First of all, thanks for the interesting project, Dolt fits perfectly with my current data engineering work! It's a very cool tool.

Currently, I have trouble setting up aws remote correctly.
I configured the remote as below.
```
dolt remote add origin --aws-region ap-northeast-1 --aws-creds-type role --aws-creds-profile myprofile  "aws://[dolt-remote:dolt-remote]/mytablename"
```

I confirmed the remote was configured correctly by

```
>> dolt remote -v
origin aws://[dolt-remote:dolt-remote]/mytablename {"aws-creds-profile":"myprofile","aws-creds-type":"role","aws-region":"ap-northeast-1"}

```

I can confirm that the dynamodb table exists from the awscli.
```
>> aws dynamodb list-tables --profile myprofile
{
    "TableNames": [
        "dolt-remote",
        ...
    ]
}

```

However, I get the following error.
```
>> dolt push --set-upstream origin main
error: push failed
cause: failed to get dynamo table: 'dolt-remote' - NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Here is my configuration for aws connection. I use assume-role, this may be related.

```
>> cat ~/.aws/credentials
...
[temporal]
aws_access_key_id =<temp aws access key>
aws_secret_access_key =<temp secret access key>
aws_session_token =<temp session token>
...
```

```
>> cat ~/.aws/config
...
[profile myprofile]
region = ap-northeast-1
source_profile = temporal
role_arn = <my role arn>
...
```

After some experiments, I noticed that if I specify a non-existent profile name, I get the same error. Perhaps dolt is not able to find the profile correctly? I cannot proceed to debug further, since the error message doesn't provide any more information, and I don't see verbose mode for `dolt push` for more logs.

Any suggestion on how I can proceed? Thanks for your help in advance 😃

**Comment by VinaiRachakonda** [comment]
@yummydum Thank you for this detailed issue! AWS remote support is essential for us so I'm sorry to see you are having problems with that. Our team will get back to you ASAP.

**Comment by reltuk** [comment]
I think dolt AWS remotes do support assume_role profiles. The way I would recommend proceeding is to avoid most of the dolt-configured credentials, so that dolt will use the default AWS SDK credentials. An example invocation looks something like:

```
$ AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=corpdev dolt clone 'aws://[dolt-ci-bats-manifests-us-west-2:dolt-ci-bats-chunks-us-west-2]/aws_remote_bats_tests'
cloning aws://[dolt-ci-bats-manifests-us-west-2:dolt-ci-bats-chunks-us-west-2]/aws_remote_bats_tests
2 of 2 chunks complete. 0 chunks being downloaded currently.
```

Or like:

```
aaronson@Aarons-MacBook-Pro aws_remote_bats_tests % dolt remote add origin 'aws://[dolt-ci-bats-manifests-us-west-2:dolt-ci-bats-chunks-us-west-2]/aws_remote_bats_tests' 
aaronson@Aarons-MacBook-Pro aws_remote_bats_tests % AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=corpdev dolt fetch
aaronson@Aarons-MacBook-Pro aws_remote_bats_tests % dolt branch -av
* main                                          	qjbru5mbk62e8em9ea6jaf7hdbhvci5k
  remotes/origin/master                         	018h0vc921g6sc4oa6kp9e2mfguo528j
```

For your use case, I think the following invocations also work:

```
$ AWS_SDK_LOAD_CONFIG=1 dolt remote add --aws-creds-profile=corpdev --aws-region=us-west-2 origin 'aws://[dolt-ci-bats-manifests-us-west-2:dolt-ci-bats-chunks-us-west-2]/aws_remote_bats_tests'
```

where the profile and region is actually associated with the remote, instead of having to be set in the environment every time correctly. Depending on your use case, that may be more useful.


We need to investigate the requirement for AWS_SDK_LOAD_CONFIG to be set in order for role credentials to work. I'm not sure what's going on there, but I can confirm that I can reproduce your failure if I don't have it set.

With AWS_SDK_LOAD_CONFIG=1 and no credentials configured on the remote, we have also tested things to work with EC2 instance roles and federated access to IAM roles through AWS EKS using `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables.

We will keep you posted on our investigation into removing the need for AWS_SDK_LOAD_CONFIG=1 (or at least documenting it...)

**Comment by yummydum** [comment]
Thanks for the quick response! 
As you suggested, if I set `AWS_SDK_LOAD_CONFIG=1`, I was able to correctly connect with the remote. 

> With AWS_SDK_LOAD_CONFIG=1 and no credentials configured on the remote, we have also tested things to work with EC2 instance roles and federated access to IAM roles through AWS EKS using AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables.

This is exactly what I will need to try as the next step. My application runs on ECS/Batch. I'm glad that these cases are tested as well. So in these cases, I also set `AWS_SDK_LOAD_CONFIG=1` and it will work?

Thank you again for the help!

**Comment by bpf120** [comment]
Hi @yummydum, Thanks for filing! We'd love to hear about your use case. Feel free to email me (brianf@dolthub.com) or swing by our Discord if you'd like to share.  

https://discord.com/invite/RFwfYpu

**Comment by reltuk** [comment]
#3506 will remove the requirement for `AWS_SDK_LOAD_CONFIG=1` to be set :).

**Comment by reltuk** [comment]
This has been released. I'm going to go ahead and close here, but feel free to reopen if you feel there's anything left to do here :).

Thank you again for the great report.

**Comment by yummydum** [comment]
Thanks for the improvement! 
I joined discord, and I have already found a lot of useful information. 
Thank you again for all your assistance!
