### ISSUE TITLE
dolt_merge_state system table

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#3504]
If a merge results in conflicts, we should expose the source (right) branch of the merge in a system table. `dolt_merge_state` would hold the relevant information.

Merging other into main:
```
> SELECT * from DOLT_MERGE_STATE;
| is_merging | source_branch |
|------------|---------------|
| true       | other         | 
```

No merge in progress:
```
> SELECT * from DOLT_MERGE_STATE;
| is_merging | source_branch |
|------------|---------------|
| false       | NULL         | 
```

**Comment by fulghum** [comment]
Is source_branch the right term? I was picturing this as the target branch receiving the contents from a merge and still having merge conflicts in its working set. Might be worth explicitly mentioning the customer use case in issues like these, just to add some more context. In this case, my understanding is the customer is merging from branchA to branchB, they have allowed conflicts to be committed in tx commits, and they need a way to identify which branches have working sets that contain conflicts that still need to be resolved and then Dolt committed. 

It looks a little odd to have a single row with is_merging=false and source_branch=null when no merges are in progress. Any other thoughts on how to expose this info? You could have the sys table be empty when no merges are in progress. Or maybe a DOLT_MERGING_BRANCHES table that just has one column with branch name? Or... an `is_merging` flag in the existing `dolt_branches` system table?

**Comment by druvv** [comment]
I believe the customer does know which branch has the transaction committed conflicts. They say:

> ... next time we open the branch (even days later) to solve the conflicts, we do not have info - (I do not know where to look for it) what was the source branch.

Seems to me that they performed a merge into a known target branch and that they need to know what the source was in order to resolve the conflicts correctly.

**Comment by druvv** [comment]
Picking this issue up today.
