### ISSUE TITLE
Support Parquet as an output format in the `-r` option

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#3518]
Two related features that would have been useful fixing a [recent bug](https://github.com/dolthub/doltpy/issues/179):

Specifying an `--asof` flag for exports:
```bash
> dolt export table --asof <revspec> mytable mytable.parquet
```

Supporting `--format pq` for the `sql` command:
```bash
> dolt sql -r pq -q "select * from mytable as of <root value>"
```

**Comment by timsehn** [comment]
For the first one, you can just checkout the branch. The second one would be nice.

**Comment by fulghum** [comment]
Parquet output support for `dolt sql` is included in https://github.com/dolthub/dolt/pull/6068

**Comment by timsehn** [comment]
Jason fixed this :-)
