### ISSUE TITLE
Dolt table import on large databases is extremely slow

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3520]
For reference every gb (~1m rows) added to this 500gb [Bitcoin Database](https://www.dolthub.com/repositories/web3/bitcoin) takes about 20minutes. 

Here are small notes to keep in mind when doing a really large database import

- Absolutely no foreign keys or unique indexes
- No blob types. Use longtext sparingly
- Be specific about commit amounts. A bunch of commits results in a really slow `dolt log`
- Gargabe collect consistently

**Comment by timsehn** [comment]
Import performance is benchmarked here and we'll improve it over time.

https://docs.dolthub.com/sql-reference/benchmarks/import
