### ISSUE TITLE
Multi-database state syncing in transactions

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#3521]
When a transaction is explicitly started with a `start transaction` statement, the statements executed within that transaction that use data from multiple databases can have stale or missing results. This is because the database state for the transaction database is synced into the current session when the `start transaction` statement is executed, but the state for other databases isn't ever synced. Autocommit transactions have a similar issue, but is potentially easier to fix since we know all the databases involved in the transaction at transaction start time since only one statement is involved. 

Note that while multi-db support within a single transaction is not officially supported, it is not explicitly disallowed either, so this is likely low priority to address currently, but still worth tracking. 

**Repro Example:**
* Session 1
  * `use db1`
  * `create table t1 (pk int);`
  * `insert into t1 values (100);`
* Session 2 _(started at the same time as session 1)_
  * `use db2;`
  * `start transaction;`
  * `select * from db1.t1;` <-- results in: table not found: t1

**Comment by zachmu** [comment]
This should work now. We record a start state for all databases being served when a transaction begins, so either the table will exist or not to another transaction, in a consistent manner.
