### ISSUE TITLE
Have 'dolt status' also show how local repo compares with remote

### ISSUE THREAD

**Issue by s0rbus** [dolthub/dolt#3599]
In git if I have cloned a repo and do 'git status' I see something like:
On branch main
Your branch is up to date with 'origin/main'.

If I make a change and commit but before pushing to remote I see something like:
On branch main
Your branch is ahead of 'origin/main' by 1 commit.

I think it would be great if 'dolt status' could do something similar.

**Comment by timsehn** [comment]
This may require we extend our `--track` functionality as I think you need to have set `--track` for this message to trigger in Git.

**Comment by VinaiRachakonda** [comment]
@jennifersp Can we close this issue now that [https://github.com/dolthub/dolt/pull/3686](3686) is merged?

**Comment by jennifersp** [comment]
Yes, remote tracking details for dolt status is now supported.
