### ISSUE TITLE
Deprecate `multi-db-dir`, databases field in `config.yaml`

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3623]
Right now there are two ways to specify where a server should find databases:

`--mutli-db-dir` command line flag
`databases` config.yaml field

We should replace both with a single flag:

`--data-dir` (`dataDir` in config.yaml)

All databases must live in the directory named. Defaults to `.`, as now.

The existing command line flag should be a synonym for the new one at least until 1.0.

The `databases` field in YAML should print a warning and not be used.

**Comment by timsehn** [comment]
This is resolved with https://github.com/dolthub/dolt/pull/3732
