### ISSUE TITLE
`USE db/branch` works differently than `call dolt_checkout('branch')`

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3637]
There are subtle differences to how we manage session state between these two constructs. We need to unify them so they work identically.

**Comment by timsehn** [comment]
@fulghum did you fix this with your current work?

**Comment by timsehn** [comment]
I might close if we can't get more specific.

**Comment by fulghum** [comment]
No, I resolved some differences around database revision specs, but I think there are still more nuanced differences hiding in here.

**Comment by timsehn** [comment]
Closing this infavor of the more specific #5314
