### ISSUE TITLE
Support `MultiLineString`, `MultiPolygon`, `MultiPoint` and `GeometryCollection ` geometry types

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#3638]
Hi, please support:

- MultiLineString
- MultiPolygon
- MultiPoint
- GeometryCollection

With this geometries Dolt should have all the basic types, except the empty geometry, need to confirm this.

Thx to @fulghum debugging a sql file to know this.

Thx!

**Comment by JCOR11599** [comment]
Took a couple PRs, but every supported geometry type in MySQL is recognized and supported in Dolt. Some of these have been included in previous releases (it might just be `geometrycollection` that is missing). Regardless, they're all in main now, and we'll get a release out later this week.

**Comment by latot** [comment]
:O :O :O Thx!, every time one step more!

Thx!
