### ISSUE TITLE
Dolt Diff across all tables

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#3650]
Dolt provides several ways to diff individual tables, but there's isn't a built in way to ask Dolt to tell you all the differences in all tables that have changed, or to ask which tables have changed between two commits. 

This came up from a customer use case where they wanted to determine all the data differences between two branches. This feature would allow them to identify all the changed tables, then use other system tables / functions (e.g.`dolt_commit_diff`) to look at the individual table data differences. 

One implementation could be a system table or table function: 
```
> select * from dolt_changed_tables where from_commit=hashof('branch1') and to_commit=hashof('branch2');
+-----------------------------------------+
| table_name | added | removed | modified |
+-----------------------------------------+
| mytable1   | true  | false   | false    |
| mytable2   | false | false   | true     |
+-----------------------------------------+
```

**Comment by timsehn** [comment]
This is implemented as empty `dolt_diff` system table.
