### ISSUE TITLE
NULLIF doesn't work properly with LONGTEXT

### ISSUE THREAD

**Issue by zdb999** [dolthub/dolt#3658]
Using `NULLIF` with two `LONGTEXT` columns produces an error if both of those columns happen to be LONGTEXT`. An simple example for reporduction is
```
SELECT NULLIF(schema(), database());
```
Which  produces
```
ERROR 1105 (HY000): incompatible conversion to SQL type: LONGTEXT
```
This is currently blocking me from using Dolt with [Mikro-Orm](https://mikro-orm.io/).

This problem doesn't just happen for function output, but also on ordinary table columns. Interestingly, the issue does not occur when either of the arguments are null or a string literal.

**Comment by bpf120** [comment]
Hi @zdb999, we love to learn more about how you are using Dolt. Feel free to swing by our Discord or send me an email if you'd like to share. 

https://discord.com/invite/RFwfYpu
brianf@dolthub.com

**Comment by Hydrocharged** [comment]
@zdb999 Found the bug and submitted a PR. This will be fixed in our release later today!

**Comment by timsehn** [comment]
https://github.com/dolthub/go-mysql-server/pull/1073

That's the change if you are curious.

**Comment by Hydrocharged** [comment]
Changes are in the newest release!

https://github.com/dolthub/dolt/releases/tag/v0.40.11

**Comment by bpf120** [comment]
@zdb999 A video chat would be great. Want to email me to coordinate?
