### ISSUE TITLE
Implement `dolt patch` and `dolt apply`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#3700]
Dolt already supports patch and apply functionality. We should make it explicit with commands.

`dolt patch` is equivalent to `dolt diff -r sql > file.sql`. `dolt apply` equivalent to `dolt sql < file.sql`.

Note, in Git it's call `format-patch`. We should alias `format-patch` to `patch`.

We may want stored procedures for these as well, though I think it would need to be shortened to one procedure `dolt_patch()` that took a diff spec. This would be similar to cherry pick but it would apply the sql and not make a commit.

**Comment by fulghum** [comment]
Just chatted with a customer who is also interested in this functionality. For their use case, they need to generate the SQL patch statements for a diff so that they can apply those patch statements on another host. 

They specifically need the stored procedure for `dolt_patch(<from_revision>, <to_revision>, [<tablename>])`.

**Comment by bpf120** [comment]
@wp4nuv Thanks for letting us know. Is your company currently using Dolt? Feel free to [email me](mailto:brianf@dolthub.com) me or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to chat more about your use case.

**Comment by jennifersp** [comment]
`dolt_patch()` stored procedure generates SQL statements needed to patch a table(s) between two revisions. The support for this has been added to Dolt in https://github.com/dolthub/dolt/pull/5413 and will be out in the next Dolt release. The CLI `dolt patch` command is not supported yet.

**Comment by timsehn** [comment]
We have `dolt_patch()` stored procedure. Going to resolve this.
