### ISSUE TITLE
dolt sql-server Port already in use

### ISSUE THREAD

**Issue by wupeaking** [dolthub/dolt#3701]
whichever port is listened, it will prompt that it has been used. (ubuntu 20.04 )
![image](https://user-images.githubusercontent.com/15843348/176159664-c922404b-3817-497f-85a2-4a4c17b643fa.png)

but, when I exec dolt in my mac , it's ok.

dolt version: v0.40.11

**Comment by timsehn** [comment]
Nice bug. We'll dig into this today and get it fixed.

**Comment by bpf120** [comment]
Hi @wupeaking, We'd love to learn about your Dolt use case and how you found us. Feel free to swing by our [Discord](https://discord.com/invite/RFwfYpu) or send me an (email)[mailto:brianf@dolthub.com) if you'd like to share.

**Comment by wupeaking** [comment]
@timsehn @fulghum  Thank you very much for your quick reply. this is my reason.  I find the reason when debug the code. dolt  check port whether is used by  dialing  the address.  one network monitoring software in my ubuntu modify iptables to accecpt any connect.  so dolt thinks the port is already in use.

**Comment by fulghum** [comment]
Ahh... interesting! Thanks for following up with us and letting us know what you found!
