### ISSUE TITLE
Import Benchmarking

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3731]
We need to have consistent benchmarks that provide clear metrics on import benchmarks. 

### Independent Variables

1. The number of rows we are importing. 1000, 10,000 .... 100,000,000
2. The format type. CSV, JSON, Parquet
3. The Schema. (More Details later)
4. The order in which we import the data. We can import in sorted key order or in a random order. 
5. The number of rows per insert statement
6. How often we commit a transaction

### Dependent Variables

1. Rows Imported Per Second. We should track this over the life span of the import over some fixed time delta (~30 seconds)
2. Garbage Generated. This should probably be in proportion to the size of the file created. 

### Defining a Testing Schema

There are several factors that influence the complexity of a schema

- The primary key.
- The types.
- Type width. Ex) varchar(100) vs varchar(200)

We'll avoid the following 

- Longtext, Blob or Geometry types. These are naturally expensive to provision
- Foreign Key Relationships. In the traditional MySQL [bulk loading](https://dev.mysql.com/doc/refman/8.0/en/optimizing-innodb-bulk-data-loading.html), foreign key checks should be turned off. 
- Secondary Indexes

Given this we can use a subset of the [First-Hour-Db all types ](https://www.dolthub.com/repositories/dolthub/first-hour-db/query/main?q=SHOW+CREATE+TABLE+%60all_types%60&active=Schemas)table to construct the following test schemas.

1. Schema with an integer primary key schema and all digit types
2. Schema with an  Integer primary key and all digit, string, and datetime types
3. Schema with a  compound primary key and uses all digit, string and datetime types

**Comment by zachmu** [comment]
Another independent variable I want to see measured is the impact of a sorted import vs. random order, we need to be able to provide guidance to our customers on this.

Also two variables for batch size: how many rows do we insert in each statement? How often do we commit the transaction?

**Comment by timsehn** [comment]
Resolved here:

https://docs.dolthub.com/sql-reference/benchmarks/import
