### ISSUE TITLE
`merge` should create a commit when are no conflicts

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3773]
When we first wrote merge, the git behavior was to leave the working set dirty with any merged in changes. That has since changed: the default for a non-ff merge is to create a new commit. `merge` accepts a `--message` flag to accommodate a commit message.

Dolt should do the same, both on the command line and in the SQL procedure.

**Comment by timsehn** [comment]
This also requires implementing the `--commit` and `--no-commit` flags.

**Comment by jennifersp** [comment]
fixed in https://github.com/dolthub/dolt/pull/4105
