### ISSUE TITLE
N-gram databases for other-language Wikipedias

### ISSUE THREAD

**Issue by a-gbg** [dolthub/dolt#3820]
Your maintained N-gram database for English-language Wikipedia is very useful. It introduced me to Dolt. Are there any plans on maintaining these for other Wikipedias? I'm particularly interested in Swedish-language Wikipedia n-grams.

**Comment by timsehn** [comment]
We kind of stopped the whole data publishing angle to focus on making Dolt a true database. We can point you to the code and you can start publishing Swedish under your account?

Code is here:

https://github.com/dolthub/dolthub-etl-jobs/tree/master/loaders/wikipedia

**Comment by a-gbg** [comment]
Thank you!
