### ISSUE TITLE
SHOW CREATE PROCEDURE dolt_branch fails when no DBs exist

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3832]
In a new directory with no dolt db:

```
dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
> show create procedure dolt_branch;
plan is not resolved because of node '*plan.ShowCreateProcedure'
```

**Comment by PavelSafronov** [comment]
This behavior seems consistent with MySQL behavior: stored procedures cannot be called without a db.

Here's the MySQL test script that attempts to show and call a stored procedure with or without a db:
```bash
mysql.server restart

mysql -u root << EOF
select 'try creating a proc without a db: this fails';
create procedure foo() select 42;
call foo();
EOF

mysql -u root << EOF
select 'create a proc with a db: this works';
drop database if exists db;
create database db;
use db;
create procedure foo() select 42;
show create procedure foo;
call foo();
EOF

mysql -u root << EOF
select 'show and call existing proc without a db: this fails';
show create procedure foo;
call foo();
EOF

mysql -u root << EOF
select 'show and call existing proc with a db: this works';
use db;
show create procedure foo;
call foo();
EOF

mysql.server stop
```

Script output:
```txt
$ ./mysql-repro.sh
 ERROR! MySQL server PID file could not be found!
Starting MySQL
.. SUCCESS! 
try creating a proc without a db: this fails
try creating a proc without a db: this fails
ERROR 1046 (3D000) at line 2: No database selected
create a proc with a db: this works
create a proc with a db: this works
Procedure       sql_mode        Create Procedure        character_set_client    collation_connection    Database Collation
foo     ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION   CREATE DEFINER=`root`@`localhost` PROCEDURE `foo`()\nselect 42   utf8mb4 utf8mb4_0900_ai_ci      utf8mb4_0900_ai_ci
42
42
show and call existing proc without a db: this fails
show and call existing proc without a db: this fails
ERROR 1046 (3D000) at line 2: No database selected
show and call existing proc with a db: this works
show and call existing proc with a db: this works
Procedure       sql_mode        Create Procedure        character_set_client    collation_connection    Database Collation
foo     ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION   CREATE DEFINER=`root`@`localhost` PROCEDURE `foo`()\nselect 42   utf8mb4 utf8mb4_0900_ai_ci      utf8mb4_0900_ai_ci
42
42
Shutting down MySQL
. SUCCESS! 
```

I think we should stick with this behavior, though it would definitely help to provide the user with a better error message. It's not obvious from `plan is not resolved because of node '*plan.ShowCreateProcedure'` that the user has to have a db.

**Comment by fulghum** [comment]
Dolt has a unique behavior here that differs a little bit from MySQL... we wanted to make the use case work where you start a brand new sql-server then run `call dolt_clone(...)` to initialize the db with a clone. That required us to make stored procedures available when no database is selected. `dolt_clone` is the only stored procedure that will actually work without a database selected. 

Improving the error message to match MySQL seems like a good outcome here. I'd be happy with that. I think we could still make it work to show the output for `show create procedure` if you want to take that further, but just improving the error message so it's not `plan is not resolved` and helped the user understand they need to select a db for the query to work would be a nice improvement.

**Comment by PavelSafronov** [comment]
This issue has been fixed by improving the error messaging when a user tries to run `show create procedure` without a DB: "error on line 1 for query show create procedure dolt_branch: no database selected"
