### ISSUE TITLE
Using `CALL` with `DOLT_CHECKOUT` returns [HY000][1105] branch not found

### ISSUE THREAD

**Issue by n0mn0m** [dolthub/dolt#3846]
When using `CALL DOLT_CHECKOUT` I get error `[HY000][1105] branch not found`. This happens for any branch, and I have confirmed the branches exist via `SELECT * FROM dolt_branches`.

I am able to checkout a branch with `SELECT DOLT_CHECKOUT()`.

**Comment by n0mn0m** [comment]
Dolt version is `0.40.5`

**Comment by druvv** [comment]
Hi @n0mn0m How are you running Dolt currently? Through the `dolt sql-server` or through `dolt sql -q`?

**Comment by n0mn0m** [comment]
Our dolt instance is hosted. I'm running this against the hosted `dolt sql-server` instance with a JDBC connection (executing this in datagrip).

**Comment by druvv** [comment]
Just adding some insight to the issue we learned last week. We attempted to reproduce this issue locally and with a copy of Flock's development database. Unfortunately, we were unable to get any repro locally.

Restarting the server fixed the issue. We will take another pass at this if it happens again.

**Comment by timsehn** [comment]
Resolving. Reopen or create a new issue if the issue recurs.
