### ISSUE TITLE
Calling `SELECT DOLT_BRANCH('-d', '<branch-name>')` results in `[HY000][1105] attempted to delete a branch that is not fully merged into its parent; use `-f` to force`

### ISSUE THREAD

**Issue by n0mn0m** [dolthub/dolt#3853]
I've been running into an error consistently when using the `-d` flag to remove a branch that is merged. The queries I execute are:

```sql
SELECT * FROM dolt_branches;
SELECT DOLT_CHECKOUT('<feature-branch-name>');
SELECT active_branch();
SELECT * FROM dolt_status WHERE staged=false;
SELECT DOLT_CHECKOUT('dev');
SELECT active_branch();
SELECT * FROM dolt_status WHERE staged=false;
SELECT DOLT_MERGE('<feature-branch-name>');
SELECT * FROM dolt_commits;
SELECT * FROM dolt_conflicts;
SELECT DOLT_BRANCH('-d', 'testing-sealed-migration');
```

Running the merge results in the return code being `1`. The staged query check result is empty, the conflict table is empty too. I can see the results of the merged data in the `dev` branch along with the commits.

When I run the drop branch procedure I get the error: `[HY000][1105] attempted to delete a branch that is not fully merged into its parent; use `-f` to force`. The data is in `dev` already, so using the `-f` flag to drop the branch is fine, but I feel like I'm missing something or doing something wrong here.

**Comment by timsehn** [comment]
@jennifersp just implemented this. She will look today.

**Comment by jennifersp** [comment]
Hi @n0mn0m, thank you for providing the queries. I'm following them, and need a little more information on whether the merge was fast-forward or non-fast-forward. For fast-forward, no changes are made, so no new commit is created or required. However, for non-fast-forward merge, with successful merge, it leaves the changes in the working set, not staged, so it requires you to commit afterwards. This might be the reason for the error you're getting when trying to delete the branch you just merged.

**Comment by n0mn0m** [comment]
Got it. That makes sense. I'll make the updates in our application. Thank you both!

**Comment by timsehn** [comment]
Actually. Already have one.

**Comment by timsehn** [comment]
https://github.com/dolthub/dolt/issues/3773

**Comment by n0mn0m** [comment]
Awesome. Subscribed 😄
