### ISSUE TITLE
Windows customer unable to clone db

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#3857]
A customer wanted to clone the hospital prices database, but had never used Dolt and didn't know how. Their background is in healthcare policy, and they're familiar with spreadsheets, CSV, but not databases per se.

Despite being motivated (and staying with me on Discord for a couple hours) they were stymied by the clone process. Nothing indicated to them (or to me) that they couldn't clone Dolt using the commands on the homepage. They didn't feel comfortable asking for help on the #dolt discord channel, I guess because they didn't want to feel like a noob.

I thought maybe DoltHub would change the install commands based on user agent, but that turns out not to be the case.

What other steps should this customer have taken? What could we have done better as a team to get this guy access to the database?

Currently following up with the customer to see if they ever managed to get Dolt installed.

**Comment by timsehn** [comment]
Did they not follow this?

https://docs.dolthub.com/introduction/installation/windows

Or were they stumped by the CLI stuff?

**Comment by alecstein** [comment]
> Did they not follow this?
> 
> https://docs.dolthub.com/introduction/installation/windows
> 
> Or were they stumped by the CLI stuff?

My impression was that they were stumped by the UX that said "Clone this db" and "Don't have a copy of Dolt? Click here" on the database page, which gave them commands that didn't work.

**Comment by timsehn** [comment]
This should probably be a DoltHub issue then. I'll move it.
