### ISSUE TITLE
Implement `dolt fsck`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#3886]
From Discord with a potential user:

>  It would be great (more from a blockchainish nonrepudiable evidence of state perspective than for gittish versioning applications) if there were some way to climb the tree from a piece of relevant state to the root hash.

Then me:

> I guess it would be `dolt prove <table> <primary key(s)>`

Then user:

> with a third optional argument so you could specify a past state root.

Running the command would spit out the exact hash of the database page (chunk in Dolt lingo) and then the hash path to root.

You could `strings` the chunk file in `.dolt` if you wanted to actually see the value on. disk. Or we could implement a way to read these files directly.

**Comment by macneale4** [comment]
In git parlance, this would be `git fsck` - verify checksums of all objects.

That said, if you really want to have confidence in your data, you need signatures of the authors: https://github.com/dolthub/dolt/issues/628

**Comment by timsehn** [comment]
Another customer recently asked for this. I think matching git syntax and implementing `dolt fsck` is the way to go.

**Comment by macneale4** [comment]
Released V1: https://github.com/dolthub/dolt/releases/tag/v1.43.2

Fixed by: https://github.com/dolthub/dolt/pull/8409
