### ISSUE TITLE
Dolt upgrade seems to have lost some settings

### ISSUE THREAD

**Issue by n0mn0m** [dolthub/dolt#3887]
Upgrade from dolt `0.40.5` to `0.40.19` last night seems to have created a couple interesting side effects.

Default branch per database settings where lost. We set the default branch using:

`SET PERSIST <db>_default_branch='dev'`

Based on the [docs](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#persisting-system-variables) I thought this would survive a restart/upgrade, but this morning the variable appeared unset and connections were operating against `main` by default.

Additionally we have a role setup with `SELECT` and `EXECUTE`:

```
CREATE ROLE foo_role;
GRANT SELECT, EXECUTE on *.* TO foo_role;
FLUSH PRIVILEGES;
GRANT foo_role TO <user>@'%';
FLUSH PRIVILEGES;
```

Previously users could run `SELECT` and `CALL` statements/procedures. Today users were receiving the error `[HY000][1105] command denied to user `.

**Comment by druvv** [comment]
Thanks for cutting the issue @n0mn0m, we'll investigate today and provide an update.

**Comment by druvv** [comment]
Just noticed that there are two bugs here. Just made https://github.com/dolthub/dolt/issues/3890 to track the second bug.

**Comment by druvv** [comment]
Hey @n0mn0m, setting that variable in Dolt versions `0.40.5` and `0.40.19` does not persist after restarting the sql-server. On restart, the following error is thrown:
```
error: failed to load persisted global variables: key: 'repro_default_branch'; Unknown system variable 'repro_default_branch'
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="info"
```

So you definitely we're using the right commands, the functionality is broken for `default_branch`. We'll make a fix for this tomorrow.

**Comment by druvv** [comment]
Getting started on this now
