### ISSUE TITLE
Upgrading Dolt seems to drop some privileges granted to users

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#3890]
Creating the following roles then upgrading from Dolt `0.40.5` to `0.40.19` denies the granted permissions on the new version:

```
CREATE ROLE foo_role;
GRANT SELECT, EXECUTE on *.* TO foo_role;
FLUSH PRIVILEGES;
GRANT foo_role TO <user>@'%';
FLUSH PRIVILEGES;
```

The error returned on the latest version is: [HY000][1105] command denied to user .

**Comment by JCOR11599** [comment]
Unable to reproduce issue.
