### ISSUE TITLE
Resolving conflict using theirs never completes

### ISSUE THREAD

**Issue by adagrad** [dolthub/dolt#3913]
I have a branch [2F6e58558530bf583cb91d](https://www.dolthub.com/repositories/adagrad/findb/data/yfinance%2Fquote%2F6e58558530bf583cb91d) which I want to merge into main. Since there are some conflicts I issued the command `dolt conflicts resolve --theirs .`. However, this command is now running for > 24 h and does not look like it is ever finishing. I wonder, how can a _use theirs_ cause such a huge workload? Shouldn't it be a simple replace?

**Comment by timsehn** [comment]
Are the database branches public? Can you share a repro? This is a bug.

**Comment by adagrad** [comment]
yes everything is public the hash link links to the repo and branch in question. Meanwhile I have managed to merge main into the feature branch using `--ours` and then merge the feature branch back to main. This is an ugly workaround but saved my day. However all the commit hashes are there as well as the branch in question. Its a rather big table which keeps growing ;-)

**Comment by timsehn** [comment]
We'll look Monday.

**Comment by druvv** [comment]
Hey @adagrad, I'm going to look at this after finishing some in flight things today.

**Comment by bpf120** [comment]
Hi @adagrad, we'd love to learn about your use case. If you'd like to share, come by our [Discord](https://github.com/dolthub/dolt) or send me an [email](mailto:brianf@dolthub.com).

Thanks!

**Comment by druvv** [comment]
Hey @adagrad, I don't see that branch on your database anymore. Any chance you could restore it?

**Comment by druvv** [comment]
Hi @adagrad, just following up here. Any chance you can get us any reproduction steps?

**Comment by timsehn** [comment]
I think @adagrad said on Discord that he found a workaround and blew away the branches. He/She'll submit a new issue if it happens again.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/5376236/181122760-aa29dd79-da3b-4f6b-8210-2823637a246d.png">
