### ISSUE TITLE
Using `dolt sql` with a running `dolt sql-server`

### ISSUE THREAD

**Issue by post-no-preference** [dolthub/dolt#3919]
For the [rates](https://www.dolthub.com/repositories/post-no-preference/rates) repository, I can do the following:

```bash
$ dolt sql -q "insert into us_treasury values ('1990-01-01', null, null, null, null, null, null, null, null, null, null, null, null);"
```

I used to be able to do the following (`-r` can be supplied or not; same error):

```bash
$ dolt sql-server -u user -r
$ dolt sql -q "insert into us_treasury values ('1990-01-01', null, null, null, null, null, null, null, null, null, null, null, null);"
```

This now returns:

```bash
error on line 1 for query insert into us_treasury values ('1990-01-01', null, null, null, null, null, null, null, null, null, null, null, null): not authorized
not authorized
```

`dolt version` is `0.40.19`

**Comment by zachmu** [comment]
We recently made it illegal to modify a database with a running server via the CLI -- you have to stop the server for any CLI commands that might update state to proceed. It seems like this is a bad error message here. @max-hoffman can you take a look?

We could improve this experience by making `dolt sql` detect the presence of a running server and connect to it automatically, rather than refusing to process DML statements. Can you give us an idea what it is about your workflow that makes this pattern necessary?

**Comment by post-no-preference** [comment]
The workflow is, from a script:

```bash
$ dolt pull
$ dolt sql -q "insert ..."
$ dolt add table
$ dolt commit table -m "message"
$ dolt push
```

It's done this way rather than going through some mysql connector as the script still needs to `pull`, `commit`, `push`, etc. which seem better done via dolt commands?

I think `dolt sql-client` is fine to use, but I am not sure if I can just supply a query for it to execute?

**Comment by zachmu** [comment]
I don't think `dolt sql-client` works that way, no. You would need to connect to the server with something like the `mysql` command line.

All of those commands are not going work work if a server is running, using a recent dolt.

In the short term, we can give you some setting to let you make changes from the CLI anyway, with the understanding that this may be unsafe / may not be reflected in query results until restart. The other option is for you to rewrite your tooling to issue SQL statements, e.g. `CALL DOLT_COMMIT(...)`

In the longer term, we need to make these CLI commands automatically adapt to the presence of a running server and behave identically to running their equivalent SQL statements on a server.

**Comment by post-no-preference** [comment]
Is there `CALL DOLT_PULL()` `CALL DOLT_PUSH()`?

**Comment by post-no-preference** [comment]
Also, I take it this sort of model will apply to `dolt table import` too?

**Comment by max-hoffman** [comment]
Working on a fix that will give better "error read only" messages in general, and in this case a more specific source for the read only mode.

**Comment by zachmu** [comment]
Yes, most CLI commands are also available as stored procedures (sometimes with limitations)

https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures

`dolt table import` is actually implemented internally as a `LOAD DATA` statement already.

**Comment by max-hoffman** [comment]
@post-no-preference this PR https://github.com/dolthub/dolt/pull/3920 will update the error message for your query:

```bash
 ~/D/d/d/rates> dolt sql -q "insert into us_treasury values ('1990-01-01', null, null, null, null, null, null, null, null, null, null, null, null);"
error on line 1 for query insert into us_treasury values ('1990-01-01', null, null, null, null, null, null, null, null, null, null, null, null): database is locked to writes
database is locked to writes
```

More work will be needed to expose the specific write lock path to the engine, but hopefully this is more useful than the `not authorized` error before.

**Comment by post-no-preference** [comment]
Ok. I think I will refactor my code to make use of the stored procedures and do all of my dolt interaction through `dolt sql-server`. Thanks all.
