### ISSUE TITLE
'dolt push' should have output for an empty database

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#392]
Since this branch is empty no chunks are pushed, however, we should inform the user that the newly created branch has been pushed:
```
[oscarbatori:scratch] >> dolt branch my-changes
[oscarbatori:scratch] >> dolt checkout my-changes
Switched to branch 'my-changes'
[oscarbatori:scratch] >> dolt push origin my-changes
```

**Comment by zachmu** [comment]
Chunks are pushed (the initial commit makes it), but no output appears in the terminal. It should have a message of some sort.

**Comment by Dbhardwaj99** [comment]
Hey, Is this issue still open? would love to contribute

**Comment by timsehn** [comment]
Yes. Still open. Contributing guide is here:

https://docs.dolthub.com/guides/contributing

The behavior should match what git does when you push an empty branch.

**Comment by timsehn** [comment]
Resolved
```
test-replace-count $ dolt push --set-upstream origin main
Uploaded 300 B of 300 B @ 1.96 kB/s.
```
