### ISSUE TITLE
granting all privileges leads to syntax error

### ISSUE THREAD

**Issue by tsonglew** [dolthub/dolt#3948]
creating user and granting select to the user works fine, but granting all privileges to the user failed.

```sql
mysql> CREATE USER 'dolt'@'%' IDENTIFIED BY 'dolt';
mysql> GRANT SELECT ON *.* TO 'dolt'@'%';
mysql> GRANT ALL PRIVILEGES  ON *.* TO 'dolt'@'%';
Error 1105: syntax error at position 22 near 'PRIVILEGES'
```

**Comment by fulghum** [comment]
Hey @tsonglew, thanks for reporting this gap. We'll dig in and take a look at extending the syntax to support this.

**Comment by timsehn** [comment]
> creating user and granting select to the user works fine, but granting all privileges to the user failed.
> 
> ```sql
> mysql> CREATE USER 'dolt'@'%' IDENTIFIED BY 'dolt';
> mysql> GRANT SELECT ON *.* TO 'dolt'@'%';
> mysql> GRANT ALL PRIVILEGES  ON *.* TO 'dolt'@'%';
> Error 1105: syntax error at position 22 near 'PRIVILEGES'
> ```

If you leave off `PRIVILEGES` and just do:

```
GRANT ALL ON *.* TO 'dolt'@'%';
```

This will work.

**Comment by timsehn** [comment]
We should implement `ALL PRIVILEGES` in addition to `ALL` ASAP since it is in all the high ranked online examples.

**Comment by zachmu** [comment]
This is fixed in source. We'll close this when it's in a release.

**Comment by timsehn** [comment]
Gonna close so we don't forget to when we release.
