### ISSUE TITLE
Panic in SQL when WHERE clause uses computed column

### ISSUE THREAD

**Issue by bheni** [dolthub/dolt#397]
This is not supported in SQL, and it should be an error... But it shouldn't panic.

```
~/datasets/irs-new>dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
doltsql> SELECT return_count - joint_count AS non_joint_count FROM allagi WHERE non_joint_count > 3;
panic: unresolved column is a placeholder node, but Type was called
```

**Comment by zachmu** [comment]
Currently aliases are treated as valid in the where clause, which is also wrong. Going to file that as a new bug, since this is no longer relevant.

https://github.com/dolthub/go-mysql-server/issues/525
