### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by ZeitgeberH** [dolthub/dolt#3970]
mysql> START TRANSACTION WITH CONSISTENT SNAPSHOT;
Error 1105: syntax error at position 23 near 'WITH'

**Comment by timsehn** [comment]
We don't support `TRANSACTION WITH`. Can you just change it to a standard BEGIN?

**Comment by bpf120** [comment]
Hi @ZeitgeberH, we'd love to learn about your use case. Swing by our [Discord](https://discord.com/invite/RFwfYpu) or shoot me an [email](mailto:brianf@dolthub.com)if you want to share. Thanks!

**Comment by ZeitgeberH** [comment]
Both `START TRANSACTION` or `BEGIN` works. 
Thanks!

**Comment by timsehn** [comment]
For anyone stumbling on this later, Dolt only supports one transaction isolation level REPEATABLE READ. Thus, we don't support specifying transaction isolation levels using the syntax in this issue.

If the SQL is generated by a tool you don't control and need it fixed. Please create a new issue and we'll make the syntax parse and drop a warning in the server logs that we don't support transaction isolation levels. That is, if you get here before we implement different transaction isolation levels :-)
