### ISSUE TITLE
Unsupported syntax: more than one expression in COUNT

### ISSUE THREAD

**Issue by pbowyer** [dolthub/dolt#3978]
The Dolt manual shows `COUNT()` with full MySQL support, but in practice it errors with the following query:
```sql
SELECT COUNT(DISTINCT `modDbRegisterMessage`.`topic`, `modDbRegisterMessage`.`id`) 
FROM `register_messages` AS `modDbRegisterMessage` 
WHERE ( `modDbRegisterMessage`.`topic` = 1 AND `modDbRegisterMessage`.`id` = '...' )
```

**Comment by fulghum** [comment]
Thanks for reporting this @pbowyer. I've asked @JCOR11599 to take a look at this one for you.

**Comment by max-hoffman** [comment]
@JCOR11599 merged the fix for this last night @pbowyer, it will fold into the next Dolt release. Let us know if you find any other syntax discrepancies!

https://github.com/dolthub/go-mysql-server/pull/1143
