### ISSUE TITLE
Verbose mode with table import

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#3990]
It would be great to have a "verbose" flag with table import so that it would dump things like rows that were not imported or had no effect.

**Comment by timsehn** [comment]
This is fixed in: https://github.com/dolthub/dolt/pull/3861

**Comment by ericmock** [comment]
That's not what I meant by "verbose mode."  I meant -vvvv verbose mode.
E.g., showing the actual rows that weren't imported because of duplicate keys or whatever...  it would be something you'd redirect to a file for inspection.
