### ISSUE TITLE
Add support for case-sensitive text in ENUM options

### ISSUE THREAD

**Issue by dlscanada** [dolthub/dolt#3991]
It appears that `dolt sql-server` cannot create case-sensitive (i.e., upper-case) ENUM options. 

## Reproduce
1. Run the follow `CREATE TABLE` command.
```sql
CREATE TABLE `test_table` (
  `LSD` char(18) NOT NULL,
  `QSEC` enum('SE','SW','NE','NW') NOT NULL
  PRIMARY KEY (`LSD`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='Test table';
```
2. Reload the table columns view in DBeaver. 
3. See that all the enum options show as lower-case (like `enum('se','sw','ne','nw')`), when viewed from the table columns list.
4. After inserting some rows with uppercase values, it appears that they show as upper case in the actual table view.

## Notes/Environment
* DBeaver 22.1.3
* Windows 10
* Dolt v0.40.10

**Comment by VinaiRachakonda** [comment]
Thank you for the bug @dlscanada! We will take a look at this as soon as possible.

**Comment by fulghum** [comment]
Another customer request for enum case preservation with enums in https://github.com/dolthub/go-mysql-server/issues/1161. Also a good callout in that issue that the enum naming doesn't appear to match MySQL's behavior.

**Comment by fulghum** [comment]
Hey @dlscanada, just wanted to let you know that [Dolt 0.40.26 was just released this afternoon](https://github.com/dolthub/dolt/releases/tag/v0.40.26), and contains this fix.  

Thanks for taking the time to report this. Please don't hesitate to cut us more issues if you notice anything else odd!
