### ISSUE TITLE
[Feature Request] use a recursive cte result in an update

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4025]
Dolt supports using a recursive cte in a select statement, for example:

```
with recursive cte (...) as (...)
select * from cte
```

What I need is to use the result of the recursive cte in an update statement, for example:

```
with recursive cte (id) as (...)
update mytable set field = 'value' where id in cte;
```

Another example/reference: https://dba.stackexchange.com/questions/299017/update-rows-based-on-a-recursive-cte-query-result

**Comment by zachmu** [comment]
Building here:

https://github.com/dolthub/dolt/pull/4045

**Comment by dphil** [comment]
I've had a chance to test this out, and it is working as expected. Thanks!
