### ISSUE TITLE
Drop revision database from SQL

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#4031]
I want to drop a database at a commit, but getting a database not found error:
```
mysql> show databases;
+-------------------------------------------+
| Database                                  |
+-------------------------------------------+
| coronavirus                               |
| information_schema                        |
| types                                     |
| types/main                                |
| us_jails                                  |
| us_jails/main                             |
| us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2 |
| us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2 |
+-------------------------------------------+
8 rows in set (0.04 sec)

mysql> drop database `us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2`;
ERROR 1105 (HY000): database not found: us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2
```

Also tried:
```
mysql> drop database 'us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2';
ERROR 1105 (HY000): syntax error at position 58 near 'us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2'
mysql> drop database "us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2";
ERROR 1105 (HY000): syntax error at position 58 near 'us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2'
mysql> drop database us_jails/tjj1kp2mnoad8crv6b94mh4a4jiq7ab2;
ERROR 1105 (HY000): syntax error at position 24 near 'us_jails'
```

Prevents the workaround for [this issue](https://github.com/dolthub/dolt/issues/4030) for hosted instances, where I only have access to the sql server

**Comment by fulghum** [comment]
I'm reworking revision databases a little bit in https://github.com/dolthub/dolt/pull/4102. Zach and I decided to stop showing all revision databases ever used from `show databases` and instead only include the revision database actively being used by the current session. I think that gives revision dbs a cleaner interface and it means we don't have to add extra support for deleting revision dbs – customers can simply `use` another DB and the revision db will not appear in the list of databases anymore.
