### ISSUE TITLE
Sub-select has no access to variable in external scope

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#405]
Repo: https://www.dolthub.com/repositories/Liquidata/corona-virus

This query to fill in NULL values in a time series works in MySQL:

```select distinct a.place_id, a.observation_time, a.confirmed_count, case when a.confirmed_count is not null then a.confirmed_count else (select b.confirmed_count from cases b where b.observation_time < a.observation_time and b.confirmed_count is not null and a.place_id = b.place_id order by b.observation_time desc limit 1) end as confirmed from cases as a order by a.place_id, a.observation_time;```

But fails like so in dolt:

```
timsehn$ dolt sql -q "select distinct a.place_id, a.observation_time, a.confirmed_count, case when a.confirmed_count is not null then a.confirmed_count else (select b.confirmed_count from cases b where b.observation_time < a.observation_time and b.confirmed_count is not null and a.place_id = b.place_id order by b.observation_time desc limit 1) end as confirmed from cases as a order by a.place_id, a.observation_time"
table not found: a, maybe you mean b?
```

It seems that variables in the outer scope are not in scope in the sub-select. 

I need this for a time_series view in that database.

**Comment by timsehn** [comment]
@zachmu is going to spend an hour on this. If he can't fix it, we'll prioritize down the line.

**Comment by zachmu** [comment]
Fixed long ago
