### ISSUE TITLE
Implicit type conversion for `InSubquery`

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4057]
MySQL will implicitly convert types for `InSubquery` nodes, but Dolt doesn't seem to do this. 

**MySQL Behavior:**
```
mysql> select 1 from dual where 1 in (select "1" from dual);
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

**Dolt Behavior:**
```
dolt> select 1 from dual where 1 in (select "1" from dual);
+---+
| 1 |
+---+
+---+
```

This seems to be isolated to `InSubquery` nodes. Another example with an equals operator and a subquery for the left-hand side executes the same on both Dolt and MySQL (`select 1 from dual where 1 = (select "1" from dual);`).

**Comment by JCOR11599** [comment]
fix is merged to main
