### ISSUE TITLE
diff limit flag ignored

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#4078]
No matter what `--limit` value you put, the entire diff will be printed

**Comment by fulghum** [comment]
Hey @CaptainStabs, thanks for opening an issue for this. I did a quick test with dolt version 0.40.25 and wasn't able to see any output difference when I used the `--limit` param either, so it seems like something isn't getting wired up correctly. We'll dig in and see what's up.

**Comment by JCOR11599** [comment]
Hey @CaptainStabs, we're actually debating whether or not to keep this parameter.

How are you using it? and what do you expect to see?
For example, if you had a limit of 1 would you expect to only see diffs for the first table? or the first row? or the first row of every table? or something else?

**Comment by timsehn** [comment]
I think I'm in favor of deprecating it. It's from a time before we supported multiple tables. I don't think it makes sense any more.

If we keep it, I think it should be limited to first N "diffs" because it can be in/out or two lines of the lexically ordered tables.

**Comment by CaptainStabs** [comment]
the diffs are unkillable on windows, and there's literally no point for me to diff 4 million rows

**Comment by timsehn** [comment]
@abmyii made a PR that seems reasonable. I think we need some bats tests but it’s a good start

**Comment by fulghum** [comment]
Thanks for the feedback. That's really helpful to hear why this is useful to you, so I'm on board to keep it (unless we can figure out a way to hit the root cause and make the diff command killable on windows). 

My preference would be that `--limit 1` only includes the first diff row from the first table. That seems a little more intuitive/expected than outputting the first row from every table, but let me know if you feel strongly. (I see @abmyii was voting for first row of every table, so feel free to push on why that interface makes more sense)

@JCOR11599 – can you take a quick stab at this one today?

**Comment by abmyii** [comment]
> I see @abmyii was voting for first row of every table, so feel free to push on why that interface makes more sense

The way I use `dolt diff` is to get a sample of what has changed. Being able to sample the first *x* number of rows from all tables would be really useful especially when multiple have been updated (else you'd only see a sample of the first table). Besides, I think that `dolt diff <table> --limit 1` is a more obvious way of diffing the first row of a specific table.

**Comment by fulghum** [comment]
Awesome feedback @abmyii. Thanks for sharing all that to help us better understand how you're using the tool. I'm convinced!

**Comment by CaptainStabs** [comment]
> Thanks for the feedback. That's really helpful to hear why this is useful to you, so I'm on board to keep it (unless we can figure out a way to hit the root cause and make the diff command killable on windows).
> 
> My preference would be that `--limit 1` only includes the first diff row from the first table. That seems a little more intuitive/expected than outputting the first row from every table, but let me know if you feel strongly. (I see @abmyii was voting for first row of every table, so feel free to push on why that interface makes more sense)
> 
> @JCOR11599 – can you take a quick stab at this one today?

First row is all I care about. Doesn't matter if it's the first row from every table or not.
