### ISSUE TITLE
Restrict `dolt_commit` and `dolt_reset` in read-only mode

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4101]
Dolt CLI commands and SQL stored procedures should respect the read-only setting of the engine and of the database. Some of these are already caught by checks that prevent changes to the working set in read-only mode, but others, like `dolt_commit` and `dolt_reset` need to explicitly check for read-only modes. 

We have [skipped BATS tests for both of these cases](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/sql-server.bats#L234).

**Comment by timsehn** [comment]
This is fixed.
```
$ dolt checkout -b tim/test
database locked by another sql-server; either clone the database to run a second server, or delete the '/Users/timsehn/dolthub/dolt/employees/.dolt/sql-server.lock' if no other sql-servers are active
$ dolt commit -am "test"   
database locked by another sql-server; either clone the database to run a second server, or delete the '/Users/timsehn/dolthub/dolt/employees/.dolt/sql-server.lock' if no other sql-servers are active
$ dolt reset --hard
database locked by another sql-server; either clone the database to run a second server, or delete the '/Users/timsehn/dolthub/dolt/employees/.dolt/sql-server.lock' if no other sql-servers are active
```
