### ISSUE TITLE
Support for date and time literals

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4127]
As with MySQL it would be nice with date and time literals (see https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html) so that queries like the following can be written:

```sql
select *
from orders
where order_date between date '2022-01-01' and date '2022-03-31'
```

**Comment by knutwannheden** [comment]
As a workaround the `CONVERT()` function can be used as in e.g. `convert('2022-01-01', date)`. The `STR_TO_DATE()` function may not work as expected: #4128

**Comment by jycor** [comment]
This is fixed by https://github.com/dolthub/vitess/pull/346
