### ISSUE TITLE
`STR_TO_DATE()` returns `DATETIME` even when just `DATE` is expected

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4128]
The expression `str_to_date('2000-12-31', '%Y-%m-%d')` evaluates to `2000-12-30 23:00:00` in my case (it appears to respect the local time zone) rather than just `2000-12-31` as I think MySQL specifies (see https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date), since the format doesn't include any time parts.

**Comment by timsehn** [comment]
Good bug. Should be a quick fix.

**Comment by jennifersp** [comment]
fixed in https://github.com/dolthub/go-mysql-server/pull/1211
