### ISSUE TITLE
Support `LATERAL` derived tables

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4130]
MySQL 8.0.14 added support for lateral derived tables (see https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-14.html#mysqld-8-0-14-sql-syntax). This is a very useful feature which would be nice to have support for in Dolt.

This may be more work, but since there is now support for `JSON_TABLE()` which is implicitly laterally joined, maybe it is not too far out of reach.

**Comment by knutwannheden** [comment]
Maybe one step closer now with #4340.

**Comment by knutwannheden** [comment]
Yet one step closer with #4534 :-)

**Comment by nicktobey** [comment]
We're tracking progress on this with https://github.com/dolthub/dolt/issues/6194, going to close this as a duplicate.
