### ISSUE TITLE
Support `CAST()` as alternative to `CONVERT()`

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4139]
The `CAST(expr AS type)` function is really equivalent to `CONVERT(expr, type)`, but since `CAST()` is more standard across SQL dialects (AFAIK it is part of the SQL standard), I think it would be nice to also support that.

Note: `CONVERT()` also has other overloads in MySQL which serve slightly different purposes. I haven't tested these in Dolt.

**Comment by fulghum** [comment]
Hey Knut, it looks like we do have some support for `CAST(expr as type)` already, even though our docs say it's not supported: 
```
> select dolt_version();
+----------------+
| dolt_version() |
+----------------+
| 0.40.25        |
+----------------+
> SELECT CAST(5-10 AS SIGNED);
+----------------------+
| CAST(5-10 AS SIGNED) |
+----------------------+
| -5                   |
+----------------------+
> SELECT CAST("14:06:10" AS TIME);
+--------------------------+
| CAST("14:06:10" AS TIME) |
+--------------------------+
| 14:06:10                 |
+--------------------------+
```

I'd bet there are probably some gaps in there though, so it's worth us doing a pass over it, adding some more tests, and then updating the documentation to indicate it's supported. 

If there's a specific data type or use case with `cast` that you need, let us know and we'll prioritize that support first.

**Comment by knutwannheden** [comment]
Right. I never actually tested it. I just read it in the docs and assumed it wouldn't work. But I can confirm that it appears to be working fine (e.g. for the `DATE` type).

**Comment by knutwannheden** [comment]
Note: Starting with MySQL 8.0.22 there is a funky [`CAST(timestamp_value AT TIME ZONE timezone_specifier AS DATETIME[(precision)])`](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast) overload.

**Comment by timsehn** [comment]
Docs PR: https://github.com/dolthub/docs/pull/867 for @Hydrocharged and @fulghum to review.

**Comment by timsehn** [comment]
I'm going to resolve this since we do support it. We noted the differences with MySQL in the docs. If you need more support cut a new, specific bug and we'll get it done.
