### ISSUE TITLE
Window function `ORDER BY` should be optional when frame specification doesn't require it

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4141]
According to the [documentation](https://dev.mysql.com/doc/refman/8.0/en/window-functions-frames.html):
> `RANGE` on a numeric or temporal expr requires `ORDER BY` on a numeric or temporal expression, respectively.

Thus it should be allowed to write a window function like:

```sql
sum(b) over (partition by a range between unbounded preceding and unbounded following)
```

MySQL also accepts this, but Dolt raises an error: `[HY000][1105] a range's order by must be one expression; found: 0`.

**Comment by fulghum** [comment]
Thanks for reporting this one Knut. You're right that Dolt isn't matching MySQL's behavior here. We'll dig in.

**Comment by fulghum** [comment]
Hey @knutwannheden, I got the fix for this one merged into `go-mysql-server` and I'll get Dolt updated with this latest version this afternoon. I'll ping again when this goes out in a Dolt release, likely early next week.

**Comment by fulghum** [comment]
Just closing the loop here... [Dolt 0.40.28 was just released](https://github.com/dolthub/dolt/releases/tag/v0.40.28), and contains this fix. 

Thanks for reporting this one so we could get it fixed! 🙏
