### ISSUE TITLE
Query crashes SQL server

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4173]
The following nonsensical query crashes the server (when starting SQL server via `dolt sql-server`) instead of reporting a user error in the session:

```sql
WITH Numbers AS
          (
              SELECT n = 1
              UNION ALL
              SELECT n + 1
              FROM Numbers
              WHERE n+1 <= 10
          )
 SELECT n
 FROM Numbers;
```

**Comment by max-hoffman** [comment]
When we get to this, we should fix either by enforcing a max nested CTE depth, or semantically validating that non-recursive CTE's do not contain self references.

**Comment by fulghum** [comment]
@JCOR11599 – you able to take a look at this one after you finish https://github.com/dolthub/dolt/issues/4200? 

We just need to make sure this can't crash the server anymore. Max's suggestions look good to me. If we can validate that non-recursive CTEs don't contain self references, that seems ideal.

**Comment by JCOR11599** [comment]
@knutwannheden the fix for this has been merged in, and should be available next release (later today).
