### ISSUE TITLE
Support `EXPLAIN EXTENDED`

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4185]
For some reason IntelliJ IDEA's "explain plan" functionality issues `EXPLAIN EXTENDED` statements, even though that `EXTENDED` keyword isn't documented as being part of the syntax: https://dev.mysql.com/doc/refman/8.0/en/explain.html. I suppose IntelliJ must be thinking it is MySQL 5.7, which is aware of that keyword: https://dev.mysql.com/doc/refman/5.7/en/explain.html

I am unsure what Dolt should about this, but it would be nice, if IntelliJ's own functionality can be used rather than manually having to prepend the query with `EXPLAIN`.

**Comment by JCOR11599** [comment]
Fix for this is merged to main, and will be in next release (probably sometime next week).
