### ISSUE TITLE
Set commit message and author while using `@@dolt_transaction_commit`

### ISSUE THREAD

**Issue by andy-wm-arthur** [dolthub/dolt#4204]
[`@@dolt_transaction_commit`](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#dolt_transaction_commit) allows users to automatically create Dolt commits on every SQL transaction commit. However, this API does not expose a way to specify commit message or author for these automated Dolt commits.

**Comment by zachmu** [comment]
We now do this by default for all commits.
