### ISSUE TITLE
Inserting large JSON object in a prepared statement causes panic

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#4211]
Looks like the json blob may be being sent in a prepared statement based on the exception. 

From a customer:

![image](https://user-images.githubusercontent.com/5376236/186937225-bed0e26e-772a-4f2b-a13a-a8e3d75cd9d8.png)

Schema:

https://media.discordapp.net/attachments/910609539957674004/1012738310612996237/unknown.png

**Comment by timsehn** [comment]
The user is trying to enter the JSON through Datagrip.

**Comment by timsehn** [comment]
I tried to repro this using the attached file on a clone of this:
[large-json.txt](https://github.com/dolthub/dolt/files/9434666/large-json.txt)

https://www.dolthub.com/repositories/timsehn/json-diff-example

It fails with this weird error on windows:
```
PS C:\Users\timse\dolthub\dolt-new\json-diff-example> dolt sql --file .\large-json.txt
Error parsing SQL
syntax error at position 2 near '�'
﻿insert into json_example values (1, '{
```

**Comment by timsehn** [comment]
Will try on my Mac later.

**Comment by timsehn** [comment]
This worked on Windows: 
```
PS C:\Users\timse\dolthub\dolt-new\json-diff-example> Get-Content .\large-json.txt | & dolt sql
Query OK, 1 row affected
```

I'll make a new bug for `--file` not working.

This makes me suspect this is prepareds mixing with large JSON.

**Comment by timsehn** [comment]
> ```
> PS C:\Users\timse\dolthub\dolt-new\json-diff-example> dolt sql --file .\large-json.txt
> Error parsing SQL
> syntax error at position 2 near '�'
> ﻿insert into json_example values (1, '{
> ```

This was due to a BOM character generated by Notepad in Windows. That's why `Get-Content` could handle it in powershell.

**Comment by timsehn** [comment]
Interesting. This python script using prepared statments was able to perform the insert. Renamed to `.txt` so GitHub would take it.

[prepared-insert-json.py.txt](https://github.com/dolthub/dolt/files/9436630/prepared-insert-json.py.txt)

**Comment by timsehn** [comment]
I was also able to insert a very large json blob from latest datagrip:

![image](https://user-images.githubusercontent.com/5376236/186999934-f777f2a4-e70a-4e9d-bc09-a00be6a52764.png)

Interestingly, it came through to Dolt as not a prepared statement. How did you make the query in datagrip?

**Comment by timsehn** [comment]
Gonna close unless I get more information.

**Comment by prodoelmit** [comment]
Couldn't reproduce on 0.50.3 now
