### ISSUE TITLE
Optimize `dolt_diff` system table access when scoped to a commit

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#4232]
A customer reports these two queries take 10s of seconds to run:

1. `SELECT * FROM dolt_diff WHERE commit_hash='ubsn3nfu3mmhdskegb1kpva9moqvtccu';`
2. `SELECT table_name FROM dolt_diff WHERE commit_hash='ubsn3nfu3mmhdskegb1kpva9moqvtccu';`

That has to be because we're not indexing the table by `commit_hash`.

**Comment by timsehn** [comment]
Confirmed full table scan.

```
json-diff-example $ dolt sql -q "explain select * from dolt_diff where commit_hash='6dp7ffcbbd25qfm7duebfmb4q002ukdj'"
+------------------------------------------------------------------------+
| plan                                                                   |
+------------------------------------------------------------------------+
| Exchange                                                               |
|  └─ Filter(dolt_diff.commit_hash = '6dp7ffcbbd25qfm7duebfmb4q002ukdj') |
|      └─ Table(dolt_diff)                                               |
+------------------------------------------------------------------------+
```

**Comment by fulghum** [comment]
@jennifersp – can you pick this one up? To optimize for `commit_hash` we could use FilteredTable's interface to push the filter down to the table and only pull the commits needed. Let's start with that and then separately we can see if there are other columns (e.g. `table_name`) that we want to tackle that might require a physical index.

**Comment by timsehn** [comment]
https://github.com/dolthub/dolt/pull/4243 in the works to fix this.
