### ISSUE TITLE
Support `LAST_VALUE()` and `LEAD()` window functions

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4260]
Dolt now already has very good support for window functions. Of the remaining few standard window functions I think the `LAST_VALUE()` and `LEAD()` functions would be very valuable to also have support for.

**Comment by knutwannheden** [comment]
Well, kudos to *you all* for your responsiveness, successful community building and the fast-paced development of an exciting product!

**Comment by timsehn** [comment]
I think @JCOR11599 could bang these out in an afternoon.

**Comment by JCOR11599** [comment]
These two window functions have been merged to main, and should be available next release either later this week or early next week.
Let us know how they work for you!
