### ISSUE TITLE
sum() of decimal types with negative numbers is incorrect

### ISSUE THREAD

**Issue by NadiaSama** [dolthub/dolt#4269]
blow is the test to reproduce  problem
```bash
# test data
mysql -uroot -h 127.0.0.1 -P 3310 mydb -e 'select * from my_table'
+------+---------------------+
| id   | val                 |
+------+---------------------+
|    1 | -2.5633000000000384 |
|    2 |  2.5633000000000370 |
|    3 |  0.0000000000000004 |
+------+---------------------+

# quey sum(val)
mysql -uroot -h 127.0.0.1 -P 3310 mydb -e 'select sum(val) from my_table'
+------------------------+
| sum(val)               |
+------------------------+
| -9.322676295501879e-16 |
+------------------------+
```

if running the same test against mysql-server(v5.7.34) 
```bash
+---------------------+
| sum(val)            |
+---------------------+
| -0.0000000000000010 |
+---------------------+
```

**Comment by timsehn** [comment]
I can repro:
```
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt init --new-format
Successfully initialized dolt data repository.
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt version
dolt version 0.40.29
database storage format: NEW ( __DOLT__ )
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "create table t (pk int primary key, c1 int, c2 double)"
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "insert into t values (0, -1, -1.00076), (1, 1, 1.00073), (2, 0, 0.000006)"
Query OK, 3 rows affected
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select * from t"
+----+----+----------+
| pk | c1 | c2       |
+----+----+----------+
| 0  | -1 | -1.00076 |
| 1  | 1  | 1.00073  |
| 2  | 0  | 6e-06    |
+----+----+----------+
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select sum(c1) from t"
+---------+
| sum(c1) |
+---------+
| 0       |
+---------+
PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select sum(c2) from t"
+-------------------------+
| sum(c2)                 |
+-------------------------+
| -2.4000000000196536e-05 |
+-------------------------+
```

**Comment by jennifersp** [comment]
Hi @NadiaSama, thank you for the issue and repro. I was able to reproduce the issue but specifically for DECIMAL data type column. I'm working on the fix now.

**Comment by timsehn** [comment]
> I can repro:
> 
> ```
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt init --new-format
> Successfully initialized dolt data repository.
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt version
> dolt version 0.40.29
> database storage format: NEW ( __DOLT__ )
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "create table t (pk int primary key, c1 int, c2 double)"
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "insert into t values (0, -1, -1.00076), (1, 1, 1.00073), (2, 0, 0.000006)"
> Query OK, 3 rows affected
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select * from t"
> +----+----+----------+
> | pk | c1 | c2       |
> +----+----+----------+
> | 0  | -1 | -1.00076 |
> | 1  | 1  | 1.00073  |
> | 2  | 0  | 6e-06    |
> +----+----+----------+
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select sum(c1) from t"
> +---------+
> | sum(c1) |
> +---------+
> | 0       |
> +---------+
> PS C:\Users\timse\dolthub\dolt-new\test-sum> dolt sql -q "select sum(c2) from t"
> +-------------------------+
> | sum(c2)                 |
> +-------------------------+
> | -2.4000000000196536e-05 |
> +-------------------------+
> ```

This is not a repro. I suck.

@jennifersp was able to repro the problem with decimals.

**Comment by NadiaSama** [comment]
> Hi @NadiaSama, thank you for the issue and repro. I was able to reproduce the issue but specifically for DECIMAL data type column. I'm working on the fix now.

yes in my test VAL column is decimal type. i forgot to mention it

**Comment by bpf120** [comment]
Hi @NadiaSama, are you using Dolt too or just go-mysql-server? We like to learn about use cases :). Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.com/invite/RFwfYpu) if you want to share.

**Comment by NadiaSama** [comment]
> Hi @NadiaSama, are you using Dolt too or just go-mysql-server? We like to learn about use cases :). Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.com/invite/RFwfYpu) if you want to share.

I just use go-mysql-server in my project for test. because it`s a in memory database and support mysql wire protocol make it easy to use in unittest.
