### ISSUE TITLE
Query to revert a single column fails

### ISSUE THREAD

**Issue by nacho53dolt** [dolthub/dolt#4288]
## Steps to Reproduce
1. Checkout [this database](https://www.dolthub.com/repositories/nacho53/us-housing-prices-v2/data/nacho53%2Fimport-1661470932)  with dolt, on this commit: "2fjhtcodn1rhbcsi6sg19ct64vf0cr2d"
2. Start `dolt sql-server`
3. Connect with DBeaver using MariaDB plugin
4. Run the following SQL script, with the intention of reverting the changes in the `building_year_built` column back to the "vlr4co3jnmsomqdimfghqto0948c8q24" commit.
```sql
UPDATE sales
JOIN (SELECT state, property_street_address, sale_datetime, building_year_built FROM sales AS OF 'vlr4co3jnmsomqdimfghqto0948c8q24') AS t
	ON sales.state = t.state AND sales.property_street_address = t.property_street_address AND sales.sale_datetime = t.sale_datetime
SET sales.building_year_built = t.building_year_built;
```
5. Observe the following error:
```
 ambiguous column name "building_year_built", it's present in all these tables: sales, t
```

## Notes
* Maybe it's an alias bug.
* In response to the request in this pull request: https://www.dolthub.com/repositories/dolthub/us-housing-prices-v2/pulls/45

**Comment by timsehn** [comment]
@fulghum is looking at aliases and I think this is an alias bug. The query above looks like it should work to me.

**Comment by fulghum** [comment]
Thanks for reporting this one @nacho53dolt. This does look like an issue with aliases and how we manipulate query plans to get symbols resolved and lined up. I'll dig in today to repro and let you know what I figure out.

**Comment by fulghum** [comment]
I was able to whittle this down into a smaller repro case:

```sql
> CREATE TABLE `sales` (
  `building_year_built` int,
  PRIMARY KEY (building_year_built),
  CONSTRAINT `valid_year_built` CHECK (`building_year_built` <= 2022)
);

> UPDATE sales JOIN (SELECT building_year_built FROM sales) AS t SET sales.building_year_built = 1235;
ambiguous column name "building_year_built", it's present in all these tables: sales, t
```

It's the check constraint in the table that is referencing `building_year_built` that's causing Dolt to get confused. 

Now that I've got a simpler repro, I'll run this through the debugger this afternoon and see how we can get this query working.

**Comment by fulghum** [comment]
As expected, the check constraint expression is getting loaded into the query plan, but the analyzer doesn't fully qualify the `building_year_built` column reference. This works fine for the basic `UPDATE` when there isn't any ambiguity, but when the same table is joined on itself, the analyzer can't disambiguate it. 

I coded up a quick change yesterday to set the name of the table when the check expressions get loaded in and verified that this query executes correctly after that, but it doesn't take into account any table aliases, so it's not ready to check in yet. Today, I'll look for a clean way to cross-check with table aliases, add some tests, and should be able to get this fix out to review.

**Comment by timsehn** [comment]
@nacho53dolt if you want the query to work you can just drop the check constraint and add it back after you run your query.

**Comment by fulghum** [comment]
I ran into a couple more bugs along the way with this one, but the linked PR has everything to make this query work correctly. I want to do a little more testing with the Dolt test suite, then I'll move it into review. 

If you need more help with a workaround until this fix gets released, like Tim mentioned above, just let us know; we're happy to help.

**Comment by fulghum** [comment]
I've got the fix reviewed and merged into go-mysql-server and Dolt. This will go out in our next Dolt release, likely in the next day or two. I'll update one more time and resolve this issue once the fix is released. 

In the meantime, let me know if you're still having any problems getting the data reverted and we're happy to help.
