### ISSUE TITLE
Specify explicit author in `dolt_merge` procedure

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#4295]
Similar to how you can specify an explicit author in the `dolt_commit` procedure, I want to be able to do something like:
```
CALL DOLT_MERGE('feature-branch', '-no-ff', '-m', 'This is a msg for a non fast forward merge', '--author', 'John Doe <johndoe@example.com>');
```

Right now the merge commit author is `Dolt System Account` and there's no way to change that

**Comment by timsehn** [comment]
@jennifersp just changed the behavior here so I think she is the best to do this. Should be quick.
