### ISSUE TITLE
Feature Request: Way to create db in new format via sql

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4307]
via the CLI, a database can be created in the new format via:
`dolt init --new-format`

When creating a new db via sql (`CREATE DATABASE ...`), the old format is used. When trying to do this programmatically as part of a running application, one could execute a child process to run a dolt cli command, though going through sql can be more convenient.

A few options I see:
1. if the new format becomes the default soon, this may become a moot request (assuming we don't care about dolt users then wanting to be able to create db's in the OLD format via sql)
2. add a database creation option, ex. `CREATE DATABASE customers_new_format DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin DOLT_FORMAT new`. Probably not a great option.
3. An arg for the dolt server telling it which format to use for new db's created through sql clients. Ex. `dolt sql-server --new-format` or `dolt sql-server --create-db-format=new`. This wouldn't be overridable by a client at runtime, but supporting use cases where someone wants to create both old and new format db's in a given running server instance through sql is presumably not a concern.

**Comment by dphil** [comment]
For context, our immediate use case is that our unit tests spin up a new db to run on. They do so by first connecting to the built-in "information_schema" db, then running a `CREATE DATABASE test_db ...` sql command and then opening a connecting to that new db to run the tests.

**Comment by timsehn** [comment]
You can set an environment variable right now. 

`DOLT_DEFAULT_BIN_FORMAT=__DOLT__`

We need a better way to do it. But that should be able to get you going.

**Comment by timsehn** [comment]
I think this also matches the format of the current selected DB.

https://github.com/dolthub/dolt/pull/4193

We may have missed the case where there is no db.

**Comment by dphil** [comment]
> You can set an environment variable right now.
> 
> `DOLT_DEFAULT_BIN_FORMAT=__DOLT__`
> 
> We need a better way to do it. But that should be able to get you going.

Oh, yes, my mistake, I found where we had discussed this previously. For some reason I thought the env var was just for the `dolt init` command.

Not sure if you wanted to use this issue for anything further, but I'm happy to have it closed otherwise.

**Comment by timsehn** [comment]
I'll let @andrew-wm-arthur and @druvv make the call tomorrow.

**Comment by timsehn** [comment]
We're going to resolve. We have a solution and we're going to deprecate the old format in a month or so.
