### ISSUE TITLE
Add `-A` option to `dolt commit` to add all new and modified tables 

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4309]
We recently changed `dolt commit -a` to match Git's behavior and *not* stage any new tables. It was convenient to have newly created tables added, but we thought it was more important to match Git's behavior exactly. As a compromise, we would like to add a new `-A` option to `dolt commit` that works in the same was as `dolt add -A` – it should stage all newly created and modified tables in the commit. 

This change should be made for the `dolt commit` command, as well as the `dolt_commit` SQL stored procedure.

**Comment by druvv** [comment]
This would be really nice. It's pretty annoying to have to run `dolt add .` or similar any time you add a new table.

**Comment by timsehn** [comment]
Just do it?

**Comment by timsehn** [comment]
![image](https://user-images.githubusercontent.com/5376236/189763429-3fd4f2aa-a3bc-4029-91cc-2d936227b983.png)
