### ISSUE TITLE
UI issue for `dolt diff` and dropped columns

### ISSUE THREAD

**Issue by tanyongzhi** [dolthub/dolt#4326]
When dropping a column, there is different behavior for `dolt diff` depending on the type of column being dropped.

![unknown-1.png](https://user-images.githubusercontent.com/35494233/189828680-df595d6f-896e-41fb-a3ee-dd40cd496521.png)

![unknown.png](https://user-images.githubusercontent.com/35494233/189828702-070aa3c5-79c9-46c6-8141-06acdf00fd08.png)

In both examples, the columns `s` and `val2` are dropped for `varchar` and `int` respectively. Notice that there is a red font color for the `varchar` column, but not for the `int` column.

**Comment by fulghum** [comment]
Major kudos to @tanyongzhi for contributing the fix for this one 🙌  

This is merged into main now and will go out in the next Dolt release in the next few days.
