### ISSUE TITLE
Publish libs that can use Dolt

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#4328]
Hi, I recently found Doltr:

https://github.com/ecohealthalliance/doltr

Is a great tool to use dolt from R, sadly there is no page that tell us this lib exists, and with the time there can be other libs that can helps to improve our experience, so I think would helps hava a page with the libs/tools we can use.

Thx!

**Comment by fulghum** [comment]
Hey @latot, very happy to hear you have found DoltR and are enjoying it! @noamross and his colleagues have done a great job putting that integration together. 👏 

We do have a small mention of DoltR in the docs under [Supported Programmatic Clients](https://docs.dolthub.com/sql-reference/supported-clients/clients#r), but that's admittedly pretty deep in the docs, so I'm not surprised it was difficult to find. Would changing the title in the sidebar to "Supported Clients and Tools" have made finding that info easier? Let us know if you have other feedback on where you expected to see that info.

**Comment by fulghum** [comment]
Awesome feedback @latot; thanks for sharing your perspective. And... you are right... I thought **for sure** I had seen that we already had a link to DoltR in the R section, but it is indeed missing. I'll go fix that right now and will think through the other doc feedback and kick some ideas around.

**Comment by timsehn** [comment]
Resolving this. Thanks for the feedback.
