### ISSUE TITLE
Doltpy v2: Lib to can use Dolt from python

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#4329]
Hi, I think would be great have a python lib, similar to Doltr, where from python we can easily connect to a repository, make commits and have the functionality of Dolt there.

Myabe is good do both, R and Python libs similar, at least to be easy move from one to other and do more simple the use of them in several lanuages.

Actually there is a package called Doltpy, but is deprecated and seems it function was other.

Thx!

**Comment by timsehn** [comment]
We think about this a lot. I think what people want who are not going to use the standard SQL path is a connection to an embedded Dolt in Python. Then you can use a standard Python SQL connector without a running server.

https://www.dolthub.com/blog/2022-07-25-embedded/

**Comment by timsehn** [comment]
I'm going to resolve this. You're feature request is noted but we aren't really focused on language specific clients right now.
