### ISSUE TITLE
Support `--user` and `--password` `sql-server` args even if their is a `config.yaml`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#4333]
This is related to #2755 but an acute case. A customer needs this fixed ASAP.

We need to honor both. 

For the customers use case, this can follow one of the following rules:

1. Only accept the `--user` and `--password` if it's not defined in config.yaml
2. CLI always overrides config.yaml
3. Create both users (ie. append)

I think we should do (1) because it's expedient and is least permissive for now until we get a concrete config design.

**Comment by tiagojufr** [comment]
https://docs.dolthub.com/cli-reference/cli#dolt-sql-server does not document this behavior
