### ISSUE TITLE
Feature Request: Generate JSON_TABLE from table column reference

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4340]
The initial implementation of JSON_TABLE (https://github.com/dolthub/dolt/issues/2163) works with raw json values, but not on a field of another table in the FROM clause. I would've logged this as a bug, but it seems like this was perhaps intentionally not included for a minimal initial scope.

So this request is to add support for queries using a table column reference, as below.

Example query structure:
`select jt.names from oranizations as o, JSON_TABLE(o.members, '$[*]' columns (names varchar(100) path '$')) as jt;`

Where the organizations table looks like:
```
organization   |    members (json)
-------------------------------------
"orgA"         |    '["bob", "john"]'
"orgB"         |    '["alice", "mary"]'
```

Expected output:
```
names
---------
"bob"
"john"
"alice"
"mary"
```

The above query works in mysql, but currently in Dolt a query of this structure produces the error:
`table not found: jt`
ie in the FROM clause it doesn't recognize the JSON_TABLE alias, making this form of query not possible.

**Comment by dphil** [comment]
Adding extra context to my current need below to make sure the use case is fully covered.

The full query I'd need would be structured as follows: 
`SELECT jt.names, COUNT(jt.names) AS count FROM organizations AS o, JSON_TABLE(o.members, '$[*]' COLUMNS (names varchar(100) path '$')) AS jt GROUP BY jt.names ORDER BY jt.names asc;`

So for an org table like this:
```
organization   |    members (json)
-------------------------------------
"orgA"         |    '["bob", "john"]'
"orgB"         |    '["alice", "mary"]'
"orgC"         |    '["kevin", "john"]'
"orgD"         |    '["alice", "alice"]'
```

The output would be:
```
names   |  count
-------------------
"alice" |   3
"bob"   |   1
"john"  |   2
"kevin" |   1
"mary"  |   1
```

**Comment by timsehn** [comment]
Just talked to @JCOR11599 about this one. It's hard. In MySQL, it's a special analyzer rule and they only supoort that one syntax :-) Still trying for Friday but likely more realistic is next week.

**Comment by JCOR11599** [comment]
Just updating y'all on the issue.
I've made some decent progress on it over the past two days, and the queries listed above appear to be working the same as MySQL.

```shell
tmp> select * from organizations;
+--------------+-------------------+
| organization | members           |
+--------------+-------------------+
| orgD         | ["alice","alice"] |
| orgA         | ["bob","john"]    |
| orgC         | ["kevin","john"]  |
| orgB         | ["alice","mary"]  |
+--------------+-------------------+
4 rows in set (0.01 sec)

tmp> select jt.names from organizations as o, JSON_TABLE(o.members, '$[*]' columns (names varchar(100) path '$')) as jt;
+-------+
| names |
+-------+
| alice |
| alice |
| bob   |
| john  |
| kevin |
| john  |
| alice |
| mary  |
+-------+
8 rows in set (0.00 sec)

tmp> SELECT jt.names, COUNT(jt.names) AS count FROM organizations AS o, JSON_TABLE(o.members, '$[*]' COLUMNS (names varchar(100) path '$')) AS jt GROUP BY jt.names ORDER BY jt.names asc;
+-------+-------+
| names | count |
+-------+-------+
| alice | 3     |
| bob   | 1     |
| john  | 2     |
| kevin | 1     |
| mary  | 1     |
+-------+-------+
5 rows in set (0.00 sec)

```

However, there still needs to be some more testing done when the `JSON_TABLE` queries involve more complicated `JOIN`s (such as `LEFT`, `RIGHT`, `INNER`, `INDEXED`), subqueries, ctes, etc.
So most likely this will be finished early next week. Thanks for your patience.

**Comment by JCOR11599** [comment]
Another update, the fix is merged to main. Expect a release later today!

**Comment by JCOR11599** [comment]
Release with is out!
