### ISSUE TITLE
Better build instructions

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#4342]
Hi all, I have read this doc:

https://docs.dolthub.com/introduction/installation/source

I think this instructions can have an improvement, a compile phase where we generate the bin and other one to install, is not ideal a build process that do things out of the compilation folder like gen a file in ```~```.

Actually I'm doing this:

```
git clone git@github.com:dolthub/dolt.git
cd dolt/go && go build "./cmd/dolt"
```

Dolt seems to be in ```dolt/go/dolt``` after build.

In the original instructions there is the folders ```./cmd/git-dolt``` and ```./cmd/git-dolt-smudge```, maybe in the time the doc was written that folders existed, now there is only ```dolt``` folder.

Thx!

**Comment by timsehn** [comment]
Yes. We deprecated `git-dolt`. I'lll update the docs.

**Comment by timsehn** [comment]
We want you to install the binary and for it to be in your path naturally. That's what `go install` does as opposed to `go build`. We're going to keep that part :-)

**Comment by timsehn** [comment]
Resolved by: https://github.com/dolthub/docs/pull/921

**Comment by latot** [comment]
Thx! I suggest to write a section for "local fast install" and other for "compilation" and "system install", I think I just ends confused when checking a compilation section that compile and install at the same time.
