### ISSUE TITLE
Is there a way to release momory？

### ISSUE THREAD

**Issue by mango-lzp** [dolthub/dolt#4349]
we use dolt to control our language version for test and development。in production environment it become so large. 
![image](https://user-images.githubusercontent.com/41472923/190338956-3404325a-1c9e-49ef-87d9-79dc0c6c0184.png)
how can I make it took a little less?
I tried to export data and delete branch, but it seems do not help.

**Comment by timsehn** [comment]
I think you need to "garbage collect" using `dolt gc`: https://docs.dolthub.com/cli-reference/cli

Dolt makes a lot of disk garbage. This is safe to run on a weekly basis or so.

**Comment by timsehn** [comment]
Reopen if that does not solve your issue. We'd also love to learn more about your use case. You can email me at tim@dolthub.com or pop over to [our discord](https://discord.com/invite/RFwfYpu).

**Comment by mango-lzp** [comment]
It works fantastic, I will follow your advice to run "dolt gc" once a week.
Thanks a lot!
![1663298732113_536668F1-965B-4556-8345-59F13A687043](https://user-images.githubusercontent.com/41472923/190550824-9d89c4eb-f0f1-4799-b3c6-92a125a95bde.png)

But why doesn't it do 'gc' automatically
