### ISSUE TITLE
Writes using branch reference syntax (ie. `<db>/<branch>`) should fail

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#4352]
Dolt's transaction logic assumes all changes are on a single branch, the currently checked out one for the session. But there's a loophole:

```sql
update `mydb/otherbranch`.mytable set foo = baz;
```

This behavior is undefined and won't work correctly on `commit`. These databases should be read-only in this context, and these writes should fail the same way they do on read-only databases.

**Comment by timsehn** [comment]
So this is fixed and replace by #5314
