### ISSUE TITLE
Add support for `--graph` option in `dolt log`

### ISSUE THREAD

**Issue by nacho53dolt** [dolthub/dolt#4367]
One of my favourite git commands in git is `git log --oneline --graph`, which shows really effectively how all the different merges/pull requests/commits/branches fit together. 

Currently, the `--graph` option is not supported in dolt. I know it may not be a high priority, but it is ultimately something I'd love to see.

This issue is a prerequisite issue for #4357 (`dolt la` alias fails).

**Comment by liuliu-dev** [comment]
Hi @nacho53dolt,

I want to let you know that `--graph` is now supported! I'm currently working on the `--online` flag and will keep you updated on the progress. :)
