### ISSUE TITLE
`dolt fetch upstream main` fails on VPS with 1GB RAM

### ISSUE THREAD

**Issue by nacho53dolt** [dolthub/dolt#4373]
## Reproduce Instructions
These work on a computer with sufficient resources, but fail on a computer with very little RAM (like a VPS).

The following is a dump of the `history` command for my ease.
```bash
 1079  dolt clone nacho53/us-housing-prices-v2
 1080  dolt remote add upstream dolthub/us-housing-prices-v2
 1081  ls
 1082  cd us-housing-prices-v2/
 1083  ls
 1084  dolt remote add upstream dolthub/us-housing-prices-v2
 1085  dolt fetch upstream
 1086  df -h
 1087  free -h
 1088  dolt fetch upstream
 1094  echo dolt sucks on low memory - open ticket later
```

## Result
```
~/us-housing-prices-v2$ dolt fetch upstream
Downloaded 19,955 chunks, 70 MB @ 1.18 MB/s.
Killed
```

## Comments
I know this is an edge case, running dolt on such a low resource system, but it has sufficient swap space available, so I don't feel as though it should be killed in such a case.

## System
* Ubuntu 20.04.05 LTS
* RAM: 1 GiB
* Swap: 4 GiB
* Cores: 1
* Dolt Version: 0.41.4

**Comment by timsehn** [comment]
This is kind of expected. Dolt needs approximately 1% of the database size to put the commit graph and associated metadata in memory.

I'm going to close because we don't have any plans to fix this in the near term.

**Comment by nacho53dolt** [comment]
Why can't it use swap space to store the commit graph? The NVMe swap on this server is faster than the RAM on my home computer, if I'm being honest.
