### ISSUE TITLE
Random failure during push, when folder is on removable media

### ISSUE THREAD

**Issue by nacho53dolt** [dolthub/dolt#4380]
It appears that my USB controller temporarily disconnects for miliseconds at a time.

The following issue happens:
```
dolt push -u origin us_main
Uploaded 3.3 GB of 4.2 GB @ 4.67 kB/s.
error: push failed
cause: unknown push error; read D:\us-housing-prices-v2\.dolt\noms\pl5mbu5t1sk4efg54tv0dgprbm1errsi: The volume for a file has been externally altered so that the opened file is no longer valid.
```

## Solution
On error, do an expo backoff retry for up to 1 second/10 tries (or similar) for any filesystem error.

## System
* Windows 10
* D: is a USB removable drive, connected through a USB hub on a single-USB-port system (which sucks)
* Dolt v0.41.4

**Comment by fulghum** [comment]
Thanks for reporting this @nacho53dolt. We have some higher priority issues in flight currently, but this is a good one to have tracked as an issue.

**Comment by timsehn** [comment]
I'm going to resolve this. We're not going to realistically debug or fix it.
