### ISSUE TITLE
Bindvars not filled in for procedure calls

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#4392]
https://github.com/dolthub/dolt/blob/main/integration-tests/mysql-client-tests/node/concurrency.js#L50

```javascript
        await conn.execute(`call dolt_commit('-am', 'created author ?')`, [name]);
```

The commit message in the log contains the bindvar placeholder (`?`) instead of the value of the bindvar.

**Comment by JCOR11599** [comment]
Added a tests for preparing `call dolt_commit`, also fixed script to use bindvar correctly.
