### ISSUE TITLE
JSON default column normalization issue causing merge conflict

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4406]
Customer ran into a schema conflict on a JSON column that defines a default value. The repro is still being investigated.

**Comment by druvv** [comment]
The specific error message reported by the customer is:
```
ERROR 1105 (HY000): schema conflict found, merge aborted. Please alter schema to prevent schema conflicts before merging.
schema conflicts for table $table:
	different column definitions for our column $col and their column $col
```

This error is thrown when $col has changed in both branches with differring schema. The type of $col must not have been changed otherwise a new tag would have been generated. The factors that affect column equality are tag, type, primary key membership, column constraints, and the column's default value.

I focused on trying to produce a situation where the column's default value looks identical in the information schema, but is not equivalent in dolt merge.

The first thing I checked was to see if information schema normalized the json value when being printed. But that is not the case. I created a json column with the default of `{"hi": 1}` on one branch and `{"hi":  1}` (an extra space) on another branch. A conflict was thrown when merged, but the information schema also showed the extra space.

I also investigated how the column defaults are being pulled from postgres, but in the end couldn't find anything obviously wrong.

**Comment by druvv** [comment]
Here is the minimal repro:

```bash
dolt init
dolt sql -q "create table t (pk int PRIMARY KEY);"
dolt commit -Am "add table t"
dolt branch right
dolt sql <<SQL
alter table t add column col1 json default ('{"test":1}');
SQL
dolt commit -am "add default"

dolt checkout right
dolt sql <<SQL
alter table t add column col1 json default ("{\"test\": 1}");
SQL
dolt commit -am "right"

dolt checkout main
dolt merge right
```

Returns the following error:
```
Updating c5d347orbrdk8gpo5l1fmlhvoss2nl3p..9mdpreapepser1gv5tvf85hfhvob3lmc
Unable to stage changes: add and commit to finish merge
error: Failed to commit changes.
cause: schema conflict found, merge aborted. Please alter schema to prevent schema conflicts before merging.
       schema conflicts for table t:
       	different column definitions for our column col1 and their column col1
```

If we inspect the schema on branch main, and right we see that they are identical:
```
> dolt checkout right
> dolt sql -q "show create table t;"
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                         |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `pk` int NOT NULL,
  `col1` json DEFAULT ('{"test": 1}'),
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

> dolt checkout main
> dolt sql -q "show create table t;"
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                        |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `pk` int NOT NULL,
  `col1` json DEFAULT ('{"test":1}'),
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by druvv** [comment]
Investigating further, the customer's database clearly shows two different values in storage. On one branch the value is `("{\"free\": 1}")` and on another the value is `('{"free": 1}')`. 

We iterated on a couple different sql statements on the latest Dolt and version v0.41.5 (which is prior to a recent change in the area) and could not get the value in storage to equal `("{\"free\": 1}")`. The string is formatted to `('{"free": 1}')` in the latest version before being put into storage.

The fix for now, is to re-set the column default. 
```bash
dolt sql <<SQL
ALTER TABLE $table_name ALTER COLUMN $col_name SET DEFAULT ('{"free": 1}');
SQL
```

If necessary, a filter-branch query could be useful to rewrite the column default value in storage across all commits in the history.

**Comment by timsehn** [comment]
I'm going to resolve this because it's a compatibnility with really old versions bug.
