### ISSUE TITLE
Unicode error running a utf8mb4 MySQL database export

### ISSUE THREAD

**Issue by societal-sandpaper** [dolthub/dolt#4419]
I have the following two SQL files (linked below) which describe a few tables, then add rows to them. The files are, as far as I can tell, standard unicode, and should work with dolt/MySQL.

Run `dolt sql < fiction_ddl.sql`, then `dolt sql < fiction_line1230.sql` and see the error:

```
dolt sql < ../fiction_line1230.sql

error executing query on line 1: "BlobString(utf8mb4_bin, 4194303)" cannot convert value "<h3>Kurzbeschreibung</h3><p>Mit dem internationalen Karlspreis hat der Kanzleivorsteher Tobias Grundler nicht viel im Sinn. ('Dann doch lieber zum Tivoli.'). Das ändert sich schlagartig, als er gemeinsam mit seinem Chef und Freund, dem Aachener Rechtsanwalt Dr. Dieter Schulz gezwungenerma�en von der Polizei eingespannt wird, um eine Anschlagsserie Rechtsradikaler und vermutetes Attentat auf den neuen Karlspreisträger, den britischen Premierminister, zu verhindern. </p> ϡ쯦���ᮥ�" of type "string" as it is invalid
```

## Shared File List
The following files were shared as attachments to this issue (renamed from .txt to .sql):
* `fiction_ddl.sql`: a few `CREATE TABLE` statements and other similar METADATA. Disregard all the locks and unlocks.
* `fiction_line1235.sql`: an `INSERT` statement which works fine (no failures)
* `fiction_line1230.sql`: a similar `INSERT` statement which **fails reliably**

[fiction_line1235.txt](https://github.com/dolthub/dolt/files/9660820/fiction_line1235.txt)
[fiction_line1230.txt](https://github.com/dolthub/dolt/files/9660821/fiction_line1230.txt)
[fiction_ddl.txt](https://github.com/dolthub/dolt/files/9660822/fiction_ddl.txt)

## Context
The files are from the Libgen database dumps: https://libgen.rs/dbdumps/ (specifically, the fiction one).

## Version
dolt v0.41.5

**Comment by timsehn** [comment]
I'm gonna try and repro and get some insight.

**Comment by timsehn** [comment]
On the tip of main I think this works:
```
$ dolt init --new-format
Successfully initialized dolt data repository.
$ dolt sql < fiction_ddl.txt 






$ less fiction_ddl.txt 
$ dolt ls
Tables in working set:
	 fiction
	 fiction_description
	 fiction_hashes

$ dolt sql < fiction_line1235.txt 
Query OK, 948 rows affected (0.07 sec)
$ dolt sql < fiction_line1230.txt 
Query OK, 872 rows affected (0.07 sec)
```

**Comment by timsehn** [comment]
When I `less` the file, it does have some unicode strings in there but it seemed to be able to make it into the DB fine.

**Comment by societal-sandpaper** [comment]
The issue appeared to be that I was doing `dolt init` instead of `dolt init --new-format`. When I do exactly what you did, I don't have any issues. Is there a reason that `dolt init` doesn't use the new format by default? 

That was a lot of wasted time reporting a bug that has already been fixed. :(

**Comment by timsehn** [comment]
It looks like the old format has something messed up in it with UTF-8 character storage. The new format is going default this week. 

I'm so sorry that we wasted your time :-(

**Comment by timsehn** [comment]
It's definitely still a bug that it doesn't work on the old format and we're investigating. So, we appreciate the bug report even though it was an easy fix.

**Comment by Hydrocharged** [comment]
The old format doesn’t really have direct support for character sets and collations. It “works” as most of the code handling it is in GMS, but there are situations that involve the storage layer (Dolt) where the old format fails. Due to the work involved (and that the new format is becoming the default anyway), the decision was made to completely ignore the old format, and it shouldn’t be any worse off than it was before the collation support.

**Comment by zachmu** [comment]
Thanks for the report @societal-sandpaper, sorry you ran into this. You caught us just as we're in the middle of making the new format that doesn't have this bug the default -- it's been in development for most of the year and is just now getting declared totally production ready. We're flipping that switch later this week. In the meantime, the flag on `dolt init` you already discovered is what you want.

Please let us know if you run into any other issues using the new format.
