### ISSUE TITLE
Collation Coercibility

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#4428]
Currently, collation coercibility is approximated using an incorrect implementation. There are many instances where we will use the wrong collation or outright fail when we should succeed. A full implementation would require quite a bit of development time, therefore this issue is simply tracking that it needs to get done at some point.

Refer to the following MySQL page for more information:
https://dev.mysql.com/doc/refman/8.0/en/charset-collation-coercibility.html

**Comment by timsehn** [comment]
@Hydrocharged is working on this now.
