### ISSUE TITLE
Question on REPLACE with trigger

### ISSUE THREAD

**Issue by joel-rieke** [dolthub/dolt#4435]
I am wondering if the REPLACE INTO query works in dolthub to create the appropriate trigger behavior (before/after DELETE then before/after INSERT).  Looking at some behavior I'm not seeing some of my triggers activate.  Does anyone know if this has been implemented?

**Comment by joel-rieke** [comment]
I've seen triggers activate before for other cases, but just not for REPLACE INTO.  The query itself works fine, I just don't see the triggers activated.

**Comment by timsehn** [comment]
Repro?

**Comment by bpf120** [comment]
Hi @joel-rieke, We'd love to learn more about your use case too. Feel free to swing by our [Discord](https://discord.com/invite/RFwfYpu) or shoot me an [email](mailto:brianf@dolthub.com) if you want to share.

**Comment by timsehn** [comment]
I can use replace into in triggers:
```
$ dolt init
Successfully initialized dolt data repository.
$ dolt sql -q "create table t1 (id int, c1 int)"
$ dolt sql -q "create table t2 (id int, c1 int)"
$ dolt sql -q "create trigger repl after insert on t1 for each row replace into t2 values (new.id, new.c1)"
$ dolt sql -q "insert into t1 values (0,0)"
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t2"
+----+----+
| id | c1 |
+----+----+
| 0  | 0  |
+----+----+

$ dolt sql -q "insert into t1 values (0,1)"
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t2"           
+----+----+
| id | c1 |
+----+----+
| 0  | 1  |
| 0  | 0  |
+----+----+

```

Please reopen with an exact repro so we can help debug further.

**Comment by timsehn** [comment]
Dolt is cool!
