### ISSUE TITLE
Support prepared statements SQL statements

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4452]
Client tooling can already execute prepared statements through commands over MySQL's wire protocol, but we don't yet support creating, executing, and deallocating prepared statements directly through SQL commands. This is a handy feature for debugging and should be easy to wire up to the existing prepared statement support. 

Add support for `PREPARE`, `EXECUTE`, and `DEALLOCATE PREPARE`: 
https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html#prepared-statement-types

**Comment by JCOR11599** [comment]
fix is merged to gms, and will eventually merge to dolt main
