### ISSUE TITLE
MySQL client with autocomplete enabled crashes connecting to Dolt if a table is named a reserved word like `rows` 

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4464]
Running dolt 0.41.7, new format.

Steps:
1. Run dolt server locally which has at least one database
2. Connect to the server using the default linux mysql client (ex. `mysql -u root --host=127.0.0.1 -P 3306 -p`)
3. Use a database - `mysql> use mydb;`
4. Try to run any query, such as showing the tables - `mysql> show tables;`

Results from the mysql client:
```
mysql> use mydb;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
ERROR 2008 (HY000): MySQL client ran out of memory
No connection. Trying to reconnect...
Connection id:    9
Current database: mydb

ERROR 2008 (HY000): MySQL client ran out of memory
No connection. Trying to reconnect...
Connection id:    10
Current database: mydb

ERROR 2008 (HY000): MySQL client ran out of memory
```

Results from the dolt server:
```
2022-10-05T09:07:06-04:00 INFO [conn 9] NewConnection {DisableClientMultiStatements=false}
2022-10-05T09:07:06-04:00 INFO [conn 10] NewConnection {DisableClientMultiStatements=false}
2022-10-05T09:07:06-04:00 ERROR [no conn] Error writing query error to client 9 (127.0.0.1:46180): write tcp 127.0.0.1:3306->127.0.0.1:46180: write: broken pipe
Write(header) failed
conn 9 {}
2022-10-05T09:07:06-04:00 INFO [conn 9] ConnectionClosed {}
```

If you run the mysql client with the `-A` option to turn off auto-rehashing (`mysql -u root -A --host=127.0.0.1 -P 3306 -p`), this problem does not occur and the database can be queried normally (presumably just without any autocompletion functionality, which is not critical at least).

**Comment by timsehn** [comment]
Interesting. Good bug. We'll look today.

**Comment by zachmu** [comment]
Trigger for this bug probably related to a table with the name `rows`.
