### ISSUE TITLE
`dolt migrate` fails with "migration failed cause: Incorrect datetime value"

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#4474]
Creating issue on behalf of a user who explained that running `dolt migrate` fails with "migration failed cause: Incorrect datetime value". Aside from the fact that the migration fails, the error message is not very helpful or actionable.

**Comment by coffeegoddd** [comment]
An update from the customer, the error `cause` is `error (cause: Incorrect datetime value: '%!s(int64=-2209161600)')`

**Comment by druvv** [comment]
This repo results in the error:
https://www.dolthub.com/repositories/dolthub/test-private-prod/jobs/826acee0-ee48-4c4e-850c-faca944e2d46?refName=master
