### ISSUE TITLE
function/string: strcmp is missing

### ISSUE THREAD

**Issue by lucab** [dolthub/dolt#4478]
I tried to connect `dolt` to an external spreadsheet software (libreoffice), but the setup/introspection logic failed on:
```
function: 'strcmp' not found
```

See https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#function_strcmp for reference.

PS: thanks for maintaining this :green_heart:

**Comment by timsehn** [comment]
I'm not sure how hard this is but I think we can usually get these done fairly quickly.

**Comment by stephkyou** [comment]
Hi @lucab, I just merged in a change to support STRCMP functionality. I'm planning on doing another pass to make sure it fully supports collation so that should be coming soon. Thanks so much for taking the time to open an issue for this bug!
