### ISSUE TITLE
Support row and column aliases in INSERT ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#4479]
Given the following example queries:
```sql
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) AS new ON DUPLICATE KEY UPDATE c = new.a+new.b;
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) AS new(m,n,p) ON DUPLICATE KEY UPDATE c = m+n;
INSERT INTO t1 SET a=1,b=2,c=3 AS new ON DUPLICATE KEY UPDATE c = new.a+new.b;
INSERT INTO t1 SET a=1,b=2,c=3 AS new(m,n,p) ON DUPLICATE KEY UPDATE c = m+n;
```

We currently do not support the `AS new` portion, which are the aliases.

Reference:
https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Comment by nicktobey** [comment]
This is a dupe of https://github.com/dolthub/dolt/issues/7638, closing this one because the other issue has more context.
