### ISSUE TITLE
support for `:=` operator in SELECT

### ISSUE THREAD

**Issue by sillydong** [dolthub/dolt#4489]
We have queries like `select @id := id from table limit 1`.  This is basically query some data into a variable. It is fully supported in MySQL, but for this project, when I run the query, I got `ERROR 1105 (HY000): syntax error at position 13 near ':'` which means the content `:=` is not supported. 

Is there any plan to support such query?

**Comment by jennifersp** [comment]
Support for `:=` for variable assignment is added [here](https://github.com/dolthub/vitess/pull/289). This PR does not include `:=` operator usage in `SELECT` as it is deprecated in MySQL.
