### ISSUE TITLE
Import resource utilization

### ISSUE THREAD

**Issue by andy-wm-arthur** [dolthub/dolt#4491]
Bulk loading data into Dolt has a number of resource utilization problems and is generally not performant. The set of performance problems encountered depends on the import path used and the shape and schema of the data being imported. `dolt table import` and `dolt sql` are the primary entry points for loading data into Dolt. `dolt table import` constructs a custom `sql.Engine` to load data, so there is a some degree of overlap between these two code paths. The major difference is that `dolt table import` makes an effort to write in large batches while batches sizes in `dolt sql` depend on how transactions are structured within the sql file. The following factors have the most significant impact on performance and resource utilization:

- Batch size: 
There are two types of batches statements and transactions. After every write statement, Dolt materializes a new prolly tree for each index in each affected table. Flushing prolly trees adds new chunks to the ChunkStrore. After each transaction, Dolt's ChunkStore ([NomsBlockStore](https://github.com/dolthub/dolt/blob/728cc0edddc52d0e7656a0501b7250f7073547cc/go/store/nbs/store.go#L973)) flushes all new chunks from the transaction into a table file. 
The worst-case access pattern for Dolt is a large import where each row is inserted in a separate statement, and `AUTOCOMMIT` commits the ChunkStore after each statement. (Unfortunately this is the structure of `dolt dump`). Ideally, we'd aggregate inserts into batches of very-large statements and structure the import as a single transaction (or transaction per-table). The tradeoff here is that Dolt must parse the entire statement into memory before processing it, so there is some upper limit. 

- Sorted/Unsorted data
Prolly trees have copy-on-write update semantics. When in-memory edits are flushed, each affected node in the tree is copied before being updated (no in-place edits). Large imports periodically flush their accumulated edits. Randomly ordered import data can result in repeated edits (and copies) the same tree node throughout the import process. An option here is to pre-sort import data before the import process.

- Number of secondary indexes
Secondary indexes increase the amount of data being written. Further, data that is sorted for the primary index may results in random access for a secondary index. Import-specific machinery could be built to lazily build indexes and/or re-sort new rows to update the secondary index in sorted order.

- Number of `FOREIGN KEY`, `UNIQUE` constraints
Both of these constraint types require secondary indexes (see above). They also require additional work to enforce the constraints during import. `UNIQUE` indexes in particular could necessitate random read access into the index to validate constraints. Again, import specific machinery could be built to accelerate this. Import data could be sorted in multiple orders to enable sequential index access during validation.

Additionally, there memory-utilization improvements to Dolt's write path that are not import-specific but would generally improve throughput. Because Dolt's allocations tend to small and frequent, reducing allocations will also reduce cpu utilization by the garbage collector.

- Improve caching for `schema.Schema`
The current schema cache stores objects that require post-processing on a cache hit. As `schema.Schema` has evolved, this post-processing work has become expensive. However, caching complete schema objects is dangerous as a number of methods mutate them in-place. Moving towards an immutable schema object would improve cache friendliness. 

- Replace `types.WalkRefs` with `types.WalkAddresses`
WalkRefs is a leftover artifact from the storage engine rewrite. On code paths where we need to traverse the DAG, we usually need to wrap a `hash.Hash` address in a `types.Ref`, which is expensive. Fully decoupling the new storage path from `types` is necessary to remove the old storage code, and will have perf wins. 

- Stream ChunkIndexes on Conjoin
NomsBlockStore combines multiple table files when it exceeds its limit of 256 active tables. The process involves merging the chunk indexes of these tables, which is currently done by loading all of each index into memory. Using a streaming merge-sort approach will reduce memory overhead

- Recycle buffers on ChunkCache eviction
This change is more speculative, as our caching story at the ChunkStore layer is immature. However, a major contributor to memory utilization on import is allocating chunk and tuple buffers for new prolly tree nodes.

**Comment by max-hoffman** [comment]
We have not investigated all of these optimizations, but none appear to currently impair the current import performance, which is comparable to our mysql performance multiple in other areas.
