### ISSUE TITLE
Support all MySQL logical operators

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4497]
We currently have support for some, but not all of [MySQL's logical operators](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html).

For example, `select 1 OR 1;` works, but not `select 1 XOR 1;`. We should review MySQL's logical operators and ensure we support all of them. 

Found by: [go-sqlsmith](https://github.com/PingCAP-QE/go-sqlsmith)

**Comment by timsehn** [comment]
Resolving because we added a note on CONVERT()
