### ISSUE TITLE
Strange behavior with enum in composite unique key in a table without primary key

### ISSUE THREAD

**Issue by Wuvist** [dolthub/dolt#4503]
I've a very strange table:
```sql
CREATE TABLE `accounts` (
  `user_id` int NOT NULL,
  `type` enum ('free', 'vip') NOT NULL DEFAULT 'free',
  `money` int(8) NOT NULL DEFAULT 0,
  UNIQUE KEY `user_id_type` (`user_id`, `type`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
```
Usually, the `UNIQUE KEY` is should be declared as primary key, but somehow it's declared as `UNIQUE KEY` only, and the table has no other keys.

If I create this table in `go-mysql-server v0.12.0`, and run the following query
```bash
mysql> insert into `accounts` (user_id, `type`, money)values(1,"free",1);
Query OK, 1 row affected (0.00 sec)

mysql> select * from `accounts`;
+---------+------+-------+
| user_id | type | money |
+---------+------+-------+
|       1 | free |     1 |
+---------+------+-------+
1 row in set (0.00 sec)

mysql> select * from `accounts` where user_id=1 and `type`="free";
Empty set (0.00 sec)
```

It failed to return result when `type` is in where condition.

I test the same table & query on `MySQL 5.7.35`, although it works:
```bash
mysql> select * from `accounts` where user_id=1 and `type`="free";
+---------+------+-------+
| user_id | type | money |
+---------+------+-------+
|       1 | free |     1 |
+---------+------+-------+
1 row in set (0.00 sec)
```

but it seems that `MySQL 5.7.35` consider the unique key as primary key:
```bash
mysql> desc accounts;
+---------+--------------------+------+-----+---------+-------+
| Field   | Type               | Null | Key | Default | Extra |
+---------+--------------------+------+-----+---------+-------+
| user_id | int(11)            | NO   | PRI | NULL    |       |
| type    | enum('free','vip') | NO   | PRI | free    |       |
| money   | int(8)             | NO   |     | 0       |       |
+---------+--------------------+------+-----+---------+-------+
3 rows in set (0.01 sec)
```

It works if unique key is declared as primary in `go-mysql-server v0.12.0`, it also works if `type` is not `enum` but `int`.

I suppose this is a extreme corner case and may not worth fixing, but would like to report it here first in case it's related to some other hidden bug related to enum support.

**Comment by timsehn** [comment]
I think I'm going to resolve this one. Please create a new bug in `go-mysql-server` if you have a persistent problem there. We've made changes to `information_schema` latesly and that issue should be fixed.
