### ISSUE TITLE
calling set `@@session.global_var = value` should fail

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#4531]
It's currently possible to the value of a global-scope-only system variable with the `@@session.` syntax. This should return an error similar to MySQL.

**Comment by PavelSafronov** [comment]
Can you give an example? Here's the query I'm trying to run against dolt, and it's failing, same as MySQL. (Though we're returning a different error code.)

MySQL:
```
mysql>  set @@session.slow_query_log=2;
ERROR 1229 (HY000): Variable 'slow_query_log' is a GLOBAL variable and should be set with SET GLOBAL
```

dolt:
```
mysql> set @@session.slow_query_log=2;
ERROR 1105 (HY000): Variable 'slow_query_log' is a GLOBAL variable and should be set with SET GLOBAL
```

**Comment by zachmu** [comment]
I don't remember which variable I ran into with this problem. We must have one defined incorrectly, but I sure can't remember which. Go ahead and close this out in the meantime since I don't have a repro for it, and it doesn't seem to be a problem generally.
