### ISSUE TITLE
Dropping a table then reimporting with inferred schema creates new tags unexpectedly

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4599]
https://github.com/dolthub/dolt/blob/f6acf21637de8d945706a18bc0eb182122937a67/go/libraries/doltcore/doltdb/root_val.go#L385

headRoot might need to be passed here. Needs a thorough investigation and tests.

**Comment by timsehn** [comment]
I'm pretty sure we eliminated all cases where Dolt depends on tags. They are now an implementation detail.
