### ISSUE TITLE
dolt migrate: Fails to migrate when a table has been renamed

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4602]
Encountered this issue while migrating https://www.dolthub.com/repositories/dolthub/us-president-precinct-results

```
migration failed
cause: Cannot create column name, the tag 10612 was already used in table candidates2
       Cannot create column fec, the tag 10798 was already used in table candidates2
       Cannot create column fec_name, the tag 6571 was already used in table candidates2
```

**Comment by andrew-wm-arthur** [comment]
This issue stems from now obsolete rules around tag reuse and table renames. At commit `l5prg47otlbtlr02habfdhghje6a1akt` in the history, tables were renamed and suffixed with `2` (eg `candidates2`) as part of a data cleanup for the bounty. The tag reuse rules that existed at the time are incompatible with the current rules. For this specific repo, the problem can be remedied with `filter-branch` operations to fix the table name discrepancy:
```
dolt filter-branch --all "rename table candidates2 to candidates"
dolt filter-branch --all "rename table counties2 to counties"
dolt filter-branch --all "rename table precincts2 to precincts"
dolt filter-branch --all "rename table vote_tallies2 to vote_tallies"
```

**Comment by druvv** [comment]
@liuliu-dev reports https://www.dolthub.com/repositories/liuliu/json-diff-example failing this this error:

```
job failed: failed to migrate: failed to migrate: migration failed
cause: Cannot create column pk, the tag 10341 was already used in table tablename
Cannot create column col1, the tag 8939 was already used in table tablename
```

**Comment by andrew-wm-arthur** [comment]
On further investigation, the issue seems to be migrating table renames

**Comment by druvv** [comment]
`@rodibasa` in discord reports a similar issue:

```
migration failed
cause: Cannot create column timestamp, the tag 12533 was already used in table "table_name"
       Cannot create column "column_name", the tag 7697 was already used in table "table_name"
```
