### ISSUE TITLE
Dolt argument parser gets confused by suffixes

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/dolt#4616]
Repro bash script:
```
echo "creating db"
rm -rf db
mkdir db
cd db
dolt init

echo "running sql"
dolt sql << EOF
use db;
create table test (id int primary key);
insert into test (id) values (1);
call dolt_add('.');
call dolt_commit('--messageWithExtraRandomSuffixYay111', 'first commit message');
EOF

dolt sql << EOF
use db;
insert into test (id) values (2);
EOF

dolt add .
dolt commit --messageWithAnotherWeirdArg "second commit message"

echo "---------------------"
dolt log --oneline
```

Result output:
```
...
8jdtjuvsrksndcacftesh70oc4dta9rc (HEAD -> main) WithAnotherWeirdArg
uqa8lhjspia0d8shr21f0sgnk8m24vh0 WithExtraRandomSuffixYay111
9plqeeg6se4kfd7kbna7kc6m7m2lt696 Initialize data repository
```

Note that the commit messages are not the strings we passed in, but the suffixes of the `--message` argument: `WithExtraRandomSuffixYay111` and `WithAnotherWeirdArg`.

**Comment by fulghum** [comment]
Good find @tanyongzhi. Looks like we're relying on that greedy match to pick up the suffix and parse that out as the value of the param. Good suggestion to stop doing that for `--` long form params. Could be cool to also not do that when the short form param doesn't take an argument.

**Comment by tanyongzhi** [comment]
I created a PR for this. I apologize if this is being worked on previously - I didn't see that this issue has already been assigned.

**Comment by fulghum** [comment]
Awesome! Thank you @tanyongzhi!! 🙏  I'll take a look at your PR in just a moment.

**Comment by fulghum** [comment]
This fix is merged to main now, and will roll out with the next Dolt release. 

Major thanks to @tanyongzhi for another awesome contribution! Thank you for investing your time and energy to help us squash bugs! 🙏
