### ISSUE TITLE
[dolt migrate]: Incorrect datetime value

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4625]
```
migration failed
cause: Incorrect datetime value: '%!s(int64=1376251200)'
```

is returned by private repo:
https://www.dolthub.com/repositories/dolthub/test-private-prod

**Comment by druvv** [comment]
Last commit date was 9/2/2021... pretty old!

**Comment by andrew-wm-arthur** [comment]
duplicate of https://github.com/dolthub/dolt/issues/4474
