### ISSUE TITLE
dolt_docs to conform to other feature tables

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#464]
We are calling tables that are backing features "feature tables" rather than "system tables". It seems that confusion was not helpful.

Query catalog and schemas table are currently created by default. We should do the same for the dolt_docs table, and then ensure it is _never_ deleted. This basically means it never appears in schema diff. Furthermore all the feature tables should be fully created with columns when repo is initialized.

**Comment by zachmu** [comment]
This is not really an issue anymore since we use pre-assigned tags for these tables
