### ISSUE TITLE
DATE_ADD does not support TIME input

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/dolt#4643]
[MySQL 8.0 DATE_ADD documentation](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add) states that DATE_ADD supports TIME input:
> (MySQL 8.0.28 and later:) [TIME](https://dev.mysql.com/doc/refman/8.0/en/time.html) if the date argument is a TIME value and the calculations involve only HOURS, MINUTES, and SECONDS parts (that is, no date parts).

MySQL 8.0.28 and later support this type of query:
```
$ mysql -u root -e "SELECT DATE_ADD(TIME('12:13:14'), INTERVAL 1 MINUTE);" 
+-----------------------------------------------+
| DATE_ADD(TIME('12:13:14'), INTERVAL 1 MINUTE) |
+-----------------------------------------------+
| 12:14:14                                      |
+-----------------------------------------------+
```

dolt doesn't support this:
```
$ dolt sql -q "SELECT DATE_ADD(TIMEDIFF('12:13:14', '00:00:00'), INTERVAL 1 MINUTE);"

error on line 1 for query SELECT DATE_ADD(TIMEDIFF('12:13:14', '00:00:00'), INTERVAL 1 MINUTE): incompatible conversion to SQL type: datetime
incompatible conversion to SQL type: datetime
```
(Note: the dolt query uses TIMEDIFF because dolt currently does not support TIME)

---

For completeness, here are the calls with string times. MySQL and dolt produce different results.

MySQL query with a time string:
```
$ mysql -u root -e "SELECT DATE_ADD('12:13:14', INTERVAL 1 MINUTE);"  
+-----------------------------------------+
| DATE_ADD('12:13:14', INTERVAL 1 MINUTE) |
+-----------------------------------------+
| NULL                                    |
+-----------------------------------------+
```

dolt query with a time string:
```
$ dolt sql -q "SELECT DATE_ADD('12:13:14', INTERVAL 1 MINUTE);" 

error on line 1 for query SELECT DATE_ADD('12:13:14', INTERVAL 1 MINUTE): Incorrect datetime value: '12:13:14'
Incorrect datetime value: '12:13:14'
```

**Comment by JCOR11599** [comment]
fix is merged to GMS main, will make it to dolt main eventually.
