### ISSUE TITLE
upgrade dolt from 0.26.6 to 0.50.2， sql error

### ISSUE THREAD

**Issue by mango-lzp** [dolthub/dolt#4652]
![image](https://user-images.githubusercontent.com/41472923/198556597-b950635a-a2e4-439e-a60f-10528ae3efe9.png)

![image](https://user-images.githubusercontent.com/41472923/198556619-4e95d148-44c9-4433-bc21-781137b74072.png)

**Comment by timsehn** [comment]
So, this interface is deprecated. To switch branches now, you use our stored procedures:

https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures

They map to the command line options. In this case, you call `call dolt_checkout('master')`;
