### ISSUE TITLE
Very large storage footprint

### ISSUE THREAD

**Issue by swaldman** [dolthub/dolt#4662]
Hi! I am just getting started with dolt, populating a [database that would be fun to share](https://cdr.ffiec.gov/public/PWS/DownloadBulkData.aspx) as a queryable database rather than the scattered mess of files by which the data is published.

It's a pretty large database, though. Playing with just a small subset of the full database (less than 5%), the source tab delimited files are like

```bash
$ du -sh ~/Downloads/FFIEC\ CDR\ Call/
61M	/Users/swaldman/Downloads/FFIEC CDR Call/
```
Parsing and organizing my subset into database tables, with dolt the storage directory grows quite extraordinarily large:

```bash
$ du -sh ~/tmp/dolt-callrep
3.6G	/Users/swaldman/tmp/dolt-callrep
```

Using identical software to populate a postgresdb (literally just changing the JDBC URL of the archiver), it's lots bigger than the source data files, but still an order of magnitude smaller than with dolt:

```bash
$ du -sh /Users/swaldman/Library/Application\ Support/Postgres/var-15
311M	/Users/swaldman/Library/Application Support/Postgres/var-15
```

The ~4GB storage footprint might not be a problem if it's a result of fixed-ish overhead in the storage structure. But if the footprint grows linearly-ish with the number of data files, it will become too unwieldy, I fear. (Also, how well do `dolt clone`, `dolt pull`, etc handle multi gigabyte data directories?) What should I expect?

Thank you!

**Comment by timsehn** [comment]
Dolt makes a bunch of disk garbage on large imports. If you want to clean it up run `dolt gc` (ie garbage collect). That should get it down to a more reasonable size. 

This would happen automatically when you push. Dolt doesn't push the garbage.

We used to `gc`  automatically  after imports but it can be slow so we stopped Maybe it's time to reconsider.

**Comment by swaldman** [comment]
Wow. Thank you!

Huge difference.

```bash
$ du -sh .
3.6G	.
$ ~/development/contrib-git/dolt/go/dolt gc
$ du -sh .
34M	.
```

34M is compressed relative to the original text data. Woohoo!

A thing that was surprising to me was that I had to run `dolt gc` in the _database_ directory, rather than the parent directory in which I had run `dolt sql-server`.

Automatic gc on import wouldn't have helped me, since this is data that's not importable in a standard way (at least not in the way I'd want it organized), an elaborate archiver parses and merges many files to build and populate the schema.

I think the manual gc is fine! You just need users less ignorant than me to use it. (Maybe it could be described more prominently in eg the getting started docs, or maybe I just missed it.)

Anyway, this is great. Many thanks!

**Comment by timsehn** [comment]
> Automatic gc on import wouldn't have helped me, since this is data that's not importable in a standard way (at least not in the way I'd want it organized), an elaborate archiver parses and merges many files to build and populate the schema.

@tbantle22 is working on automatic sql-server gc next! Should be done between Thanksgiving and Christmas

> You just need users less ignorant than me to use it.

Unfortunately for us this is a real problem and not a user problem :-) You're the second person to ask about it in the past week.

**Comment by swaldman** [comment]
(it might be useful if one could `call dolt_gc()` as an SQL stored procedure on the database in-use in sql-server mode, though perhaps the automatic gc soon will obviate that.)
