### ISSUE TITLE
Add support for `DROP TABLE CASCADE`

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4674]

**Comment by prodoelmit** [comment]
For our internal reference: DX-396

**Comment by druvv** [comment]
Customer is dropping all tables in their working set and is receiving an error similar to:
```
test> drop table parent;
cannot drop table `parent` as it is referenced in foreign key `fk`
test> drop table parent cascade;
cannot drop table `parent` as it is referenced in foreign key `fk`
```

As a solution, `SET FOREIGN_KEY_CHECKS = 0` can be used to drop the table.

**Comment by druvv** [comment]
Closing this issue, MySQL says:

> The RESTRICT and CASCADE keywords do nothing. They are permitted to make porting easier from other database systems.

https://dev.mysql.com/doc/refman/8.0/en/drop-table.html

**Comment by prodoelmit** [comment]
Confirmed working
