### ISSUE TITLE
Dolt docs `doc_text` column is `varchar(16383)`, should be `TEXT`

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#4713]
Dolt docs have an artificially low size restriction based on [`typeinfo.StringDefaultType`](https://github.com/dolthub/dolt/blob/c26da29d2cf4dba1ae2055c7285aaf9551edbda1/go/libraries/doltcore/schema/typeinfo/varstring.go#L51)

**Comment by JCOR11599** [comment]
fix is merged to gms main
