### ISSUE TITLE
Simple case statement doesn't work with enums

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4716]
Searched case statements can handle enums properly, but simple case statements seem to have problems, as can be seen with the following simple example:
```sql
create table t(e enum('a'));

insert into t values ('a');

select e,
       case when e = 'a' then 1 end c1, 
       case e when 'a' then 1 end c2
from t;
```
The query returns `(a, 1, null)` rather than `(a, 1, 1)`.

**Comment by fulghum** [comment]
Thanks for reporting this one @knutwannheden! I was able to easily repro using your example. This looks like a good one for @PavelSafronov to dig into this week.

**Comment by PavelSafronov** [comment]
Thanks for finding this bug, @knutwannheden !
Seems we were evaluating part of the case expression early and were losing some data. This is fixed now.
