### ISSUE TITLE
`dolt merge --no-ff <branch>` (no message) and `dolt merge --no-ff --no-commit <branch>` are still committing

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#4761]
### Basic info
dolt version 0.50.15

### Problem description
Merging a remote branch into my main shouldn't be creating a commit, but it is.

I've tried doing both `dolt merge --no-ff <remote branch>` (doing `:wq` in vim) and `dolt merge --no-off --no-commit <remote branch>`

Both times a merge commit immediately appears in my commit log.

Is this a bug or am I just using dolt wrong?

### Quick repro
You can try with
```sh
dolt clone onefact/paylesshealth
dolt remote add rl1987 https://doltremoteapi.dolthub.com/rl1987/paylesshealth
dolt fetch rl1987
```
followed by
`dolt merge --no-ff remotes/rl1987/google_dork_xlsx_urls`
and no commit message. This results in the merge commit:
```
commit aqbbag47r3bnraq9km92bl6scmbofudl (HEAD -> main) 
Merge: vgjdol2ndjqmskfnvpm2mdvg401glkgi 1cjnqqfq2dp3omjlpt9bdfvuqf4724qj
Author: spacelove <alec@dolthub.com>
Date:  Fri Nov 11 12:45:32 -0500 2022

        Merge branch 'remotes/rl1987/google_dork_xlsx_urls' into main
```

You can also do:
`dolt merge --no-ff --no-commit remotes/rl1987/google_dork_xlsx_urls`
This results in `dolt diff` returning nothing, but also nothing new in the commit log.

**Comment by fulghum** [comment]
I missed that you were using `--no-ff` and `--no-commit` together and **still** getting a new commit created. That's definitely a bug. Thanks for pointing this out! 🙏 

I'm going to close this one in favor of the new issue I created that includes this issue, as well as couple other behavioral differences between `dolt merge` and `git merge` that I noticed while repro'ing this.  (https://github.com/dolthub/dolt/issues/4762)
