### ISSUE TITLE
Strange Behavior with Dolt History Table

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4791]
select * from dolt_history_hospitals where ccn = "501309" order by commit_date;

returns a list of 172 rows.

select chargemaster_indirect_url, committer, commit_date from dolt_history_hospitals where ccn = "501309" order by commit_date;

returns a list of 7 rows.

**Comment by timsehn** [comment]
Latest onefact/paylesshealth database

```
$ dolt sql -q "select count(*) from dolt_history_hospitals where ccn = "501309" order by commit_date"
+----------+
| count(*) |
+----------+
| 209      |
+----------+

```
$ dolt sql -q "select chargemaster_indirect_url, committer, commit_date from dolt_history_hospitals where ccn = "501309" order by commit_date"
+---------------------------+-----------+-------------------------+
| chargemaster_indirect_url | committer | commit_date             |
+---------------------------+-----------+-------------------------+
| NULL                      | spacelove | 2022-10-27 21:34:04.772 |
| NULL                      | spacelove | 2022-10-27 21:34:27.559 |
| NULL                      | spacelove | 2022-10-27 21:54:41.688 |
| NULL                      | spacelove | 2022-10-27 21:54:52.808 |
| NULL                      | spacelove | 2022-10-28 17:09:51.567 |
| NULL                      | jaan      | 2022-10-28 18:03:40.102 |
| NULL                      | andy      | 2022-10-28 18:46:54.58  |
+---------------------------+-----------+-------------------------+
```

I can repro. It's weird. It's almost like in the second case it's not traversing both sides of merge commits.

**Comment by max-hoffman** [comment]
Thank you for the report and helpful repro @ericmock. We will merge this fix as soon as I finish testing around the edge case https://github.com/dolthub/dolt/pull/4799.

**Comment by timsehn** [comment]
Fix confirmed.
```
$ dolt sql -q "select count(*) from dolt_history_hospitals where ccn = "501309" order by commit_date"                                        
+----------+
| count(*) |
+----------+
| 209      |
+----------+

$ dolt sql -q "select count(commit_date) from dolt_history_hospitals where ccn = "501309" order by commit_date"
+--------------------+
| count(commit_date) |
+--------------------+
| 209                |
+--------------------+
```
