### ISSUE TITLE
Add the git config variable to always set the upstream on push

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4792]
When you create a new branch locally and push to DoltHub, you are warned:

fatal: The current branch branch_BF has no upstream branch.
To push the current branch and set the remote as upstream, use
	dolt push --set-upstream origin branch_BF

I have yet to ever not then copy/paste that command to set the upstream origin.

Suggestion:  Give a Yes/No prompt asking the user whether to proceed with the push.

**Comment by timsehn** [comment]
In git this is handled by a config variable. We could match that.

**Comment by ericmock** [comment]
Yeh!!  Thank you.

To push the current branch and set the remote as upstream, use
	dolt push --set-upstream origin branch_FM4
To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'dolt config --help'.
