### ISSUE TITLE
SQL statements with INNER JOIN

### ISSUE THREAD

**Issue by OscarFolhaMsgLifeIberia** [dolthub/dolt#4793]
Hey guys, whenever I try to run a dolt SQL statement with an INNER JOIN, like this one 
`SELECT * FROM DOLT_DIFF('f18pugr9bl9e8av2kvslnqfptq5de8g8', '9v08lncu5j61euuurgpel6ufb6k1f7uf','DWB_DWBTABLE') INNER JOIN DWB_DWBTABLE dd ON dd.Name = to_NAME AND dd.Id = to_ID`
I got an error, even though the dolt_diff returns a result.
I get something like this in the command line as well:
![error](https://user-images.githubusercontent.com/118288240/201955169-459727db-c7c7-4620-bda7-344f3ee7c89f.png)
This error has been appearing since version 0.50.9 and it's still occurring in version 0.51.0. Does anyone know a solution for this? Thank you!

**Comment by max-hoffman** [comment]
Hi @OscarFolhaMsgLifeIberia , thanks for taking the time to file an issue. We will get this sorted out today, we should not be panicking here.

This is the fix to track: https://github.com/dolthub/go-mysql-server/pull/1405
