### ISSUE TITLE
Table functions need unique names in queries, like tables

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#4798]
I am not sure this `DiffTableFunctionScriptTest` should succeed. The table/column resolving should be ambiguous.

```sql
SELECT to_pk, to_c1, to_c2, from_pk, from_c1, from_c2, diff_type
from dolt_diff(@Commit1, @Commit2, 't')
join dolt_diff(@Commit1, @Commit3, 't') on to_pk = to_pk
```

**Comment by zachmu** [comment]
Yes, one of those should be required to have an alias to resolve the ambiguity.
