### ISSUE TITLE
Default change:  Reset --hard

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4802]
I'm not sure what git does (I don't use it), so I'm not sure if you're mirroring its behavior, but I've seen many times in the bounties that people assumed `dolt reset` does what `dolt reset --hard` does.  I realize --hard is more destructive, but I've never seen reset used for anything besides what was supposed to be a hard reset.

**Comment by timsehn** [comment]
reset, no args moves a file (table in dolt's case) out of staged into working  
reset --soft moves the commit graph to the named commit and makes the changes between HEAD and that commit staged  
reset --hard moves the commit graph to the named commit and destroys all the changes. 

We are not going to change any defaults away from Git. Matching git is our product strategy and it works in general.
