### ISSUE TITLE
add create database header to dolt dump sql file

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#4837]
Currently, `dolt dump` does not include `CREATE DATABASE IF NOT EXISTS ...; USE db;` queries for sql file dumps. 
If the dump is imported to dolt in non database directory, it gives error `no database selected`.

**Comment by fulghum** [comment]
We had a related question (https://github.com/dolthub/dolt/issues/4865) about how `mysqldump` determines whether or not to include `CREATE DATABASE IF NOT EXISTS ...; USE db;` and updated our docs to recommend people run `mysqldump` with the `--databases` flag to ensure that statement gets included. However, I'd still vote that we just do this automatically for `dolt dump` though.
