### ISSUE TITLE
Merge stats are not accurate

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#484]
Skipped bats test included here: https://github.com/liquidata-inc/dolt/pull/482

Stat summary output after merge doesn't accurately reflect the row changes.
Example: 
Adding 10 rows to a table via `dolt merge <branch>` still outputs
`<table> | 0`
`1 tables changed, 0 rows added(+), 0 rows modified(*), 0 rows deleted(-)`

**Comment by VinaiRachakonda** [comment]
This bats test is unskipped and passes. Closing issue
