### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by SergeyDjam** [dolthub/dolt#4840]
Hello. May be support PostgreSQL?

**Comment by SergeyDjam** [comment]
I see on the road map that it is set for 2023. Great.

**Comment by fulghum** [comment]
Hey @SergeyDjam, thanks for checking out the [Dolt roadmap](https://docs.dolthub.com/other/roadmap). PostgreSQL support is on there, although not yet committed for 2023. We are in very early stages for thinking about a PostgreSQL Dolt, so if you have _any_ feedback to share about why it's important to you or what specific features you'd need, that would be helpful info for us to hear. 

On a related note... we did [release a project this year that translates a PostgreSQL data dump to a MySQL data dump](https://www.dolthub.com/blog/2022-01-19-transforming-postgres-dumps-into-mysql-dumps/) that can then be loaded by Dolt. It's not PostgreSQL Dolt of course, but it has enabled some PostgreSQL customers to try out their data in Dolt. 

Thanks for taking the time to provide some feedback. Feel free to swing by the [DoltHub Discord server](https://discord.com/invite/RFwfYpu) if you wanna chat more, too!

**Comment by timsehn** [comment]
Here's an article we wrote on this:

https://www.dolthub.com/blog/2022-03-28-have-postgres-want-dolt/

**Comment by knutwannheden** [comment]
I think Doltgres would definitely be very cool. PostgreSQL offers a lot of interesting functionality which I miss in MySQL. Some of the things I like best:
* A `WITH` query can modify data and the results feed into other queries all part of the same statement. How cool is that? https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-MODIFYING
* Window functions have a `FILTER` clause: https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS
* Transactional DDL 
* Range types: https://www.postgresql.org/docs/current/rangetypes.html

I probably forgot a whole lot of other things.

**Comment by fulghum** [comment]
Thanks for sharing the feedback @knutwannheden. Very helpful to have it recorded and tracked here. 

**All** - feel free to add more feedback or concrete details on why a PostgreSQL flavored Dolt would be helpful for you and we'll use that as input for planning.

**Comment by durkie** [comment]
One more vote for Postgresql support here -- I have an application that relies heavily on OpenStreetMap data and being able to time-travel through different versions of OSM geometry data would be hugely valuable for me.

**Comment by timsehn** [comment]
> One more vote for Postgresql support here -- I have an application that relies heavily on OpenStreetMap data and being able to time-travel through different versions of OSM geometry data would be hugely valuable for me.

We have support coming for MySQL's version of spatial indexes coming soon. Would that work?

**Comment by timsehn** [comment]
Might as well have this as an open issue for tracking.

**Comment by durkie** [comment]
> 



> We have support coming for MySQL's version of spatial indexes coming soon. Would that work?

I think that could potentially cover a lot of my use cases. It would require a little reconfiguring versus running everything through PostGIS, but even getting fast bounding box / intersection filter would be a great improvement since I could at least filter the rows of interest and import those to a local spatialite db or temporary Postgres table for further spatial needs.

**Comment by timsehn** [comment]
This is the spatial index PR: https://github.com/dolthub/dolt/pull/5164

It is close. We will have something by end of month.

**Comment by durkie** [comment]
fantastic -- thank you!

**Comment by timsehn** [comment]
This is the blog article about this:

https://www.dolthub.com/blog/2022-03-28-have-postgres-want-dolt/

Next step is to make Dolt work with the Postgres MySQL FDW: https://github.com/dolthub/dolt/issues/5441

**Comment by JCOR11599** [comment]
Update here:

We added limited support for MySQL's Server Side Cursors, and as a result the Postgres MySQL FDW release 2.9.0 (currently the latest) seems to work with dolt.

**Comment by timsehn** [comment]
Dolt works with `mysql_fdw`:

https://www.dolthub.com/blog/2023-04-12-dolt-with-mysql_fdw/

**Comment by latot** [comment]
:O I'm so exited with this tooo!!

**Comment by lofcz** [comment]
If Postgre suport is ever finished, we are ready to transition from SqlServer.

**Comment by timsehn** [comment]
We have an Postgres emulator we're working on. News soon.

**Comment by Hydrocharged** [comment]
We're officially working on PostgreSQL support!
https://github.com/dolthub/doltgresql
