### ISSUE TITLE
Incorrect capitalization of sql-server param in docs

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4864]
In this section: https://docs.dolthub.com/sql-reference/server/troubleshooting#set-your-log-level-to-trace
it refers to parameter `--loglevel=DEBUG`. This capitalization is not accepted (produces `loglevel is invalid: DEBUG`). The correct values must be all lower-case, ie `--loglevel=debug`.

**Comment by fulghum** [comment]
Thanks for reporting this one @dphil. We'll get the docs updated and also look at changing the behavior to make the log level param case insensitive.

**Comment by fulghum** [comment]
Thanks again for the good feedback @dphil. I just merged in a change to make the `loglevel` param case insensitive in the CLI arg and in the YAML config format. That'll roll out in a new release for you in the next hour or so.

**Comment by dphil** [comment]
Case-insensitive is even better. Thanks!
