### ISSUE TITLE
Error while restoring mysql dump into dolt

### ISSUE THREAD

**Issue by gopal-faircent** [dolthub/dolt#4865]
There is error, while restoring mysqldump into dolt.
As per error screenshot, we have deleted the mentioned tables and re-backup and trying to restore, but everytime there is new table comes with same error. 

Please help on this issue.
![Screenshot 2022-11-28 120811](https://user-images.githubusercontent.com/106506928/204210451-4891aabc-9702-407b-a420-43020406519c.jpg)

**Comment by gopal-faircent** [comment]
error on line 18 for query 

--
-- Table structure for table `accesslog`
--

DROP TABLE IF EXISTS `accesslog`: no database selected
no database selected

**Comment by timsehn** [comment]
You need to create and use a database. What tool generated the SQL?

**Comment by gopal-faircent** [comment]
Hi timsehn,
The backup I have taken from MySQL database using mysqldump command and trying to restore in dolt.

**Comment by fulghum** [comment]
It looks like using the `--databases` arg for `mysqldump` will cause the `CREATE DATABASE` command to be included in the dump. 
https://stackoverflow.com/questions/16452523/mysqldump-with-create-database-line

That would be a great detail to mention in our docs on importing from MySQL: 
https://docs.dolthub.com/guides/import#mysql-databases

I'll double check that it works as expected and happy to update our docs.

**Comment by fulghum** [comment]
I just pushed a doc update to recommend that people use the `--databases` flag when running `mysqldump`:
https://docs.dolthub.com/guides/import#mysql-databases

That will force the `create database <dbname>;` and 'use <dbname>;` statements to be in the generated dump file, and should fix this problem for you. 

I'll go ahead and close this issue, but please don't hesitate to reopen if you're still having problems getting a mysql dump to load into Dolt and we'll be more than happy to help you!

**Comment by gopal-faircent** [comment]
Hi tim/fulghum,
- The backup I'hve taken using cmnd: "sudo mysqldump -uroot -p fair > fair.sql" in mysql server. 
- Backup copy moved to dolt server one of the directories. 
- dolt sql server is up and running and new database created with same name in dolt server. Screenshot attached. 
![Uploading image.png…]()
- Tried all below command to restore database into dolt.
> using SQL client dolt sql-client -uroot > /dolt/fair.sql
> using SQL client dolt sql-server -uroot > /dolt/fair.sql
> using SQL server dolt sql < fair.sql
by login into sql and without login into sql.

**Comment by timsehn** [comment]
This command:

`sudo mysqldump -uroot -p fair > fair.sql`

Needs to be:

`sudo mysqldump --databases -uroot -p fair > fair.sql`

**Comment by timsehn** [comment]
This command:

`sudo mysqldump -uroot -p fair > fair.sql`

Needs to be:

`sudo mysqldump --databases -uroot -p fair > fair.sql`
