### ISSUE TITLE
Percent symbol (%) in commit strings is interpreted a format placeholder

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#4919]
e.g.
```
$ dolt commit -m "Replace quoted %25 with % in all urls"
[...]
        Replace quoted %! (MISSING)with %!i(MISSING)n all urls
```
Also shows in `dolt log`.

**Comment by timsehn** [comment]
I think this is a shell issue? You need to escape those yourself.

**Comment by abmyii** [comment]
I tried that too to no avail. I've got a fix which I'm going to write tests for and push as a PR.

**Comment by timsehn** [comment]
Great! Thanks.

**Comment by abmyii** [comment]
Fixed in https://github.com/dolthub/dolt/pull/4939.
