### ISSUE TITLE
DBeaver does not support updating a branch

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4925]
Version:  tip of main

dolt checkout branch_2
dolt sql-server
In DBeaver:
* select * from from `mydatabase/branch_1`.table
* edit a cell

See the screenshot.

![image](https://user-images.githubusercontent.com/25640/205753594-87faa12d-c026-41d9-89a1-a1dfcc495e96.png)

**Comment by JCOR11599** [comment]
Hey @ericmock, thanks for the bug report!
It seems like dBeaver is doing something strange when trying to edit result sets from branches that the server isn't on.

I'm currently looking into this issue, but for now here is a workaround.
dBeaver script:
```sql
use `paylesshealth`;
call dolt_checkout('branch_EN4');
select * from `hospitals` where ccn = "041302";
```

Basically, make sure to not use the `database/branch` syntax and `call dolt_checkout()` the branch you want right before selecting.
Hopefully, this lets you continue working, while we look more into this.
