### ISSUE TITLE
Output 'conflicts cat' to csv

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4930]
It would be great to be able to output conflicts to a csv file.  In fact, it would be great to be able to make all output a csv.

Stuff like shown below is really hard to work with.

![image](https://user-images.githubusercontent.com/25640/205774101-c0f7322d-3dd4-428d-8a72-54cf76f46202.png)

**Comment by timsehn** [comment]
Unlikely to get to this very soon. We're focusing on SQL not the CLI.

**Comment by timsehn** [comment]
dolt sql -r csv `select * from dolt_conflicts_<tablename>` is the workaround here and for most things CSV.

**Comment by timsehn** [comment]
I think the workaround is sufficient in this case.
