### ISSUE TITLE
Remote requests on sql commands

### ISSUE THREAD

**Issue by ralfebert** [dolthub/dolt#504]
Following the introduction steps at https://github.com/liquidata-inc/dolt#first-repository, I am seeing 'dolt' making a remote request to 54.244.85.252/eventsapi.dolthub.com on executing the sql commands. This seems to slow down the commands a bit. It seems to be some kind of tracking; if so: I would prefer being asked about that. What's going on there?

**Comment by zachmu** [comment]
Hi @ralfebert,

Sorry for the lack of a response here!

Those are indeed anonymous usage metrics. If you would prefer not to send them, you can set a config key like so:

`metrics.disabled = true`
