### ISSUE TITLE
Dolt CLI should always use the pager when results are more than one page.

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#505]
Also, compatibility with rlwrap would be nice to have.

**Comment by timsehn** [comment]
Places to use the pager:

1. SQL Results
2. --help text

Add more as we discover them here.

**Comment by nicktobey** [comment]
Many failure modes for commands print the help text, even though --help wasn't passed in. Using the pager there could be potentially unexpected though, since the intended command shouldn't print the help string.

**Comment by timsehn** [comment]
I've noticed we do this now.
