### ISSUE TITLE
In `dolt config`, make `--set` an alias/substitute for `--add` to match `git`'s behavior 

### ISSUE THREAD

**Issue by dlscanada** [dolthub/dolt#5050]
Ideally, these two commands would do the same thing:
```
dolt config --global --add user.email <myemail>
dolt config --global --set user.email <myemail>
```

The latter is currently invalid though. Should be a super easy improvement. 

With git, I believe both of those are valid.

**Comment by timsehn** [comment]
This is a good one to fix quick @stephkyou.

**Comment by stephkyou** [comment]
Hi @dlscanada, thanks for opening an issue! I just merged in a PR to add the `--set` flag for `dolt config`. `dolt config --set` will now do the same as `dolt config --add`.
