### ISSUE TITLE
`CREATE TABLE LIKE` does not replicate CHECK constraints

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5072]
Schema is:

```
CREATE TABLE `image_labels` (
  `image_id` int NOT NULL,
  `label` varchar(100) NOT NULL,
  `top_left_x` int,
  `top_left_y` int,
  `bottom_right_x` int,
  `bottom_right_y` int,
  PRIMARY KEY (`image_id`,`label`),
  CONSTRAINT `chk_esd5b974` CHECK ((`top_left_x` < `bottom_right_x`)),
  CONSTRAINT `chk_r4sbrdks` CHECK ((`top_left_y` < `bottom_right_y`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
```

Run 
```
CREATE TABLE image_labels2 AS SELECT * FROM image_labels;
```

Result:

```
CREATE TABLE `image_labels2` (
  `image_id` int NOT NULL,
  `label` varchar(100) NOT NULL,
  `top_left_x` int,
  `top_left_y` int,
  `bottom_right_x` int,
  `bottom_right_y` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
```

**Comment by druvv** [comment]
It dropped the primary key too.

**Comment by fulghum** [comment]
`CREATE TABLE t2 AS SELECT * FROM t1` looks like it's working correctly and has the same behavior as MySQL – `t2` is created with the data from the projection on `t1`. This doesn't seem to be an issue.

However... `CREATE TABLE t2 LIKE t1` does *NOT* behave the same as MySQL. It creates a new table with the same schema and the same primary key, but it does not copy the check constraints. To match MySQL's behavior, we need to update `CREATE TABLE ... LIKE ...` to also copy over check constraints.

**Comment by timsehn** [comment]
Fixed by https://github.com/dolthub/go-mysql-server/pull/1768

Waiting for the Dolt bump to resolve.

**Comment by nicktobey** [comment]
Bump is in.
