### ISSUE TITLE
Can't edit table's data in navicat

### ISSUE THREAD

**Issue by Jinsns** [dolthub/dolt#5080]
In navicat premium 15
![image](https://user-images.githubusercontent.com/56482300/210316748-a82d6e41-7429-4690-8fcc-68253d13f108.png)

**Comment by timsehn** [comment]
We'll look at this today.

**Comment by jennifersp** [comment]
Hi @Jinsns, thank you for reporting this issue. I have tried `Navicat for MySQL Version 16.1.5` which is the latest version and `Navicat Premium Essentials Version 15.0.36` on MacOS so far, and I was not able to reproduce this issue. Can you give us more information on this issue?
- What is the specific version of Navicat are you using? 
- What is the type of this column that could not be edited? 
- Is there any specific error message you're getting?

**Comment by Jinsns** [comment]
My navicat version is 15.0.11 premium.
![image](https://user-images.githubusercontent.com/56482300/210507469-8c173885-eb9c-47f6-adce-921794206028.png)
![image](https://user-images.githubusercontent.com/56482300/210507545-c4b4af63-b7f7-4fa1-a2d0-5ac921b1db52.png)

I didn't get any error message. It just didn't response when I typing in the cell of table.
![image](https://user-images.githubusercontent.com/56482300/210509945-a1c22365-1acf-420f-8bbc-f1d555fbc969.png)

By the way, collation 'utf8mb4_0900_bin', which is the only choice, is unfamiliar to me. I used to use utf8mb4_general_ci. I'm not sure if this matters.

**Comment by jennifersp** [comment]
Thank you for providing more information on this issue. Sorry, I was not able to get this specific version of Navicat premium. What Dolt version are you using? I recommend upgrading your Dolt version to the latest version. 

Can you try upgrading your Navicat version? I did find in the Navicat release notes that they made bug-fix for `Unable to update data in some cases` in `version 15.0.28`. https://navicat.com/en/products/navicat-premium-release-note

You can also try using `dolt sql-server` command with flag `--loglevel='trace'`. This lets you see all the queries run from Navicat and errors.
