### ISSUE TITLE
Slow importing with foreign keys

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#5097]
While I have not done any explicit tests, it appears that the time it takes when importing data to a table with foreign keys grows like N^2.  This isn't an issue when importing tables with thousands of rows, but it becomes very slow when importing tables with hundreds of thousands of rows.  Are there optimizations that could be made?

**Comment by ericmock** [comment]
I'd been breaking things into smaller chunks as a workaround.  It still seemed to get bogged down.  A garbage collection seemed to help a bit.

I was not aware you could turn off the foreign key checks.  Is that persistent across imports?

**Comment by fulghum** [comment]
`SET foreign_key_checks = 0;` will turn off foreign key checks for only the current session. You would typically put this into your SQL batch file at the start to disable foreign key checks while you run all the import statements. 

If you want this behavior to be global in a `dolt sql-server` mode (i.e. for all user sessions on a Dolt sql-server), you could run `SET @@global.foreign_key_checks = 0;`. You could also have the setting persist across `dolt sql` and `dolt sql-server` restarts with `SET @@PERSIST.foreign_key_checks = 0;`. 

Just note that when you turn `foreign_key_checks` back on, it does **not** go back over any existing data and perform constraint checks – it will only perform those constraint checks on new changes going forward. 

Glad you found the garbage collection tip! We're working on some GC enhancements that should remove the need to manually run GC, but until then, explicitly running GC after an import is a great practice. 

btw... in case you didn't already find this... we have [a guide for importing data dumps into Dolt](https://docs.dolthub.com/guides/import), and there are a few best practices/tips listed at the end (including GC and a small mention of foreign keys). If you have any feedback on how that guide could have helped you more, we'd be happy to improve those docs.

**Comment by ericmock** [comment]
Thank you for the great information.  I had never scrolled to the end of that importing guide.  That said, it might be good to put those tips at the top of the page.  I suspect most users will find the section for the type of data they want to import and not read further down.

If I import with foreign key checking off, add data, then turn checking back on, dolt does not rescan the database to determine if constraints are violated, right?  What if I try to merge that data with foreign-key violations with a database that has foreign-key checking turned on?

**Comment by timsehn** [comment]
You can run this:

https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures#dolt_verify_constraints

Or the command line version.

**Comment by ericmock** [comment]
Thank you.  Would there be any performance benefit to turning off constraint verification during import and then ensuring nothing was violated with the above command afterward?

**Comment by timsehn** [comment]
It will be way faster. Turning off foreign key checking is very common on import.

**Comment by ericmock** [comment]
Thanks.  That's great to know.

**Comment by fulghum** [comment]
Yup, you can also turn off foreign-key checks when using `dolt table import` – just pass the `--disable-fk-checks` flag. 

The `--disable-fk-checks` flag is very simple to use, but here's the [reference documentation for `dolt table import`](https://docs.dolthub.com/cli-reference/cli#dolt-table-import) just in case you want to dig into any other options. 

Thanks for the good feedback on the import docs! Let us know how the rest of your import experience goes and if there's any other feedback or questions you have or anything we can do to help.

**Comment by ericmock** [comment]
Thank you for the feedback.  I'm embarrassed that, after doing so many imports, I didn't notice the `--disable-fk-checks` flag.

**Comment by fulghum** [comment]
No need to be embarrassed!! We got some good feedback from you on the import experience and got some takeaways to improve the Data Import guide, so this was definitely useful for us. 😄

**Comment by fulghum** [comment]
I'm gunna close this one out since I think we got everything sorted out now and we've got a separate issue for some import doc updates. Don't be shy to reopen or ping us on Discord if you still need anything here!
