### ISSUE TITLE
dolt distinguishes the type of an argument based on the presence of an extension

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#51]
Consider the below, where we want to import `csv` file `bar` into a new table, `foo`:
```
oscarbatori $>> dolt table import foo --pk=station_name,lines -c bar
Error creating reader for bar.
cause: table not found
When attempting to move data from dolt table:bar to dolt foo, could not open a reader.
```
Changing the name of `bar` to `bar.csv` fixes the issue. We should make users explicitly specify whether the source is a file name or a table name, or some other form of input.

**Comment by bheni** [comment]
if it's a file without an extension or a non standard extension there is a --file-type parameter that you can use.  like git, dolt attempts a lot of DWIM.

**Comment by oscarbatori** [comment]
Do you want to keep it that way? I'd prefer we make it explicit, that was quite confusing for a second.

**Comment by bheni** [comment]
In your example

  dolt table import foo --pk=station_name,lines --file-type csv -c bar

**Comment by bheni** [comment]
I definitely think we could improve the error messaging.  Other things we could do are look for a file and a table with the given name.  If both exists require explicit designation.

**Comment by oscarbatori** [comment]
@bheni agreed, anything that provokes people to give up easily is the enemy of adoption.

**Comment by oscarbatori** [comment]
I think we need to look at this again at some point, as @timsehn also raised a similar issue [here](https://github.com/liquidata-inc/ld/issues/1863).
