### ISSUE TITLE
[Feature Request] Consider branch auto-fetch on connection for replicas

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#5108]
Connecting to a branch directly in the connection string via `dbName/branchName` only works if the db has the branch locally. If that branch only exists in the remote, you need to first connect to `dbName` (which will connect to the default main branch) or some other branch that exists locally in the db, and then checkout the desired branch (which implicitly triggers the fetch).

One area this comes up more is in the case of a replication setup (specifically, [replication via remote](https://docs.dolthub.com/sql-reference/server/replication#replication-through-a-remote)). In this case, you have a backing remote db, and you spin up a write node + read replicas. The write node is cloned from the remote, but does not have any branches locally other than main to start with. So trying to connect to known branches on the remote via a direct `dbName/branchName` connection string doesn't work.

In this kind of setup, it could be convenient to not need to be concerned with the replication details - you simply connect to the write/read replicas as you would the backing remote db.

**Comment by fulghum** [comment]
Jennifer is going to take a look at this one for us. Thanks @jennifersp!

**Comment by jennifersp** [comment]
Fix, https://github.com/dolthub/dolt/pull/5132, is merged to main. It will be included in the next Dolt release.
