### ISSUE TITLE
Using `--result-fomat` gives an error when requesting the working head of a repository using the `@@db_working` system variable

### ISSUE THREAD

**Issue by crisp-snakey** [dolthub/dolt#5158]
Using the `dolt sql` command with a specified `--result-format` results in an error complaining about an unexpected StringType.

Example asking for the working head without a result-format:
```
 % dolt sql --query 'select @@foo_working as working'                    
+----------------------------------+
| working                          |
+----------------------------------+
| bfcdviirnq7baf9lmu0osu5pk5er8jps |
+----------------------------------+
```

Performing the same query with a result-format:
```
 % dolt sql --query 'select @@foo_working as working' --result-format csv 
error on line 1 for query select @@foo_working as working: expected "StringType" from SQL basetype "VarChar"
expected "StringType" from SQL basetype "VarChar"
```

Other (similar) queries do work when specifying a result-format:
```
 % dolt sql --query "select HASHOF('HEAD') as working" --result-format csv
working
vo83mf07ki0hug20ov952i7l60nb8ads
```

This was using the latest version:
```
 % dolt version
dolt version 0.52.5
database storage format: NEW ( __DOLT__ )
```

**Comment by timsehn** [comment]
@zachmu is gonna crank this one out.

**Comment by fulghum** [comment]
Thanks again for taking the time to send us this feedback @crisp-snakey! This fix has been released now. 

Let us know if you hit any other snags, or have any more feedback for us – we'd love to hear from you again.
