### ISSUE TITLE
Datagrip cannot connect

### ISSUE THREAD

**Issue by markschwarz** [dolthub/dolt#516]
The world needs dolt!  I'm excited and poking around.  I didn't get as far as I'd hoped.

To reproduce:
1. Install dolt.
2. Pull the Liquidata/corona-virus.
3. Run 'dolt sql-server'
4. Connect Datagrip to look around.  'jdbc:mysql://localhost:3306/'

Expected: Connection succeeds.
Actual: Connection to @localhost failed.  [HY000][1105] unknown error: column "utf8" could not be found in any table in scope.

I've tried setting my character set explicitly and running the server in debug mode.  I've not run a mysql host in forever.  I did some basic poking:

https://medium.com/@manish_demblani/breaking-out-from-the-mysql-character-set-hell-24c6a306e1e5

debug mode shows no error.  It does show Datagrip checking settings on connection: "/* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout"

**Comment by timsehn** [comment]
Thanks for the vote of confidence and the issue.

I've copied Zach (@zachmu ) who is in charge of the MySQL server. I think this may have something to do with connection strings. We don't support every type of connection yet and that definitely needs some documentation.

In the meantime, you can access the data offline using `dolt sql`. That opens an interactive shell or you can run individual queries with `dolt sql -q`.

**Comment by zachmu** [comment]
Hi Mark,

I've got this mostly working in Datagrip. The big missing piece of the puzzle is that sql-server is currently read-only, which makes SQL IDEs like Datagrip a lot less useful. See this issue:

https://github.com/liquidata-inc/dolt/issues/549

We're planning on releasing changes to make Datagrip work with sql-server next week, ahead of changes to persist writes to sql-server. Just be aware that this initial release will be read-only until our next release (2 weeks later).

**Comment by zachmu** [comment]
Mark,

When you have a chance, can you try this again with the newest release? It seems to work for me, but could use some more testing. I'm using datagrip via GoLand on Windows.

Known limitations:
1) 1 concurrent connection to the DB https://github.com/liquidata-inc/dolt/issues/579
2) Views can't be opened https://github.com/liquidata-inc/dolt/issues/581

If you find any other issues, please let us know!

**Comment by ptman** [comment]
Is there a GUI MySQL client that can connect? I've tried dbeaver, squirrel, sequeler etc. and it just doesn't seem to work

**Comment by timsehn** [comment]
We need to get those all working. Someone on the team uses TablePlus.

**Comment by timsehn** [comment]
@ptman do you mind making a new issue for each of those clients. Our goal is to make them all work and write tests making sure the SQL statements they issue are supported.

**Comment by VinaiRachakonda** [comment]
Datagrip should work as per https://docs.dolthub.com/reference/performance/latency

**Comment by markschwarz** [comment]
@zachmu, thanks for the clear communication.  I've finally retested this in both GoLand and DataGrip (Mac, Apple Silicon).  I still got the 'utf8' error above when using the mySQL 8.0.11 JDBC driver. 

If I switch to Amazon's Aurora mySQL JDBC driver in GoLand or DataGrip, I can get logged in to dolt sql-server without errors.  Details below.  A sample query works well, if I have no errors in my query.   If I type a query incorrectly, I get a great error message from the sql-server engine, along with a java.lang.NullPointerException from Datagrip for each error.  It's working!
 

DBMS: MySQL (ver. 5.7.9-Vitess)
Case sensitivity: plain=exact, delimited=exact
Driver: MariaDB Connector/J (ver. 2.7.3, JDBC4.2)
Effective version: MySQL (ver. 8.0.11)

I found that the JDBC connection setting for 'characterEncoding' is the culprit. If I change this to any other value in Datagrip/Goland, the error message above changes.  It appears that the mySQL 'show character set;' command is not supported in Dolt.  I'm guessing this is related.

**Comment by zachmu** [comment]
Thanks for the info, @markschwarz . We'll investigate the character set issues and see if it can be fixed this week.

**Comment by zachmu** [comment]
Vinai, I meant to assign this to you and dropped the ball. You're working on something similar now I believe.

**Comment by VinaiRachakonda** [comment]
@markschwarz 

`show character set` has been implemented.

I also tested Datagrip/Dolt with both a MySQL driver and a MariaDB driver and did not see any problems. Please let me know if you see the error persists with the most recent version of Dolt.
