### ISSUE TITLE
translate count(*) to count(1) automatically

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#5171]
Customer reports that query `select count(*) from table where col is null` is consuming 100% CPU and not returning. Table has approximately 1M rows. Same query with `count(primary_key_col)` is fast, as expected.

**Comment by timsehn** [comment]
This was diagnosed to be related to the use of text columns which are blobs.

**Comment by zachmu** [comment]
Remaining work here is to automatically translate count(*) into count(1) in the analyzer. Updating description.
