### ISSUE TITLE
One-time "optimistic lock failed on database Root update" on read replicas after dolt upgrade

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#5183]
After upgrading from Dolt 0.52.8 to 0.52.9, the initial checkout of any given branch on a read replica is producing the error:

`CALL DOLT_CHECKOUT('branchName'); - optimistic lock failed on database Root update`

Trying again on a new connection works without issue.

**Comment by timsehn** [comment]
@zachmu will look at this after he debugs his current issue.

**Comment by zachmu** [comment]
This is fixed, sorry for not updating sooner.
