### ISSUE TITLE
Extremely variable `dolt pull` download speeds

### ISSUE THREAD

**Issue by radao** [dolthub/dolt#5194]
Calling `dolt pull` on a ~70MB repository results in download speeds ranging from single digits B/s bursting to hundreds of Kb/s for a few seconds and back down again. Is this speed/variability expected?

**Comment by timsehn** [comment]
Can I get a few more details? 

Is this against DoltHub or another remote? https://docs.dolthub.com/sql-reference/version-control/remotes

Is this on a network where you expect consistent speeds?

**Comment by radao** [comment]
> Can I get a few more details?
> 
> Is this against DoltHub or another remote? https://docs.dolthub.com/sql-reference/version-control/remotes
> 
> Is this on a network where you expect consistent speeds?

I'll try to get some benchmarks. Seems to be fine now, was very slow yesterday when I was running some tests.

This was against DoltHub and using a high speed office connection.

**Comment by timsehn** [comment]
We were having an operational issue with DoltHub a couple of days back when this was cut. I suspect that was the root cause. These should be rare.

We have seen some issues with overseas home connections as well. I'm going to resolve. Reopen if you have more information.
