### ISSUE TITLE
Dolt SQL: Support 'on duplicate key update'

### ISSUE THREAD

**Issue by katiemcculloch** [dolthub/dolt#520]
Added skipped bats test here: https://github.com/liquidata-inc/dolt/pull/519

This SQL feature would be incredibly powerful for a repository that is stitching together many data sources that all share the same primary key (i.e. Liquidata/country-codes, most datasets out there have the ISO-3166-1-Alpha-3 country code, and then a handful of different columns depending on the source). Right now I have to do some tedious CSV sorting and joining that could be solved for with this sort of flexible insert.

**Comment by zachmu** [comment]
Until we implement this, REPLACE INTO statements are supported and do the same thing.

**Comment by katiemcculloch** [comment]
Per offline discussion, I think REPLACE will create a new row if the row is not found, but you are not able to define what columns should join between the new and old row.

**Comment by zachmu** [comment]
This is now supported
