### ISSUE TITLE
Optionally `SHOW SCHEMAS` should show all `db.branch` combinations available

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5219]
In Apache Superset (and likely other tools), there's no way to access version history because there are no custom queries.

When I inspect the debug log of how Superset is finding the databases available I see:
```
2023-01-25T16:21:45-08:00 DEBUG [conn 2] Query finished in 0 ms {connectTime=2023-01-25T16:21:45-08:00, connectionDb=simple_example, query=SHOW schemas}
```

I need a way to have `SHOW schemas` or `SHOW databases` return all `db.branch` pairs. Then I could access branches via the Superset UI. This could be done by setting a dolt system variable.

If I wanted a old commit I could just use `call dolt_checkout()` in supersets SQL UI.

Superset makes a new connection on every query to the db so I can't rely on `dolt_checkout()` persisting across connections.

**Comment by timsehn** [comment]
The system variable could be something like `@@dolt_show_branch_databases`

**Comment by timsehn** [comment]
Somewhat related #2073

**Comment by fulghum** [comment]
Zachmu got this implemented in https://github.com/dolthub/dolt/pull/5223
