### ISSUE TITLE
EXPLAIN with uuid_to_bin is not working in IntelliJ IDEA (like DataGrip)

### ISSUE THREAD

**Issue by nkonev** [dolthub/dolt#5287]
Repro:

```
echo 'create database companies;' > /tmp/init.sql
docker run --rm -v /tmp/init.sql:/docker-entrypoint-initdb.d/init.sql -p 3306:3306 -t dolthub/dolt-sql-server:0.52.19
```

Then add MySQL database
![Screenshot from 2023-02-02 23-27-55](https://user-images.githubusercontent.com/3160384/216430857-bf027efc-e6dc-40f9-a43f-bc390b3a9aa3.png)

Then open console, create tables
![Screenshot from 2023-02-02 23-21-29](https://user-images.githubusercontent.com/3160384/216431011-17a6e221-7e40-48e9-92fa-8087b0107bdc.png)
```sql
CREATE TABLE company(
                        id binary(16) DEFAULT (UUID_TO_BIN(uuid())) PRIMARY KEY,
                        name varchar(255),
                        bank_account varchar(255),
                        estimated_size int,
                        modified_at TIMESTAMP
);

CREATE TABLE mapping(
                        branch_id binary(16) PRIMARY KEY,
                        user_id binary(16) NOT NULL,
                        company_id binary(16) NOT NULL
);
```

Then run
```
EXPLAIN SELECT m.* FROM mapping m WHERE user_id = uuid_to_bin('1c4c4e33-8ad7-4421-8450-9d5182816ac3');

```

Error will be like
```
[HY000][1105] failed to encode `utf8mb4`
```
![Screenshot from 2023-02-02 23-31-46](https://user-images.githubusercontent.com/3160384/216431435-2042c46d-a043-4ed7-ba8a-d04b3f52a545.png)

In the logs I see
```
2023-02-02T19:49:10Z WARN [conn 4] error running query {connectTime=2023-02-02T19:21:31Z, connectionDb=companies, error=failed to encode `utf8mb4`, query=/* ApplicationName=IntelliJ IDEA 2022.3.1 */ EXPLAIN SELECT m.* FROM mapping m WHERE user_id = uuid_to_bin('1c4c4e33-8ad7-4421-8450-9d5182816ac3')}
```

---

In MySQL it works
```
echo 'create database companies;' > /tmp/init.sql
docker run --rm -v /tmp/init.sql:/docker-entrypoint-initdb.d/init.sql -p 13306:3306 -t -e MYSQL_ROOT_PASSWORD=SupErOassword mysql:8.0.32-debian
```
![Screenshot from 2023-02-02 23-36-08](https://user-images.githubusercontent.com/3160384/216432418-9eb40218-6c41-42cb-b4da-156fc206e8d4.png)

![Screenshot from 2023-02-02 23-36-37](https://user-images.githubusercontent.com/3160384/216432451-a51c6a3d-d689-4f9c-8429-0b0ff94a8bf0.png)

---

looks related to https://github.com/dolthub/go-mysql-server/pull/1566, I noticed this bug on version 0.52.8 also

**Comment by timsehn** [comment]
Collations plus info schema gonna be the bain of our existence :-) 

@jennifersp will grab this next.

**Comment by nkonev** [comment]
It works from 0.53.0, thank you, team!
