### ISSUE TITLE
Argument order is very important to the dolt CLI

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/dolt#5305]
I'm trying to run `dolt sql-server` with some parameters, but the CLI is very picky when it comes to the order of argument/commands.

Here are all the parameters I'm trying to pass to dolt:
- `sql-server`
- `--ignore-lock-file`
- `--prof mem`
- `--config ./dolt-config.yaml`

Below are the various orderings that do not work, as well as the errors they show (errors are also inconsistent):
```
# fails with "Unknown Command --config"
dolt \
    --ignore-lock-file \
    --prof mem \
    --config ./dolt-config.yaml \
    sql-server \

# fails with "error: unknown option `ignore-lock-file'" and shows help
dolt \
    sql-server \
    --ignore-lock-file \
    --prof mem \
    --config ./dolt-config.yaml \

# fails with "error: unknown option `prof'" and shows help
dolt \
    --ignore-lock-file \
    sql-server \
    --prof mem \
    --config ./dolt-config.yaml \

# fails with "Unknown Command --config"
dolt \
    --ignore-lock-file \
    --prof mem \
    --config ./dolt-config.yaml \
    sql-server \
```

And this is the only order that I've tried that works (lock file is ignored, memory profiling is enabled, and configs are taken into account):
```
dolt \
    --ignore-lock-file \
    --prof mem \
    sql-server \
    --config ./dolt-config.yaml \
```

Should the order or arguments matter?

Additionally, the [sql-server documentation](https://docs.dolthub.com/cli-reference/cli#text-dolt-sql-server) states
> If `--config <file>` is provided all other command line arguments are ignored.
But this is clearly wrong:
- omitting `--ignore-lock-file` results in the error `Failed to setup the temporary directory. failed to create temp dir './.tmp': mkdir ./.tmp: read-only file system`
- if omitting `--prof mem`, profiling is not enabled

**Comment by timsehn** [comment]
@zachmu has a configuration rationalization document. Maybe you can tackle this after we get NTC working :-)

**Comment by reltuk** [comment]
FWIW, what's happening here is that some of the arguments are to the `sql-server` command and some of the arguments are to the dolt binary as a whole. Maybe not the best UX, but pretty common in general -- `kubectl` behaves this way, `bazel`, and even `git` itself behaves this way. For example,

* `git -v add somefile` <--- print the git version, does not add a file,
* `git add -v somefile` <--- add `somefile` to the git index, run in verbose mode.

**Comment by PavelSafronov** [comment]
@reltuk , fascinating, I had no idea about this behavior.

In that light, the current behavior seems accurate. Feel free to close this issue.

**Comment by PavelSafronov** [comment]
It would be nice to upgrade the documentation to reference this particular behavior: https://docs.dolthub.com/cli-reference/cli
There is also no mention of the `dolt` binary and the various flags/arguments that it supports, like `--ignore-lock-file`, `--prof mem`, and `--pprof-server`. Would be good to explicitly document these.
