### ISSUE TITLE
Dump of `dolt_schemas` table not compatible with MySQL. Maybe need a `views` option with `dolt`, `none`, or `mysql` as options?

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5318]
Error is:
```
$ mysql -uroot < doltdump.sql
ERROR 1071 (42000) at line 459: Specified key was too long; max key length is 3072 bytes
```

Here's a drive link to the dump file.

https://drive.google.com/file/d/1z1AQBDKVPSXb9zIBo0aNS-Ckfx8vHfM_/view?usp=share_link

Now I opened the file up in `emacs` went to line 459 and it was the `dolt_schemas` table. I deleted that and the dump imported fine.

Maybe need a `views` option with `dolt`, `none`, or `mysql` as options?

**Comment by JCOR11599** [comment]
Alternatively, we could change the `dolt_schema` schema to be compatible with MySQL?
Like this:
```sql
DROP TABLE IF EXISTS `dolt_schemas`;
CREATE TABLE `dolt_schemas` (
  `type` varchar(64),
  `name` varchar(64),
  `fragment` longtext,
  `id` bigint NOT NULL,
  `extra` json,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fragment_name` (`type`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
```

It's worth noting that removing the Unique Key gives us a different error (which is why `fragment` should be `longtext`):
```
ERROR: 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```
