### ISSUE TITLE
Long running queries on dolthub.com timeout with confusing UI error message

### ISSUE THREAD

**Issue by tomdottom** [dolthub/dolt#532]
When running the following against the `Liquidata/github-repos` data repo

```sql
SELECT *
FROM `repos`
WHERE `name` LIKE '0---0/%'
LIMIT 10;
```

The UI displays the following error:

> Network error: Unexpected token u in JSON at position 0

The related graphql request gives the message:

```
upstream request timeout
```

OG Query:

https://www.dolthub.com/repositories/Liquidata/github-repos/query/master?q=SELECT%20*%0AFROM%20%60repos%60%0AWHERE%20%60name%60%20LIKE%20%270---0%2F%25%27%0ALIMIT%2010%3B%0A%0A%0A%0A%0A%0A

**Comment by timsehn** [comment]
That's a300Gb repo. You'll have to run that query locally :-)

**Comment by tomdottom** [comment]
I have just discovered it was BIG :laughing: 

```
error: clone failed
cause: write .dolt/noms/bnfhsntlotg5k2i0a7rg3h7lattqrhtq: no space left on device
```

However, a nice UI error message for queyr timeouts might be more user friendly :)

Lastly, I fully support #507

**Comment by timsehn** [comment]
Agreed :-) We'll keep the issue open.

**Comment by zachmu** [comment]
We've gotten a lot better at this -- you can now query a few millions rows before getting these timeouts. The error message is also better now.
