### ISSUE TITLE
Old versions of dolt not available through homebrew

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/dolt#5324]
Only the current/latest version of dolt appears to be installable from brew, none of the old versions are available. It doesn't even seem possible to specify a version.

Right now, the latest version is 0.52.20, but it's not possible to install this version by specifying the version:

```sh
brew install dolt@0.52.20
Warning: No available formula with the name "dolt@0.52.20".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for dolt@0.52.20.
```

Or an older version:
```sh
brew install dolt@0.52.10
Warning: No available formula with the name "dolt@0.52.10".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for dolt@0.52.10.
```

**Comment by timsehn** [comment]
I don't think we're going to fix this.
