### ISSUE TITLE
Cloning a dolt repo onto a virtual machine 

### ISSUE THREAD

**Issue by nilswachsmuth-imtf** [dolthub/dolt#5344]
Hi Dolt team,

We are trying to use dolt on a virtual machine. After `dolt status` we get that we are on the main branch, so dolt is installed. However, when we try to clone the needed dolt repo we get the following error:

<img width="1293" alt="Screenshot error message dolt" src="https://user-images.githubusercontent.com/110540593/218124355-040d8052-c53f-4681-a0fe-9a07bd1c6994.png">

Any chance we can get some help on this?

Thanks a lot!!

**Comment by nilswachsmuth-imtf** [comment]
We also checked the credentials. Using ‘dolt creds ls’, we see that we use credentials that are linked to our account.

**Comment by fulghum** [comment]
Hey @nilswachsmuth-imtf, thanks for reaching out. We're happy to help. Could you run `dolt version` and let us know what version of the Dolt command line you're using on that virtual machine? The error about `unsupported repo format (__DOLT__)` makes me think there might be an out of date version. 

It looks like you are using DoltLab, so I'm also tagging @coffeegoddd as well just in case he sees any other clues.

**Comment by coffeegoddd** [comment]
@nilswachsmuth-imtf I sent an email with my proposed fix. I believe this has to do with the versions of DoltLab and Dolt you are using. Please upgrade to the latest [DoltLab](https://github.com/dolthub/doltlab-issues/releases/tag/v0.7.4) and [Dolt](https://github.com/dolthub/dolt/releases/tag/v0.52.20) and let me know if the problem persists. The DoltLab `docker-compose.yaml` file should have the `-allow-nbf-dolt` flag set in the `doltlabremoteapi` block.

**Comment by timsehn** [comment]
I'm going to cloe this. Please reopen if the issue persists after upgrade.
