### ISSUE TITLE
unexpected error when using div operation

### ISSUE THREAD

**Issue by rbasa** [dolthub/dolt#5369]
My db repo: https://www.dolthub.com/repositories/bitfinex/securities-analysis
If I use `/` i have a small discrepancy on the result, which is solved in the following PR using the div operator: https://github.com/dolthub/go-mysql-server/pull/1365
But when using my div in this query i get an error BIGINT value is out of range (0 DIV 314990)
when this should give a result like -0.0158417728

> with temp_table as (
  ->   select
  ->     a.date,
  ->     a.asset_id,
  ->     a.accrued_interest,
  ->     a.clean_price,
  ->     a.dirty_price,
  ->     a.fx_return,
  ->     coupon,
  ->     b.dirty_price as dirty_price_y,
  ->     b.clean_price as clean_price_y,
  ->     b.accrued_interest as accrued_interest_y
  ->   from
  ->     debt_asset_market a
  ->   join
  ->     debt_asset_market b
  ->   on
  ->     a.asset_id = b.asset_id and
  ->     b.date = date_add(a.date, interval -1 day)
  ->   join
  ->     debt_asset c
  ->   on
  ->     a.asset_id = c.asset_id
  ->   where 
  ->     a.date = '2022-03-31'
  -> )
  ->  select
  ->   (clean_price - clean_price_y + fx_return) div dirty_price_y as price_return
  -> from 
    ->   temp_table;
BIGINT value is out of range (0 DIV 314990)

**Comment by fulghum** [comment]
Thanks for reporting this one @rbasa. I was able to get a simple repro for this one:

```sql
create table t (d decimal(25,10) primary key);

insert into t values (-4990);

select d div 314990 from t;
BIGINT value is out of range (-4990 DIV 314990)
```

This error is only returned in one place, so there's something incorrect in this code:
https://github.com/dolthub/go-mysql-server/blob/cef3e5981b7c0e320f47d9c820c291204ed03bec/sql/expression/div.go#L723

@jennifersp – since you've got good context on this code, could you take a quick look and see if you can spot the problem?

**Comment by fulghum** [comment]
Hey @rbasa, thanks again for taking the time to report this so we could get it fixed! 🙏 Jennifer has the fix merged into `go-mysql-server` and we'll run a Dolt release this evening or tomorrow. Feel free to holler if you'd like a release faster than that and we'll be happy to run one for you. 

Let us know if you hit any other snags and we'll jump on it.

**Comment by rbasa** [comment]
Great, thanks for dedicating the necessary time to resolve the issue!
