### ISSUE TITLE
Mysql Database import fails `duplicate primary key given: [1]`

### ISSUE THREAD

**Issue by wp4nuv** [dolthub/dolt#5394]
I have initialized a new directory for dolt operations and started importing a mysqldump file when the execution stopped due to a duplicate key given. I verified on the database from where the mysqldump came from using this query:
```
SELECT 
    id, 
    COUNT(id)
FROM
    master_loans.brokerages
GROUP BY id
HAVING COUNT(id) > 1;
```
and, as expected, it came back empty.  I'm not sure what exactly is happening here. Is there a way to see logs or other execution statements that may help resolve this?

**Comment by timsehn** [comment]
Can you send us the dump file? Even obfuscated works. That should not happen.

**Comment by timsehn** [comment]
Without m ore information, we have to close. Let us know if you have a better repro.
