### ISSUE TITLE
dolt clone command only output is the word 'Killed'

### ISSUE THREAD

**Issue by dcritchfield-threekit** [dolthub/dolt#5405]
When trying to clone a large database from a GCS bucket into a pod that has a smaller persistent volume mounted than the bucket size, the clone command hangs with no output until the process eventually outputs the word "Killed" and does not proceed with any download. No other error information is printed.

**Comment by timsehn** [comment]
This could be related to #5405

**Comment by timsehn** [comment]
Customer reports this is on a fresh deployment so unlikely related to #5405.

**Comment by timsehn** [comment]
Going to resolve as we can't control what the OS does when it OOMs.
