### ISSUE TITLE
Add support for `dolt show`

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#5425]
Similar to `git show` - commonly used to look at a commit, and combine the commit description and the diff.

https://git-scm.com/docs/git-show - It's also used to look at internal objects, which is not really necessary to emulate.

**Comment by solipsis-project** [comment]
I like the idea of being able to look at internal objects, I think it would be a useful onboarding tool. But it looks like doing just commits to start will make the implementation simpler.

The first spec for this can be really simple:

Dolt Show

dolt show [<object>…​]

object is required to be a commit_spec. That is, one of the following:
- HEAD
- commit hash
- branch, tag, or remote name
- an expression using one of the above (such as "HEAD~")

If not provided, HEAD is assumed.

There are no current options for this command.

Output:

```
commit hp4q6avd9k9606984kgu54j4es1p2rj3 (HEAD -> main)
Author: Solipsis Project <the.solipsis.project@gmail.com>
Date:  Fri Mar 10 16:13:39 -0800 2023

        Add employee table
		
diff --dolt a/employees b/employees
added table
+CREATE TABLE `employees` (
+  `id` int NOT NULL,
+  `first_name` varchar(16383),
+  `last_name` varchar(16383),
+  PRIMARY KEY (`id`)
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
+---+----+------------+-----------+
|   | id | first_name | last_name |
+---+----+------------+-----------+
| + | 0  | Tim        | Sehn      |
| + | 1  | Brian      | Hendriks  |
| + | 2  | Aaron      | Son       |
+---+----+------------+-----------+
```

**Comment by solipsis-project** [comment]
Pull request created at https://github.com/dolthub/dolt/pull/5564

**Comment by nicktobey** [comment]
Should we leave this open as a low-priority issue for inspecting internal objects (as `git show` does?) Or should that be a new issue?

**Comment by timsehn** [comment]
New issue I think.
