### ISSUE TITLE
Connecting via linux mysql client won't accept password as '-p' option

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#5427]
An odd find, and possibly not a Dolt issue, but when using the builtin mysql client on Ubuntu 22.04 to connect to a local dolt server, the following works:

```
mysql -u bob --password=<password> -h 127.0.0.1
```
But this form gives `ERROR 1045 (28000): Access denied for user 'bob'` :
```
mysql -u bob -p <password> -h 127.0.0.1
```

The '-p' format works fine with the same options on the sql-client provided with Dolt. So it seems to be something about the way Dolt is processing the short and long formats of the password option from the mysql client.

**Comment by timsehn** [comment]
I think in this form you have to remove the space. I have had this issue before. So:

`mysql -u bob -p<password> -h 127.0.0.1`

This will repro on MySQL as well. It is a mysql client feature me thinks.

**Comment by dphil** [comment]
Yep, that's it. Thankyou.
