### ISSUE TITLE
dolt_diff() missing `from_` columns when table created

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#5439]
```
> create table test (k int, v int);
> insert into test values (1,10);
> call dolt_add('test');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

> call dolt_commit('-m', 'create table with data');
+----------------------------------+
| hash                             |
+----------------------------------+
| 24mree5f724sn0kqo0p6s20r9urbhfq0 |
+----------------------------------+
1 row in set (0.00 sec)

> select * from dolt_diff('HEAD~1','HEAD','test');
+------+------+-----------+-------------------------+-------------+-------------------------+-----------+
| to_k | to_v | to_commit | to_commit_date          | from_commit | from_commit_date        | diff_type |
+------+------+-----------+-------------------------+-------------+-------------------------+-----------+
| 1    | 10   | HEAD      | 2023-02-28 01:05:43.138 | HEAD~1      | 2023-02-28 01:02:39.441 | added     |
+------+------+-----------+-------------------------+-------------+-------------------------+-----------+
1 row in set (0.00 sec)
```

The columns `from_k' and 'from_v` are expected to be returned. When additional rows are added, the results of the `dolt_diff()` method are as expected'

```
> insert into test values (2,100);
> call dolt_add('test');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

> call dolt_commit('-m', 'add data to test table');
+----------------------------------+
| hash                             |
+----------------------------------+
| nsb04rhng14bp35a6vhjnvs2saksmafs |
+----------------------------------+
1 row in set (0.00 sec)

> select * from dolt_diff('HEAD~1','HEAD','test');
+------+------+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
| to_k | to_v | to_commit | to_commit_date          | from_k | from_v | from_commit | from_commit_date        | diff_type |
+------+------+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
| 2    | 100  | HEAD      | 2023-02-28 01:08:45.606 | NULL   | NULL   | HEAD~1      | 2023-02-28 01:05:43.138 | added     |
+------+------+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
1 row in set (0.00 sec)
```

Conversely, data removed during a table drop will not show the `to_k` and `to_v` columns:

```> drop table test;
> call dolt_add('test');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

> call dolt_commit('-m', 'drop the table and data');
+----------------------------------+
| hash                             |
+----------------------------------+
| 629d2mimpk168rsbie5s0q2gob81meqk |
+----------------------------------+
1 row in set (0.00 sec)

> select * from dolt_diff('HEAD~1','HEAD','test');
+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
| to_commit | to_commit_date          | from_k | from_v | from_commit | from_commit_date        | diff_type |
+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
| HEAD      | 2023-02-28 01:21:38.303 | 2      | 100    | HEAD~1      | 2023-02-28 01:08:45.606 | removed   |
| HEAD      | 2023-02-28 01:21:38.303 | 1      | 10     | HEAD~1      | 2023-02-28 01:08:45.606 | removed   |
+-----------+-------------------------+--------+--------+-------------+-------------------------+-----------+
2 rows in set (0.00 sec)
```

Finally, I was able to verify that this behavior does not manifest if the table is created in it's own commit, and data is added to it ina different commit.

The expected behavior would be that all of the `from_*` and `to_*` columns would consistently show in the results returned from `dolt_diff()`

**Comment by fulghum** [comment]
Good concrete examples. `dolt_diff()` creates its schema from the table's schema at `from_commit` plus the table's schema at `to_commit`, so when there isn't a schema at one of those commits, it doesn't include any `to_` (or `from_`) columns, which I guess is accurate... but not very helpful. 😊

If a table doesn't exist at either `to_commit` or `from_commit`, it seems like we should reuse the table's schema from the other commit so that we still have a `from_` and a `to_` set of columns. That makes the output make a little more sense, although does slightly complicate the mental model for `dolt_diff()` ("use the schema at `to_commit` for `to_` columns, and the schema at `from_commit` for `for_` columns, _unless one doesn't exist..._"). 

There are also other valid reasons customers would want to select different schemas, so could be interesting to think for a minute about other ways to give even more control of the diff results schema.

**Comment by macneale4** [comment]
There may be a better way to represent schema changes, but I'm sure this particular edge case serves no one. It strictly forces the caller to have special logic to handle for the concern of missing columns. If they aren't interested in the columns they simply to select for them.

Can you elaborate on complicating the mental model for `dolt_diff()`? Looking at the code in a debugger, fromSch and toSch are non-nil in every case [here](https://github.com/dolthub/dolt/blob/5cf46262d4e4a5d5d55e42d87c78872efb932314/go/libraries/doltcore/sqle/dtables/diff_table.go#L906) with the exception of when the table has been added or dropped. I propose we simply use `fromSch = toSch` which `fromSch = nil` and visa versa.
