### ISSUE TITLE
Dolt does not work with the Postgres MySQL Foreign Data Wrapper

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5441]
Corresponding `mysql_fdw` issue: https://github.com/EnterpriseDB/mysql_fdw/issues/218

There are debug steps in there but @reltuk was able to easily reproduce. He should put his debug steps in here.

**Comment by timsehn** [comment]
This should be resolved correct? @JCOR11599 @reltuk ?

**Comment by JCOR11599** [comment]
After adding a limited implementation of MySQL's Server Side Cursors, dolt appears to be working with MySQL FDW 2.9.0

https://github.com/dolthub/dolt/issues/3029#issuecomment-1504222417
