### ISSUE TITLE
Slow join orders

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5444]
Dolt's analyzer currently choses inefficient join plans when filters are involved.

To compute an optimal join order, we need two pieces of perfect information:

1) How expensive it is to execute an expression in a certain way with a certain number of input rows.

2) How many rows will an expression output.

If a join plan has all cross joins and no filters, every combination of every row will be returned. But most of the time there are filters that toggle the selectivity of join expressions. For example, a well-placed join filter with a selectivity of .0005 will reduce a 100x100 row join to only 5 output rows. On the other hand, a join filter with a selectivity of 1.0 will input 10x100 rows and output 1000 rows. If we just went by table sizes, the second deceivingly appears more promising.

We lack the statistics about column distributions to accurately estimate how many output rows a join expression returns. In the absence of histograms and index statistics, we fallback to table size and execution strategies as rough proxies for expression cardinality (output row number).

For example, the query below for the [quest-v4 database](https://www.dolthub.com/repositories/dolthub/quest-v4) returns in 1 second with the join hint, but takes much longer without. By default we front-load the smallest tables in the join, expecting to minimize the number of output rows. However joining two larger tables with highly selective filters dramatically reduces the number of rows passed to higher levels of the join tree.

```sql
SELECT /*+ JOIN_ORDER(c,r,i,pm,trf,nt) */
        r.id,
        r.negotiated_rate,
        nt.npi,
        i.reporting_entity_name,
        i.reporting_entity_type, 
        c.billing_code_type_version,
        c.billing_code,
        service_code,
        pm.expiration_date,
        pm.additional_information,
        pm.negotiated_type,
        pm.billing_code_modifier 
FROM rate r
JOIN insurer i
  ON r.insurer_id = i.id
    AND i.reporting_entity_type IN (
        'Health Insurance Issuer',
        'Health Insurance Network',
        'Insurer',
        'INSURER',
        'health insurance issuer',
        'HEALTHINSURANCEINSURER',
        'Shared Administration Vendor',
        'Rental Network',
        'Health insurance issuer',
        'Health Insurance network',
        'Heath Insurance Network'
    )
JOIN code c
  ON r.code_id = c.id
    AND c.billing_code_type = 'CPT'
    AND c.billing_code = '81404'
JOIN price_metadata pm
  ON r.price_metadata_id = pm.id
    AND date(pm.expiration_date) > date('2023-01-01')
JOIN tin_rate_file trf
  ON [r.id](http://r.id/) = trf.rate_id
JOIN npi_tin nt
  ON trf.tin_id = nt.tin_id
ORDER BY
  c.billing_code,
  i.reporting_entity_name,
  nt.npi;
  ```

**Comment by timsehn** [comment]
We now have implemented table stats and analyze to produce correct join orders.
