### ISSUE TITLE
Ability to "project" schema at a commit onto data at another commit

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#5486]
In MySQL, an error rightfully gets thrown when a non-existent column is selected.

Being a versioned database, I wonder if it's worthwhile to provide a querying statement that would allow unfound columns to gracefully return `null`. It's possible to have a Dolt table in "state 1" contain columns `Name`, `id`; and then perform a migration and commit the table in "state 2" with columns `Name`, `Birthdate`, `id`.

Table at "state 1":

| Name | id |
| --- | --- |
| text | int |

Table at "state 2":

| Name | Birthdate | id |
| --- | --- | --- |
| text | date | int |

Standard query:

With Dolt checked out at "state 1", this query throws an error:

```sql
SELECT Name, Birthdate
FROM people;
```

While still checked out at "state 1", this hypothetical query could avoid errors:

```sql
BEGIN;
CALL safe_query("Birthdate"); -- declare "Birthdate" as a column that may return `null` if it doesn't exist
SELECT Name, Birthdate
FROM people;
COMMIT;
```

This is a long shot (and a rough sketch), but thought I'd ask since it would save work for Dolt consumers having to `DESCRIBE table` and check existence of columns before performing queries through historic data or migrations.

**Comment by timsehn** [comment]
Intrestesitng idea!

I think our workaround here is to use the `dolt_diff_tablename` system table but I think that even has some issues with schema changes. 

Your use case is you want a query that returns successfully across all `as of` or checked out branches even if the columns are not defined in the tables at that commit hash.

**Comment by theetrain** [comment]
> Your use case is you want a query that returns successfully across all as of or checked out branches even if the columns are not defined in the tables at that commit hash.

That's right, the xyproblem so to speak is, "I want to have some assurance or safety in writing queries that will be backwards-compatible as I add or remove columns during table migrations across commits."

**Comment by timsehn** [comment]
One idea here is to add a table function that casts a set of data to a schema revision. Something like:

`dolt_select_as_of_pin_schema(<table>, <data commit>, <schema commit>)`

In this case, we "project" the schema from `<schema commit>` onto data at `<data commit>`.

For your use case where you just want NULLs to show up in columns that don't exist, you would call something like:

`dolt_select_as_of_pin_schema('people', 'state-1', 'main')`

This would project the schema on main onto `state-1` branch and show columns that exist in `main` as NULL.

I think this is more generally useful but does require non-standard SQL syntax.

**Comment by timsehn** [comment]
The other option we discussed was having a `@@dolt_pin_schema` variable that does the above for all queries.

**Comment by zachmu** [comment]
We're definitely interested in this problem and will solve it for application developers. We just haven't agreed on a UX for it yet. All options are still on the table.

**Comment by fulghum** [comment]
Hey @theetrain, thanks again for this great feature request. 🙏  We [just published a blog post](https://www.dolthub.com/blog/2024-03-22-schema-overriding/) explaining how to use the new `@@dolt_override_schema` system variable and showing some examples. 

Let us know if we can do anything else to help you build with Dolt!
