### ISSUE TITLE
Additional `dolt_patch` features (three dot, `--schema`/`--data` flags)

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#5491]
Three (and two) dot can use the same pattern as the dolt diff table functions here if you make it a table function instead of procedure: https://docs.dolthub.com/sql-reference/version-control/dolt-sql-functions#table-functions

The `--schema` flag would just output sql statements that alter the table schema

Could also add a `--data` flag that only outputs sql statements that alter the data (less of a priority for me but would be cool)

**Comment by timsehn** [comment]
We also discussed outputting the results with a `statement_order` primary key so that you know the order to apply the SQL statements is explicit.

**Comment by fulghum** [comment]
Including the commit that the generated patch statement comes from would also be nice.
