### ISSUE TITLE
Support CREATE EVENT statement

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5498]
Talked to a customer and they need events supported.

**Comment by timsehn** [comment]
https://dev.mysql.com/doc/refman/8.0/en/create-event.html

**Comment by nkonev** [comment]
Also use case can be following:
automatic scheduled GC calls from EVENT, roughly like auto vacuum in PostgreSQL

**Comment by timsehn** [comment]
Yeah. There are lots of good ones, like creating a Dolt commit on a schedule so your application doesn't need to care

**Comment by timsehn** [comment]
Update here.

The latest dolt release supports creating events as of #5717. The events are stored and versioned in the `dolt_events` table. The stored events do not execute. 

@jennifersp is on vacation for the next two weeks but she will get events executing when she gets back.

**Comment by timsehn** [comment]
#6108 is the PR for event execution. Once that is merged this can be resolved.

**Comment by fulghum** [comment]
[Dolt version 1.17.0](https://github.com/dolthub/dolt/releases/tag/v1.17.0) adds support for executing Scheduled Events
