### ISSUE TITLE
dolt command --help should use a pager

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#5510]
Currently, all dolt commands print and exit when provided the `--help` argument. Unfortunately many commands have more than a page of text, and the user is forced to append `| less` to the end of the command.

Git by default uses a pager when the --help argument is provided, which saves the user time (and annoyance).

**Comment by macneale4** [comment]
One additional detail, when you run a command like `dolt diff --help`, there are bold characters where emphasis is helpful. That is lost when you pipe to less. Using paging like with do with `dolt log` would address this issue.

**Comment by timsehn** [comment]
This is related to #505 which asks for all output to be paged.

**Comment by timsehn** [comment]
Resolving this in favor of more general #505
