### ISSUE TITLE
Function `dolt_push` not found

### ISSUE THREAD

**Issue by grovera-md** [dolthub/dolt#5536]
**Issue**:   
The push function does not work at all. I always get the error `Error SQL [1105] [HY000]: function: 'dolt_push' not found`

**Context**:  
I was trying to setup a simple example of "Filesystem Based Remotes" according to the documentation (https://www.dolthub.com/blog/2021-07-19-remotes/) (https://www.dolthub.com/blog/2021-09-22-sql-remotes/).   
(Note: the test "remote folder" was created in the home directory, and it was not a parent/descendant of the dolt folder) .

I can correctly set the remote and display it with the command `dolt sql -q "select * from dolt_remotes"`. 

But when I  execute the command `dolt sql -q "select dolt_push('origin', 'master')"` (or `dolt sql -q "select dolt_push('origin')"`), I get the above error. The same happens if I try to execute the SQL statement directly in the MySQL editor.

**Comment by timsehn** [comment]
We deprecated the `select` function versions in favor of the `call` procedure versions. So, just do `call dolt_push()` instead.

We did not like selects modifying the state of the database.

**Comment by grovera-md** [comment]
Thank you very much for the prompt feedback. It works.   
Dolt is amazing!  

P.s. I suggest to update the older blog posts with a note about the changed syntax.

**Comment by timsehn** [comment]
Updating old blogs with new syntax is a good idea :-)
