### ISSUE TITLE
dolt log incorrectly identifies HEAD

### ISSUE THREAD

**Issue by solipsis-project** [dolthub/dolt#5558]
The function `log.go::hashIsHead` is used to determine whether a given commit hash is the head of the current working branch... but it's implementation can't possibly be correct.

To observe the incorrect behavior:

1. Create a repo with two commits: commit2 is HEAD, and commit1 is its parent.
2. Tag both commits
3. `dolt log <commit1>` will incorrectly show commit1 to be HEAD
4. `dolt log <commit1> <commit2>` will show neither commit to be HEAD.

I have a fix in the works.

**Comment by fulghum** [comment]
Great find @solipsis-project! Your fix looked clean and correct to me, so I went ahead and merged it in. Thank you! 🙏 

Leaving this issue open so I can throw in a quick BATS test for the incorrect log behavior you pointed out. It would be nice to have an assertion that we aren't incorrectly displaying something as the branch HEAD when it isn't.

**Comment by timsehn** [comment]
Is this fixed?

**Comment by solipsis-project** [comment]
It's fixed, the issue is just staying open pending a BATS test. I have enough experience with BATS now that I should be able to throw together a test without much trouble.

**Comment by fulghum** [comment]
Thanks for sending over the BATS test, too! 🙏  I got it merged in, so resolving this issue now.
