### ISSUE TITLE
dolt table create --help is completely wrong

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#56]
It looks like we've updated the format since writing this, and writing a "valid" schema file according to the documentation will throw a panic instead.

**Comment by oscarbatori** [comment]
@Hydrocharged is this still open?

**Comment by Hydrocharged** [comment]
> 
> 
> @Hydrocharged is this still open?

Yep, just ran the command and made a schema as defined by the help documentation and a panic was still thrown.
