### ISSUE TITLE
Valid SQL column names are not handled correctly by `dolt sql`

### ISSUE THREAD

**Issue by ndac-todoroki** [dolthub/dolt#560]
I tried some CREATE TABLEs, which includes function names as column names.

```sql
doltsql> create table foo (id INT, comment VARCHAR(10));
WARN[0000] ignoring error parsing DDL 'create table bar (id INT, comment VARCHAR(10));': syntax error at position 34 near 'comment' 
Error parsing SQL
While Parsing DDL: syntax error at position 34 near 'comment'
create table bar (id INT, comment VARCHAR(10));
                                  ^
doltsql> create table foo (id INT, level TINYINT(3));
WARN[0001] ignoring error parsing DDL 'create table foo (id INT, level TINYINT(3));': syntax error at position 32 near 'level' 
Error parsing SQL
While Parsing DDL: syntax error at position 32 near 'level'
create table foo (id INT, level TINYINT(3));
                                ^
```

This works on mysql:
```mysql
mysql> create table bar (id INT, comment VARCHAR(10));
Query OK, 0 rows affected (0.01 sec)

mysql> create table foo (id INT, level TINYINT(3));
Query OK, 0 rows affected (0.01 sec)
```

I think these words are not reserved words. Even if I try wrapping those with double quotations, it does not work.

**Comment by timsehn** [comment]
Thanks for the bug. I think the comment one needs to be backticked because
it's a reserved word. Zach, will address why it works on MySQL though.

--Tim

**Comment by timsehn** [comment]
Oh, and there needs to be a primary key in Dolt. so if you append , primary key(id) to each query and backtick comment and level (did not know level was a reserved word):

```
Timothys-MacBook-Pro:dolt-test timsehn$ dolt sql -q "create table bar (id INT, \`comment\` VARCHAR(10), primary key(id));"
Timothys-MacBook-Pro:dolt-test timsehn$ dolt sql -q "create table foo (id INT, \`level\` TINYINT(3), primary key (id));"
Timothys-MacBook-Pro:dolt-test timsehn$ dolt schema show
bar @ working
CREATE TABLE `bar` (
  `id` INT NOT NULL COMMENT 'tag:0',
  `comment` VARCHAR(10) COMMENT 'tag:1',
  PRIMARY KEY (`id`)
);

foo @ working
CREATE TABLE `foo` (
  `id` INT NOT NULL COMMENT 'tag:0',
  `level` TINYINT COMMENT 'tag:1',
  PRIMARY KEY (`id`)
);
```

This is a bad error message.

**Comment by zachmu** [comment]
We'll work on making the parser more lenient for DDL statements. In the meantime, surrounding the column names in backticks should allow you to create the table. But note what Tim said: Dolt tables require a primary key.

**Comment by timsehn** [comment]
https://github.com/liquidata-inc/dolt/pull/565

Skipped bats test to allow SQL keywords without backticks. Backticks should only be required for reserved words.
