### ISSUE TITLE
Concurrent table edits leaves uncommitted branch state

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#5608]
When running transactions in parallel to update different rows in a table, there is both unstaged and staged changes left over in the branch state (as evident in `select * from dolt_status`).

In a larger use case we have with many concurrent transactions each updating separate rows, it appears that a few of the transactions' edits are left in that working/staged state. Checking the state of the latest commit (`select * from table as of 'lastCommitHash'`) confirms the working/staged changes are not committed.

We are encountering errors related to constraint violations in the working state, and suspect it might be a side effect of these uncommitted changes.

**Comment by timsehn** [comment]
@zachmu is actively working this today.

**Comment by zachmu** [comment]
This will be included in 0.75.8, going out in ~45 minutes.
