### ISSUE TITLE
Missing support for ALTER TABLE table_name COLLATE utf8mb4_bin;

### ISSUE THREAD

**Issue by jacobATcertifiedfoodDotinfo** [dolthub/dolt#5623]
ALTER TABLE table1 COLLATE utf8mb4_bin;
The above works with MySQL (tested with db-fiddle.com), but it does not work with dolt (tested with Hosted dolt workbench)

**Comment by timsehn** [comment]
A workaround you can rename the current table, create a new table with the collation you want, and select into the new table. This should work if we can coerce the collation into the other.

Better support for that is coming here:

https://github.com/dolthub/dolt/issues/4428

**Comment by timsehn** [comment]
@Hydrocharged will knock this out in the next few days.
