### ISSUE TITLE
Variable NAMES not working

### ISSUE THREAD

**Issue by kolemikko** [dolthub/dolt#5627]
Following query fails with error "Unknown system variable 'names'":

`SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION')),time_zone='+00:00',NAMES utf8mb4 COLLATE utf8mb4_unicode_ci}`

Noticed this when using https://github.com/launchbadge/sqlx library to connect to Dolt with rust.

**Comment by fulghum** [comment]
Hey @kolemikko, thanks for taking the time to report this. Looks like we just need to add support for [MySQL's `SET NAMES` statement](https://dev.mysql.com/doc/refman/8.0/en/set-names.html) to get this working for you. 

This should be an easy one for us to knock out. We'll dig in to this today and get you an update soon.

**Comment by jennifersp** [comment]
Hi @kolemikko, thank you for reporting this issue. The fix for this issue has been merged in and will be in the next Dolt release.

**Comment by kolemikko** [comment]
> Hey @kolemikko, thanks for taking the time to report this. It looks like we do support running `SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci` when that is the only `set` expression provided. However, something seems to be going wrong when `NAMES` is set as part of setting multiple expressions in the same statement.
> 
> Looking at our parser code... we seem to [only check for expanding `NAMES`](https://github.com/dolthub/go-mysql-server/blob/e50e01c3229fc61118374cb167e040c4dacc9211/sql/parse/parse.go#L594) into the three system variables that it sets when there is only one `set` expression provided. (`isCharset` has a similar behavior and we look at that while we're in here, too.)
> 
> This should be an easy one for us to knock out. We'll dig in to this today and get you an update soon.

Thanks for very fast response, great work!

**Comment by kolemikko** [comment]
> Hi @kolemikko, thank you for reporting this issue. The fix for this issue has been merged in and will be in the next Dolt release.

Thanks a lot, great work!
