### ISSUE TITLE
Dolt server deadlock with `dolt_transaction_commit=1`

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#5636]
On Hosted Dolt running `v0.75.6`, seeing the server deadlock and refuse to accept any connections after about 36 hours. The server is configured with `dolt_transaction_commit=1`. Also the chunk journal is enabled for this instance.

Hosted Dolt also attempts to automatically backup server instances every 24 hours, but seeing the backups fail with:
```
rpc error: code = Unknown desc = backup of 'instance' failed. query: call dolt_backup('sync-url', 'aws://[instance-backups:backups]/deployment1/backups/20230317T192346.053/instance'), Error 1105: error syncing backup: failed to get all chunks.
```

Observed behavior is that the server stops accepting new connections at a certain point and appears to be deadlocked, requiring a manual restart.

Will update this issue with go-routine dump when available as well as a count of new connections to closed connections to rule out whether closed connections aren't being returned to the connection pool.

**Comment by timsehn** [comment]
We upgraded to the latest version and were unable to rerpoduce this.
