### ISSUE TITLE
Point lookups should match prefix

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5648]
Join point lookups are broken:

```sql
create table uv (u int primary key, v int, unique key(v));
insert into uv values (1,1),(2,2);
create table xy (x int primary key, v int);
insert into xy values (0,0),(1,1);
select /*+ LOOKUP_JOIN(xy,applySubq0) */ * from xy where x not in (select v from uv);
+---+---+
| x | v |
+---+---+
| 0 | 0 |
| 1 | 1 |
+---+---+
```
The query above should return only `(0,0)`.

We can't perform a map.Get on a partial tuple, the comparison always fails. Revert this PR https://github.com/dolthub/dolt/pull/5533 and use cursor for prefix searching (in `newPointLookup` for this specific test).

**Comment by andy-wm-arthur** [comment]
I think we'd be better off implementing a `GetPrefix()` method than exposing the `tree.Cursor` publicly. As I mentioned, most calls to cursor methods outside the `tree` package were used incorrectly and were buggy. `prolly.Map` currently has a [`HasPrefix()`](https://github.com/dolthub/dolt/blob/main/go/store/prolly/tuple_map.go#L280) method that can be used as a reference.

**Comment by max-hoffman** [comment]
We might need another sysbench test too, with a unique key and join hint to make sure we're testing the point lookup path.
