### ISSUE TITLE
Implement SQL function `find_in_set`

### ISSUE THREAD

**Issue by okhowang** [dolthub/dolt#5659]
https://mariadb.com/kb/en/find_in_set/

**Comment by timsehn** [comment]
This is also a MySQL function:

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_find-in-set

**Comment by fulghum** [comment]
@okhowang – thank you for opening an issue to request this! 🙏  James implemented `find_in_set` and we updated our SQL reference documentation to indicate that it is now supported. 

Let us know if you hit any issues with it, or have any other functions you need for your application.
