### ISSUE TITLE
JSON operator `->>` not supported

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#5662]
Hello, please revise the docs at https://docs.dolthub.com/sql-reference/sql-support/expressions-functions-operators#functions-and-operators to confirm which JSON operators are or are not supported. I had received this warning while querying:

```sql
SELECT `Product`,Price
FROM products
WHERE `SKU` LIKE 'SP%' AND NOT `Removed`->>'$.americas' = 'true'
```

> unsupported feature: (->>) JSON operators not supported

Any insight to when this may be supported would be appreciated. My workaround is using `JSON_EXTRACT()` and that works well:

```sql
SELECT `Product`,Price
FROM products
WHERE `SKU` LIKE 'SP%' AND NOT JSON_EXTRACT(`Removed`, '$.americas') = 'true'
```

**Comment by timsehn** [comment]
Docs are wrong. We'll get those patched. Thanks for the feature request.

**Comment by timsehn** [comment]
Docs PR: https://github.com/dolthub/docs/pull/1282
