### ISSUE TITLE
Intellectual property rights and Patent Number for the Dolt DB Storage method.

### ISSUE THREAD

**Issue by ganeshkbhat** [dolthub/dolt#5676]
This is fantastic. I will give this a try. On a check on Intellectual property rights, Is there a patent associated to this Git like version control system for Data? Can you share the Patent Number if so?

**Comment by fulghum** [comment]
Glad you are liking the product! Dolt is open source, and licensed under the [Apache 2.0 license](https://github.com/dolthub/dolt/blob/main/LICENSE), so patents do not apply here.

**Comment by ganeshkbhat** [comment]
@fulghum  Ok nice. Thank you. Is there any patent in the market for this format of data storage db if I use something similar architecture and that may be clashing with their intellectual property rights? I know Google Docs have version control docs but unsure if that is or is not patented or associated to intellectual property rights.
