### ISSUE TITLE
Add JSON_SET support

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#5680]
Hello, may I humbly request support for the `JSON_SET` function. I have a query that performs math against current JSON values like this:

```sql
UPDATE products
SET price=JSON_MERGE_PRESERVE(
  IFNULL(
    JSON_EXTRACT(price, '$'),
    "{}"
  ),
  CAST(CONCAT('{"americas":', JSON_EXTRACT(price, '$.americas') + 100, '}') AS JSON)
)
WHERE ...;
```

That's very brittle, and would be much safer with `JSON_SET`:

```sql
UPDATE products
SET price=JSON_SET(price, '$.americas', JSON_EXTRACT(price, '$.americas') + 100)
WHERE ...;
```

Thank you for your time and effort.

**Comment by stephkyou** [comment]
Hi @theetrain,
Thanks for waiting while I worked on this issue! I've just merged in a PR that adds support for the `json_set` function. Let me know if you notice any issues using this function. This first iteration lacks some support for more niche use cases, like using array indexing. I'm currently working on filling in those gaps but you can check which cases are still missing [here](https://github.com/dolthub/go-mysql-server/blob/main/sql/expression/function/json_set_test.go#L77).

**Comment by theetrain** [comment]
I noticed `JSON_SET` is still marked as not supported in the Dolt docs, and it hasn't appeared in recent releases. Has this feature been released yet?

**Comment by timsehn** [comment]
Our release notes got so long they truncated on the GitHib releases page for 0.75.13. 

The `json_set` changes are released there if you click on that release to expand the release notes:

https://github.com/dolthub/dolt/releases/tag/v0.75.13

**Comment by timsehn** [comment]
@stephkyou will do that today. Thanks for the reminder.

**Comment by stephkyou** [comment]
Hi @theetrain, 
The docs should be updated now! Thanks for checking in. :)
