### ISSUE TITLE
`dolt diff --summary` no longer shows how many rows were modified

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolt#5698]
Currently the output of this command is something like this:

```
$ dolt diff --summary
+------------+-----------+-------------+---------------+
| Table name | Diff type | Data change | Schema change |
+------------+-----------+-------------+---------------+
| hospitals  | modified  | true        | false         |
+------------+-----------+-------------+---------------+
```

It used to also show how many rows were added, removed and updated, but no longer does. 

As an user, I would like to see these row counts again.

**Comment by timsehn** [comment]
We changed the old summary view to `dolt diff --stat` to more closely match Git.

**Comment by rl1987** [comment]
Perhaps the output of `dolt diff --summary` should mention the `--stat` option?

**Comment by CaptainStabs** [comment]
this ^
