### ISSUE TITLE
Collation description in CREATE TABLE context fails when uppercased

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#5699]
When defining collations in a CREATE TABLE setting:

`COLLATE utf8mb4_general_ci` works

but 

`COLLATE UTF8MB4_GENERAL_CI` does not.
```
> Unknown collation: UTF8MB4_GENERAL_CI
```

**Comment by timsehn** [comment]
@Hydrocharged is this allowed in MySQL?

**Comment by Hydrocharged** [comment]
Absolutely, we're applying case sensitivity here when we should not be.
