### ISSUE TITLE
"Format PR" CI Workflow fails on PRs that come from forks.

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#5723]
(markup for the workflow found here: https://github.com/dolthub/dolt/blob/main/.github/workflows/ci-format-repo.yaml)

The workflow runs `actions/checkout@v3` to fetch the ref pointed to by the PR. But if the PR is from a fork, then the ref isn't in the repo and the action fails.

This can be seen in action on this PR: https://github.com/dolthub/dolt/actions/runs/4580694905/workflow?pr=5655

**Comment by coffeegoddd** [comment]
Not sure how to fix this atm. afaict we're kinda plagued by this issue https://github.com/actions/checkout/issues/455 .

Using `pull_request_target` event enabling "Allow commits from maintainers" still results in failed commits to the pull request fork branch.

**Comment by fulghum** [comment]
Thanks for looking into this one. Maybe the best we can do right now is only run `auto-format` and `verify-formatting` on PRs in the same repo, and for forks, only run `verify-formatting`? If that's doable, that would still be a nice improvement where the CI check wouldn't always fail for all contributions; if `verify-formatting` does fail, at least contributors could still take care of it manually and get all their CI checks green.

**Comment by coffeegoddd** [comment]
good idea, ill work on this

**Comment by coffeegoddd** [comment]
Think this does the right thing https://github.com/dolthub/dolt/pull/5782, closing this issue for now.
