### ISSUE TITLE
Runtime error when using dolt_commit_diff_$tablename

### ISSUE THREAD

**Issue by kolemikko** [dolthub/dolt#5730]
I've gotten this runtime error now multiple times when diffing, it seems like it's maybe related to table not existing (or having some radical changes such as table being removed and added again etc.) between from_revision or to_revision. It's pretty bad since the panic will drop the whole server, instead some error would be nice.

I think I've gotten same error if both from_revision and to_revision hash are the same, also having uncommitted changes on the table might be a factor. Hard to say, haven't been able to get solid repro on this.

Happens at least on versions 0.75.9 and 0.75.10.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x105fbdad8]

goroutine 2099 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*Table).NodeStore(...)
	github.com/dolthub/dolt/go/libraries/doltcore/doltdb/table.go:129
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables.newProllyDiffIter(_, {_, _, {_, _}, {_, _}, _, _, {_, ...}, ...}, ...)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables/diff_iter.go:275 +0x3e8
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables.DiffPartition.GetRowIter({0x0, 0x0, {0x140011bbde0, 0x20}, {0x140011bbc80, 0x20}, 0x14001952048, 0x14001952060, {0x106d74a60, 0x14001286a20}, ...}, ...)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables/diff_table.go:640 +0xf0
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables.(*CommitDiffTable).PartitionRows(0x1400279e9b8?, 0x10560d048?, {0x106d44180?, 0x14001286ea0?})
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables/commit_diff_table.go:307 +0xb0
github.com/dolthub/go-mysql-server/sql/plan.(*ProcessTable).PartitionRows(0x14001339d70, 0x104e7db74?, {0x106d44180, 0x14001286ea0})
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/sql/plan/process.go:285 +0x38
github.com/dolthub/go-mysql-server/sql.(*TableRowIter).Next(0x14001809c20, 0x14000d4d040)
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/sql/table_iter.go:60 +0x14c
github.com/dolthub/go-mysql-server/sql/plan.(*projectIter).Next(0x1400127c0f0, 0x104e3e3d0?)
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/sql/plan/project.go:157 +0x34
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/sql/plan/transaction_committing_iter.go:118
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x14001809c70, 0x104e485d0?)
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/sql/plan/process.go:387 +0x30
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func2()
	github.com/dolthub/go-mysql-server@v0.14.1-0.20230329021806-7d5325285657/server/handler.go:413 +0x1fc
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x9c
```

**Comment by timsehn** [comment]
Agreed this is bad. Thanks for the report. We'll get on this today.

Thanks for the clue about wildly different table structure between to and from revisions.

**Comment by bpf120** [comment]
@kolemikko, we'd love to learn more about your Dolt use case too. You can [email](mailto:brianf@dolthub.com) me or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you would like to share. Thanks for trying Dolt.

**Comment by zachmu** [comment]
This happens when the table in question exists in the current HEAD but doesn't exist in the `from_commit` or `to_commit` revisions.

**Comment by kolemikko** [comment]
> This happens when the table in question exists in the current HEAD but doesn't exist in the `from_commit` or `to_commit` revisions.

Ah, makes sense now! Thanks for very fast fix, great work!

**Comment by kolemikko** [comment]
> @kolemikko, we'd love to learn more about your Dolt use case too. You can [email](mailto:brianf@dolthub.com) me or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you would like to share. Thanks for trying Dolt.

For sure! I'm on your Discord already, will totally give you some insight on our tooling around Dolt when it's in more stable state :)
