### ISSUE TITLE
Incorrect autoincrement value being used

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#5731]
We have a scenario where upon insertion of a row that uses an autoincrementing value, it appears as though Dolt is using a value based on values in a table of the same name in a different branch. So for example the table in the current branch has autoincremented primary keys 1-12, but inserting a new row is trying to use a primary key of 3 for some reason. 3 would be the next available autoincrement for this table on a different branch, so it appears there may be some conflict regarding autoincrementing on a table that exists in multiple branches.

**Comment by timsehn** [comment]
@zachmu has this reproduced and will get a fix out in the next release.
