### ISSUE TITLE
Bad error message for omitting branch in push command

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#575]
```
$ dolt-dev push dupe-origin
error: unable to find dupe-origin
```
The true cause of the error is the missing branch parameter, but the error message hides this.

**Comment by timsehn** [comment]
Skipped Bats test?

**Comment by timsehn** [comment]
Skipped bats test:

https://github.com/liquidata-inc/dolt/pull/600

**Comment by timsehn** [comment]
Test is not skipped any more.
