### ISSUE TITLE
Getting Started Docs `sql-client` missing user parameter

### ISSUE THREAD

**Issue by wcedmisten** [dolthub/dolt#5755]
In the [getting started docs](https://docs.dolthub.com/introduction/getting-started/database), the following commands are given:

```
dolt sql-server
dolt sql-client
```

However, when I run the latter command, I get the error:

```
dolt sql-client
--user or -u argument is required
```

The default `sql-server` user is an empty string, so I just added this to the `sql-client` command to fix the issue.

```
dolt sql-client -u ""
```

This should either be updated in the docs, or provided as a default user for `sql-client`.

**Comment by timsehn** [comment]
I think you need `dolt sql-client -u root` now. I'll update the docs. Thanks for the report.

**Comment by timsehn** [comment]
https://github.com/dolthub/docs/pull/1307
