### ISSUE TITLE
Support multiple concurrent connections modifying the working set in SQL server

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#579]
We limit concurrent connections to 1, which means e.g. you can't edit multiple tables in DataGrip at the same time.

**Comment by VinaiRachakonda** [comment]
This is now fixed

**Comment by d-baranowski** [comment]
Can you elaborate? What is the concurrent connection limit on dolthub?

**Comment by timsehn** [comment]
There is none :-) We fully support transactions as of last release:

https://docs.dolthub.com/interfaces/sql/heads
https://www.dolthub.com/blog/2021-05-19-dolt-transactions/
