### ISSUE TITLE
Improve error messaging when multiple processes connect to db concurrently.

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#5793]
Today I tried to run some CLI commands on a database while I had a debug process suspended in my IDE.

The error message read:

```
error on line 1 for query DROP TABLE t: cannot update manifest: database is read only
cannot update manifest: database is read only
```

It's good that we detect and disallow concurrent modifications to the database, but our messaging could be better. Is it possible for the CLI to distinguish between a db that's locked because of concurrent access and a db that's actually read-only?

**Comment by timsehn** [comment]
@macneale4 will fix this with his current work as you'll be able to connect with the CLI to a running database. 

Gonna close it in favor of the uber issue #3922
