### ISSUE TITLE
tighter coupling of GitHub release tags and commit graph

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#580]
Currently we cut a release and manually create a bunch of system specific binaries, create some Windows binaries, bump the version and push, and then "tag" a release. The shortcoming here is twofold:
- "tag" is not meaningful in the context of the commit graph, but rather a number we have chosen to associate with some binaries (that rely on human diligence to be correct)
- a bunch of manual steps

We should automate this process to create a tight coupling between the commit graph, and the release, where we have a GitHub Action(s) that builds the relevant binaries and places them on a release draft triggered by pushing a tag. This would motivate to automate the manual steps out of release workflow.

**Comment by reltuk** [comment]
The windows installer build was hard to automate when we previously looked at this, but probably worth revisiting now.

**Comment by VinaiRachakonda** [comment]
@oscarbatori Seems like this can be closed? Lots of automation has been done on the actions
