### ISSUE TITLE
Slow select order by limit

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5812]
Explain plan is:
```
explain select data from auctions order by ai desc limit 1;
+------------------------------------+
| plan                               |
+------------------------------------+
| Limit(1)                           |
|  └─ Project                        |
|      ├─ columns: [auctions.data]   |
|      └─ Sort(auctions.ai DESC)     |
|          └─ Table                  |
|              ├─ name: auctions     |
|              └─ columns: [ai data] |
+------------------------------------+
```
There should be a TopN node there instead of a limit.

A workaround is:
```
explain select data from auction where ai = (select ai from auction order by 1 limit 1);
+-------------------------------------------------+
| plan                                            |
+-------------------------------------------------+
| Project                                         |
|  ├─ columns: [auction.data]                     |
|  └─ SemiJoin                                    |
|      ├─ (auction.ai = applySubq0.ai)            |
|      ├─ Table                                   |
|      │   └─ name: auction                       |
|      └─ Max1Row                                 |
|          └─ SubqueryAlias                       |
|              ├─ name: applySubq0                |
|              ├─ outerVisibility: false          |
|              ├─ cacheable: true                 |
|              └─ Limit(1)                        |
|                  └─ IndexedTableAccess(auction) |
|                      ├─ index: [auction.ai]     |
|                      ├─ filters: [{[NULL, ∞)}]  |
|                      └─ columns: [ai]           |
+-------------------------------------------------+
16 rows in set (0.00 sec)
```

**Comment by max-hoffman** [comment]
One option is to have the TopN rule pattern match through projections. The real perf win is identifying that a sorted scan satisfies the sort operator, which is also doable.

**Comment by max-hoffman** [comment]
If we replace sort operators with sorted index scans, the base case is simple but there are a lot of edge cases.

The base case is:
- find a Sort operator (capture limit/offset also)
- find the child ResolvedTable or IndexedTableAccess
- If resolvedTable, find an applicable index that satisfies the sort order. Delete the sort/limit/offset, replace ResolvedTable with a `MaxNSortedIndexScan(sortedIndex, offset, limit)` or the IndexedTableAccess.
- If scope's relation is indexedTableAccess, check whether the index already satisfies the sort expressions. If yes, replace with `MaxNSortedIndexScan(sortedIndex, offset, limit)` with the index already in indexedTableAccess and delete sort/limit/offset.

An index "satisfies" a sort condition when the sort expressions are a prefix of the index expressions, in addition to nullability considerations that we should test against MySQL.

An index can satisfy a sort without a Limit clause. In that case, we would just delete the sort and use a regular IndexedTableAccess.

Scopes with joins are more complicated. Simplest case is similar to the case (2) above, where the left-most relation in the join satisfies the sort expressions. More complicated versions would put this logic into the memo, which will apply the same logic to all physical operators in a memo group, and then let costing take care of whether a certain join order without a sort node will be less expensive than alternative plans. Probably not in-scope for a first-pass.

Aaron pointed out that nulls, descending/ascending, collations are all tricky edge cases that need to be tested. Zach wants the OrderedIndex interface to be used to make sure indexes are sorted.

**Comment by max-hoffman** [comment]
@nicktobey @JCOR11599 for visibility

**Comment by JCOR11599** [comment]
An optimization that addresses this has been merged to main.
Queries that `ORDER BY` a primary key in `ASC` or `DESC` will produce plans that use IndexedTableAccess instead of sorting. As a result, queries like `select * from t order by pk desc limit 1` will produce plans like so
```
+--------------------------------+
| plan                           |
+--------------------------------+
| Limit(1)                       |
|  └─ IndexedTableAccess(t)      |
|      ├─ index: [t.pk]          |
|      ├─ filters: [{[NULL, ∞)}] |
|      ├─ columns: [pk]          |
|      └─ reverse: true          |
+--------------------------------+
6 rows in set (0.00 sec)
```

which should perform significantly better than before
