### ISSUE TITLE
SQL regressions in 0.16.0

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#582]
Log here (only visible to liquidata org): https://jenkins.awsdev.ld-corp.com/job/Dolt_SQL_Nightly/225/consoleFull

**Comment by zachmu** [comment]
Caused by a change in handling of DECIMAL type

**Comment by andrew-wm-arthur** [comment]
@Hydrocharged Is this still open?

**Comment by Hydrocharged** [comment]
Yes, I haven’t had the time to look into this just yet.
