### ISSUE TITLE
Long JSON query truncated

### ISSUE THREAD

**Issue by jigglyjams** [dolthub/dolt#5822]
I think I am experience a delta between mariaDB server and go-mysql-server. I am using a bit of a wild SQL query (chatGPT assisted) to build an object to be consumed by nodejs application.

The database is here: https://www.dolthub.com/repositories/jigglyjams/waterbox

I may be wildly offbase here with this style of database setup BUT would like to be able to do the following [query (link to dolt API query)](https://www.dolthub.com/repositories/jigglyjams/waterbox/query/main?active=Tables&q=SELECT+proposals.uuid%2C%0A++CONCAT%28%0A++++%27%5B%27%2C%0A++++GROUP_CONCAT%28%0A++++++JSON_UNQUOTE%28%0A++++++++JSON_OBJECT%28%0A++++++++++%27type%27%2C+%27Payout%27%2C%0A++++++++++%27uuid%27%2C+payouts.uuidOfPayout%2C%0A++++++++++%27payload%27%2C+JSON_OBJECT%28%0A++++++++++++%27amountUSD%27%2C+payouts.amount%2C%0A++++++++++++%27governanceCycleStart%27%2C+payouts.governanceCycleStart%2C%0A++++++++++++%27count%27%2C+payouts.numberOfPayouts%2C%0A++++++++++++%27address%27%2C+payouts.payAddress%2C%0A++++++++++++%27project%27%2C+payouts.payProject%0A++++++++++%29%0A++++++++%29%0A++++++%29%0A++++++SEPARATOR+%27%2C%27%0A++++%29%2C%0A++++%27%2C%27%2C%0A++++GROUP_CONCAT%28%0A++++++JSON_UNQUOTE%28%0A++++++++JSON_OBJECT%28%0A++++++++++%27type%27%2C+%27Transfer%27%2C%0A++++++++++%27uuid%27%2C+transfers.uuidOfTransfer%2C%0A++++++++++%27payload%27%2C+JSON_OBJECT%28%0A++++++++++++%27contract%27%2C+transfers.transferTokenAddress%2C%0A++++++++++++%27tokenName%27%2C+transfers.transferTokenName%2C%0A++++++++++++%27to%27%2C+transfers.transferAddress%2C%0A++++++++++++%27amount%27%2C+transfers.transferAmount%0A++++++++++%29%0A++++++++%29%0A++++++%29%0A++++++SEPARATOR+%27%2C%27%0A++++%29%2C%0A++++%27%2C%27%2C%0A++++GROUP_CONCAT%28%0A++++++JSON_UNQUOTE%28%0A++++++++JSON_OBJECT%28%0A++++++++++%27type%27%2C+%27Custom+Transaction%27%2C%0A++++++++++%27uuid%27%2C+customTransactions.uuidOfTransaction%2C%0A++++++++++%27payload%27%2C+JSON_OBJECT%28%0A++++++++++++%27contract%27%2C+customTransactions.transactionAddress%2C%0A++++++++++++%27value%27%2C+customTransactions.transactionValue%2C%0A++++++++++++%27functionName%27%2C+customTransactions.transactionFunctionName%2C%0A++++++++++++%27args%27%2C+customTransactions.transactionFunctionArgs%0A++++++++++%29%0A++++++++%29%0A++++++%29%0A++++++SEPARATOR+%27%2C%27%0A++++%29%2C%0A++++%27%2C%27%2C%0A++++GROUP_CONCAT%28%0A++++++JSON_UNQUOTE%28%0A++++++++JSON_OBJECT%28%0A++++++++++%27type%27%2C+%27Reserve%27%2C%0A++++++++++%27uuid%27%2C+reserves.uuidOfReserve%2C%0A++++++++++%27payload%27%2C+JSON_OBJECT%28%0A++++++++++++%27splits%27%2C+reserves.splits%0A++++++++++%29%0A++++++++%29%0A++++++%29%0A++++++SEPARATOR+%27%2C%27%0A++++%29%2C%0A++++%27%5D%27%0A++%29+as+actions%0AFROM+proposals%0ALEFT+JOIN+payouts+ON+proposals.uuid+%3D+payouts.uuidOfProposal%0ALEFT+JOIN+transfers+ON+proposals.uuid+%3D+transfers.uuidOfProposal%0ALEFT+JOIN+reserves+ON+proposals.uuid+%3D+reserves.uuidOfProposal%0ALEFT+JOIN+customTransactions+ON+proposals.uuid+%3D+customTransactions.uuidOfProposal%0AWHERE+governanceCycle%3D41+AND+uuid+%3D+%277799fcb5d1664b829f447d41256347da%27%0AGROUP+BY+proposals.uuid%3B%0A%0A):
```sql
SELECT proposals.uuid,
  CONCAT(
    '[',
    GROUP_CONCAT(
      JSON_UNQUOTE(
        JSON_OBJECT(
          'type', 'Payout',
          'uuid', payouts.uuidOfPayout,
          'payload', JSON_OBJECT(
            'amountUSD', payouts.amount,
            'governanceCycleStart', payouts.governanceCycleStart,
            'count', payouts.numberOfPayouts,
            'address', payouts.payAddress,
            'project', payouts.payProject
          )
        )
      )
      SEPARATOR ','
    ),
    ',',
    GROUP_CONCAT(
      JSON_UNQUOTE(
        JSON_OBJECT(
          'type', 'Transfer',
          'uuid', transfers.uuidOfTransfer,
          'payload', JSON_OBJECT(
            'contract', transfers.transferTokenAddress,
            'tokenName', transfers.transferTokenName,
            'to', transfers.transferAddress,
            'amount', transfers.transferAmount
          )
        )
      )
      SEPARATOR ','
    ),
    ',',
    GROUP_CONCAT(
      JSON_UNQUOTE(
        JSON_OBJECT(
          'type', 'Custom Transaction',
          'uuid', customTransactions.uuidOfTransaction,
          'payload', JSON_OBJECT(
            'contract', customTransactions.transactionAddress,
            'value', customTransactions.transactionValue,
            'functionName', customTransactions.transactionFunctionName,
            'args', customTransactions.transactionFunctionArgs
          )
        )
      )
      SEPARATOR ','
    ),
    ',',
    GROUP_CONCAT(
      JSON_UNQUOTE(
        JSON_OBJECT(
          'type', 'Reserve',
          'uuid', reserves.uuidOfReserve,
          'payload', JSON_OBJECT(
            'splits', reserves.splits
          )
        )
      )
      SEPARATOR ','
    ),
    ']'
  ) as actions
FROM proposals
LEFT JOIN payouts ON proposals.uuid = payouts.uuidOfProposal
LEFT JOIN transfers ON proposals.uuid = transfers.uuidOfProposal
LEFT JOIN reserves ON proposals.uuid = reserves.uuidOfProposal
LEFT JOIN customTransactions ON proposals.uuid = customTransactions.uuidOfProposal
WHERE governanceCycle=41 AND uuid = '7799fcb5d1664b829f447d41256347da'
GROUP BY proposals.uuid;
```

If you expand the result you can see that the last `{ payload: [<splits>]` array is getting truncated. This occurs when querying locally on a self hosted instance of `dolt server` and from my hosted instance.

I was able to get the query to properly work in mariaDB in this online sandbox: https://sqliteonline.com/

Wondering if you've run into this before or if I shouldnt be doing things like this. Thanks!

![image](https://user-images.githubusercontent.com/83923290/234763551-3c7b1c92-30f2-4451-95c9-7e1972fb7bcf.png)

**Comment by jigglyjams** [comment]
This query is pretty crazy and I have found a better solution with the following query:

```
SELECT proposals.*,
  CONCAT(
    '[',
    (
      SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
          'type', 'Payout',
          'uuid', payouts.uuidOfPayout,
          'payload', JSON_OBJECT(
            'amountUSD', payouts.amount,
            'governanceCycleStart', payouts.governanceCycleStart,
            'count', payouts.numberOfPayouts,
            'address', payouts.payAddress,
            'project', payouts.payProject
          )
        )
      )
      FROM payouts
      WHERE proposals.uuid = payouts.uuidOfProposal AND payouts.uuidOfPayout IS NOT NULL
    ),
    ',',
    (
      SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
          'type', 'Transfer',
          'uuid', transfers.uuidOfTransfer,
          'payload', JSON_OBJECT(
            'contract', transfers.transferTokenAddress,
            'tokenName', transfers.transferTokenName,
            'to', transfers.transferAddress,
            'amount', transfers.transferAmount
          )
        )
      )
      FROM transfers
      WHERE proposals.uuid = transfers.uuidOfProposal AND transfers.uuidOfTransfer IS NOT NULL
    ),
    ',',
    (
      SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
          'type', 'Custom Transaction',
          'uuid', customTransactions.uuidOfTransaction,
          'payload', JSON_OBJECT(
            'contract', customTransactions.transactionAddress,
            'value', customTransactions.transactionValue,
            'functionName', customTransactions.transactionFunctionName,
            'args', customTransactions.transactionFunctionArgs
          )
        )
      )
      FROM customTransactions
      WHERE proposals.uuid = customTransactions.uuidOfProposal AND customTransactions.uuidOfTransaction IS NOT NULL
    ),
    ',',
    (
      SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
          'type', 'Reserve',
          'uuid', reserves.uuidOfReserve,
          'payload', JSON_OBJECT(
            'splits', reserves.splits
          )
        )
      )
      FROM reserves
      WHERE proposals.uuid = reserves.uuidOfProposal AND reserves.uuidOfReserve IS NOT NULL
    ),
    ']'
  ) as actions
FROM proposals
WHERE governanceCycle=41 AND uuid = '7799fcb5d1664b829f447d41256347da';
```

**Comment by fulghum** [comment]
Hey @jigglyjams, glad you found another query that unblocks you. I was able to repro the behavior you posted and simplified it down to this repro case:
```sql
select GROUP_CONCAT(
      JSON_UNQUOTE(
        JSON_OBJECT(
            'splits', reserves.splits
        )
      )
      SEPARATOR ','
    )
from proposals 
LEFT JOIN reserves ON proposals.uuid = reserves.uuidOfProposal;
```

I noticed that the output is cut off at 1024 chars and was suspicious of `GROUP_CONCAT`. Taking a look at the documentation, [this is actually a MySQL behavior for `GROUP_CONCAT`](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat): 
> The result is truncated to the maximum length that is given by the [group_concat_max_len](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_group_concat_max_len) system variable, which has a default value of 1024. The value can be set higher, although the effective maximum length of the return value is constrained by the value of [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet)

Dolt **does** honor the `group_concat_max_len` session variable, but that approach seems fragile if you can't guarantee for sure that your data will always fit in that length. 

So... it looks like things are working as intended, and the `GROUP_CONCAT` function is just not the best fit for the query you need to run. Glad to see you already found another query (that doesn't use `GROUP_CONCAT`) that gets you the results you need! 

I'm going to go ahead and resolve since it sounds like you're all set now, but don't hesitate to let us know if you see anything else weird. We're always happy to help!
