### ISSUE TITLE
Dolt SQL REPL sometimes eats up preceding lines in terminal when query is being edited

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolt#5824]
<img width="1440" alt="Screenshot 2023-04-27 at 18 15 14" src="https://user-images.githubusercontent.com/1080220/234862938-419325fa-8529-48a0-ac80-dd7c60e3e489.png">
<img width="1440" alt="Screenshot 2023-04-27 at 18 15 21" src="https://user-images.githubusercontent.com/1080220/234862971-f4307f7c-0737-40dd-a4f3-d7cda939f7fd.png">

**Comment by timsehn** [comment]
We are unlikely to focus to much on the built in sql shell on the CLI but thanks for the report.

**Comment by timsehn** [comment]
I'm going to close this one.

**Comment by timsehn** [comment]
Reopening because another user reported this.
