### ISSUE TITLE
Cloning database with new format tables to instance with old format tables causes errors

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#5849]
On Hosted I have a deployment with tables in the old format: https://hosted.doltdb.com/deployments/dolthub/us-jails-3

If I clone a database from dolthub that has new format tables, the clone succeeds but then I get errors that look like this when I use the workbench to browse data:
<img width="1312" alt="Screen Shot 2023-05-01 at 11 04 42 AM" src="https://user-images.githubusercontent.com/29443194/235502675-5030dcce-f763-4736-b846-efabe721be4b.png">

I'm not able to drop the newly cloned database:
```
mysql> drop database `im-interested`;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    5
Current database: us_jails

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    6
Current database: us_jails

ERROR 2013 (HY000): Lost connection to MySQL server during query
```

To repro:
Using the us-jails-3 deployment, clone a database from dolthub
```
mysql> call dolt_clone("dolthub/im-interested");
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.37 sec)
```
Use that database and try to run a query:
```
mysql> use im-interested;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT *
    -> FROM `submissions`
    -> ORDER BY `id` ASC
    -> LIMIT 200;
ERROR 1105 (HY000): read /var/lib/doltsqlserv/db/im-interested/.dolt/noms/rpnp4piju9mm3gev8r6edicll3itknda: file already closed```

**Comment by timsehn** [comment]
Gonna close this one as there are not too many old format dbs out there any more.
