### ISSUE TITLE
Trigger requires an empty column in order to set new row value with dolt table import

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#5855]
In `dolt sql`, copy+paste
```sql
create table cat (
    id varchar(64),
    type varchar(20),
    primary key (id)
    );
```
followed by
```sql
create trigger make_cat_id
before insert on cat
for each row
    set new.id = sha2(new.type);
```

Then try to insert
`cats.csv`
```
type
Calico
Orange
Black
```
with `dolt table import -u cat cats.csv`.

You'll get 
```
Error determining the output schema.
cause: input primary keys do not match primary keys of existing table
When attempting to move data from csv file:cats.csv to cat, could not determine the output schema.
Schema File: ""
explicit pks: ""
```

The correct behavior should be to check if the value `new.row_id` exists just before doing the insert, and not upon reading the CSV. 

This is related [this bug](https://github.com/dolthub/dolt/issues/5848).

**Comment by alecstein** [comment]
Thanks to @fulghum for pointing out the workaround:

```
create table cat (
    id varchar(64) default 0,
    type varchar(20),
    primary key (id)
    );
    
    
create trigger make_cat_id
before insert on cat
for each row
    set new.id = sha2(new.type, 256);
```

**Comment by fulghum** [comment]
We got Alec unblocked here, and we have issue https://github.com/dolthub/dolt/issues/5848 open with some improvements to `dolt table import`, so I think we're clear to resolve this one.
