### ISSUE TITLE
Dolt is especially slow executing queries from within a loop

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#5906]
Now that we use Dolt as the db for dolthub dev, we've noticed some significant performance hits, especially in services that execute queries from within a loop. Removing these improves performance for Dolt, while there's little difference in performance for these queries on prod (which still uses Postgres for reads). 

For example, this:

```go
func (impl *organizationUseCaseImpl) ListByUserID(ctx context.Context, userID UserID) ([]*OrganizationMemberWithOrganization, error) {
	memberships, err := impl.orgMemberRepo.ListByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	returned := make([]*OrganizationMemberWithOrganization, len(memberships))
	for i := range memberships {
		org, err := impl.orgRepo.GetByID(ctx, memberships[i].OrganizationIDFK)
		if err != nil {
			return nil, err
		}
		returned[i] = &OrganizationMemberWithOrganization{
			Member:       memberships[i],
			Organization: org,
		}
	}
	return returned, nil
}
```

Is much slower than this when running against Dolt, whereas the difference in Postgres is minimal
```go
func (impl *organizationUseCaseImpl) ListByUserID(ctx context.Context, userID UserID) ([]*OrganizationMemberWithOrganization, error) {
	memberships, err := impl.orgMemberRepo.ListByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	orgIDs := make([]OrganizationID, len(memberships))
	for i, mem := range memberships {
		orgIDs[i] = mem.OrganizationIDFK
	}
	orgs, err := impl.orgRepo.GetByIDs(ctx, orgIDs)
	if err != nil {
		return nil, err
	}
	returned := make([]*OrganizationMemberWithOrganization, len(memberships))
	for i := range memberships {
		org, ok := orgs[memberships[i].OrganizationIDFK]
		if !ok {
			return nil, fmt.Errorf("could not find org %s", memberships[i].OrganizationIDFK)
		}
		returned[i] = &OrganizationMemberWithOrganization{
			Member:       memberships[i],
			Organization: org,
		}
	}
	return returned, nil
}
```

Here are my two `ld` PRs where I measured load times for certain queries and looked at how they improved when I removed some queries from loops:
- For repo lists: https://github.com/dolthub/ld/pull/13928
- For org/org member/team lists: https://github.com/dolthub/ld/pull/13955

This seems like something other users will run into so wanted to document/we should try to improve

**Comment by timsehn** [comment]
@tbantle22 let me know this was a round trip issue with dev dolthub being on one coast and hosted dolt being on the other. In prod, this pattern is about @X Postgres which we would expect.
