### ISSUE TITLE
Can't push if sql-server is running

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5910]
```
$ dolt remote add origin timsehn/test_write_triggers
$ dolt push origin main
Uploaded 376 B of 376 B @ 3.38 kB/s.
error: push failed
cause: unknown push error; cannot update manifest: database is read only
```

**Comment by timsehn** [comment]
This happened because I had a sql-server running. This is a bad error message at least. But @macneale4 should figure out if I should be able to push in this case.

**Comment by timsehn** [comment]
I'm pretty sure @stephkyou is fixing this or has fixed this.

**Comment by stephkyou** [comment]
Should be fixed by https://github.com/dolthub/dolt/pull/6738
