### ISSUE TITLE
Problems uploading data with ogr2ogr (spatial data)

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#5917]
Hi all!, long time no see., here after some time and with the spatial index ready to work!

I'm testing uploading spatial data with dolt, for now this is what happened, which is.. weird, sorry I don't have other way to describe this.

```
dolt init
dolt sql-server
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="info"|S="/tmp/mysql.sock"
```

```
ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,tables=data,host=127.0.0.1" "data.gpkg"
ERROR 1: MySQL error message:table not found: data Description: DESCRIBE Failed
ERROR 1: MySQL error message:table with name aeropuertos already exists Description: CREATE TABLE `aeropuertos` (    fid INT UNIQUE NOT NULL AUTO_INCREMENT,    geom GEOMETRY NOT NULL)
ERROR 1: Terminating translation prematurely after failed
translation of layer aeropuertos (use -skipfailures to skip errors)
```

And now, if I check db-eaver I found this.

- The table is shown in the table list
- If we try to get data from it, we got "SQL Error [1146] [42S02]: table not found: aeropuertos"

If I don't set a table name in ogr2ogr:
```
ERROR 1: MySQL error message:There's no spatial reference with SRID 4294967294 Description: INSERT INTO `aeropuertos` (`geom` , `objectid_1`, `cod_comuna`, `categoría`, `cod_oaci`, `cod_iata`, `aerodromo`, `region`, `provincia`, `comuna`) VALUES (ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2) , 39, 3201, 'Aeródromo', 'SCRA', 'CNR', 'Aeródromo Chañaral', 'Región de Atacama', 'Chañaral', 'Chañaral')
ERROR 1: Unable to write feature 1 from layer aeropuertos.
ERROR 1: Terminating translation prematurely after failed
translation of layer aeropuertos (use -skipfailures to skip errors)
```

Thx!
[data.zip](https://github.com/dolthub/dolt/files/11446232/data.zip)

**Comment by timsehn** [comment]
@JCOR11599 will look at this today.

**Comment by latot** [comment]
Tricky, but if we do this:

```
ogr2ogr -f MySQL -overwrite "MYSQL:dolt,user=root,port=3306,host=127.0.0.1" "data.gpkg"
```

The command will end successful, but the table will be the same buggy one :3

**Comment by JCOR11599** [comment]
Hey @latot, thank you for the great repro description!
I managed to reproduce the issue on my end.

I was able to view and query the table like so
Setup:
```
$ mkdir test_db
$ cd test_db
$ dolt init
$ dolt sql-server
$ cp data.gpkg
```

ogr2ogr import:
```
ogr2ogr -f MySQL "MYSQL:test_db,user=root,port=3306,host=127.0.0.1" "data.gpkg"
```

This is the table I get
```
test_db> describe aeropuertos;
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| fid        | int         | NO   | UNI | NULL    | auto_increment |
| geom       | geometry    | NO   | MUL | NULL    |                |
| objectid_1 | bigint      | YES  |     | NULL    |                |
| cod_comuna | double      | YES  |     | NULL    |                |
| categoría  | varchar(50) | YES  |     | NULL    |                |
| cod_oaci   | varchar(50) | YES  |     | NULL    |                |
| cod_iata   | varchar(50) | YES  |     | NULL    |                |
| aerodromo  | varchar(50) | YES  |     | NULL    |                |
| region     | varchar(60) | YES  |     | NULL    |                |
| provincia  | varchar(60) | YES  |     | NULL    |                |
| comuna     | varchar(60) | YES  |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

```

This is with dolt 1.0.0, GDAL 3.6.3, and dBeaver 22.3.1
I am also on Windows, no clue if that makes a difference

Hopefully, this gets you unblocked.

I'm not too familiar with ogr2ogr, but I will look into exactly what ogr2ogr is doing.
It seems like the `MySQL:<database_name>` and `tables=<table_name>` argument matters a lot.

**Comment by JCOR11599** [comment]
Upon further investigation, it appears that MySQL actually does the same thing as dolt here

```shell
$ ogr2ogr -f MySQL  "MYSQL:test_db,user=root,password=root,port=3306,host=127.0.0.1,tables=aeropuertos" "data.gpkg"
ERROR 1: MySQL error message:Table 'test_db.aeropuertos' doesn't exist Description: DESCRIBE Failed
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
```

I believe that the `tables=` argument is meant for updating an existing table?
@latot let me know if this helps

**Comment by latot** [comment]
Hi!, thx checking it!, tomorrow I'll check all this, is late now here.

@JCOR11599  Thx!

**Comment by latot** [comment]
Oks, to get better tests I'll the next, every command will be executed in a new dolt repo, so we can isolate some effects.

And I'll open a postgis server too with docker, to be able to know the expected behavior from ogr2ogr.

Ogr2ogr works with drivers, every driver has its own ways to set params, for MySQL we can check that here:
https://gdal.org/drivers/vector/mysql.html

Here for postgres urls!
https://gdal.org/drivers/vector/pg.html

I'm using Gentoo 64 (Linux), DBeaver-23.0.3, Dolt 1.0.0

I used that versions in the original tests too.

For gentoo users you can check dolt-bin here https://github.com/latot/latot-overlay

Notes:

The argument "tables" is for restrict the access to only the listed tables.

Test 1:

Upload without tables param:
```
ogr2ogr -f MySQL "MYSQL:no_table,user=root,port=3306,host=127.0.0.1" "data.gpkg"
```
Results:

DB-eaver does not shows the table initially, but after disconnect and connect again it works, this happens to me before with other db, so should be a problem of dolt.
I can see and work with the table

Postgres: The same as above.

Test 2:

Upload with table param where the tables param is the same as the gpkg layer:
```
ogr2ogr -f MySQL  "MYSQL:table,user=root,port=3306,host=127.0.0.1,tables=aeropuertos" "data.gpkg"
ERROR 1: MySQL error message:table not found: aeropuertos Description: DESCRIBE Failed
```
Results:

I can see the table and work with it, the error is right because there was no table with that name to restrict the url to it.

Postgres: 
```
ERROR 1: Layer aeropuertos already exists, CreateLayer failed.
Use the layer creation option OVERWRITE=YES to replace it.
ERROR 1: Terminating translation prematurely after failed
translation of layer aeropuertos (use -skipfailures to skip errors)
```
Seems when we execute this on postgres there is the assumption the table already exists, and compares it with the layer name.
No idea if this behavior is about ogr2ogr/gdal driver (who handles the connection) or with Dolt.

Test 3:

Upload with table param where the tables param is not the same as the gpkg layer:
```
ogr2ogr -f MySQL  "MYSQL:other_table,user=root,port=3306,host=127.0.0.1,tables=data" "data.gpkg"
ERROR 1: MySQL error message:table not found: data Description: DESCRIBE Failed
```
Results:

Same as Test 2, the table still does not exists, was written correctly.

Postgres: No warning, but write fine, but still ogr2ogr should not write due to the tables param who should filter permisisons, Dolt is good here too.

Until here dolt is doing all great!, but still is the errors from the first post...
After test and test I was able to reproduce it! or at least part of it...

First, upload the data:
```
ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,host=127.0.0.1" "data.gpkg"
```

Here all will be fine, we can read the table even remove it. But if new we run the same command:
```
ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,host=127.0.0.1" "data.gpkg"
ERROR 1: MySQL error message:There's no spatial reference with SRID 4294967294 Description: INSERT INTO `aeropuertos` (`geom` , `objectid_1`, `cod_comuna`, `categoría`, `cod_oaci`, `cod_iata`, `aerodromo`, `region`, `provincia`, `comuna`) VALUES (ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2) , 39, 3201, 'Aeródromo', 'SCRA', 'CNR', 'Aeródromo Chañaral', 'Región de Atacama', 'Chañaral', 'Chañaral')
ERROR 1: Unable to write feature 1 from layer aeropuertos.
ERROR 1: Terminating translation prematurely after failed
translation of layer aeropuertos (use -skipfailures to skip errors)
```

Now we got the error!! And not only that.

From the server perspective:

```
2023-05-11T15:13:33-04:00 WARN [conn 4] error running query {connectTime=2023-05-11T15:13:33-04:00, connectionDb=dolt, error=There's no spatial reference with SRID 4294967294, query=INSERT INTO `aeropuertos` (`geom` , `objectid_1`, `cod_comuna`, `categoría`, `cod_oaci`, `cod_iata`, `aerodromo`, `region`, `provincia`, `comuna`) VALUES (ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2) , 39, 3201, 'Aeródromo', 'SCRA', 'CNR', 'Aeródromo Chañaral', 'Región de Atacama', 'Chañaral', 'Chañaral')}
```

And if try to remove the table from DBeaver, we will be able to remove it, but if you dissconect to the database and connect again, you will see the table is still there!

From the server perspective there is no error removing the table.

If we do this with a postgres server, ogr2ogr will append the data, which should be the correct way, because is sending an INSERT command.

Now, after we reach this point, if set "tables" params again but with a table that does not exists, we got a new error:
```
ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,host=127.0.0.1,tables=data" "data.gpkg"
ERROR 1: MySQL error message:table not found: data Description: DESCRIBE Failed
ERROR 1: MySQL error message:table with name aeropuertos already exists Description: CREATE TABLE `aeropuertos` (    fid INT UNIQUE NOT NULL AUTO_INCREMENT,    geom GEOMETRY NOT NULL)ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,host=127.0.0.1,tables=data" "data.gpkg"
ERROR 1: Terminating translation prematurely after failed
translation of layer aeropuertos (use -skipfailures to skip errors)
```

that error is not great... is like ogr2ogr was not able to know if the table exists....
While, if we use the layer name as the table name, we will get the error when we try to append data to the existent table.

Well, seems this last one is why the error was tricky, no idea why it happend, but now you should be able to reproduce it.

For now, I'll talk with gdal ppl due to the bugs above, maybe they are even not bugs, just bad documentation.

The part I don't get how to reproduce it, is where I was not able to load any data from the table.

Thx!

**Comment by latot** [comment]
@JCOR11599 There is all I was able to found!

**Comment by latot** [comment]
I confirmed with GDAL, "tables", is an option not for restrict access, is to avoid a massive scanning of tables, to only read or check the ones we wrote, so I will not affect read/write data, or it should not matters, but the error above shows there is a weird behavior with that param.

**Comment by JCOR11599** [comment]
@latot thank you for the thorough testing, comparing it against Postgres is a good idea!
I should note that dolt is meant to be a drop in replacement for MySQL and not necessarily Postgres


Additionally, you can start the server with better logging if that is useful

```
dolt sql-server --loglevel=debug
```

or 

```
dolt sql-server --loglevel=trace
```


What is your end goal here?
Other than getting the `aeropuertos` table into dolt (which it looks like you were able to do), is there anything else you want to happen?

**Comment by latot** [comment]
in this case, it should append the data with the second command.

**Comment by JCOR11599** [comment]
yes, we have a Discord
https://discord.com/invite/gqr7K4VNKe

I am `@jcor#0001`

**Comment by latot** [comment]
This issue was a start point, seems to have a lot of things inside, now is all spplited to the right issues.
