### ISSUE TITLE
Table function aliases

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5928]
The parser does not currently support aliasing table functions, which makes it tricky to perform joins between diff tables. The current workaround is that we assign `{tableName}_{id}` names, with `{id}` incrementing. This doesn't affect useres in the general case, and makes it possible to backdoor join table functions:

```sql
select 
dolt_diff_1.to_id
from dolt_diff('q5kuqa79dmfoeeijd11laa8ppl03dbm8', 'bethkimble/ascension_G', 'hospital')
left join (
    select distinct to_hospital_id
    from dolt_diff('q5kuqa79dmfoeeijd11laa8ppl03dbm8', 'bethkimble/ascension_G', 'rate')
) as r
on dolt_diff_1.to_id = r.to_hospital_id
where r.to_hospital_id is null;
```

We don't want to rely on this behavior long-term. In some cases the implicit renaming obfuscates errors, making it harder to figure out how queries are malformed.

The maybe better solution:

1) Add table function aliasing to parser.

2) Permit non-aliased table functions for single-relation scopes (backwards compatibility).

3) Require table aliasing for join scopes with more than one table function of the same name.

**Comment by timsehn** [comment]
@JCOR11599 is going to do this next.

**Comment by JCOR11599** [comment]
PRs have been merged to GMS main, and will eventually make it dolt main.
