### ISSUE TITLE
Agnostic Geometries from CRS

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#5973]
Hi all, this comes from here https://github.com/dolthub/dolt/issues/5960#issuecomment-1550520896

The solution of @JCOR11599 proposed is great, I want to introduce a little why is great, and why I think is one of the best routes.

At the same time, the issue https://github.com/dolthub/dolt/issues/5960 is focused in fix a MySQL problem, this issue is different.

In the GIS world, we have several types of CRS that we can use, we have the next types:

UTM: This ones assumes all the cords are planar, but only works in a extent of territory, inside the extent 1 meter will be 1 meter but out of it, it will be extremely distorted.
0: Planar, but can be anything, not world related, like if you want to draw.
-1: Unknown CRS: When we don't know the CRS
-2: Not Initialized: When the CRS was not able to be created in the db
Non-planar, like Spherical: I'll call them spherical, like 4326(WGS84) or 3857.

In the ideal world, support everything is great, but is too hard!

The CRS, -1 and -2 are the needed ones, we can miss all the CRS but while these two exists the db will be consistent and should be easy to support this two, and every function like ST_Buffer/etc should throw an error.

The 0 and UTM, works in planar, there is a lot of libs to work with them, like GEOS, SFCGAL and others, this needs work to link and test everything, is possible but needs time.

The Spharical CRS... this ones needs more complex calculations, actually from what I know, from all the non-planar ones, there is only one lib that is able to do the right calculations, and not for all of them!, just for the 4326 and is the S2 lib, but 4326 is great!, because we can work with data from all the world in a consistent way.

Support all the spatial CRS is hard, even now there is no easy way for consistent calculations across the world, even postgis has incomplete the 4326, the 3857 is not supported but can be stored.

Due to the time it takes to develop everything, the usual, and best is be able to store any CRS in the db, even if wen can't use the geometries with functions like ST_Buffer/etc, an error of unsupported is enough, and when is possible be including new features, new supports and extend part by part.

Thx!

**Comment by JCOR11599** [comment]
Closing in favor of: https://github.com/dolthub/dolt/issues/5988
