### ISSUE TITLE
Leak in hosted instance causing a crash

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#5996]
We have a hosted instance on prod (us-jails-3) that has crashed twice. We run cypress tests against the workbench (which connects to the instance and runs queries to display data via system tables, etc) every 1-3 hours. These are the metrics graphs from right before the crash:

![Screen_Shot_2023-05-22_at_9 19 41_AM-1](https://github.com/dolthub/dolt/assets/29443194/55c05194-0497-4bb6-8bde-f5b8b9a38191)

I ran one of the cypress test suites against the same instance on dev with debug logs on and [captured the full log output](https://gist.github.com/tbantle22/7b5261b26aca4763109a7ef2bdefbc5e), as well as the [extracted and dedup'ed individual queries being executed](https://gist.github.com/fulghum/a823b488daba83b960fed8a148b97044).

Update: not sure if this is relevant or not, but this crash happened both times a few days after I cloned a new format database from dolthub (dolthub/im-interested) to this instance (which I guess has old format databases). When we restored the instance only the newly cloned database (im-interested) shows up. We have to ssh into the instance and manually remove that database directory to see the old databases.

**Comment by fulghum** [comment]
I tried to repro the memory leak yesterday, but didn't have much luck yet catching it. I had a script pounding a local sql-server with the following queries I pulled out of [the query logs Taylor collected](https://gist.github.com/fulghum/a823b488daba83b960fed8a148b97044): 
- `SELECT table_name, index_name, comment, non_unique, GROUP_CONCAT(column_name ORDER BY seq_in_index) AS COLUMNS FROM information_schema.statistics WHERE table_schema='us_jails/main' AND table_name='inmate_population_snapshots' AND index_name!='PRIMARY' GROUP BY index_name;`
- `SELECT table_name, index_name, comment, non_unique, GROUP_CONCAT(column_name ORDER BY seq_in_index) AS COLUMNS FROM information_schema.statistics WHERE table_schema='us_jails/main' AND table_name='inmate_population_snapshots' AND index_name!='PRIMARY' GROUP BY index_name;`
- `SELECT * FROM incidents ORDER BY id ASC, start_date ASC, end_date ASC LIMIT 51 OFFSET 0;`

The memory used by the Dolt sql-server process stayed pretty consistent throughout a full day (~8 hours) of running the test. 

Note that this first round of testing was against the DoltHub `us-jails` database, which **has** been migrated to the new storage format. From Taylor's last update on the issue, it sounds like we may need a non-migrated version of the DB and may also need to clone a database into the sqls-server to trigger this. 

I've got a non-migrated copy of the us-jails database now, so will continue some more testing and see if I can catch this happening.

**Comment by timsehn** [comment]
I don't think we should be testing against un-migrated databases. If they leak, the solution is to migrate.

**Comment by tbantle22** [comment]
How do I migrate on Hosted?

**Comment by timsehn** [comment]
I think you need to drop the database and `call dolt_clone()` an migrated copy

**Comment by timsehn** [comment]
Resolving this one.
