### ISSUE TITLE
Customer wants to delete a branch named `-b`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6001]
A customer somehow got a branch named `-b`. This is hard to do. 

I can't repro with:
```
$ dolt branch '-b'
error: unknown option `b'
$ dolt branch b    
$ dolt branch mv 'b' '-b'
error: unknown option `b'
```

Or on the SQL Server:
```
mysql> call dolt_branch('-b');
ERROR 1105 (HY000): error: unknown option `b'
mysql> call dolt_branch('\-b');
ERROR 1105 (HY000): error: unknown option `b'
```

I think this became harder after: #5762.

So, we need to provide a way to escape the `-` in command line arguments. In bash you do this with `--` so creating and deleting a branch named `-b` would be as follows:
```
$ dolt branch -- -b
$ dolt branch -d -- -b
```

And on the sql server:
```
mysql> call dolt_branch('--', '-b');
mysql> call dolt_branch('-d', '--', '-b');
```

**Comment by fulghum** [comment]
This fix is merged to main and will go out in Dolt 1.8.2.
