### ISSUE TITLE
Support CREATE SPATIAL REFERENCE SYSTEM query

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#6002]
Hi, actually MySQL is not very popular among spatial data, but..! after tests and reporting problems to GDAL here https://github.com/OSGeo/gdal/issues/7781#issuecomment-1557917560 now GDAL will create missing CRS for spatial data! which also means a global support for CRS in MySQL, that fix is here: https://github.com/OSGeo/gdal/pull/7812

Oks, now, MySQL does not allow us to add a new CRS, the MySQL way to do it is using the query:
```
CREATE SPATIAL REFERENCE SYSTEM query
```

Here the docs: https://dev.mysql.com/doc/refman/8.0/en/create-spatial-reference-system.html

With this support, now all will rest on the MySQL driver, Dolt should not think about this if possible.
Is crucial this support, so is even great this fix goes on the right place, which is GDAL.

This support should cover almost all the https://github.com/dolthub/dolt/issues/5988

The only point that remains would be the support for -1 and -2 CRS, maybe the best would be do as postgis and transform them to 0, but that should only happens if they are explicit used, that would more about debug cases, in any other case the CRS should be created.

And wait next GDAL release :)

Thx!

**Comment by JCOR11599** [comment]
Hey @latot, this feature has just been merged, and it's currently making its way up to dolt main. We plan to release later today.
This PR allows you to add essentially any SRID with a valid name, description, etc. through `CREATE SPATIAL REFERENCE SYSTEM ...`.
MySQL has some additional rules about what definitions are valid, but we are much more lax with that (for now).

More importantly, SRIDs added do not persist between sessions; when you exit the shell, restart the server, etc. the new/modified SRIDs are lost. This is somewhat consistent with MySQL as they throw a warning that custom SRIDs may be lost through updates.
