### ISSUE TITLE
ERROR 1: MySQL error message:value exceeded max field size of 65kb

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#6012]
Hi, I was testing upload spatial data, and I found this error, maybe is even not related to spatial data:

```
ogr2ogr -f MySQL  "MYSQL:mx_osm_other_relations,user=root,port=3306,host=127.0.0.1" "other_relations.gpkg"
ERROR 1: MySQL error message:value exceeded max field size of 65kb Description: INSERT INTO `other_relations` (`geom` , `osm_id`, `name`, `type`, `other_tags`) VALUES (ST_GeomFromText('GEOMETRYCOLLECTION (....a lot of linestirngs.....)',4326, 'axis-order=long-lat') , '2266294', 'U.S.-Mexico border fence', 'collection', '"collection"=>"us_mexico_border_fence","name:en"=>"U.S.-Mexico border fence","name:ru"=>"Американо-мексиканская стена","wikidata"=>"Q2631595","wikipedia"=>"en:Mexico–United States barrier"')
ERROR 1: Unable to write feature 45 from layer other_relations.
ERROR 1: Terminating translation prematurely after failed
translation of layer other_relations (use -skipfailures to skip errors)
```

Seems there is a limit of 65kb of size for a cell which is pretty low.

Related Docs: https://dev.mysql.com/doc/refman/8.0/en/innodb-limits.html

Recommendations:

Actually, the limit of cells is a topic that has been checked in DBs like Postgres, years ago 1GB as a limit was fine, but for today where we have more and more data the DBs can change to a higher value. There is a team that is extending Postgres limit, so any solution, I think would be great if is extensible or flexible for the future.

Maybe an option for Dolt to us be able to change this limits? would be a middle point.

Some JSON can hit on this too, for some big cases of data.

Note: MySQL is able to load the data to the db.

Thx!
[other_relations.zip](https://github.com/dolthub/dolt/files/11548007/other_relations.zip)

**Comment by timsehn** [comment]
@JCOR11599 is fixing this right now:

https://github.com/dolthub/dolt/pull/6933

Closing in favor of this newer issue: 

https://github.com/dolthub/dolt/issues/6927
