### ISSUE TITLE
Choose most selective index for Merge Join.

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6020]
Merge joins use the first join expression as a comparison operator for index scanning. The comparison drives which index to increment on each iteration.

If the comparison and indexes are chosen such that the relations are equal for every entry in the index, we will attempt to accumulate n^2 matches in memory.

Below, orgId is the same for every value in the table. As a result the merge join will accumulate the cartesian product of the two tables in memory.

```
+------------------------------------------------------------------------------------------------------------------------+
| plan                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                |
|  ├─ columns: [am.id, am.orgId]     |
|  └─ MergeJoin                                                                                                          |
|      ├─ cmp: (am2.orgId = am.orgId)                                                                                    |
|      ├─ sel: ((am.name = am2.name) AND (am.value = am2.value))                                                         |
|      ├─ TableAlias(am2)                                                                                                |
|      │   └─ IndexedTableAccess(am)                                                                        |
|      │       ├─ index: [am.orgId,am.assetId]                                                 |
|      │       ├─ filters: [{[NULL, ∞), [NULL, ∞)}]                                                                      |
|      │       └─ columns: [id orgid assetid name value]                                                                 |
|      └─ TableAlias(am)                                                                                                 |
|          └─ IndexedTableAccess(am)                                                                        |
|              ├─ index: [am.orgId,am.assetId]                                                 |
|              ├─ filters: [{[NULL, ∞), [NULL, ∞)}]                                                                      |
|              └─ columns: [id orgid assetid name value]  
+------------------------------------------------------------------------------------------------------------------------+
```

Merge join costing should use either a strict key or the most selective index. Selection filters should fold into the comparison filter aggressively.

**Comment by nicktobey** [comment]
It looks like we don't actually use O(N^2) memory for this. Even in the worst case where the comparsion values are equal for all rows, we load all of the RHS table's rows into memory and then get each LHS table row one at a time. So O(N) memory but O(N^2) time. This isn't ideal, and is potentially worse memory performance than a naive loop join because we load the entire RHS table into memory.

> Merge join costing should use either a strict key or the most selective index. Selection filters should fold into the comparison filter aggressively.

This part is definitely actionable though. It looks like we currently treat all merge join plans as equally preferable and don't account for the index used at all. We should be smarter about which index we choose.
