### ISSUE TITLE
Running `LEAST` with system variables throws an error

### ISSUE THREAD

**Issue by ricardoreiter** [dolthub/dolt#6022]
I'm trying to use https://github.com/jeremydaly/serverless-mysql library as a client to Dolt's sql-server, but that library runs a few queries to check the number of active connections.

The following query throws an error
`SELECT LEAST(@@max_user_connections,@@max_connections)`
`unsupported type for greatest/least argument: types.systemIntType`

**Comment by timsehn** [comment]
Interesting. I think this is an easy fix.

Really easy repro:
```
$ dolt sql -q "SELECT LEAST(@@max_user_connections,@@max_connections)" 
error on line 1 for query SELECT LEAST(@@max_user_connections,@@max_connections): unsupported type for greatest/least argument: types.systemIntType
unsupported type for greatest/least argument: types.systemIntType
```

We should be able to have a fix in the next couple days.

**Comment by zachmu** [comment]
This fix will be in the next release, should be out tomorrow. Thanks for the report!
