### ISSUE TITLE
Dolt interactive sql-client cli: Support database name for connection

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#6062]
A minor quality of life suggestion.

ex. `dolt sql-client -u root <dbName>`
or `dolt sql-client -u root <dbName>/<branchName>` for a branch-specific connection

The above work with a normal mysql client, just not the dolt sql-client, requiring an extra `use <dbName>` after the connection is made.

**Comment by timsehn** [comment]
I ran into this yesterday myself.

We're actually reworking `dolt sql` right now so that it can connect to a running server. This may obviate the need for `dolt sql-client`.

@macneale4 for visibility.
