### ISSUE TITLE
Prevent Indexing JSON Fields

### ISSUE THREAD

**Issue by jycor** [dolthub/dolt#6064]
In MySQL, creating `SECONDARY` indexes over a `JSON` column results in this error
```sql
mysql> create table t (i int primary key, j json);
Query OK, 0 rows affected (0.0148 sec)
mysql> create index test on t (j);
ERROR: 3152: JSON column 'j' supports indexing only via generated columns on a specified JSON path.
```

In dolt, an index is formed directly referencing the `BLOB` data.
Some MySQL docs for context: https://dev.mysql.com/doc/refman/8.0/en/create-table-secondary-indexes.html

**Comment by nicktobey** [comment]
Do we do it correctly though? If this is a feature we already have working I see no reason to disable it just to match 1:1 with MySql

**Comment by timsehn** [comment]
> Do we do it correctly though? If this is a feature we already have working I see no reason to disable it just to match 1:1 with MySql

We definitely do not do it correctly :-)
