### ISSUE TITLE
Allow conflict resolving for dolt_cherry_pick()

### ISSUE THREAD

**Issue by prodoelmit** [dolthub/dolt#6095]
Currently you cannot cherry-pick any commit if there are any conflicts. This behavior is tested in [cherry-pick tests](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/cherry-pick.bats#LL159C19-L159C19)

As Dolt is truly Git-like for us, we sometimes need to cherry-pick some commits, e.g. from develop to release branch, like we could do in Git. 
It would be nice to have the tools to apply cherry-pick with some modifications in case of conflict. 

E.g. we could have the same behavior as with dolt_merge:
* Pause cherry-picking 
* Allow viewing three-way-merge 
* Allow cherry-pick to be committed after all conflict rows are deleted

As I can see, both cherry-pick and merge already use the same merge logic defined in [merge.MergeRoots](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/merge/merge.go#L119) so it should be quite possible.

**Comment by timsehn** [comment]
Petty sure this is released right @fulghum ?

**Comment by fulghum** [comment]
Ah, sorry I forgot to close this issue with the PR. Yup – this was implemented in PR https://github.com/dolthub/dolt/pull/6144 and released last week. 

Thank you for this feature request @prodoelmit! 🙏
