### ISSUE TITLE
`event` reserved keyword quoting differences with MySQL

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#6123]
A customer reported that Dolt requires quoting the `EVENT` keyword in places where MySQL does not. I thought PR https://github.com/dolthub/vitess/pull/242 fixed this, but looks like that was for the `EVENTS` keyword and mentioned grammar conflicts for the `EVENT` keyword. I was just able to repro with the tip of main.

Repro:
```
CREATE TABLE webhook_events (pk int primary key);

ALTER TABLE webhook_events ADD COLUMN event varchar(255) DEFAULT NULL;
Error parsing SQL
syntax error at position 44 near 'event'
ALTER TABLE webhook_events ADD COLUMN event varchar(255) DEFAULT NULL
```

Note that this does not require quoting if the `event` column is used in the `create table` statement, but fails parsing when part of an `ALTER TABLE` statement.

**Comment by jennifersp** [comment]
The [fix](https://github.com/dolthub/vitess/pull/245) is merged to main.
