### ISSUE TITLE
Feature Request: Is there any chance to support Supabase or VectorDB?

### ISSUE THREAD

**Issue by firespike2050** [dolthub/dolt#6155]
Dolt is amazing.
Supabase is really good too and pgvector works well.New species like Qdrant Milvus are trending.
Vectors and embeddings have many use cases for version controlled branching.
Is any chance to support VectorDBs in future?
Thanks a lot!

**Comment by timsehn** [comment]
Thanks for the issue. I haven't researched too much into what special features these databases do. Our prolly tree data structure is pretty generalizable and could probably be made to work. Happy to hop on a quick call so you could explain your use case a bit more. Then, I would go off and do some technical research to figure out how support would look.

**Comment by timsehn** [comment]
I'm going to resolve this issue. It's too big to have a specific GitHub issue for. We are hard at work building an OLTP SQL database. We think a version controlled version of every type of database will eventually exist. We might not be the ones to build every one of them but we'd be happy if other people took our storage engine and built them with it.
