### ISSUE TITLE
`select count(*) from <table>` confusingly slow for some users

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6157]
This is a very common query and most databases special case it to return fast. Dolt does not, performing a full table scan. We should also special case it so that it fits people's performance expectations.

**Comment by timsehn** [comment]
GMS PR for this:

https://github.com/dolthub/go-mysql-server/pull/1829

**Comment by max-hoffman** [comment]
Waiting to close this until i get the Dolt side merged
