### ISSUE TITLE
Feature request: `call dolt_merge(..., '--no-ff')` should return the commit hash

### ISSUE THREAD

**Issue by ricardoreiter** [dolthub/dolt#6159]
Returning the commit hash made by a non-fast-forward merge is useful in a multitenant environment to properly identify the commit that was made. This would be helpful in cases where you want to tag the merge (`call dolt_tag()`) so it can be reverted in the future with `call dolt_revert`.

**Comment by JCOR11599** [comment]
The fix for this has been merged to dolt main, a release will be out later today.
There is now a hash column when calling dolt_merge()
```sql
tmp> call dolt_merge('main', '--no-ff');
+----------------------------------+--------------+-----------+
| hash                             | fast_forward | conflicts |
+----------------------------------+--------------+-----------+
| u87jjucg18q1r903kitmmui6un1208ib | 0            | 0         |
+----------------------------------+--------------+-----------+
1 row in set (0.00 sec)
```

In cases where a merge commit isn't created (ff merge, merge failed, etc.) that column is empty
```sql
tmp> call dolt_merge('main');
+------+--------------+-----------+
| hash | fast_forward | conflicts |
+------+--------------+-----------+
|      | 1            | 0         |
+------+--------------+-----------+
1 row in set (0.00 sec)
```

**Comment by ricardoreiter** [comment]
Thank you so much @JCOR11599
