### ISSUE TITLE
Optimizer statistics v1

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6161]
## Background

There are two behaviorally useful kinds of SQL transformations. The first are simplifications that always lead to faster queries. For example, the query `select x from (select * from xyz)` is best executed simply as `select x from xyz`. The latter removes a redundant projection and deserializes only a subset of columns from the table.

The second kind of transformations are cost-based transformations, the topic here. The query `select * from xy join uv on x = u where x > 1` can be executed in two mirrored commutations: `rangescan(xy, x>1) x tablescan(uv)` and `tablescan(uv) x rangescan(xy, x>1)`. We have to pick one, but the best plan depends on the shape of the data in our database at the time of the query. The optimal execution order might change for the same tables in the same database over time.

Digging into `select * from xy join uv on x = u where x > 1` a bit deeper, we want to pick the plan that does the least amount of work. For joins, that usually means using the smaller of two tables as the primary. If `select count(*) from xy where x < 1` is less than `select count(*) from uv`, the fastest plan will likely be `rangescan(xy, x>1) x tablescan(uv)`. To be concrete, if `select count(*) from xy where x < 1` = 10 and `select count(*) from uv`= 100, our preferred plan might do 10 units of work. If we added rows to xy so that `select count(*) from xy where x < 1` = 1000, the same plan might be 1000 units of work.

There is a long tail of statistics that can be used to better measure cardinality:
- Index histograms for filter selectivity (ex: `x < 1 or x > 10` as a fraction of `xy`)
- N-Distinct counts (ex: how many distinct rows will the aggregation `GROUP BY a, b` return)
- Multi-variate column correlation coefficients (ex: how many distinct rows where `a = 1 AND b = 10`)

Additionally, estimations of cost can help guide row or vector-based execution strategies (low cost queries rarely benefit from the overhead of batching and vectorization).

The common thread here is the relationship between a filters and the distribution/correlation of values in the underlying table. We need a system to configure stats, gather stats, manage the lifetime of stats updates, and use statistics in the query planner.

## No stats

Opting out of stats still needs to work. The barebone version should work seamlessly all of the more complex formats.
- empty stats object in GMS?
- gather barebones buckets with min/max uniform distribution in GMS if no stats?

## Configuration

SQL variables for
- stats on/off
- stats refresh rate
- memory or disk support
- branch behavior: only default branch? multiple stats for different branches?
- histogram version (GMS internal)

SQL table for:
- store custom stats; aggregate, n-distinct, multi-variate stats not collected by default
- store histogram for testing

SQL commands for triggering refresh (of certain commit hash?)
- ANALYZE command already supported
- reset the statistics cache

MySQL has a specific interface for inspecting statistic and traces for specific queries, linked in the resources below. We probably don't need to support every feature. We already lean into `information_schema` as the way of accessing and updating this information.

## Gather & Refresh

How we update depends also on how we bucket. Most databases refresh by performing table scans periodically, but most databases don't have merkle hashing. If our histogram buckets are chunks, there is upside on the refresh side:
- Every commit could be pushed to an async queue that updates a bucket and its parents
- We could use diffs to measure staleness at certain heights in the prolly tree to trigger refreshes
- We can use diffs to refresh only a subset of buckets
- Statistics could be aggregated up the tree to mirror the database structure
- The diffs will add and subtract counts, NULL counts, distinct counts based on the fraction of the tree we're replacing
- Merging values in buckets -- exact counts are easy to sum and subtract. There are sparse counting intrinsics for merging, subtraction might be more difficult. The alternative would be re-merging 200-1 buckets for updating a parent.

The downside is maybe buckets aren't as adaptable. Distinct count estimation is often fuzzy, and systems will massage per-bucket distincts so sum of fuzzy estimates match the exact row count.

Another downside for chunk-bucketing is that the statistics solution is probably not generalizable in GMS. A lot of logic would be pushed to the Dolt side for gathering, control, caching.

Statistics might need a caching and truncation mechanism, depending on if we have memory-only and disk-backed support. At any given time at least HEAD should be represented.
- memory only
- write every bucket to disk; need GC to clear only references
- periodically replace the version on disk with current stats; keep commit references so we can rebuild stats with diff rather than table scan?

## Branches

Branches need to not stomp each others stats. It is better for us to have one set of stats for each branch, or always only maintain HEAD of the default branch?

## Stats use

GMS will want access to a generic data structure with the following info:
- row count
- NULL count
- distinct count

These could be exact, approximate, or stale, the optimizer needs to work regardless.

The histogram representation should be mutable:
- apply filter to histogram
- join two histograms
- union/intersect two histograms
- histogram for literal values
- histograms for table functions (partial information, like table count and min/max)

## Versioning

There's a difference between different statistic gathering strategies (i.e. exact vs approximate) and histogram formats that are incompatible. It is hard to gauge how often the latter would happen. Even for the latter case, customers using a certain version of statistics might want to upgrade Dolt without changing their statistics strategy. Allowing further rounds of testing with a new stats strategy is helpful.

# Concrete Deliverable

Contrary to some features, I think the first pass of statistics that we test with query plans should be more than bare-bones. I lean towards:
- in-memory buckets and truncation (Dolt side)
- chunk-based buckets that mirror Prolly tree (Dolt side)
- index prefixes only, numeric columns and string prefixes (some fixed length) only
- 3 modes: no updates, manual updates, async continuous updates
- histogram representation (GMS)
- mutating histograms with filters, intersections, and joins (GMS)
- GMS costing STILL has to work with no statistics

This requires equal Dolt and GMS changes. Dolt side implements of gathering and updating buckets, GMS side implements manipulating the histogram aggregation of buckets for costing query plans.

Testing is going to be extremely valuable here:
- All query plan tests should come with cost estimates
- Short term use TPC-C, and medium term TPC-DS to drive guide improvements.

Better debug support for explorative query costing might be useful.

Resource:
- https://www.postgresql.org/docs/current/planner-stats.html
- https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170908_sql_optimizer_statistics.md
- https://youtu.be/wHo-VtzTHx0?t=1720
- https://www.postgresql.org/docs/current/multivariate-statistics-examples.html
- https://dev.mysql.com/blog-archive/histogram-statistics-in-mysql/
- https://github.com/axiomhq/hyperloglog

**Comment by timsehn** [comment]
We have table statistics but they are not auto-generated. You must run `analyze` first.

**Comment by max-hoffman** [comment]
I think I did all of the basics in this list. A lot more can be done for applying statistics to more queries, update performance, throughput limiting updates so it doesn't impact ongoing query performance, etc.
