### ISSUE TITLE
Phpmyadmin crashes Dolt

### ISSUE THREAD

**Issue by EliasKotlyar** [dolthub/dolt#6179]
Hello everyone,

I am trying to run Dolt together with a PHP Application. Unfortunately, this does not work, not even with Tricks.

There are multiple issues:
1. PHPMyadmin is checking the Mysql Version using 

`SELECT @@version, @@version_comment`

Unfortunately, this query does not result any results.

4. PHPmyadmin runs following Query if you want to create a new Database:

`SELECT` *, CAST(BIN_NAME AS CHAR CHARACTER SET utf8) AS SCHEMA_NAME FROM (SELECT BINARY s.SCHEMA_NAME AS BIN_NAME, s.DEFAULT_COLLATION_NAME FROM `information_schema`.SCHEMATA s  GROUP BY BINARY s.SCHEMA_NAME, s.DEFAULT_COLLATION_NAME ORDER BY BINARY `SCHEMA_NAME` ASC) a`

This leads to a kernel Panic in dolt:

`
root-instance-db     | panic: interface conversion: interface {} is []uint8, not string
root-instance-db     | 
root-instance-db     | goroutine 331 [running]:
root-instance-db     | github.com/dolthub/go-mysql-server/sql/rowexec.groupingKey(0xc000e37700?, {0xc000cd1de0, 0x2, 0x20?}, {0xc0004a2d80, 0x6, 0x6})
root-instance-db     |  /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230616233436-b08dd4d7c957/sql/rowexec/agg.go:251 +0x2e8
root-instance-db     | github.com/dolthub/go-mysql-server/sql/rowexec.(*groupByGroupingIter).compute(0xc000e83300, 0x1?)
root-instance-db     |  /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230616233436-b08dd4d7c957/sql/rowexec/agg.go:160 +0x9c
root-instance-db     | github.com/dolthub/go-mysql-server/sql/rowexec.(*groupByGroupingIter).Next(0xc000e83300, 0xc00039f7c0)
root-instance-db     |  /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230616233436-b08dd4d7c957/sql/rowexec/agg.go:133 +0x76
root-instance-db     | github.com/dolthub/go-mysql-server/sql/rowexec.(*sortIter).computeSortedRows(0xc000c8ef00, 0xc00039f7c0)
`

**Comment by timsehn** [comment]
Thanks for the issue. These should be easy to fix. We are off tomorrow but either @JCOR11599 or @fulghum will get to it.

We'll also add an integration test for `phpmyadmin`.

**Comment by timsehn** [comment]
@JCOR11599 is going to grab this one soon.

**Comment by JCOR11599** [comment]
Hey @EliasKotlyar, 
The fix for both of them have been merged into GMS, and will make it to dolt main soon; they'll be in the next dolt release.

The output for `select @@version, @@version_comment;` is now
```sql
tmp> select @@version, @@version_comment;
+-------------------+---------------------------+
| @@SESSION.version | @@SESSION.version_comment |
+-------------------+---------------------------+
| 8.0.11            | Dolt                      |
+-------------------+---------------------------+
1 row in set (0.00 sec)
```

The panicking query now outputs:
```sql
tmp> SELECT *, CAST(BIN_NAME AS CHAR CHARACTER SET utf8) AS SCHEMA_NAME FROM (SELECT BINARY s.SCHEMA_NAME AS BIN_NAME, s.DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA s GROUP BY BINARY s.SCHEMA_NAME, s.DEFAULT_COLLATION_NAME ORDER BY BINARY SCHEMA_NAME ASC) a;
+--------------------+------------------------+--------------------+
| BIN_NAME           | DEFAULT_COLLATION_NAME | SCHEMA_NAME        |
+--------------------+------------------------+--------------------+
| information_schema | utf8mb4_0900_bin       | information_schema |
| tmp                | utf8mb4_0900_bin       | tmp                |
+--------------------+------------------------+--------------------+
2 rows in set (0.00 sec)
```

Hopefully, this gets PHPMyAdmin working for you.
Thanks for submitting these issues, please make more if/when you find more bugs!
