### ISSUE TITLE
Dolt does not allow strings as collate name

### ISSUE THREAD

**Issue by Nadyita** [dolthub/dolt#6192]
In MySQL, the following SQL is perfectly valid:
```sql
create table `migrations` (
  `id` bigint unsigned not null auto_increment primary key,
  `module` varchar(255) not null,
  `migration` varchar(255) not null,
  `applied_at` int not null
) default character set utf8 collate 'utf8_unicode_ci'
```
But dolt complains with `INVALID_ARGUMENT syntax error at position 232 near 'utf8_unicode_ci'`. Removing the 2 `'` fixes it, but since it's valid SQL, it should not complain.

**Comment by timsehn** [comment]
Good find and good workaround.

@Hydrocharged will fix this today.

**Comment by bpf120** [comment]
Hi @Nadyita , we'd love to learn about your Dolt use case too. You can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.
