### ISSUE TITLE
All command line arguments that use table or column names should match case-insensitive

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#620]
Use SQL case sensitivity semantics anywhere we take tables as an argument or parameter. 
- `dolt table import <table> data.csv`
- `dolt diff <table>`
- `dolt schema show <table>`
- `dolt add <table>`
- etc

(PS case should be a style annotation FWIW)

**Comment by timsehn** [comment]
I think this is fixed. Reopen specific cases if need be.
