### ISSUE TITLE
Differences between `dolt sql` results and `dolt sql-server` results

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#6220]
When Dolt executes statements directly in a `dolt sql` shell, the results can be slightly different than the same query executed over a SQL connection to `dolt sql-server`. This is caused by `dolt sql-server` executing additional logic as part of marshalling the result set to go over the SQL connection. 

Issue https://github.com/dolthub/dolt/issues/5835 mentions one concrete example of this – in `dolt sql` Decimal type values are not expanded to their full scale, while through `dolt sql-server` they are, which matches MySQL's behavior (e.g. "10" instead of "10.00" for `DECIMAL(4,2)`). 

Our Go enginetests have this same issue – they don't run all the code that runs when the same queries are executed over a SQL connection, and we've occasionally seen issues where we have test coverage, but the additional SQL marhsalling code has uncaught bugs that our tests would have caught if they were running all the SQL marshalling logic.

**Comment by timsehn** [comment]
We'll resolve this one for these reasons:

1. dolt sql now goes through a running server if one exists
2. This is what @jennifersp is testing with her new engine test harness.

If we find specific bugs where `dolt sql` does not match `dolt sql-server` plus a client, let's get them opened as specific bugs.
