### ISSUE TITLE
Automatically merge changes that enlarge varchar fields

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#6261]
If one branch of a merge has enlarged the length of a varchar column, but not the other side, then dolt merge will report a schema conflict and ask the user to resolve it before the merge has completed. Enlarging a varchar column is guaranteed to be a safe type change to make, since we know it won't truncate any existing data. We should optimize this case so that dolt can automatically merge this type of column change without requiring user invention. We do this currently for adding a new value to the end of a set or enum. I'll need to double check how we are storing this data in table files – if this change requires rewriting all the data in a type file, then it's a bit trickier to implement, but if it doesn't, it's a very easy change to make. I believe that it *will* require rewriting all the table data, but I'll double check and update this issue.

**Comment by timsehn** [comment]
Customer pinged on this one in Discord.

**Comment by fulghum** [comment]
I did a quick spike on this one and it looks like we should be able to support widening `varchar` types pretty easily. Widening beyond `varchar (i.e. to `text`) is a bit more involved, but certainly doable – it just requires updating all existing rows to change the encoding from a variable length string encoding to a blob encoding. 

I need to refactor a few interfaces and clean up tests, but I should be able to have a PR out for this by tomorrow.
