### ISSUE TITLE
Create flag for specifying the initial branch for a sql client.

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#6273]
Something like `dolt --branch=foo sql ...`. Using this flag would change the initial branch for the `sql` command, as well as any commands that make sql queries under the hood.

Currently, the only way to do this is with the `dolt sql-client` command, which accepts a db/revision pair for its --use-db parameter.

Implementing this is mostly a convenience feature that eliminates the need for `use` or `call dolt_checkout` commands in the sql, but is also important for the rare case where `repo_state.json` is in a bad state that prevents the server from starting. (We have a regression test for this in `deleted_branches.bats`, but that test depends on the current implementation of `dolt checkout` which we are migrating away from.

**Comment by Nithinps021** [comment]
@nicktobey The way I taught to implement this is by appending `use database/branch` or calling `dolt_checkout("branch")` at the start of the user `input query`. I don't know whether its clean way or not.

**Comment by macneale4** [comment]
We do have branch support in the db name, so you can do the following:

`dolt --use-db=database_foo/branch_bar status`

A separate flag would be a nice addition though.
