### ISSUE TITLE
Implement Signed Commits

### ISSUE THREAD

**Issue by canadaduane** [dolthub/dolt#628]
Are there plans to sign a changeset with a private key of some kind (SSH, GPG, etc.) so that a change to the data can be non-repudiable via the corresponding public key? This would lend itself well to auditing data as it is changed within a production system.

**Comment by reltuk** [comment]
Yes, we definitely want to provide this. Dropping signatures into commits when they're generated is probably pretty straight forward, but there's potentially large surface area regarding things like verification in log contexts, on dolthub, etc. This requires more investigation on our end.

Based on the inquiry, am I correct that the MVP here something like:
* a mechanism to sign a commit when it's generated using a locally available private key
* a mechanism to verify a commit signature using a locally available public key

?

**Comment by canadaduane** [comment]
Yes, precisely.

**Comment by michi-zuri** [comment]
yes please! https://medium.com/@pjbgf/spoofing-git-commits-7bef357d72f0

**Comment by oscarbatori** [comment]
Is this a feature request?

**Comment by michi-zuri** [comment]
> Is this a feature request?

Well, technically my comment is a bump of a feature request with an added reference, to underline why this is important.

**Comment by oscarbatori** [comment]
@michi-zuri this came to my inbox without the prior thread, missed this, thanks for sharing that.

**Comment by edulix** [comment]
It would be great if this can be kind of generic to make it easy to support different signing methods (cryptography evolves, so make it "future proof") and support adding metadata (for example to add timestamping).

**Comment by PhilipOakley** [comment]
The issue of providing PGP signed commits for open exchange of verifiable data sets is a necessity for some users of Git, so as to match that of the code integrity.  The discussion is [here](https://lore.kernel.org/git/CAE9CXuhvqfhARrqz2=oS1=9BF=iNhGbJv7y3HmYs1tddn8ndiQ@mail.gmail.com/t/#u)

**Comment by timsehn** [comment]
We agree. It's on the roadmap after we finish new storage engine work:

https://www.dolthub.com/blog/2022-05-20-new-format-alpha/

We'll likely finish storage engine around September.

**Comment by bpf120** [comment]
Hi @PhilipOakley , let us know if you have a Dolt use case you're considering. Feel free to swing by our Discord to share.  

https://discord.com/invite/RFwfYpu

**Comment by macneale4** [comment]
This feature has been shipped in 1.43.0.

Blog: https://www.dolthub.com/blog/2024-09-16-signed-commits/
