### ISSUE TITLE
`mysql.help_topic` not found error

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6308]
A user hit this error:

```sql
error=table not found: help_topic, query=SELECT name FROM mysql.help_topic WHERE name LIKE "SHOW %"}
```

The most I could find in the MySQL docs is [this](https://dev.mysql.com/doc/refman/8.0/en/server-side-help-support.html). [MariaDB docs](https://mariadb.com/kb/en/mysqlhelp_topic-table/) have a bit more info.

**Comment by fulghum** [comment]
This looks like it should be a pretty easy one for us to fill in. MySQL even [provides a script to populate the data](https://github.com/google/mysql/blob/master/scripts/fill_help_tables.sql). The only potentially tricky part is that this is in the mysql database, and we manipulate that database a little differently than info_schema. I'll dig into this a little more and give another update this afternoon.

**Comment by fulghum** [comment]
Resolving this one now that [Dolt 1.7.5](https://github.com/dolthub/dolt/releases/tag/v1.7.5) is released and includes the `mysql.help_` tables. Note that these tables aren't populated yet, but that seems to also be true in many MySQL versions. This change does resolve the `table not found` error above though.
