### ISSUE TITLE
Support for foreign keys

### ISSUE THREAD

**Issue by cfljam** [dolthub/dolt#631]
Importation and setting primary keys works smoothly , as does row updates, but Im having trouble seeing how to easily set foreign key constraints. Is this coming? 
```
$ dolt version
dolt version 0.16.2
 $ dolt sql -q 'ALTER TABLE samples 
>             ADD FOREIGN KEY FOREIGN KEY("contract_name") REFERENCES "contracts"("contract_name")'
unsupported feature: alter table samples
```

ALTER TABLE  ADD seem to work..
```
$ dolt sql -q 'ALTER TABLE samples 
            ADD newcolumn TEXT;'
```

**Comment by timsehn** [comment]
Foreign keys is coming but not on the immediate roadmap.

Assigning to Zach for visibility. He can also fill you in on the SQL roadmap.

**Comment by zachmu** [comment]
This is about a month out, after unique constraints.

We'll improve the error message for alter table in the meantime.

**Comment by evdubs** [comment]
Does this foreign key roadmap include foreign keys across different repositories?

**Comment by zachmu** [comment]
> Does this foreign key roadmap include foreign keys across different repositories?

Yes, but constraints involving more than one repository are farther out. There's a large design component to that kind of constraint, and it will obviously work differently locally v. on DoltHub. We haven't scoped that work yet.

**Comment by evdubs** [comment]
Is it worth opening a new issue for foreign keys across different repositories to make sure that is tracked?

**Comment by timsehn** [comment]
We're tracking it :-) It's on the SQL roadmap.

**Comment by VinaiRachakonda** [comment]
Fks have been in for a bit. Closing
