### ISSUE TITLE
Query with OFFSET does not use Index

### ISSUE THREAD

**Issue by jdclarke5** [dolthub/dolt#6347]
This issue is related to the Discord message https://discord.com/channels/746150696465727668/746150696465727671/1129583603379085413

It is observed that the first query below (no offset) is much slower than the second (zero offset).

1. `SELECT * FROM ohlcv ORDER BY date DESC LIMIT 10` https://www.dolthub.com/repositories/post-no-preference/stocks/query/master?active=Tables&q=SELECT+*%0AFROM+%60ohlcv%60%0AORDER+BY+%60date%60+DESC%0ALIMIT+10%3B%0A
 2. `SELECT * FROM ohlcv ORDER BY date DESC LIMIT 0, 10` https://www.dolthub.com/repositories/post-no-preference/stocks/query/master?active=Tables&q=SELECT+*%0AFROM+%60ohlcv%60%0AORDER+BY+%60date%60+DESC%0ALIMIT+0%2C+10%3B%0A

In my local clone, I see an execution time of ~0.03s versus ~17s! I have tried adding an index and do not see significant improvement. I can see using EXPLAIN that the first query uses `IndexedTableAccess` while the second does not.

**Comment by timsehn** [comment]
transferring to dolthub/dolt repository

**Comment by jdclarke5** [comment]
Thanks @max-hoffman. I would just also note that the two queries I noted originally gave different results for me. I wouldn't think this is necessarily unexpected since the order is not fully specified. However, since `OFFSET` is often used for pagination, I would expect that that "Page 2" is logically follows from "Page 1" (i.e. `OFFSET 0`). I thought this worth mentioning given you were folding into a no-op.

**Comment by max-hoffman** [comment]
Yeah that is understandable @jdclarke5. You seem to already understand but will summarize here for anyone else that runs into this.

Two queries with partial sorting and LIMIT/OFFSET will be consistent as long as we use the same index for sorting results. So two different indexes might rearrange results given the partial sorting criteria. The only circumstance we should change the index is if the query uses an index for filters and the filters change, or you add a new index that becomes preferable, or we change index preferences between Dolt versions for perf reasons. A bad reason is a bug in our plan selection, which was the difference here. One defense against this is join hinting -- we could add a `ICP(index_name)` hint that will always prefer plans with a certain index pushdown condition.

**Comment by JCOR11599** [comment]
Fix for this is merged in dolt main. A release will be out later this week.
