### ISSUE TITLE
Valid join query erroneously reported as ambiguous

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#6394]
Reproduction steps:

```
create table a (b int);
create table c (d int);

select * from a join c c1 on b = d join c c2 on c1.d = c2.d;
```

MySql result: query runs

Dolt output:

```
ambiguous column name "d", it's present in all these tables: c1, c2
```

We seem to be trying to resolve the references in `b = d` in the context of the complete 3-way join, even though it should be resolved just in the context of `a join c c1`

Out of curiosity I changed the query to:

```
select * from a join c c1 on b = c2.d join c c2 on c1.d = c2.d;
```

This is an invalid query and MySQL recognizes it as such:

```
Unknown column 'c2.d' in 'on clause'
```

Dolt also fails but with a different, nonsensical error:

```
table "c2" does not have column "d"
```

(table c2, does, in fact, have a column d. Perhaps it returns this error because it thinks the table exists but the column doesn't.)

(Mirror of https://github.com/dolthub/go-mysql-server/issues/1902)

**Comment by max-hoffman** [comment]
Looks like we'll get this right with updated name res:
```
> explain select * from a join c c1 on b = d join c c2 on c1.d = c2.d;
InnerJoin
 ├─ Eq
 │   ├─ c1.d:1
 │   └─ c2.d:2
 ├─ InnerJoin
 │   ├─ Eq
 │   │   ├─ a.b:0
 │   │   └─ c1.d:1
 │   ├─ Table
 │   │   ├─ name: a
 │   │   └─ columns: [b]
 │   └─ TableAlias(c1)
 │       └─ Table
 │           ├─ name: c
 │           └─ columns: [d]
 └─ TableAlias(c2)
     └─ Table
         ├─ name: c
         └─ columns: [d]
```

the error for the second:
> select * from a join c c1 on b = c2.d join c c2 on c1.d = c2.d;
column "c2.d" could not be found in any table in scope
```
