### ISSUE TITLE
MySQL Performance Benchmark

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#640]
Now that we have the saved query for current correctness percentage on the dolt repo Liquidata/dolt-sql-performance:
```
timsehn$ dolt sql -x "Percent correct"
Executing saved query 'Percent correct':
select round(ok/(ok+not_ok+did_not_run+.01), 4) as percent_ok from (select sum(if(result = 'ok', 1, 0)) as ok, sum(if(result = 'skipped', 1, 0)) as skipped, sum(if(result = 'not ok', 1, 0)) as not_ok, sum(if(result = 'did not run', 1, 0)) as did_not_run, sum(if(result = 'timeout', 1, 0)) as timeout from releases_dolt_results) as results;
+------------+
| percent_ok |
+------------+
| 0.9113     |
+------------+
```
What I really want is a saved query on that repo with a MySQL benchmark. Do a test run pass on MySQL and record the duration of the tests. Run it every quarter or so. Then show P10, P50, P90, P99 and average duration of the tests for MySQL vs Dolt in a table. That table should be generated by a saved query.

**Comment by VinaiRachakonda** [comment]
Closing this as our performance benchmark are public here: https://docs.dolthub.com/reference/performance/latency
