### ISSUE TITLE
`FOUND_ROWS()` returns incorrect results

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#6406]
Hello 👋 

When using `SELECT SQL_CALC_FOUND_ROWS` and then `SELECT FOUND_ROWS()` in all versions of Dolt, I've observed inconsistent results.

To reproduce:

```sh
# Run temporary container
docker run --rm -it --entrypoint bash dolthub/dolt:1.4.2 -c bash

# You can run all of these in one go
dolt config --global --add user.email "you@example.com"
dolt config --global --add user.name "Your Name"
dolt init
dolt sql -q "create table test (name text);"
dolt sql -q "insert into test (name) values ('one'), ('two'), ('three');"
dolt sql -q "SELECT SQL_CALC_FOUND_ROWS * FROM test LIMIT 0, 25;"
dolt sql -q "select found_rows();"
```

The query outputs are:

```
Query OK, 3 rows affected (0.04 sec)
+-------+
| name  |
+-------+
| one   |
| two   |
| three |
+-------+

+--------------+
| found_rows() |
+--------------+
| 1            |
+--------------+
```

Though the count of `found_rows()` should be `3` in the above case.

I also tested on Dolt version `0.50.9` and had a `found_rows()` count of `4`. I can't remember if this was working at some point, and I seem to get inconsistent results.

**Comment by timsehn** [comment]
We'll get on this soon. It will likely be @fulghum but he mat assign someone else.

**Comment by fulghum** [comment]
Hey @theetrain, thank you for taking the time to report this one! While we dig in, I'm guessing you already have ideas for workarounds (e.g. `select count(*) from test;`), but we always like to double check that customers aren't blocked. Speaking of `select count(*)`... it looks like MySQL has recently deprecated `FOUND_ROWS()` and will eventually remove it, so `select count(*)` may not be a bad option anyway, although it's of course a little slower to do it in two separate queries. 

We do have some tests that cover `FOUND_ROWS()`, but there's obviously a gap in their coverage here. We'll repro, dig in, and see where things are getting messed up.

**Comment by theetrain** [comment]
Thanks for your comment, I suppose I should shift to the new recommendation since `FOUND_ROWS()` is deprecated: https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows

**Comment by fulghum** [comment]
Closing this one, since the original author decided to avoid the deprecated `FOUND_ROWS()` function and use MySQL's recommended workaround. Feel free to reopen or create a new issue if you do need this support and aren't able to use the recommended workaround and we'll be happy to take another look.

**Comment by zachmu** [comment]
Needed for various wordpress functionality.

**Comment by timsehn** [comment]
We're gonna track this one in: #6829

**Comment by JCOR11599** [comment]
Hey @theetrain, `SQL_CALC_FOUND_ROWS` and `found_rows()` work based off the current session.
`dolt sql -q` creates a completely new session every time and the default return value for `found_rows()` is 1.

If you were to execute this command in the `dolt sql` shell (no `-q`) it should work as expected.
```
tmp> SELECT SQL_CALC_FOUND_ROWS * FROM test;
+-------+
| name  |
+-------+
| one   |
| two   |
| three |
+-------+
3 rows in set (0.00 sec)

tmp> select found_rows();
+--------------+
| found_rows() |
+--------------+
| 3            |
+--------------+
1 row in set (0.00 sec)
```

However, there is a bug with how this works with the `LIMIT` clause (specifically when `LIMIT > count(*)`)
```
tmp> SELECT SQL_CALC_FOUND_ROWS * FROM test LIMIT 25;
+-------+
| name  |
+-------+
| one   |
| two   |
| three |
+-------+
3 rows in set (0.00 sec)

tmp> select found_rows();
+--------------+
| found_rows() |
+--------------+
| 4            |
+--------------+
1 row in set (0.00 sec)
```

I think I know what's wrong, and am working on a fix.
