### ISSUE TITLE
feature request: dolt table import add option to default to text/varchar type

### ISSUE THREAD

**Issue by LaPingvino** [dolthub/dolt#6471]
some imported column's types are not detected properly. this way you can be sure the data goes in properly first and you can fix up the types later.

**Comment by LaPingvino** [comment]
I was just thinking, it might even better to add an option where you get can edit the detected schema before doing the upload instead.

**Comment by timsehn** [comment]
On the CLI that is `dolt schema import --dry-run`:

https://docs.dolthub.com/cli-reference/cli#dolt-schema-import
