### ISSUE TITLE
Show/Drop Index no longer working on most tables

### ISSUE THREAD

**Issue by Kelley12** [dolthub/dolt#6479]
This appears to be a regression and works on `1.8.0` but no longer works on `1.9.0`.

Indexes are no longer showing up on most of our tables when using `SHOW INDEX FROM table`. We are also unable to drop indexes on those same tables with `DROP INDEX`. A drop results in the following error:

`error: can't drop 'idx_index'; check that column/key exists`

Indexes do show up correctly when querying `information_schema.statistics`:

```sql
SELECT DISTINCT table_name, index_name
FROM information_schema.statistics
WHERE table_schema = 'schema'
```

**Comment by timsehn** [comment]
This is a bad one and a clear gap in our tests. Thanks for the report. We'll get it fixed and releases asap.

**Comment by timsehn** [comment]
This is a bad one and a clear gap in our tests. Thanks for the report. We'll get it fixed and releases asap.
