### ISSUE TITLE
Allow pattern-matching in replicate_heads variable

### ISSUE THREAD

**Issue by prodoelmit** [dolthub/dolt#6486]
We use our read-replica to have clean state for CI. As we're using git-flow, there are multiple release branches which are all named like `release*`. 

We would like to be able to replicate only them, but currently we can either use `"replicate_heads": "release_1,release_2,release_3"` and update it each time we have new branch, or use `replicate_all_heads` that has too much overhead for replicating a single new branch. 

Suggestion: support wildcards in replicate_heads, e.g. `"replicate_heads": "develop,release*,main"`

**Comment by fulghum** [comment]
Great feature request @prodoelmit. I'm getting started on this one today for you.

**Comment by fulghum** [comment]
Thanks for the great feature request @prodoelmit! 🙏 This change has been released in [Dolt version 1.13.5](https://github.com/dolthub/dolt/releases/tag/v1.13.5) and the [docs for `@@dolt_replicate_heads`](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#dolt_replicate_heads) have been updated to mention this feature, too.
