### ISSUE TITLE
`LAST_INSERT_ID()` always returns `0`

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#6497]
When setting up a table with an `AUTO_INCREMENT` primary key, inserting new values and then querying `SELECT LAST_INSERT_ID()` returns `0` consistently.

## Reproduction

```sh
# Run temporary container
docker run --rm -it --entrypoint bash dolthub/dolt:1.10.1 -c bash

# You can run all of these in one go
dolt config --global --add user.email "you@example.com"
dolt config --global --add user.name "Your Name"
dolt init
dolt sql -q "CREATE TABLE test (name TEXT, id INT AUTO_INCREMENT NOT NULL PRIMARY KEY);"
dolt sql -q "INSERT INTO test (name) VALUES ('one');"
dolt sql -q "SELECT LAST_INSERT_ID()"
dolt sql -q "SELECT * FROM test;"
```

Output is:

```sh
Query OK, 1 row affected (0.04 sec)
+------------------+
| LAST_INSERT_ID() |
+------------------+
| 0                |
+------------------+

+------+----+
| name | id |
+------+----+
| one  | 1  |
+------+----+
```

Expected output of `SELECT LAST_INSERT_ID()` is `1`.

The issue also appears on these versions: `v0.75.9`, `v1.0.0`, `v1.4.0`, and `v1.8.0`.

**Comment by timsehn** [comment]
@zachmu is the autoincrement expert. He will look at this Monday.

**Comment by timsehn** [comment]
I just reminded @zachmu of this now. It kind of slipped through the cracks. He is looking now.

**Comment by zachmu** [comment]
The reason this doesn't work is that `last_insert_id()` is local to a session. Every time you run `dolt sql`, it has a new session. If you want all those statements to run in the same session, include multiple statements in a single `dolt sql` invocation. This works:

```bash
% dolt sql -q "CREATE TABLE test (name TEXT, id INT AUTO_INCREMENT NOT NULL PRIMARY KEY); INSERT INTO test (name) VALUES ('one'); SELECT LAST_INSERT_ID(); SELECT * FROM test;"
Query OK, 1 row affected (0.00 sec)
+------------------+
| LAST_INSERT_ID() |
+------------------+
| 1                |
+------------------+

+------+----+
| name | id |
+------+----+
| one  | 1  |
+------+----+
```

You could also start a server with `dolt sql-server` and connect to it with a mysql client, then issue the same statements (in the same connection).

I'm closing this issue, but please reopen it if you have further questions.
