### ISSUE TITLE
Dolt datetime defaults to precision 6, mysql defaults to 0

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#6503]
Specifying a column type as `datetime` in Dolt defaults to datetime(6), while in mysql the default precision is 0 if unspecified. To an unwary user this can cause precision loss when transferring Dolt data to a mysql db that is created using the same DDL.

Ex. In Dolt:
```
mysql> create table foo (bar datetime);
Query OK (0.01 sec)
mysql> show create table foo;
+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| foo   | CREATE TABLE `foo` (                                             |
|       |   `bar` datetime(6)                                              |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+-------+------------------------------------------------------------------+
1 row in set (0.02 sec)

mysql>
```

**Comment by dphil** [comment]
Related reference:
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-type-syntax.html#:~:text=If%20omitted%2C%20the%20default%20precision,updating%20properties%3B%20see%20Section%2011.2.

> The fsp value, if given, must be in the range 0 to 6. A value of 0 signifies that there is no fractional part. If omitted, the default precision is 0. (This differs from the standard SQL default of 6, for compatibility with previous MySQL versions.)

**Comment by timsehn** [comment]
@zachmu is going to tackle this next.
