### ISSUE TITLE
Specify database name on running docker image dolt-sql-server

### ISSUE THREAD

**Issue by riccardolorenzon** [dolthub/dolt#6508]
I'm running for test purposes a dolt sql server on a docker-compose like environment. 
I need a database initialised where i can apply all DDL commands necessary to execute the integration tests. 
I tried two approaches: 
First approach - connect with dolt to the running container and create a database: 
```
➜  docker run -p 3399:3306 dolthub/dolt-sql-server dolt sql-server -H 0.0.0.0
➜  docker exec -ti <container_id> bash`
➜  dolt sql --query='create database test;
```
If i then connect with `mysqli` to the dolt instance, i can't see the newly created database `test`, nor create a new database called `test`: 
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
+--------------------+
2 rows in set (0.01 sec)

mysql> create database test;
ERROR 1007 (HY000): can't create database test; database exists
mysql> use database test;
ERROR 1105 (HY000): unknown error: database not found: database
```
Second approach: create a new folder called `test`, intialise it with dolt and then run dolt sql server:
```
➜  mkdir test_dolt
➜  cd test_dolt
➜  dolt init
Successfully initialized dolt data repository.
➜  dolt sql-server -P 3400
➜  mysql> show databases;l
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| test_dolt          |
+--------------------+
```
this seems to work, but how can i replicate it using docker only? I tried to start the docker container from the docker sql-server image specifying the custom command to create the directory and init it beforehand, but i didn't manage. 
```
docker run -p 3399:3306 dolthub/dolt-sql-server:latest  dolt config --global --add user.email "you@example.com" && dolt config --global --add user.name "Your Name" && dolt init && dolt sql-server -H 0.0.0.0

docker: Error response from daemon: driver failed programming external connectivity on endpoint bold_leakey (a43cd98db1b9ecf88e7dc86c1a4e2f48cdeab6ceefaaf30b6ae5618f97c75ff1): Bind for 0.0.0.0:3399 failed: port is already allocated.
ERRO[0000] error waiting for container: context canceled
```

**Comment by timsehn** [comment]
@coffeegoddd or @reltuk is the best person to answer this. I'm not a docker expert.

**Comment by reltuk** [comment]
What specifically do you need to do that can't be done against the SQL server itself?

Why doesn't something like

```sh
$ docker run -p 3399:3306 dolthub/dolt-sql-server dolt sql-server -H 0.0.0.0 &
$ mysql -H 127.0.0.1 -P 3399
mysql> CREATE DATABASE test;
...
```

work for creating the database?

Alternatively, if you don't have a MySQL client on the host itself, you can use `dolt` from within the container as a SQL client against the server. Something like (change the container name as appropriate):

```sh
$ docker exec -ti 640b86e0da13 dolt --host 127.0.0.1 --port 3306 --no-tls sql --query 'create database test'
```

**Comment by macneale4** [comment]
This is actually not related to docker at all. This is a result of `sql-server` starting in an empty directory.  Try `dolt init` in that directory before starting the server.

`dolt sql-server` automatically initializing an empty directory is possible. I'm looking into that.

**Comment by reltuk** [comment]
As my colleague @macneale4 points out, it would be better if `dolt sql` run from the working directory of the docker container connected to the sql-server instance by default, so that the `CREATE DATABASE ...` invocation in your first example worked as expected. We are looking into that.

In the meantime, maybe the explicit `--port ... --host ... --no-tls` arguments to the `dolt sql` invocation from within the docker container can unblock you.

**Comment by riccardolorenzon** [comment]
As I pointed out on my first scenario, running the dolt command to create the database does not solve the issue, the database is not visible on the MySQL client, the issue should be reproducible, if not let me know.

I could use a MySQL client on my integration test setup, but that would complicate my setup, I was wondering if there was a more straightforward solution.

**Comment by timsehn** [comment]
> As I pointed out on my first scenario, running the dolt command to create the database does not solve the issue, the database is not visible on the MySQL client, the issue should be reproducible, if not let me know.
> 
> I could use a MySQL client on my integration test setup, but that would complicate my setup, I was wondering if there was a more straightforward solution.

The solution is instead of running:

`dolt sql --query='create database test;`

Run:

`docker exec -ti 640b86e0da13 dolt --host 127.0.0.1 --port 3306 --no-tls sql --query 'create database test'`

If you want to do everything from the command line.

The problem is `dolt sql --query='create database test;` is starting anew serevr outside of docker and creating a database for you.

**Comment by riccardolorenzon** [comment]
I was not clear enough, but I was running the dolt command within the docker container. 
Can you reproduce the issue?

**Comment by reltuk** [comment]
@riccardolorenzon In the above instructions, we are also running the dolt command within the docker container. We can reproduce the issue. If you do not provide the arguments we are suggesting, then the created database is not visible. If you do provide the arguments we suggest, then the database is visible. My colleague is looking into making it work without providing the arguments, but in the meantime you can provide the arguments.

**Comment by riccardolorenzon** [comment]
I confirm that using the additional parameters `host` `port` and `no-tls` solves the issue. Thanks!
