### ISSUE TITLE
Prepared statements cache AST nodes

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6572]
`oltp_point_select` spends a lot of time in parser, maybe ~30% of analyzer time (the time spent in execution barely registers in profile). If prepared statements cache the AST rather than a PreparedQuery, we'd trim this time to almost 0%:
 
<img width="1607" alt="image" src="https://github.com/dolthub/dolt/assets/18337807/130d57f2-0661-4937-9a09-a4b7875aab0f">

I had back luck with my first stab at this, but I don't think it should be particularly edge-casey. The only thing we really need is a reliably way to walk an AST and copy it into a format with BindVar replaced with `expression.Literal`. The built-in walking helper `ast.Walk` might need a visitor capable of implicitly buffering/accumulating child nodes during an in-order traversal. Any other implementation that treats the cached AST as immutable and generates a copy with BindVariables replaced is equally great.

Saving the AST rather than the post-planbuilder node is a preferable step because we get most of the performance benefit with little correctness risk.

**Comment by timsehn** [comment]
> I had back luck with my first stab at this

:-(

**Comment by max-hoffman** [comment]
> > I had back luck with my first stab at this
> 
> :-(

My first attempt was while rewriting name resolution and juggling several things, I didn't hit any resistance with ParsedQuery so I just ran with that to merge my refactor sooner. In isolation I don't think this is going to be a lot more than writing a helper function to copy arbitrary AST nodes.

**Comment by timsehn** [comment]
We ended up doing this one right? Can we close?

**Comment by fulghum** [comment]
Yup, this change landed in PR https://github.com/dolthub/go-mysql-server/pull/1976 at the end of August
