### ISSUE TITLE
Support for JSON modification functions

### ISSUE THREAD

**Issue by Kelley12** [dolthub/dolt#6585]
**Is your feature request related to a problem? Please describe.**

When working with a JSON column, it's easy to query that column for the values, but when attempting to update the values, the functions to do so are not supported.

**Describe the solution you'd like**

Support for the basic JSON modification functions:

* [JSON_INSERT](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-insert)
* [JSON_REPLACE](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-replace)
* [JSON_REMOVE](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-remove)

**Describe alternatives you've considered**

1. Modifying those columns to be relational. This would require a lot of rework and many schema conflict issues with our workflow.
2. Extracting the JSON, updating the object, and updating using an update script. This is possible but cumbersome
3. Manually updating the JSON values. Possible with a few rows but not feasible with hundreds or thousands of rows

**Comment by timsehn** [comment]
We'll get on this right quick. Thanks for the request. A function usually takes about 4 hours of developer time so this is a couple days of work.

**Comment by macneale4** [comment]
I'm going to add [JSON_SET](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-set) to the list to implement.

All four are recommended in concert to give full control
