### ISSUE TITLE
NULL values written to Noms tuple

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#659]
The issue fixed in [this pr](https://github.com/liquidata-inc/dolt/pull/645) was caused by comparison to Noms NULL values in non-primary-key columns. Null values are supposed to be omitted in the row storage.

**Comment by timsehn** [comment]
Potential repro steps:

1. Run that import script (it does a table import) to create the table with an all text schema.
2. Inspect the schema looking for better types
3. For columns I wanted different type I dropped the column, added with a
new type, same name different tag using alter table sql statements. 
4. Run the import again to add the values back to the column (used table import -r)
