### ISSUE TITLE
invalid type: double since 1.13.5

### ISSUE THREAD

**Issue by attrib** [dolthub/dolt#6610]
Getting a error since `dolthub/dolt-sql-server:1.13.5` (also fails for  `dolthub/dolt-sql-server:1.13.6`)

```
foxhole-api-dolt-1  | 2023-09-03T20:45:05Z WARN [conn 1] error running query {connectTime=2023-09-03T20:44:31Z, connectionDb=foxhole, error=invalid type: double}
foxhole-api-map-1   |   code: 'ER_UNKNOWN_ERROR',
foxhole-api-map-1   |   errno: 1105,
foxhole-api-map-1   |   sql: 'SELECT * FROM dolt_diff_feature WHERE to_warId = ? AND to_commit IN (SELECT commit_hash FROM dolt_log WHERE date >= ?) ORDER BY to_commit_date DESC LIMIT ?, ?',
foxhole-api-map-1   |   sqlState: 'HY000',
foxhole-api-map-1   |   sqlMessage: 'invalid type: double'
```

Same query works when I downgrade to `dolthub/dolt-sql-server:1.13.4`

feature table:
```sql
CREATE TABLE feature (
                     `id` varchar(36) NOT NULL,
                     `warId` varchar(36) NOT NULL,
                     `shard` varchar(20) NOT NULL,
                     `map` varchar(50) NOT NULL,
                     `x` double NOT NULL,
                     `y` double NOT NULL,
                     `iconType` int NOT NULL,
                     `teamId` varchar(50) NOT NULL,
                     `flags` int NOT NULL,
                     `text` varchar(100) NOT NULL,
                     PRIMARY KEY (`id`, `shard`, `warId`)
) DEFAULT CHARSET=utf8;
```

**Comment by max-hoffman** [comment]
Thanks or the report @attrib, would you mind providing an example of parameters for the prepared statement that trigger the error?

**Comment by attrib** [comment]
Oh sorry, forgot that.

```
[
  "837d43fe-b9b2-41d5-a582-bb1fa607c761",
  "2023-09-05",
  0,
  1000
]
```

example return data, which fails with the new version
```
[
    {
      "commit": "e1tj06gpb27bivh5bvdaj7hujd2sclra",
      "date": "2023-09-05T20:03:27.576Z",
      "diff_type": "modified",
      "from_objectId": "43a441f8-39df-402c-8a36-27ab234179cf",
      "from_map": "SableportHex",
      "from_shard": "Able",
      "from_x": 0.7148144,
      "from_y": 0.33608449,
      "from_iconType": 45,
      "from_teamId": "COLONIALS",
      "from_flags": 8,
      "from_text": "The Pendant Small Relic Base"
      "to_objectId": "43a441f8-39df-402c-8a36-27ab234179cf",
      "to_map": "SableportHex",
      "to_shard": "Able",
      "to_x": 0.7148144,
      "to_y": 0.33608449,
      "to_iconType": 45,
      "to_teamId": "NONE",
      "to_flags": 0,
      "to_text": "The Pendant Small Relic Base"
    },
]
```

not sure about commit/date as I quickly got this out of the api which does minimal transformation (see https://api.warden.express/api-docs/#/map/get_worldconquest_maps_history)

**Comment by bpf120** [comment]
@attrib,  we'd love to learn about your Dolt use case too sometime. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

**Comment by attrib** [comment]
After discussion on discord we pin pointed the issue to the prepared statement.

The error doesn't happen if I use a normal query.

As pointed out by timsehn on discord, probably related to https://github.com/dolthub/go-mysql-server/pull/1976

**Comment by max-hoffman** [comment]
I can to repro the error in at least in one way, if I input the LIMIT bindings as floats. I confirmed that the same query that errors on `1.13.5` does not error on `1.13.4`. Because I am guessing at the root cause, there is a small and unlikely chance that the same error message could be produced by a different problem on the same query. I will fix the known bug shortly.

**Comment by max-hoffman** [comment]
Fix here, we'll get this in a release within the next week. If you need it sooner just let us know and we'll release faster
https://github.com/dolthub/go-mysql-server/pull/1990
