### ISSUE TITLE
Creating attribute with more than 64 character is allowed but causes error.

### ISSUE THREAD

**Issue by EminUZUN** [dolthub/dolt#6611]
Dolt allows me to create a table with more than 64 characters. But later gives an error about it.

> query error: string 'ix_uq_country_division_translation_country_division_id_language_code' is too large for column 'varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci'

I think it should not allow table to create if index/column_name/table_name/ etc. is longer than 64

**Comment by zachmu** [comment]
Can you give us a set of SQL statements that reproduce the behavior you're seeing?

**Comment by EminUZUN** [comment]
BTW dolt defaults to utf8mb4 but information schema defaults to utf8mb3. From what I understand
