### ISSUE TITLE
Implement `dolt push --all`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6626]
`git push` has the `--all` argument to push all branches.

<img width="643" alt="image" src="https://github.com/dolthub/dolt/assets/5376236/fa8815dd-d978-4b02-8807-33dfb71dc8df">

A user asked for the same support in Dolt on both the CLI and the SQL procedure.

**Comment by ricardoreiter** [comment]
It was me! That would be a great feature for us.

**Comment by fulghum** [comment]
@jennifersp – this would be a good one to pick up in the next week or so, if you need to get a change of scenery from the wire serialization test harness work.
