### ISSUE TITLE
Parse SECONDARY_ENGINE parameter in queries

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#6632]
SECONDARY_ENGINE is a parameter than can appear on `CREATE_TABLE` and `ALTER_TABLE` statements.

The value used is stored and can be read with `SHOW CREATE TABLE`, and unset by setting it to NULL

Examples:

```
> ALTER TABLE orders SECONDARY_ENGINE RAPID;
> SHOW CREATE TABLE orders;

CREATE TABLE `orders` (
  `O_ORDERKEY` int NOT NULL,
  PRIMARY KEY (`O_ORDERKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin SECONDARY_ENGINE=RAPID
```

The purpose of the parameter in MySQL is to influence which execution engine is used with this table. It should not have any impact on the expected output of queries. Thus, we can safely ignore it.

However, of the 4859 tests in sqllogictest that are still failing on dolt, 1073 are failing because we don't parse SECONDARY_ENGINE.

It looks like Vitess does SECONDARY_ENGINE in its grammar, so I'm not sure why it's not getting parsed.

**Comment by timsehn** [comment]
This would be great to parse, keep on the table, and ignore.

**Comment by JCOR11599** [comment]
Our parser has been updated to fix this issue.
However, like most table options, we just parse and ignore, we do not keep these on the table.
