### ISSUE TITLE
DBeaver loses connection after calling DOLT_GC() 

### ISSUE THREAD

**Issue by nmoreaud** [dolthub/dolt#6633]
```
call dolt_gc();
select 1;
```

SQL Error [1105] [HY000]: this connection was established when this server performed an online garbage collection. this connection can no longer be used. please reconnect

**Comment by timsehn** [comment]
This is known. Dolt needs to re-establish all connections after garbage collection.

**Comment by nmoreaud** [comment]
It would be interesting to document it.

**Comment by timsehn** [comment]
https://docs.dolthub.com/sql-reference/server/garbage-collection#online

**Comment by nmoreaud** [comment]
Maybe you could add a link from this page:
https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures#dolt_gc

**Comment by timsehn** [comment]
Good call out.

https://github.com/dolthub/docs/pull/1713

**Comment by timsehn** [comment]
I'm going to close this. Thanks for the documentation call out. It's a known gap we will eventually fix.
