### ISSUE TITLE
SECURITY ERROR v1.70.x

### ISSUE THREAD

**Issue by SergeyDjam** [dolthub/dolt#6758]
verifying github.com/bcicen/jstream@v1.0.0: checksum mismatch
	downloaded: h1:NiAVuRsoevmPZoLXTljw0JPjT73LeP+l0/iDpjc4rws=
	go.sum:     h1:gOi+Sn9mHrpePlENynPKA6Dra/PjLaIpqrTevhfvLAA=
SECURITY ERROR

**Comment by timsehn** [comment]
Going to close. Can't repro. Seems like something messed up with your local cache.
