### ISSUE TITLE
SELECT LAST_INSERT_ID() returns BIGINT SIGNED for BIGINT UNSIGNED ids

### ISSUE THREAD

**Issue by gitasmus** [dolthub/dolt#6776]
```
dolt sql -q "create database test"
dolt sql -q "use test"
dolt sql -q "create table test.tab (id bigint unsigned not null auto_increment primary key, col varchar(255))"
dolt sql -q "insert into test.tab(col) values ('one')"
```

Using the {MySQL ODBC 8.0 Unicode Driver} to access my 'dolt sql-server' and querying the attributes of the column returned after a 'SELECT LAST_INSERT_ID()' for an AUTO_INCREMENT id key using SQLColAttribute with FieldIdentifier=SQL_DESC_UNSIGNED results in NumericAttributePtr == 0, i.e. FALSE. 

TRUE is expected. 

https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlcolattribute-function

**Comment by timsehn** [comment]
This is fixed in the latest release that went out last night v1.18.1.
