### ISSUE TITLE
Read-only databases allow creating new branches using `DOLT_CHECKOUT()`

### ISSUE THREAD

**Issue by uSlashVlad** [dolthub/dolt#6785]
I believe this issue is connected to #6730 

Now, running dolt sql-server in read-only mode can create new branches using `DOLT_CHECKOUT`, but you can not with `DOLT_BRANCH`. Also you can not delete them.

You can create branch on specific commit using procedure like this:

```sql
CALL DOLT_CHECKOUT('tl9jqbh7t8p9jpten3n5oa63t5i06n4h', '-b', 'branch123');
```

With result:

```
status|message                       |
------+------------------------------+
     0|Switched to branch 'branch123'|
```

But still can not do this:

```sql
CALL DOLT_BRANCH('branch123', 'tl9jqbh7t8p9jpten3n5oa63t5i06n4h');
```

Because `SQL Error [1105] [HY000]: database server is set to read only mode`

I think checking out with `-b` argument should not be allowed in read-only mode, since it can create new branches, so it changes repository.
But then the problem arises. Dolt can not have detached head, so to checkout on some commit without branch or tag name, you have to create branch on it with `-b` argument.
So, that way you can not checkout on commits without branch or tag aligned to it in read-only mode.

---

Checked on dolt version 1.18.1, on Linux

**Comment by uSlashVlad** [comment]
@fulghum, I am not relying on this behavior for now, and it doesn't disrupt anything in my project.
Such behavior even bad for me too.

I think that I will work around lack of detached head with server running in read-write mode by creating branch and then deleting it.

Anyway, are there any plans to create true detached-head mode?
There is nothing about it in roadmap. It isn't technically possible?

**Comment by fulghum** [comment]
Thanks for the extra context @uSlashVlad. Glad to hear closing up this gap won't impact you. 

Support for a detached head mode is definitely possible ([detached-head mode tracking issue](https://github.com/dolthub/dolt/issues/2464)), there are just some usability challenges to work through, and since there is often an easy workaround (i.e. create a branch), we haven't prioritized it yet. That said, we do hear this request from customers from time to time, so I think we will eventually add support for it.

**Comment by fulghum** [comment]
Sorry it took me a couple days to get to this one – I had to wrap up a couple other items in my queue. 

Thanks for reporting this bug. I just opened PR https://github.com/dolthub/dolt/pull/6810 that closes this gap. I'll resolve this issue once we get the fix merged in and ready to go out in a release. 

Please let us know if you find any other issues or sharp edges. 🙏 If you have any feedback or feature requests for Dolt, we always love hearing those, too!

**Comment by fulghum** [comment]
Thanks again for taking the time to report this so we could fix it! I've merged the fix in to main and it's ready to go out in the next release, likely on Monday or Tuesday of next week. 

Let us know if we can do anything else to help!
