### ISSUE TITLE
Laravel example app requires environment variable Dolt does not support

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6797]
Repro:

1. Install composer. It was enough for me to `brew install composer` and `brew upgrade`.
2. Run:
```
$ composer create-project laravel/laravel example-app
```
3. Start a `dolt-sql-server --loglevel=debug`
4. Create a database called laravel
```
mysql -u root -e "create database laravel`
```
5. Run:
```
php artisan migrate
```
6. Notice in the Dolt logs
```
unable to prepare query: value NO_AUTO_CREATE_USER was not found in the set {query=set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'}
```

We should at least parse and ignore those environment variable.

**Comment by fulghum** [comment]
It looks like `NO_AUTO_CREATE_USER` may have been deprecated in MySQL 5.7 and doesn't exist in anymore in 8.x:
https://stackoverflow.com/questions/71110454/no-auto-create-user-in-mysql-8-0

**Comment by sbrow** [comment]
Turns out this is because Laravel reads the version number from dolt as `5.7.9`, and so talks to it like it's a MySQL 5.7 server instead of a MySQL 8.0 server.

**Comment by timsehn** [comment]
Combining into #6799.
