### ISSUE TITLE
Support `JSON_VALID()`

### ISSUE THREAD

**Issue by sbrow** [dolthub/dolt#6808]
It would appear that the json functions documented [here](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html) are not implemented in dolt.

I tried to import a `mysqldump` file that contained references to `JSON_VALID`, and it didn't work.

Thanks for the *awesome* software!

**Comment by timsehn** [comment]
`JSON_VALID()` only? Or others?

https://docs.dolthub.com/sql-reference/sql-support/expressions-functions-operators

<img width="255" alt="image" src="https://github.com/dolthub/dolt/assets/5376236/fd083970-5e03-43de-8ec5-7eebe418f5ae">

Tell us which ones you want and we'll do em. They take about 4 hours apiece on average.

**Comment by sbrow** [comment]
Yes, `JSON_VALID` is the only one I'm currently using. But I am using an ORM, so I have no idea what others might crop up.

Not used to the precision and speed you guys have when handling issue requests :heart:

**Comment by timsehn** [comment]
I renamed this one to scope it down. If you need others just ask in a new issue.

**Comment by jennifersp** [comment]
Thank you, @sbrow for this issue request. The support for `JSON_VALID` function is now merged into Dolt. It will be out in the next Dolt release.
