### ISSUE TITLE
`$ dolt push` generates lots of `Uploading...` text in cron

### ISSUE THREAD

**Issue by post-no-preference** [dolthub/dolt#6828]
When I use the command `$ dolt push`, I see lots of the following

```
Uploading...^H^H^H^H^H^H^H^H^H^H^H^H^H^H-
```

I would like to be able to suppress this sort of output as it clutters cron.

**Comment by macneale4** [comment]
`fetch` and `pull` have the same behavior. Adding a "--silent" option to all of them seems reasonable.
