### ISSUE TITLE
SQL_CALC_FOUND_ROWS doesn't work?

### ISSUE THREAD

**Issue by sbrow** [dolthub/dolt#6829]
Ran into an issue with the following query using WordPress and GravityForms:

```sql
SELECT SQL_CALC_FOUND_ROWS DISTINCT `t1`.`id` FROM `wp_gf_entry` AS `t1` WHERE (`t1`.`form_id` IN (112) AND `t1`.`status` = 'active') ORDER BY `t1`.`id` DESC LIMIT 20;
```

Works okay in mysql, but not in dolt version 1.19.0.

Thanks!

**Comment by timsehn** [comment]
So `FOUND_ROWS()` and `SQL_CALC_FOUND_ROWS()` are deprecated in MySQL 8.0.17:

https://dev.mysql.com/doc/refman/8.0/en/information-functions.html

Because of this we've chosen to not implement them. Can you use these recommended alternatives?

Old way:
```
SELECT SQL_CALC_FOUND_ROWS * FROM tbl_name WHERE id > 100 LIMIT 10;
SELECT FOUND_ROWS();
```
Recommended way:
```
SELECT * FROM tbl_name WHERE id > 100 LIMIT 10;
SELECT COUNT(*) FROM tbl_name WHERE id > 100;
```

**Comment by timsehn** [comment]
If a WordPress plug in uses the deprecated functionality we may have to support these two functions.

**Comment by sbrow** [comment]
> Because of this we've chosen to not implement them. Can you use these recommended alternatives?

Unfortunately, I cannot. The query comes from a third-party plugin that I have no control over. It's possible that more recent versions of the plugin have fixed it, but I'm not sure. Not really the end of the world, but an issue I have run into in the wild. Gravity Forms is widely used.

**Comment by timsehn** [comment]
OK. We'll get these implemented.

**Comment by sbrow** [comment]
You guys are the best :heart:

**Comment by timsehn** [comment]
Related to #6406

**Comment by timsehn** [comment]
@JCOR11599 Tried to invoke the international law of "not it" and failed so he is gonna fix this one.

<img width="659" alt="image" src="https://github.com/dolthub/dolt/assets/5376236/cc1c1749-b6c8-4735-a57e-fb9c36dadcc1">

Might be a bit harder than our 24-hour desired turnaround though.

**Comment by JCOR11599** [comment]
Hey @sbrow, it turns out there were two separate, but related bugs here.
One was a syntax error: we supported `select distinct sql_calc_found_rows ...`, but not `select sql_calc_found_rows distinct ...`.
Another was that large `LIMIT` clauses were causing an off by one error.

They're both fixed now; we are in the process of bumping and merging, so expect a relase later today!

**Comment by sbrow** [comment]
Works great :)
