### ISSUE TITLE
Can't reverse tables to model in navicat. Problem with name resolution on an `order by` clause on the triggers table.

### ISSUE THREAD

**Issue by happydpc** [dolthub/dolt#6854]
**Version: 1.21.0**
the problem is **ambiguous column name "event_object_table"**
Log: 
```
error running query {connectTime=2023-10-20T17:49:38+08:00, connectionDb=AvevaMarineSample, error=ambiguous column name "event_object_table", it's present in all these tables: [triggers triggers]}
```

![1697815069256](https://github.com/dolthub/dolt/assets/771776/aa9b4780-b30d-4556-9d07-6681b668e774)

**Comment by timsehn** [comment]
Can you give us a bit more information on what you were trying to do? I'm unfamiliar with Navicat so I don't know what "reverse tables" means.

**Comment by happydpc** [comment]
It use the schema info to generate the tables' relation diagrams. like this:
![1697822558382](https://github.com/dolthub/dolt/assets/771776/496fc749-36e1-4023-99ea-4de23e7a86b9)

**Comment by timsehn** [comment]
Trying now.

**Comment by timsehn** [comment]
So I see you have Sakila loaded. I loaded a test database with two tables:

<img width="1241" alt="image" src="https://github.com/dolthub/dolt/assets/5376236/ec415a4b-aaa0-4480-9ef8-b9850b95fed9">

What do I click to reproduce the error? I am clicking around and everything seems to be working otherwise.

**Comment by timsehn** [comment]
I was able to create an ER Diagram for my simple database:

<img width="1689" alt="image" src="https://github.com/dolthub/dolt/assets/5376236/9a021b0e-6a71-4739-bae0-c0fa6cecf892">

The best way to help us figure out what is going on is to run the dolt sql-server with `loglevel=debug` and find teh query and error Navicat is running/getting. Also, a `dolt schema show` of your database would help.

**Comment by happydpc** [comment]
Right-click a table,  find the "reverse tables to model"  menu, click it , then it should report the error.

**Comment by timsehn** [comment]
Yay! that worked . Thanks.

**Comment by happydpc** [comment]
Ok, I will have a try. Thanks.

**Comment by timsehn** [comment]
```
2023-10-20T10:57:29-07:00 DEBUG [conn 5] Starting query {connectTime=2023-10-20T10:43:57-07:00, connectionDb=autoincrement_vs_uuid, query=SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, DEFINER, ACTION_STATEMENT, ACTION_TIMING FROM information_schema.triggers WHERE event_object_schema = BINARY 'autoincrement_vs_uuid' AND event_object_table = BINARY 't_autoincrement' ORDER BY event_object_table}
2023-10-20T10:57:29-07:00 WARN [conn 5] error running query {connectTime=2023-10-20T10:43:57-07:00, connectionDb=autoincrement_vs_uuid, error=ambiguous column name "event_object_table", it's present in all these tables: [triggers triggers], query=SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, DEFINER, ACTION_STATEMENT, ACTION_TIMING FROM information_schema.triggers WHERE event_object_schema = BINARY 'autoincrement_vs_uuid' AND event_object_table = BINARY 't_autoincrement' ORDER BY event_object_table}
```

**Comment by timsehn** [comment]
My bet is that Dolt does not support that binary syntax. Testing.

**Comment by happydpc** [comment]
Is this result right? repo_state.json not exist.

![88bad3686a008cfcbe582dff95956e3](https://github.com/dolthub/dolt/assets/771776/00b34f99-18c3-4c00-aff0-8094d3886667)

**Comment by timsehn** [comment]
No. You need to be in the directory where your Dolt database is. I don't need it now. 

This is a bug in our analyzer. Something about the order by clause on that query is messing Dolt up.

For @max-hoffman:

```
MySQL [autoincrement_vs_uuid]> SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, DEFINER, ACTION_STATEMENT, ACTION_TIMING FROM information_schema.triggers WHERE event_object_schema = 'autoincrement_vs_uuid' AND event_object_table = 't_autoincrement' ORDER BY event_object_table;
ERROR 1105 (HY000): ambiguous column name "event_object_table", it's present in all these tables: [triggers triggers]
MySQL [autoincrement_vs_uuid]> SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, DEFINER, ACTION_STATEMENT, ACTION_TIMING FROM information_schema.triggers WHERE event_object_schema = 'autoincrement_vs_uuid' AND event_object_table = 't_autoincrement';
Empty set (0.001 sec)
```

**Comment by timsehn** [comment]
This boils down to Dolt not being able to handle this pattern:
```
SELECT EVENT_OBJECT_TABLE, EVENT_OBJECT_TABLE, ... ORDER BY EVENT_OBJECT_TABLE
```
Select the same column multiple times and then try to order by it. We are fixing.

**Comment by timsehn** [comment]
This is the fix. https://github.com/dolthub/go-mysql-server/pull/2091

**Comment by bpf120** [comment]
@happydpc , we'd love to learn about what you are using Dolt for too. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share. thanks!

**Comment by max-hoffman** [comment]
[dolt version 1.21.1](https://github.com/dolthub/dolt/releases/tag/v1.21.1) is released and should fix this issue. Let us know if you find related issues that still give you trouble.
