### ISSUE TITLE
FULLTEXT index creation fails with column `C1` has an incorrect definition error

### ISSUE THREAD

**Issue by medmond** [dolthub/dolt#6941]
I've cloned this database: [transparency-in-pricing](https://www.dolthub.com/repositories/dolthub/transparency-in-pricing/data/main/rate)

When I attempt to create a fulltext index on the `rate` table, I get the following error:

```
transparency_in_pricing> alter table rate add fulltext index rate(description);
Full-Text table `dolt_rate_rate_0_fts_position` column `C1` has an incorrect definition
```

Is this expected behavior? Thanks.

**Comment by timsehn** [comment]
Thanks for the issue. @Hydrocharged is our Fulltext expert. I'll let him comment.

**Comment by Hydrocharged** [comment]
@medmond What version of Dolt are you using? We've recently made some Full-Text changes, so that will make the investigation much easier.

**Comment by medmond** [comment]
I had been running 1.22 (installed yesterday) but was able to upgrade to 1.24.1 just now.

**Comment by Hydrocharged** [comment]
I've identified and submitted a PR to fix the root issue. We were mistreating default values within the Full-Text context. The linked PR contains more technical details if interested.
