### ISSUE TITLE
virtual column merges don't work

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#6945]
We just launched initial support for virtual columns, but merges on these columns fail in some cases.

**Comment by timsehn** [comment]
@zachmu is working on this now and should be fixed shortly.

**Comment by zachmu** [comment]
Merging virtual columns now works in most cases, but there remain merges that won't succeed in the case of schema changes on one side of the merge. In all cases, applying ALTER table statements to both sides of the merge to make their schemas match before applying the merge is a viable workaround.

Closing this in favor of more targeted issues as they may arise.
