### ISSUE TITLE
Cannot `DROP` column if it's named `geometry`

### ISSUE THREAD

**Issue by bstadlbauer** [dolthub/dolt#6950]
The following snippet:

```mysql
CREATE TABLE a (
    b INT,
    geometry INT
);

ALTER TABLE a
    DROP COLUMN geometry;
```

Will result in 
```
[2023-11-05 18:28:50] [HY000][1105] syntax error at position 78 near 'geometry'
```

This was testing in `dolt version 1.21.0`. I've checked this against mysql 8.2.0 and this worked as expected

**Comment by timsehn** [comment]
Thanks for the report. @JCOR11599 will fix this asap. Good bug.

**Comment by JCOR11599** [comment]
Hey @bstadlbauer, fix for this has been merged and is making its way to main.
Expect a release later today, once all the bumps have gone through.
