### ISSUE TITLE
RepoState.Remotes map not safe for concurrent use

### ISSUE THREAD

**Issue by nustiueudinastea** [dolthub/dolt#6965]
Dear Dolt folks,

While using Dolt in embedded mode, the unsafe RepoState.Remotes  map (https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/env/repo_state.go#L71) leads to failure when stress testing and adding/removing/reading remotes happens fast enough.

```
stdout 'dsw4':  /opt/homebrew/Cellar/go/1.21.3/libexec/src/encoding/json/encode.go:162 +0x94                                                                                          
stdout 'dsw4': encoding/json.MarshalIndent({0x105ae31c0?, 0x140022984b0?}, {0x0, 0x0}, {0x10550d000, 0x2})                              
stdout 'dsw4':  /opt/homebrew/Cellar/go/1.21.3/libexec/src/encoding/json/encode.go:175 +0x34                                                  
stdout 'dsw4': github.com/dolthub/dolt/go/libraries/doltcore/env.RepoState.Save({{{0x105c12db0, 0x14001189f70}}, 0x1400119f560, 0x1400119f590, 0x1400119f530, {0x0, 0x0}, {0x0, 0x0}, 0x0}, ...)
stdout 'dsw4':  /Users/al3x/code/protos/code/dolt/go/libraries/doltcore/env/repo_state.go:197 +0x7c                                           
stdout 'dsw4': github.com/dolthub/dolt/go/libraries/doltcore/env.(*DoltEnv).RemoveRemote(0x140011ba360, {0x105c1a598, 0x108b11220}, {0x14001e81880?, 0x14001eb8570?})
stdout 'dsw4':  /Users/al3x/code/protos/code/dolt/go/libraries/doltcore/env/environment.go:965 +0x3e4      
```

I fixed this in my own fork by switching to sync.Map, and that fixes it. In the end I don't like this solution because it litters the code with type assertions so tomorrow I will attempt a fix with a generic map protected by a mutex, and will follow with a PR.

**Comment by timsehn** [comment]
@zachmu will review your PR when it comes in. Thanks for the issue and the (upcoming) contribution.

**Comment by nustiueudinastea** [comment]
Hey @zachmu I opened a PR which fixes this issue. Let me know if you're ok with the approach. If you are, I will create tests with the new concurrent map and then we can discuss if backups and branches also need to be converted.
