### ISSUE TITLE
Upload to dolthub won't work for new `GEOMETRY` columns

### ISSUE THREAD

**Issue by bstadlbauer** [dolthub/dolt#6969]
After #6927 was fixed, `GEOMETRY` works as expected locally and does not error any longer for large geometries. However, when pushing a database to remote, the geometry does not show up and and the following error is shown in the UI:

```
query error: panic in ExchangeIterPartitionRows: assertion failed: empty chunk returned from ChunkStore
```

Steps to reproduce:
```sql
-- Contents of test.sql
CREATE TABLE a(
    b GEOMETRY
);

INSERT INTO a (b)
VALUES (ST_GeomFromText('Point(1 1)'));
```

```shell
dolt init
dolt sql -f test.sql
dolt add .
dolt commit -m "Add some data"
dolt remote add origin bstadlbauer/mre-geometry-upload
dolt push --set-upstream origin main
```

You can find the test-database [here](https://www.dolthub.com/repositories/bstadlbauer/mre-geometry-upload/data/main). cc @JCOR11599 as this might be related to your change.

<img width="1438" alt="image" src="https://github.com/dolthub/dolt/assets/11799671/dee36c7e-77ef-42ed-bcfa-2e3741f5c493">

**Comment by bstadlbauer** [comment]
I've also noticed that the push was incredibly fast, so I'd suspect that the data has never been uploaded

**Comment by timsehn** [comment]
I think this is because we have to update the version on DoltHub. @tbantle22 @coffeegoddd and @liuliu-dev will take a look and tell @JCOR11599 what he missed.

**Comment by timsehn** [comment]
I repro-ed like this. 

Locally
```sh
$ dolt init --fun
Successfully initialized dolt data repository.
$ create table us_state_capitals (state varchar(50) primary key, city varchar(50), coord point);
zsh: no matches found: (state varchar(50) primary key, city varchar(50), coord point)
$ dolt sql -q "create table us_state_capitals (state varchar(50) primary key, city varchar(50), coord point);"
$ dolt sql -q "insert into us_state_capitals values ('alabama', 'montgomery', point(32.361667, -86.279167));"
Query OK, 1 row affected (0.00 sec)
$ dolt commit -Am "Geoometry data"
commit ie6c5em0r721l2qjelbjun6a433i2ni1 (HEAD -> main) 
Author: timsehn <tim@dolthub.com>
Date:  Wed Nov 08 09:06:08 -0800 2023

        Geoometry data

$ dolt remote add origin timsehn/test-geometry
$ dolt push origin main
- Uploading...
To https://doltremoteapi.dolthub.com/timsehn/test-geometry
 * [new branch]          main -> main
$ dolt sql -q "select * from us_state_capitals"
+---------+------------+----------------+
| state   | city       | coord          |
+---------+------------+----------------+
| alabama | montgomery | n??K.@@??C?ݑU? |
+---------+------------+----------------+
```

On DoltHub:

https://www.dolthub.com/repositories/timsehn/test-geometry

**Comment by JCOR11599** [comment]
Hey @bstadlbauer 

Thanks for reporting this issue! The fix has been merged to dolt main, so expect a release later today.
Additionally, dolthub will be updated soon to fix this issue.

Unfortunately, I believe that you will have to recreate your local dolt repo (with the latest version of dolt).
