### ISSUE TITLE
Unexpected Results when Using '%' operator

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7006]
Considering the test case below:

```sql
CREATE TABLE t0(c1 INT);
INSERT INTO t0(c1) VALUES (1);

SELECT * FROM t0;
SELECT (c1 NOT IN (1%true)) IS NULL FROM t0;  -- 1
SELECT * FROM t0 WHERE (c1 NOT IN (1%true)) IS NULL; 
-- Expected: 1
-- Actual: empty
```

The third `SELECT` returns an empty result, which is surprising: If the result of second query is 1 (`TRUE`), the value of the `NOT IN` expression should be true, and thus the third query should return the row in `t0`.

This test case works well in MySQL 8.0.33, however not works in dolt 1.26.1

Besides, I also find a discrepancy between dolt and MySQL for this query:

```sql
SELECT 1 % true;
-- MySQL: 0
-- dolt: NULL
```

I originally find this when using the latest docker image dolt-sql-server 1.26.1

**Comment by timsehn** [comment]
Thanks for the issue. We will look at this today. I'm pretty sure because of the IN expression this is analyzer related so @max-hoffman or @JCOR11599 will dig in.

**Comment by max-hoffman** [comment]
It looks like bad type conversion is at least one issue here, we convert the true to a decimal type of zero and error for division by zero. Will get a fix for that shortly

**Comment by max-hoffman** [comment]
This fixes the bug in my testing https://github.com/dolthub/go-mysql-server/pull/2147. The original query you posted `SELECT * FROM t0 WHERE (c1 NOT IN (1%true)) IS NULL; ` returns an empty result set when I test in MySQL and Dolt; `(c1 NOT IN (1%true))` => `c1 not in {0}` => `1 not in {0}` will be true, and so `(c1 NOT IN (1%true)) IS NULL` will be false. Let me know if there are other bugs here I am missing, our type coercion is still patchy in some places.

**Comment by bpf120** [comment]
@suyZhong , Thanks for filing. We'd love to learn about how you are using Dolt too. If you want to share, [email me](brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe).
