### ISSUE TITLE
`dolt clone` can include extraneous remote refs

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#7043]
A remote database can include remote refs (e.g. `refs/remotes/origin/branch`) for a variety of reasons, including being a backup. During `dolt clone`, we pull all these refs, then rewrite them to be relative to the remote we just pulled from. If there are any remote refs that don't refer to the same remote we just pulled from, they're just ignored. This means that it's possible that future operations on one of these remote refs will encounter ambiguity and error out.

For example, if the remote database has two refs that like so:

```
refs/remotes/origin/branch1
refs/remotes/backup/branch1
```

Then if I run `dolt checkout branch1` I'll get an error:

```
'branch1' matched multiple (2) remote tracking branches.
```

The solution to this is that during a clone, we should discard any extra remote refs during the ref rewriting process, such that we have only a single set of remote refs which match the name of the remote that we cloned from.

**Comment by ricardoreiter** [comment]
@zachmu any progress on this one?
Is there a way to work around it? Can we remove one of the remote refs?

**Comment by macneale4** [comment]
There isn't a mechanism to alter the root value manually. I'll make clone do the right thing, then we'll determine if additional tooling would be helpful.

**Comment by reltuk** [comment]
@ricardoreiter You can currently work around this by adding a fake `remote` which matches the remote branches you want to delete and the deleting it. So, for example, if I had:

```
aaronson@Aarons-MacBook-Pro restored % dolt branch -a                         
* main                                          	
  remotes/origin/main
  remotes/upstream/main
```

after a `clone` or a `backup restore`, but I had no corresponding `upstream` remote, I can do:

```
$ dolt remote add upstream https://localhost
$ dolt remote rm upstream
```

And then all the `remotes/upstream/...` tracking branches will be gone.

Of course, we hope to fix the `clone` behavior soon :).

**Comment by ricardoreiter** [comment]
Thanks @reltuk 
that worked!
