### ISSUE TITLE
Potential Issue Using ROUND

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7073]
Consider the following test cases, the second query executes slowly. (I'm using MySQL client)

```sql
mysql> SELECT ROUND(3, -9999999);
+--------------------+
| ROUND(3, -9999999) |
+--------------------+
|                  0 |
+--------------------+
1 row in set (0.00 sec)

mysql> SELECT ROUND(3%5, -9999999); -- increasing the second argument would lead to server hang
+----------------------+
| ROUND(3%5, -9999999) |
+----------------------+
|                    0 |
+----------------------+
1 row in set (3.19 sec)
```

I understand that the negative value for the second argument of ROUND is somewhat illegal. However, when it goes to `-1e8`, the query needs more than 1 minute to execute. MySQL takes less than 0.01 second.

I originally find this in the source code version 804f1c1d8f6. It could also be reproduced in 1.26.1.

**Comment by timsehn** [comment]
This is very interesting. Keep the bugs coming. They are awesome.
