### ISSUE TITLE
Dolt Checkout: -B Support

### ISSUE THREAD

**Issue by IntrepidHOvadia** [dolthub/dolt#7116]
Like `git checkout -B`, I would like a way for using the command line or stored procedure (`DOLT_CHECKOUT`) to provide the -B argument, which will create the branch if it doesn't exist, and then checkout or, if it does exist, it skips creation and just does a checkout like normal.

see: https://git-scm.com/docs/git-checkout

**Comment by macneale4** [comment]
Feature released: https://github.com/dolthub/dolt/releases/tag/v1.29.2
