### ISSUE TITLE
support `current_timestamp` synonyms

### ISSUE THREAD

**Issue by jycor** [dolthub/dolt#7129]
In MySQL, these are all the same function:
 - `CURRENT_TIMESTAMP`
 - `CURRENT_TIMESTAMP()`
 - `NOW()`
 - `LOCALTIME`
 - `LOCALTIME()`
 - `LOCALTIMESTAMP`
 - `LOCALTIMESTAMP()`

Dolt lacks support for these
```sql
dolt> select localtime;
function: 'localtime' not found
dolt> select localtime();
function: 'localtime' not found
dolt> select localtimestamp;
function: 'localtimestamp' not found
dolt> select localtimestamp();
function: 'localtimestamp' not found
```
Note: We also have slightly different implementations of `NOW()` and `CURRENT_TIMESTAMP()`

As a result, we lack support for using these functions as column defaults and as on update expressions.
```sql
dolt> create table t (ts timestamp default localtime);
function: 'localtime' not found
```

Note: We just support `on update localtime`, but treat it like a no-op
```sql
dolt> create table t (ts timestamp on update localtime);
dolt> show create table t;
+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                               |
|       |   `ts` timestamp                                                 |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+-------+------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Relevant MySQL Docs: 
 - https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html
 - https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

Related Issues: 
 - https://github.com/dolthub/dolt/issues/6030
 - https://github.com/dolthub/dolt/issues/6058

**Comment by JCOR11599** [comment]
Additionally, we should support parsing these synonyms in parenthesized on update expressions
```sql
create table t (ts timestamp on update (current_timestamp));
```
