### ISSUE TITLE
How to connect a dolt sql-server from a remote server

### ISSUE THREAD

**Issue by Mickychen00** [dolthub/dolt#7164]
Hello. I use the manual https://docs.dolthub.com/introduction/installation/application-server to build a sql-server in my remote server. In this remote server, I can use this server's mysql-client with command
**mysql -u root -p password -S "tmp/mysql.sock" -P 3306**
to connect the server.

However, I cannot use mysql-client of my laptop with command
**mysql -u root -p password -P 3306 --host my_remote_ip**
to connect it.

The message is "mysql: [Warning] Using a password on the command line interface can be insecure.ERROR 2003 (HY000): Can't connect to MySQL server on 'my_remote_up:3306' (61)

I am sure that I have open the port 3306 to public.
I don't know where is wrong?

After that, I have tested the connection with a origin MySQL Database. My laptop can connect it correctly. But dolt is not.

**Comment by timsehn** [comment]
So, this likely has something to do with your environment. Dolt can certainly be used over networks.

There is nothing in your description that suggests anything done incorrectly. The easiest way for us to help you debug would be for you to come by our Discord and we can help you figure out what is going on.

https://discord.gg/gqr7K4VNKe

**Comment by Mickychen00** [comment]
Thanks for you help. I realized that the server should set the --host to 0.0.0.0 to allow any IP ping.
mysql -u root -p password -S "tmp/mysql.sock" -P 3306 --host 0.0.0.0,

**Comment by timsehn** [comment]
Action item coming out of this is to error when we parse values we don't understand in `dolt_config.json`. Making a new issue
