### ISSUE TITLE
dolt can be deleted oddly

### ISSUE THREAD

**Issue by minesunny** [dolthub/dolt#7221]
I install dolt on windows platform, after a few mins, it was deleted, and not found in recycle, and windows defender doesn't have any virus history

**Comment by minesunny** [comment]
It was deleted by lenovo defender,and I uninstall lenovo defender

**Comment by bpf120** [comment]
@minesunny Thanks for using Dolt! Keep us posted on how it goes and we love learning about use cases. Feel free to join our [Discord](https://discord.gg/gqr7K4VNKe) or send me an [email](mailto:brianf@discord.com) if you want to share.
