### ISSUE TITLE
Unexpected Results when Using ROUND()

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7222]
Consider the test case below. The result of the query is different from MySQL. 

```sql
SELECT ROUND('');
-- MySQL: 0
-- Dolt: Empty set
```

Besides, it would cause below query return an unexpected result.

```sql
SELECT 1 WHERE (ROUND('')) UNION ALL SELECT 1 WHERE (NOT (ROUND(''))) UNION ALL SELECT 1 WHERE ((ROUND('')) IS NULL);
-- Expected: 1
-- Actual: Empty set
```

I originally find this by building dolt from source code https://github.com/dolthub/dolt/commit/3c8cc088c2f352cb3b346b4bd30dda7decf002e5

**Comment by max-hoffman** [comment]
Thanks! Tagging @jycor for visibility, might not get to this one until next week because of the New Year.
