### ISSUE TITLE
Unexpected Result when Querying with `CONCAT`

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7261]
Considering the test case below:

```sql
CREATE TABLE t0(c0 INT, PRIMARY KEY(c0));
INSERT INTO t0 (c0) VALUES (0);

SELECT c0 FROM t0; -- 0
SELECT c0 > (CONCAT(-0.5)) FROM t0; -- 1
SELECT c0 FROM t0 WHERE (c0>(CONCAT(-0.5)));
-- Expected: 0
-- Actual: empty
```

The third `SELECT` returns an empty result, which is surprising: If the result of second query is 1 (`TRUE`), the value of the `CONCAT` should be less than `c0`, and thus the third query should return the row in `t0`.

These test cases works well in MySQL, however not in dolt.

I originally find this by building dolt from source version 2d0a2edbc208e699fb913c34c0183. It could also be reproduced in 1.29.7

**Comment by max-hoffman** [comment]
Thanks for the report @suyZhong! @jycor this one is kind of interesting, I thought we standardized the `ConvertToBool` logic but we must have missed something.
