### ISSUE TITLE
Please implement SYSDATE for Mediawiki install 

### ISSUE THREAD

**Issue by genieck** [dolthub/dolt#7270]
It's the only blocker, changing it to CURRENT_TS resulted in a working install.

**Comment by timsehn** [comment]
We'll have this out today.

**Comment by fulghum** [comment]
Awesome that you got Mediawiki working with Dolt! Thanks for taking the time to let us know about the `sysdate` gap. 

This should be a quick function for us to add. I've got it started already and will keep you updated as we review and release it for you.

**Comment by fulghum** [comment]
@genieck – Thanks for taking the time to report this! 🙏  We've released [Dolt version 1.31.0](https://github.com/dolthub/dolt/releases/tag/v1.31.0), which supports the MySQL `SYSDATE()` function.

Please let us know how the rest of your testing goes with Mediawiki. If you hit _any_ other issues, we want to know so we can fix them. Hearing more about how you're using Mediawiki with Dolt would be really cool, too!
