### ISSUE TITLE
Implement SUBDATE

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#7277]
Potential customer request:

https://www.reddit.com/r/PHP/comments/191yakg/comment/kh103cz/?context=3

https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_subdate

**Comment by fulghum** [comment]
The `subdate` function is now supported and was released last night in [Dolt 1.31.2](https://github.com/dolthub/dolt/releases/tag/v1.31.2).
