### ISSUE TITLE
Subquery in an INSERT statement return NULL

### ISSUE THREAD

**Issue by Axel-1** [dolthub/dolt#7322]
SELECT subquery in an INSERT statement doesn't return the expected value.
Here is the SQL script to reproduce the issue : 

```sql
create table role
(
    role_id int auto_increment primary key,
    code varchar(50) not null
);

create table app_user
(
    user_id int auto_increment primary key,
    name varchar(50) null,
    user_role_id int null,
    constraint app_user_role_role_id_fk foreign key (user_role_id) references role (role_id)
);

INSERT INTO test.role (role_id, code) VALUES (1, 'admin');
INSERT INTO test.role (role_id, code) VALUES (2, 'standard');
```

INSERT statement with subquery : 
```sql
INSERT INTO app_user(name, user_role_id) VALUES ('Test', (SELECT role_id FROM role WHERE code = 'admin'));
```

**Dolt :** 

![Capture d’écran du 2024-01-16 08-58-13](https://github.com/dolthub/dolt/assets/65816310/c11ca179-22c4-4fb3-9731-8e8c562aba0b)

**MySQL :** 

![Capture d’écran du 2024-01-16 09-01-45](https://github.com/dolthub/dolt/assets/65816310/0c970d46-9723-4ddd-93a0-aa07e08dfdc0)

Thanks !

**Comment by max-hoffman** [comment]
The immediate workaround will be to use a derived table rather than a VALUES statement:

```sql
INSERT INTO app_user(name, user_role_id) select * from (select 'Test', role_id FROM role WHERE code = 'admin') dt;
```

We currently expect VALUES statements to be scalar expressions. We would need to extend support for VALUES scalar subqueries for this to work.

**Comment by Axel-1** [comment]
Ok ! I will try that tomorrow and I will let you know if it works.

**Comment by max-hoffman** [comment]
I have a PR and test for the query you shared, and will release the fixes later today. If you find other differences between Dolt and MySQL running your library of inserts, please follow up and we will try to get them all working for you.

**Comment by Axel-1** [comment]
Thank you for your quick response! I confirm that my SQL scripts are working properly
