### ISSUE TITLE
Add "Alter User" and "Set Password" SQL Statements

### ISSUE THREAD

**Issue by Keimya** [dolthub/dolt#7348]
Hello,

I have built an instance of Dolt for my data team, and we are thrilled to begin using it in production and look forward to all the features we can leverage with it. 

Unfortunately, we are unable to move forward at this time because we cannot create multiple users and allow them to alter/assign/set private passwords for their user accounts using the standard Alter User or Set SQL Syntax. Because of our inability to secure database access by setting credentials in this way, we are not in compliance with our InfoSec standards to use Dolt in production at this time.

It would be great if these statements could be included in an upcoming release if possible.

Thanks for all your work!

**Comment by timsehn** [comment]
Thank you for the feedback. We will assign someone to this right away. Right now the workaround is to delete the user and create the user with the new password but we'll get the `ALTER USER` Syntax working.

**Comment by timsehn** [comment]
@fulghum is going to pick this up today and will get you an estimate for when he can have it complete asap.

**Comment by Keimya** [comment]
That's amazing thank you so much

**Comment by bpf120** [comment]
@Keimya Thanks for using Dolt and filing these issues. We'd love to learn more details about your use case. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.

**Comment by fulghum** [comment]
Hey @Keimya, glad to hear you and your team are excited to start using Dolt! We're happy to help you however we can. 

To enable users to change passwords, we can add support for the following syntax:
`ALTER USER user@host IDENTIFIED BY 'password';`

(MySQL also provides a `SET PASSWORD` statement, but the documentation mentions users should prefer `ALTER USER`, so I'll go ahead and start there, but if `SET PASSWORD` is needed for whatever reason, we're happy to add it, too.)

Adding this support should be very straightforward. I haven't scoped everything out yet, but I expect we can get this released by end of day tomorrow for you. I'll start digging in now and will update this issue later today with how the progress is going and if we've run into any complications.

**Comment by Keimya** [comment]
Hi Jason,

Alter User is perfect. Thank you so much for this update and for working on this. I greatly appreciate it!!

**Comment by fulghum** [comment]
We made good progress on this today – our parser now supports the `ALTER USER` syntax for changing a password, and I've got a first implementation of the sql-server code roughed out. I wrote some initial tests and so far, it looks like the code is working correctly. I still need to do some more testing and clean up tomorrow morning to make sure I didn't miss anything, then I'll get this out for review and release.

**Comment by fulghum** [comment]
The support for `ALTER USER` has been reviewed and merged in. 🎉  We're running a few changes through our CI pipeline now, and will release a new version of Dolt (version 1.32.0) in the next couple of hours that will include this change. 

Once you pick up version 1.32.0, you'll be able to change user passwords like this:
```sql
ALTER USER `user1`@`%` IDENTIFIED BY 'myNewPassword';
```

Following MySQL's privileges for this command, any user with access to the database is allowed to change their own password. To change another user's password, you must either have the `CREATE USER` privilege or you must have the `UPDATE` privilege on the `mysql` database/schema. 

Thank you for requesting this feature! 🙏 This was a great one to add. I'll leave this issue open a little while longer while we get the release out.

**Comment by Keimya** [comment]
Hi Jason,

This is perfect!! Thank you so much for adding this feature and for getting it out so quickly - truly amazing!

**Comment by fulghum** [comment]
Completely our pleasure! Let us know anything else we can do to help!

[Dolt 1.32.0](https://github.com/dolthub/dolt/releases/tag/v1.32.0) is out now, so I'll go ahead and resolve, but don't hesitate to let us know if you have any problems using this new feature or need anything else.
