### ISSUE TITLE
Schema and ColCollection

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/dolt#739]
In many places, we treat `*ColCollection` the same as a `Schema`. This used to be true, but as new features are added to the schema, this assumption is now false. This can lead to the loss any extra information that is encoded in the schema but not on the columns themselves, such as indexes. This assumption should be changed all throughout the codebase.

**Comment by zachmu** [comment]
Going to close this out as it's not a specific defect or suggestion for improvement. @Hydrocharged, if you have a way to make this more specific or actionable, please reopen.

Also if I told you to create this bug to track this problem I'm sorry.
