### ISSUE TITLE
`@@server_uuid` generated by `mysqlsh`. Dolt does not support that system variable.

### ISSUE THREAD

**Issue by wp4nuv** [dolthub/dolt#7431]
I know this is not documented, but I've been experimenting with restoring a MySQL backup generated with `mysqlsh` into dolt and received the following error:

```Util.loadDump: Unknown system variable '@@server_uuid' (MYSQLSH 1105)```

Is this related to configuration or something special related to how dolt works?

**Comment by timsehn** [comment]
We do support loading any `mysqldump`. I'm unfamiliar with `mysqlsh`.

In this case, we just don't support the `server_uuid` system variable. If you delete the line where it is in the dump file, it should work. 

In the meantime, we can make it work.

**Comment by timsehn** [comment]
Out of curiosity, what command did you run in `mysqlsh` to generate the backup? I would like to test this path because it may generate other syntax Dolt doesn't understand. Thanks.

**Comment by wp4nuv** [comment]
> Out of curiosity, what command did you run in `mysqlsh` to generate the backup? I would like to test this path because it may generate other syntax Dolt doesn't understand. Thanks.

It's something like this:
```util.dumpSchemas(["master_loans"], "C:/Users/gokha/Documents/dumps2", {consistent: true, compatibility: ["ignore_missing_pks", "strip_definers", "force_innodb"], threads: 16, showProgress: true})```
I'll try to find the file with that line. A `mysqlsh` backup is a mix of SQL structure, compressed data, index files, and JSON files. I suspect the JSON files direct how `mysqlsh` writes back the generated files.
Because it's compressed and multithreaded by default, `mysqlsh` has become our favorite way to make backups for other developers since moving to RDS.

**Comment by timsehn** [comment]
Cool. We'll get it on our list to extensively test it. Meanwhile, this PR has the fix for the missing system variable.

https://github.com/dolthub/go-mysql-server/pull/2302

if you want to build off that branch and test. We'll have it out in the released build latest tomorrow. I'm worried you'll hit other unsupported syntax so I want to turn it around quick for you.

**Comment by wp4nuv** [comment]
I have searched throughout the files and I can't find any references to @@server_uuid, so I'm not sure where it's coming from. In the meantime, I'll keep looking for the source.
