### ISSUE TITLE
Make phone home behavior opt-in

### ISSUE THREAD

**Issue by jonforums** [dolthub/dolt#7435]
Read your blogs, interesting idea, and finally got around to trying `dolt` only to be greeted by this sad message

``` powershell
PS $ dolt version
dolt version 1.32.3
Warning: you are on an old version of Dolt. The newest version is 1.32.4.
```

Really, the siren song of auto phone home features in the name of convenience remains that strong?

Didn't find mention of dolt's behavior in the README. Didn't find mention of dolt's behavior in the docs.

Didn't even find a way to opt-in/opt-out via an envar.

But did find the [phone home code](https://github.com/dolthub/dolt/blob/main/go/cmd/dolt/commands/version.go#L135).

Consider making any phone home behavior opt-in via an envar and prominently document it. While I dislike deno's opt-out rather than opt-in stance, at least they [documented the envar needed to disable phone home auto version checks](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#environment-variables).

**Comment by timsehn** [comment]
This feature is rather new. It was implemented in December.

https://github.com/dolthub/dolt/issues/3417

I agree there should be an env var to disable the behavior.

**Comment by timsehn** [comment]
You'll also notice this "phones home" to GitHub not "home" per se. We do not collect metrics off of it.

https://github.com/dolthub/dolt/blob/a62f902fffe85a15fa7eb5167a35762a8b3ce46b/go/cmd/dolt/commands/version.go#L188

We do collect usage metrics from each client which you can disable. @zachmu is most familiar with that code.

**Comment by zachmu** [comment]
Hi @jonforums,

We're updating the docs to mention how to disable any phoning home behavior. In the meantime, you can run this command to opt out of anonymous metrics collection:

```bash
dolt config --global --add metrics.disabled true
```

**Comment by timsehn** [comment]
After some internal discussion, we are going to do the following things:

1. Make an env var to disable version checks to GitHub and document it in the actual message it sends. Something like:
```
$ dolt version
dolt version 1.32.3
Warning: you are on an old version of Dolt. The newest version is 1.32.4.
Set DOLT_DISABLE_VERSION_CHECKS = 1 to disable this check.
```
We will send this once for each new version. of the client, not on every call to dolt version.

2. We will document the client metrics behavior in our FAQ (https://docs.dolthub.com/other/faq). Our README is quite long so I bet it has a better chance being found in the FAQ. I don't think it's the right thing for product adoption to lead with it in the README.

**Comment by timsehn** [comment]
These action items are complete.
