### ISSUE TITLE
Add support for "SELECT INTO" for files

### ISSUE THREAD

**Issue by tim-oh-thee** [dolthub/dolt#7453]
The documentation here: https://docs.dolthub.com/sql-reference/sql-support/supported-statements states that one cannot use a select into statement for a file. Could we get this added?

MySQL reference: https://dev.mysql.com/doc/refman/8.0/en/select-into.html

**Comment by jycor** [comment]
Hey @tim-oh-thee,

Support for this feature has been added to dolt. You should be able to `select ... into outfile ...` now. We didn't add collation/charset support in this pass, but we could if its something y'all require.

It should be available in the next release; either today or Monday.

**Comment by tim-oh-thee** [comment]
Awesome, thank you!
