### ISSUE TITLE
Use go.etcd.io/bbolt instead of github.com/boltdb/bolt

### ISSUE THREAD

**Issue by nikolaevn** [dolthub/dolt#7491]
Since github.com/boltdb/bolt is not maintained anymore.
See https://github.com/boltdb/bolt?tab=readme-ov-file#a-message-from-the-author for details.

**Comment by reltuk** [comment]
@nikolaevn Do you have an example of where you see `dolt` pulling in `github.com/boltdb/bolt`?

Dolt only uses `boltdb` in some microbenchmarking test code, but AFAICT it already uses `go.etcd.io/bbolt` and there are no references to `github.com/boltdb/bolt`.

Thanks!
