### ISSUE TITLE
Creation of a database with a name identical to a recently dropped-and-dolt_purge_dropped_database() database fails on Windows 

### ISSUE THREAD

**Issue by gitasmus** [dolthub/dolt#7492]
On Windows, the newest dolt release https://github.com/dolthub/dolt/releases/download/v1.34.0/dolt-windows-amd64.msi causes the problem described in the subject line of this issue.

```SQL
create database to_be_purged;
drop database to_be_purged;
call dolt_purge_dropped_databases();
create database to_be_purged;
```
returns the error
```
error reading from or writing to noms: cannot update manifest: database is read only
```
On Linux, there is no such problem for 1.34.0.

**Comment by gitasmus** [comment]
Addition: On Windows you get this error regardless of whether you have called `dolt_purge_dropped_databases()` before the `create database` command.

**Comment by fulghum** [comment]
Hi @gitasmus, thank you for taking the time to report this one to us. 🙏  We'll get someone on our team with a Windows laptop to dig into this one today and see what's going on.

**Comment by fulghum** [comment]
Okay, @jycor is going to try and repro this one today on Windows. We'll let you know what we find.

**Comment by jycor** [comment]
Hey @gitasmus, 

Thanks for reporting this issue!  It turns out we weren't clearing some cache correctly.
I was able to reproduce and fix the problem; a PR with the fix is currently out for review.
We'll try to get a release out ASAP, likely later today or tomorrow.

A workaround for now is to exit the shell right after dropping the database.

```shell
$ dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
tmp/main> create database test_db;
tmp/main> drop database test_db;
tmp/main> exit
Bye

$ dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
tmp/main> create database test_db;
tmp/main> exit
Bye
```
