### ISSUE TITLE
"Data length" (i.e., table size on disk) value in DBeaver appears to be wrong

### ISSUE THREAD

**Issue by StudioBreeze** [dolthub/dolt#7561]
1. Clone this database: https://www.dolthub.com/repositories/studio-breeze/coinslate-scrape
2. Run `dolt sql-server`
3. Connect with DBeaver using the MySQL connector
4. See that the `hash_algos` table size is reported as "1.2G" (1.2 GB or GiB). 

The actual table size is a couple of MB max. The total DB size on disk is only 1.2 MB. It's very weird that it's being reported as so large.

![image](https://github.com/dolthub/dolt/assets/161806762/3f8c9e02-3789-4f24-8756-9d7cc0072d10)

**Comment by timsehn** [comment]
This is a known issue.

https://github.com/dolthub/dolt/issues/6624

Closing as this is a dupe.
