### ISSUE TITLE
One more issue related to the Adobe Commerce ( Magento ) installation.

### ISSUE THREAD

**Issue by palamar** [dolthub/dolt#7601]
MySql allows define primary key as constraint, and Magento uses `CONSTRAINT PRIMARY KEY` to simplify code generation.
But Dolt not allow such thin, so such SQL would generate error.

```
CREATE TABLE test (
  pk INT,
  col1 VARCHAR(255),
  CONSTRAINT PRIMARY KEY (pk)
);
```
erro
`query error: Error parsing SQL: syntax error at position 73 near 'PRIMARY'.`

**Comment by jycor** [comment]
Hey @palamar, thanks for reporting this.
We'll get started on supporting this syntax for you!

**Comment by jycor** [comment]
Hey @palamar, the fix for this has been merged and is making its way through our pipeline.
Expect a release with the fix tomorrow!

**Comment by bpf120** [comment]
Hi @palamar , thanks again for the issues. We'd love to learn more about your Dolt use case too. Feel free to join our [Discord](https://discord.gg/gqr7K4VNKe) or send me an [email](mailto:brianf@dolthub.com) if you'd like to share.
