### ISSUE TITLE
Conditionally creating a table in a script produces index already exists error 

### ISSUE THREAD

**Issue by dlynam01** [dolthub/dolt#7602]
If you create a simple table using conditional expression 

```
CREATE TABLE IF NOT EXISTS `test` (
                                           `id` INT PRIMARY KEY AUTO_INCREMENT,
                                           `name` VARCHAR(255) UNIQUE
    );
```

Executing this code multiple times works as expected in Mysql (it only executes a single time)

In DoltDB an error is produced when this code is run for a second time

> ERROR 1105 (HY000): `name` already exists as an index for this table

**Comment by fulghum** [comment]
Good find @dlynam01! I was able to repro this behavior. 

Thanks for taking the time to open this one. We'll debug through this one today and we should be able to get a fix out quickly for you.

**Comment by jycor** [comment]
Hey @dlynam01, the fix for this has been merged to gms main, and is making its way to dolt main.
Expect a release with the fix tomorrow!

**Comment by bpf120** [comment]
@dlynam01 , we love to learn about your Dolt use case. Feel free to join our [Discord](https://discord.gg/gqr7K4VNKe) or [email me](mailto:brianf@dolthub.com) if you'd like to share.
