### ISSUE TITLE
Migrate `dolt gc` to SQL

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#7621]
`dolt gc` currently bypasses a running sql-server, and should instead use the `DOLT_GC()` stored procedure.

Difficulty: Low
Value: Medium

Overarching Ticket: https://github.com/dolthub/dolt/issues/3922

**Comment by reltuk** [comment]
I thought this went through SQL now?

**Comment by macneale4** [comment]
good catch @reltuk . This one has been migrated. Resolving.
