### ISSUE TITLE
Support for `traditional` and `consecutive` behavior for `innodb_autoinc_lock_mode`

### ISSUE THREAD

**Issue by arvidfm** [dolthub/dolt#7634]
For MySQL we're currently checking `innodb_autoinc_lock_mode` because our system relies on it being set to `traditional` (0) or `consecutive` (1) for bulk inserts to behave as expected, but it seems Dolt doesn't support it:

```
> SELECT @@GLOBAL.innodb_autoinc_lock_mode;
ERROR 1105 (HY000): Unknown system variable '@@global.innodb_autoinc_lock_mode'
```

I also couldn't find any documentation on how Dolt handles autoinc IDs by default in regards to locking and interleaving, besides the risk of conflicts across distinct clones (which is not an issue for our use case).

**Comment by jycor** [comment]
Based off my understanding of the [MySQL Docs](https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html#innodb-auto-increment-lock-modes), Dolt's current transaction model, and Dolt's auto_increment behavior, I think we currently do Interleaved, so `innodb_autoinc_lock_mode=2`.

I will get started on adding this variable, should take maybe a day or two.
I'll see how difficult it would be to support traditional locking.

**Comment by zachmu** [comment]
@arvidfm can you comment on whether having the `innodb_autoinc_lock_mode` report the correct value is sufficient, or if you are blocked on getting the other two modes to work the same as in MySQL?

**Comment by arvidfm** [comment]
@zachmu In our case we do specifically need to be able to set it to consecutive (or traditional) as we rely on it for bulk inserts; it allows us to correctly calculate the IDs of inserted items without having to either run another query or insert the items one by one using the method described e.g. [here](https://stackoverflow.com/a/16592867) (as MySQL unfortunately doesn't supporting a `RETURNING` clause, unlike e.g. MariaDB). And we do a *lot* of bulk inserts.

**Comment by zachmu** [comment]
Thanks for the confirmation. We'll get started on implementing the different modes.

**Comment by zachmu** [comment]
@nicktobey is going to start on this today, we should have this out soon.

**Comment by nicktobey** [comment]
@arvidfm: to clarify, do you require **both** `traditional` and `consecutive` lock modes, or do you just need *either* lock mode to be supported?

**Comment by arvidfm** [comment]
@nicktobey Either is fine as far as we're concerned. Probably `consecutive` would be preferable since it can avoid locking the table for the whole duration of the statement in some cases, as described in [the documentation](https://dev.mysql.com/doc/refman/8.3/en/innodb-auto-increment-handling.html), so it should scale better generally. The difference in semantics for "mixed-mode" inserts is not relevant to us.

**Comment by bpf120** [comment]
@arvidfm , it would be great to learn about your Dolt use case too. Feel free to join our [Discord](https://discord.gg/gqr7K4VNKe) or send me an [email](mailto:brianf@dolthub.com) if you'd like to share.

**Comment by arvidfm** [comment]
@nicktobey Wow, that's amazing, thank you so much! I'll definitely give it a spin when I can. Also, sorry I didn't manage to find the time to dig up my Discord account to share our use case, is that something you're still interested in?

**Comment by bpf120** [comment]
@arvidfm, we are still interested in your use case. :) You can email me at brianf@dolthub.com if that's easier than Discord.
