### ISSUE TITLE
Questions about Dolt

### ISSUE THREAD

**Issue by AngryRocket** [dolthub/dolt#7649]
1.In daily projects, if it is necessary to integrate Dolt, it is necessary to export and import the original database data into Dolt, which may not be very convenient
﻿
2.What is the implementation principle of Dolt? Did you encapsulate or modify the source code of MySQL at the MySQL level
﻿
3. After installing Dolt, if there is a MySQL instance in the service, can we remove the current instance and replace it with another MySQL instance during installation?

**Comment by jycor** [comment]
1. Dolt is capable of reading MySQL dumps (as well as some other formats), so it's really a matter of just running `mysqldump` then `dolt sql < dump.sql` once at the very beginning. You can also just create a dolt repo and treat it like a mysql server.

2. Dolt does not reuse any MySQL code anywhere; we're building an entirely new sql engine in golang.
Some relevant repositories:
Dolt: https://github.com/dolthub/dolt
GMS (sql engine): https://github.com/dolthub/go-mysql-server
Vitess (fork of parser): https://github.com/dolthub/vitess

**Comment by zachmu** [comment]
Hi @AngryRocket,

If you give us a little more context on what you're trying to do we're happy to offer suggestions on how to best use Dolt.

For 3), are you asking about running Dolt on a machine that's also running MySQL, or something else?
