### ISSUE TITLE
JSON_CONTAINS regression

### ISSUE THREAD

**Issue by mlucic** [dolthub/dolt#7656]
After upgrading to v0.18.1-0.20240326173717-f57423646998 from v0.18.1-0.20240229000135-9b7e161e5e39 one of our queries which uses JSON_CONTAINS no longer returns results.

```sql
SELECT b.id as `id`
FROM table1 a
INNER JOIN table1 b
ON JSON_CONTAINS(a.numList, CAST(b.id AS json), '$')
WHERE b.id IN (1,2,3,4);
```

Where table1.numList is a JSON list of numbers. e.g. `[1, 2]`.

**Comment by fulghum** [comment]
@mlucic – thanks for bringing this one to our attention. https://github.com/dolthub/go-mysql-server/pull/2419 fixes the issue in `go-mysql-server`. If you pull the latest `go-mysql-server` from main, you should see the correct behavior again now. This fix will also go out with the next Dolt release. 

Let us know if you run into any other snags and we'll be happy to help!
