### ISSUE TITLE
cannot convert type longtext COLLATE utf8mb4_0900_ai_ci to datetime

### ISSUE THREAD

**Issue by guilhem** [dolthub/dolt#7781]
Running WooCommerce, we have this error:
```
cannot convert type longtext COLLATE utf8mb4_0900_ai_ci to datetime
```

```
$ dolt version 
dolt version 1.35.10
```

**Comment by fulghum** [comment]
Hi @guilhem, thanks for taking the time to report this to us. Someone on our team will work on a repro today. If you are able to turn on `--loglevel=DEBUG` when you start up `dolt sql-server` then you'll get a log of which queries are being executed – if you can share the exact query, that could help us get a better repro faster.

**Comment by jycor** [comment]
I tried some stuff, and I was able to get the same error through these sql statements:
```sql
tmp/main> create table t1 (d datetime);
tmp/main*> create table t2 (lt longtext collate utf8mb4_0900_ai_ci);
tmp/main*> insert into t1(d) select lt from t2;
cannot convert type longtext COLLATE utf8mb4_0900_ai_ci to datetime
```

We'll get started on resolving this issue asap, but the specific queries received from WooCommerce would be helpful too.
