### ISSUE TITLE
Ability to export diffs as SQL

### ISSUE THREAD

**Issue by ethanblake4** [dolthub/dolt#7813]
We are exploring using Dolt as a replication layer for an existing MySQL database to track development changes. One thing that would be very helpful is the ability to export a diff between two commits as SQL, so we can create migrations from the changes we've made.

**Comment by timsehn** [comment]
This exists!

https://docs.dolthub.com/sql-reference/version-control/dolt-sql-functions#dolt_patch

Example usage here:

https://docs.dolthub.com/introduction/getting-started/versioned-mysql-replica#revert-a-bad-change

**Comment by fulghum** [comment]
Sounds like a cool use case @ethanblake4. I'm assuming you're already using [the Dolt->MySQL replication support](https://docs.dolthub.com/guides/binlog-replication). Let us know if you hit any issues with that or have any other questions or feedback for us. We're happy to help!
