### ISSUE TITLE
Make sure deleting a branch behaves similarly to `drop database`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#7845]
A customer reports being able to run queries and possibly even connect to a branch that has been deleted. Deleting a branch should behave equivalently to `drop database`; probably breaking all active connections to it and returning "branch not found" for any subsequent queries and connections to it.

This whole space should get a battery of automated tests to make sure we do the right thing.

**Comment by jycor** [comment]
After some investigation, I believe that dolt is behaving correctly.

There are existing tests for the exact scenario in https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/sqle/enginetest/dolt_server_test.go#L42

During my testing, the session in the deleted branch returns `branch not found` for almost every query.
The only exceptions are queries that don't reference any tables.
```sql
mysql> select active_branch();
+-----------------+
| active_branch() |
+-----------------+
| NULL            |
+-----------------+
1 row in set (0.0005 sec)
```

```sql
mysql> select 1 + 2;
+-------+
| 1 + 2 |
+-------+
|     3 |
+-------+
1 row in set (0.0006 sec)
```

The only weird case is that the session is still able to `use db/deleted-branch` (but no queries work).
Sessions connected after the branch has been deleted are not able to `use db/deleted-branch`.

**Comment by timsehn** [comment]
Resolving.
