### ISSUE TITLE
Filters do not seem to be functioning properly on Dolt history tables

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#792]
I encountered the following seemingly strange behavior when query Dolt history table, note the filter seems to grab many things _except_ the thing being filtered for:
<img width="1441" alt="Screen Shot 2020-07-12 at 12 25 01 PM" src="https://user-images.githubusercontent.com/1596348/87255030-0c336c80-c43c-11ea-8452-0ddd978fb0e1.png">

Changing the commit doesn't help, nor does flipping the sign (which produces a strange error):
<img width="1613" alt="Screen Shot 2020-07-12 at 12 29 31 PM" src="https://user-images.githubusercontent.com/1596348/87255026-089fe580-c43c-11ea-9e6b-a02bec9406b2.png">

I snap shotted the test repo, reach out to me and I can send it, as GitHub issues does not allow attaching arbitrary formats.

**Comment by zachmu** [comment]
This seems to work on a cursory examination. I know many related bugs have been fixed.
