### ISSUE TITLE
Add support for `DOLT_HASHOF_DB()`

### ISSUE THREAD

**Issue by hdriqi** [dolthub/dolt#7970]
Currently Dolt only supports `DOLT_HASHOF_TABLE()` that return the hash value of the table. For decentralized technology (p2p, blockchain, etc.) use cases, there's the need to keep track of the whole database. 

I'm suggesting:
1. New function `DOLT_HASHOF_DB()` to generate the hash of the whole database at that time
2. Get database hash from each commit

**Comment by timsehn** [comment]
@bheni is going to crank this out today.
