### ISSUE TITLE
Temporary tables don't support AUTO_INCREMENT

### ISSUE THREAD

**Issue by arvidfm** [dolthub/dolt#7972]
If you create a temporary table with an `AUTO_INCREMENT` column, attempting to insert into it will yield the following error: `ERROR 1105 (HY000): table ... does not support AUTO_INCREMENT columns`. It works with MySQL on the other hand.

A simple workaround is to just use a normal table and drop it, but it would be nice to have this to simplify cleanup when using temporary tables during migrations.

MWE that fails with Dolt but works with Percona Server 8.3:
```sql
DROP TABLE IF EXISTS a_test;

CREATE TEMPORARY TABLE a_test(
    id INT PRIMARY KEY AUTO_INCREMENT
);

INSERT INTO a_test () VALUES (), (), (), ();

DROP TABLE a_test;
```

**Comment by jycor** [comment]
Hey @arvidfm , thanks for reporting this issue!
Issue has been fixed, and is making its way to dolt main. Expect a release with the fix soon.
