### ISSUE TITLE
Creating temporary tables can cause tag collisions

### ISSUE THREAD

**Issue by arvidfm** [dolthub/dolt#7995]
Temporary tables simply [use the column index as the column tag](https://github.com/dolthub/dolt/blob/add3ceac9609c14dc741d59df5951df4bdf670ea/go/libraries/doltcore/sqle/temp_table.go#L449-L451), so if you're very unlucky you can end up with a tag collision if a non-temporary table with the same tag already exists.

The below MWE always results in the error `ERROR 1105 (HY000): cannot create column g on table tmp_tbl, the tag 6 was already used in table note`:
```sql
DROP TABLE IF EXISTS note, tmp_tbl;

CREATE TABLE note(a int, b int, userid int);
CREATE TEMPORARY TABLE tmp_tbl(a int, b int, c int, d int, e int, f int, g int);

DROP TABLE note;
```

**Comment by timsehn** [comment]
I hate tags. Good find.

**Comment by jycor** [comment]
Hey @arvidfm nice find!

We made a change that has temporary tables use the same tag generating logic as persisting tables.
It does fix this particular collision, and will probably make future collisions more unlikely, probably.
