### ISSUE TITLE
dolt init fails on nfs-mounted directories

### ISSUE THREAD

**Issue by oconnoat** [dolthub/dolt#802]
When I run dolt init  on an nfs-mounted directory, it fails

`$dolt init` gives

`Failed to initialize directory as a data repo. error reading from or writing to noms`

`$ dolt status` after this gives:

`The current directories repository state is invalid
open /home/ec2-user/SageMaker/efs/alex/d/.dolt/repo_state.json: no such file or directory`

it also fails if you init on a locally-mounted directory and copy

**Comment by timsehn** [comment]
Sorry we seemed to have missed this. We will look into it.

Were you able to use a local directory as a work around?

**Comment by oconnoat** [comment]
Hi there it all works on local, so it's just when the nfs is used.

**Comment by timsehn** [comment]
OK. We've had another similar issue: https://github.com/liquidata-inc/dolt/issues/253. We thought we fixed it. I'll have @bheni look into this when he gets back.

**Comment by timsehn** [comment]
I'm pretty sure we found the root of this and fixed it. We haven't had a report in about a year.
