### ISSUE TITLE
Users are able to create branches with a "-" at the start. If you try to delete the branch after that, it looks like dolt is understanding it as an option for dolt_branch

### ISSUE THREAD

**Issue by tim-oh-thee** [dolthub/dolt#8034]
The following statements will fail with the final deletion statement. This means the branch is stuck there (as far as I know).
call dolt_checkout('-b','-qa');
call dolt_checkout('main');
call dolt_branch('-d','-qa');
SQL Error [1105] [HY000]: error: unknown option `qa'

**Comment by tim-oh-thee** [comment]
Absolutely!! Figured I’d put it out there for you to decide what to do with it.

Thanks,

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jycor** [comment]
git doesn't allow branch names that start with `-`, so it seems like we should prevent branches with that name


```shell
$ git checkout -b -test
fatal: '-test' is not a valid branch name

$ git checkout -b --test
fatal: '--test' is not a valid branch name

$ git checkout -b \-test
fatal: '-test' is not a valid branch name
```

**Comment by jycor** [comment]
Did some more digging, and apparently we allow escaping `-` with `--`, so

```sql
tmp/main> call dolt_branch('-D', '--', '-test');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)
```
