### ISSUE TITLE
mysql:latest - missing error: [HY000][1524] Plugin 'mysql_native_password' is not loaded

### ISSUE THREAD

**Issue by muescha** [dolthub/dolt#8042]
Note: I report this because dolt should react 1:1 the same as MySQL. But maybe this is not a bug.

# Setup MySQL

I pulled the image `mysql:latest` and startet it in Docker

I run the sql:

```sql
CREATE USER IF NOT EXISTS `restadmin`@`%` 
IDENTIFIED WITH mysql_native_password BY 'password';
```

# MySQL

```mysql
[HY000][1524] Plugin 'mysql_native_password' is not loaded
```

# Dolt

No error. User is created.

**Comment by timsehn** [comment]
This is a bit of a tricky one for us. 

We're not going to support MySQL authentication plugins so we likely parse `WITH mysql_native_password`, ignore it, and create the user anyway using our authentication method. This is for compatibility with applications specifically built for MySQL. I'm pretty sure this is the way we want this to behave in this circumstance. 

Is there a reason beyond exact compatibility that you need this query to fail?

**Comment by muescha** [comment]
I don't have a reason; I just noticed different behavior.

**Comment by timsehn** [comment]
OK. I'll resolve as won't fix. In general, we are sometimes more permissive than MySQL. Please keep cutting issues with incompatibilities you find.
