### ISSUE TITLE
`dolt sql-server` should ignore subdirectories that are not Dolt repos with a warning

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#809]
I cloned to Dolt repos into the same directory as a Git repo, and couldn't run `dolt sql --multi-db-dir .` since it failed on trying to create a DB from the Git repo.

As discussed offline, this should just warn on each subdirectory that is not a Git repo.

**Comment by zachmu** [comment]
Should also ignore broken dolt repositories by default (i.e. there is a .dolt directory, but it won't load cleanly for whatever reason)

**Comment by timsehn** [comment]
I think this is resolved.
