### ISSUE TITLE
Tag releases: database not found

### ISSUE THREAD

**Issue by Trojanku** [dolthub/dolt#8147]
When using capital letters in a release tag, the `use database/tag` doesn't work.

`dolt-sql-server: 1.35.7`

Steps to reproduce using mysql cli:

1. Check for existing tags: 
```
mysql> select tag_name from dolt_tags;
Empty set (0.00 sec)
```

2. Create a tag with capital letter in it:
```
mysql> call dolt_tag('V1', 'main', '-m', 'message');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.01 sec)
```

3. Disconnect from db connection and reconnect.

4. Checkout to database/tag:
```
mysql> use daq/V1;
Database changed
```
4. Try to perform any query:
```
mysql> select name from dolt_branches;
ERROR 1105 (HY000): database not found: daq/v1
```

At the end, it always gives back `database not found: daq/v1`.

To solution that works:
Do not use capital letters in a name of release tag. With this, the above issue does not appear.

**Comment by timsehn** [comment]
Good find. @jycor will get this fixed today.

**Comment by jycor** [comment]
Hey @Trojanku , thanks for reporting this issue.
The fix for this has been merged to dolt main. Expect a release with the fix tomorrow.
