### ISSUE TITLE
Use-Case proposition: Machine Learning Ground Truth Curation

### ISSUE THREAD

**Issue by fkoehne** [dolthub/dolt#815]
As a data scientist I'd like to be able to manually clean a label dataset (i.e. our ground truth) in an auditable way (since we may introduce different errors or biases) as a team effort.

**Comment by oscarbatori** [comment]
That sounds like a reasonable use case. Have you had any success or do you need to discuss implementation details?

**Comment by fkoehne** [comment]
I liked your use-case blogpost and wanted to contribute the idea and see if anyone has made experiences with that kind of workflow using dolt, already. 
I'm currently curating this kind of datasets with a workflow based on CSV files / git and sometimes DVC.

**Comment by oscarbatori** [comment]
@fkoehne thanks for your interest, and glad you enjoyed the blog post. If you enjoyed that you might enjoy this more concrete [example](https://www.dolthub.com/blog/2020-07-24-data-dependencies-using-dolthub-an-example/) of using Dolt for data science work.
 
We have some folks right now working on implementing Dolt as a tool for managing researcher produced datasets which then get fed into machine learning model training pipeline. 

Would you be open to discussing your use-case in further detail? That would be of great help to us in understanding the needs of potential users.

**Comment by timsehn** [comment]
Any data:

1. that's important
2. bigger or more structured than can fit in a spreadsheet
3. that multiple people are hand editing 

...is the target use case for Dolt. 

We have had a hard time marketing to the Machine Learning community (our Reddit posts get modded away etc) so we have not spent much time writing about the use cases. But for instance, we think ImageNet would have happened much more quickly and much more efficiently with far fewer bad labels had Dolt been used to build it.

**Comment by zachmu** [comment]
@fkoehne, this is a great question for us, but I'm going to close it out due to its age and the non-specific nature. We would be glad to continue talking to you about this use case and refining it! Please join us on discord, or file more issues here, if you want to continue the conversation.
