### ISSUE TITLE
chore: initialize go workspaces

### ISSUE THREAD

**Issue by laciferin2024** [dolthub/dolt#8185]
Hi,

The CI seems to be failing: https://github.com/dolthub/dolt/actions/runs/10188809026/job/28185673578

Close https://github.com/dolthub/dolt/pull/8163

Hiro

**Comment by fulghum** [comment]
Thanks for flagging the CI failures. I believe those checks don't run correctly for PR authors outside our group. I'll dig in and double check and get you a response on the PR today.

**Comment by fulghum** [comment]
Thanks for the contribution @laciferin2024. Closing this issue now that the https://github.com/dolthub/dolt/pull/8163 is merged.
