### ISSUE TITLE
Unknown JSON struct tag in schema_marshaling.go

### ISSUE THREAD

**Issue by chavacava** [dolthub/dolt#8206]
https://github.com/dolthub/dolt/blob/c290ade4ea3035349fbea70af777bae497285ab0/go/libraries/doltcore/schema/encoding/schema_marshaling.go#L183

`omitEmpty` should be `omitempty`

(found with [revive](https://github.com/mgechev/revive) @nicktobey )

**Comment by jycor** [comment]
Hey @chavacava, thanks for reporting all these issues! That linter is very handy!
Fixes for all of those have been merged to dolt main.

If you haven't already, I think the same linter should be run over some of our other repos:
- https://github.com/dolthub/go-mysql-server
- https://github.com/dolthub/vitess

**Comment by bpf120** [comment]
@chavacava Are you building something with Dolt? Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

**Comment by chavacava** [comment]
> Hey @chavacava, thanks for reporting all these issues! That linter is very handy! Fixes for all of those have been merged to dolt main.

Hi @jycor, nice! 

> If you haven't already, I think the same linter should be run over some of our other repos:
> 
> * https://github.com/dolthub/go-mysql-server
> * https://github.com/dolthub/vitess

I'll make a pass on these repos and see if the `revive` spots something.

**Comment by chavacava** [comment]
> @chavacava Are you building something with Dolt? Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

Hi @bpf120, I don't use Dolt. I maintain the Go linter [`revive`](https://github.com/mgechev/revive). Last week I read the blog entry [What's the best Static Analysis tool for Golang?](https://www.dolthub.com/blog/2024-07-24-static-analysis/) by @nicktobey and I decided to see if you use `revive` (via `golangci-lint`), I saw you don't thus I ran it over `dolt` code base to showcase some interesting findings that `revive` is able to do.

**Comment by chavacava** [comment]
Hi @jycor,

> If you haven't already, I think the same linter should be run over some of our other repos:
> 
>     * https://github.com/dolthub/go-mysql-server
Among other things like:
  390  unchecked-type-assertion  
  76   modifies-value-receiver   
  43   increment-decrement       
  21   empty-block               
  16   redefines-builtin-id      
  13   range                     
  4    unreachable-code          
  4    superfluous-else          
  1    if-return                 
  1    useless-break             
  1    context-as-argument   

revive found some unreachable code at:

sql/values/encoding.go:253:2: unreachable code after this statement
sql/values/encoding.go:269:2: unreachable code after this statement
sql/memo/rel_props.go:452:5: unreachable code after this statement
sql/analyzer/indexed_joins.go:467:5: unreachable code after this statement
 
>     * https://github.com/dolthub/vitess

Among other things like:
Warnings:
  35  unchecked-type-assertion  
  5   modifies-value-receiver   
  3   redefines-builtin-id      
  3   unreachable-code          
  2   empty-block               
  1   superfluous-else   

revive found some unreachable code at:
go/vt/sqlparser/parse_next_test.go:90:4: unreachable code after this statement
go/vt/sqlparser/parse_next_test.go:97:4: unreachable code after this statement
go/vt/sqlparser/parse_next_test.go:153:5: unreachable code after this statement
