### ISSUE TITLE
nested (delete) triggers have the wrong context in the nested call

### ISSUE THREAD

**Issue by MueckeMa** [dolthub/dolt#8213]
If two triggers are nested so that one trigger calls the next, I noticed the following with two triggers on delete:

- In the context of the second trigger, the value of OLD is the value from the context of the first trigger
- If I execute more than one insert command in the same table, only the first one is executed and the subsequent ones are ignored

Result of the demo case in table_log with dolt
(docker dolthub/dolt-sql-server:1.42.8)
| id  | message                                          |
|-----|--------------------------------------|
| 2   | Deleteing from table3: 2 by id: 1    |

Result of the demo case in table_log with MySQL
(docker mysql:5.7)
| id  | message                                          |
|-----|--------------------------------------|
| 2   | Deleteing from table3: 3 by id: 2    |
| 3   | Deleted from table3: 3                    |

Here is a demo that reproduces the case
```sql
DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table2;
DROP TABLE IF EXISTS table3;
DROP TABLE IF EXISTS table_log;
DROP TRIGGER IF EXISTS delete_from_table2_if_table1_deleted;
DROP TRIGGER IF EXISTS delete_from_table3_if_table2_deleted;
DROP TRIGGER IF EXISTS log_delete_from_table3;

-- Create table1
CREATE TABLE table1 (
    id INT PRIMARY KEY,
    table2_id INT
);

-- Create table2
CREATE TABLE table2 (
    id INT PRIMARY KEY,
    table3_id INT
);

-- Create table3
CREATE TABLE table3 (
    id INT PRIMARY KEY
);

-- Create log table
CREATE TABLE table_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(255)
);

-- Insert data into table1
INSERT INTO table1 (id, table2_id) VALUES (1, 2);

-- Insert data into table2
INSERT INTO table2 (id, table3_id) VALUES (2, 3);

-- Insert data into table3
INSERT INTO table3 (id) VALUES (3);

-- Create trigger on table1
DELIMITER //
CREATE TRIGGER delete_from_table2_if_table1_deleted
AFTER DELETE ON table1
FOR EACH ROW
BEGIN
    DELETE FROM table2 WHERE id = OLD.table2_id;
    -- uncomment this line to see the complete log
    -- INSERT INTO table_log (id, message) VALUES (1, CONCAT('Deleteing from table2: ', OLD.table2_id, ' by id: ', OLD.id));
END;
//

DELIMITER ;

-- Create trigger on table2
DELIMITER //
CREATE TRIGGER delete_from_table3_if_table2_deleted
AFTER DELETE ON table2
FOR EACH ROW
BEGIN
    DELETE FROM table3 WHERE id = OLD.table3_id;
    INSERT INTO table_log (id, message) VALUES (2, CONCAT('Deleteing from table3: ', OLD.table3_id, ' by id: ', OLD.id));
END;
//

DELIMITER ;

-- Create trigger on table3
DELIMITER //
CREATE TRIGGER log_delete_from_table3
AFTER DELETE ON table3
FOR EACH ROW
BEGIN
    INSERT INTO table_log (id, message) VALUES (3, CONCAT('Deleted from table3: ', OLD.id));
END;
//

DELIMITER ;

-- Delete from table1 to trigger the nested triggers
DELETE FROM table1 WHERE id = 1;
```

**Comment by jycor** [comment]
Hey @MueckeMa, thanks for reporting this issue.

I had some time to take a look at this, and I am working on a fix.
Will keep you posted on the progress.

**Comment by jycor** [comment]
https://github.com/dolthub/go-mysql-server/pull/2631 only partially addresses this issue.

Single insert/update/delete statements inside a single trigger should be working now.
However, multiple statements inside `begin...end` blocks are still causing problems; we're still looking into it.

**Comment by MueckeMa** [comment]
Thank you for the quick solution and attention to the second problem.

**Comment by jycor** [comment]
Triggers have always been a challenging area for us, but the changes [here](https://github.com/dolthub/go-mysql-server/pull/2635) should allow dolt to run more complex combinations of triggers.

Thanks again @MueckeMa for reporting this issue.
The fix is making its way to dolt main, we'll cut a release for you later this week!
