### ISSUE TITLE
Correctness Issue, queries run differently on MySQL and Dolt

### ISSUE THREAD

**Issue by tiksn** [dolthub/dolt#8220]
In https://github.com/fossa-app/scripts repository I have docker compose containing FusionAuth docker container and MySQL db running in `main` branch. In `use-dolt` branch I replaced MySQL with Dolt.

FusionAuth initialized database by running huge migration script. Some part of it run differently with MySQL and with Dolt. I separated those queries.

Query 1: syntax error at position 75 near 'instant'

```SQL
CREATE TABLE raw_logins (
  applications_id BINARY(16)   NULL,
  instant         BIGINT       NOT NULL,
  ip_address      VARCHAR(255) NULL,
  users_id        BINARY(16)   NOT NULL,
  CONSTRAINT raw_logins_fk_1 FOREIGN KEY (applications_id) REFERENCES applications(id),
  CONSTRAINT raw_logins_fk_2 FOREIGN KEY (users_id) REFERENCES users(id)
)
  ENGINE = innodb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_bin;
```

Query 2: syntax error at position 50 near 'instant'

```SQL
CREATE INDEX raw_logins_i_1 ON raw_logins(instant);
```

Query 3: syntax error at position 60 near 'instant'

```SQL
CREATE INDEX raw_logins_i_2 ON raw_logins(users_id, instant);
```

Query 4: syntax error at position 72 near 'instant'

```SQL
CREATE TABLE master_record (
  id      BINARY(16) NOT NULL,
  instant BIGINT     NOT NULL
)
  ENGINE = innodb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_bin;
```

Feels like word `instant` is reserved in Dolt but not in MySQL.

dolt version 1.42.7

**Comment by timsehn** [comment]
@jycor will get this fixed and released today.

**Comment by jycor** [comment]
Hey @tiksn , thanks for reporting this issue!
The fix has made its way to dolt main, and we can cut a release for you later this week.

**Comment by tiksn** [comment]
Thanks @jycor it was really quick. I will keep an eye for the release.
