### ISSUE TITLE
Issue with datetime(6) column using timestamp(6) range

### ISSUE THREAD

**Issue by dtminnaar** [dolthub/dolt#8236]
When storing a record with the datetime value of 1000-01-01 00:00:00 I get the following error:
` MySqlConnector.MySqlException (0x80004005): value "1000-01-01 00:00:00" is outside of timestamp(6) range`

The column in the database is datetime(6), not timestamp(6).
Manually changing the value in the database works.

You can recreate this error by adding the following lines to Program.cs in this sample:
```
app.MapRazorPages();

// Test adding a movie with date 1000-1-1 00:00:00
using var scope = app.Services.CreateScope();
using var doltContext = scope.ServiceProvider.GetRequiredService<DoltContext>();
if (doltContext.Database.GetPendingMigrations().Any())
{
	doltContext.Database.Migrate();
	doltContext.Database.ExecuteSql($"call dolt_commit('-Am', Applied database migration);");
}

doltContext.Add(new Movie
{
	Genre ="test",
	Price = 1,
	ReleaseDate = new DateTime(1000, 1, 1, 0, 0, 0),
	Title = "test",
});

try
{
	doltContext.SaveChangesAndCommitAsync("added test movie").Wait();
}
catch (Exception ex)
{
	// Why is the type timestamp(6) used?
	Console.WriteLine(ex.ToString());
}

app.Run();
```

Updated sample to .net core 8.0.7
Updated Pomelo.EntityFrameworkCore.MySql to 8.0.2
Using docker image dolt-sql-server version 1.42.7

Best regards.

**Comment by fulghum** [comment]
I fixed the issue in the `go-mysql-server` library and it's building into `dolt` right now. I took a dev build of `dolt` with that change and confirmed that your repro code is now able to correctly insert a movie with a "1000-01-01 00:00:00" date. 🙌 

I'll kick off a release once that build is finished so you can pick up the fix at your convenience. 

Thanks again for helping us find this one! This was a good one to fix!

**Comment by fulghum** [comment]
@dtminnaar – [Dolt 1.42.10](https://github.com/dolthub/dolt/releases/tag/v1.42.10) contains the fix for this one. Let us know if we can do anything else to help you build with Dolt!
