### ISSUE TITLE
`SELECT WHERE (id = x AND id = y)` returns row matching `y` instead of no results

### ISSUE THREAD

**Issue by glennmatthews** [dolthub/dolt#8317]
Follow on to #8308, retesting with 1.42.17 shows fewer issues now (thanks for the quick fix!) but we're now seeing another failure, as illustrated by the below. 

*May be specific to UUID primary keys as I don't see this issue for other tables having integer PKs.*

```sql
> CREATE TABLE `foo` (`id` char(32) NOT NULL, PRIMARY KEY (`id`));
Query OK, 0 rows affected (0.015 sec)

> INSERT INTO foo (id) VALUES ('ec222d46a03d4f86af58a004f54abcd0');
Query OK, 1 row affected (0.028 sec)

> INSERT INTO foo (id) VALUES ('eba39c1c04c149fb96b605b61997481d');
Query OK, 1 row affected (0.028 sec)

> SELECT * FROM foo;
+----------------------------------+
| id                               |
+----------------------------------+
| eba39c1c04c149fb96b605b61997481d |
| ec222d46a03d4f86af58a004f54abcd0 |
+----------------------------------+
2 rows in set (0.003 sec)

> SELECT * FROM foo WHERE (id = 'eba39c1c04c149fb96b605b61997481d' AND id = 'ec222d46a03d4f86af58a004f54abcd0');
+----------------------------------+
| id                               |
+----------------------------------+
| ec222d46a03d4f86af58a004f54abcd0 |
+----------------------------------+
1 row in set (0.001 sec)

> SELECT * FROM foo WHERE (id = 'ec222d46a03d4f86af58a004f54abcd0' AND id = 'eba39c1c04c149fb96b605b61997481d');
+----------------------------------+
| id                               |
+----------------------------------+
| eba39c1c04c149fb96b605b61997481d |
+----------------------------------+
1 row in set (0.001 sec)
```

Thanks!

**Comment by timsehn** [comment]
@max-hoffman will fix this one tomorrow. Thanks for the great bug reports and sorry for the issues.

**Comment by max-hoffman** [comment]
I have a fix linked above, I'm surprised we did not have a test for this one but thanks for taking the time to file and issue and help us patch the gap. We will release this tonight.

**Comment by glennmatthews** [comment]
Thank you!

**Comment by max-hoffman** [comment]
Release 1.42.18 is set to run, but GitHub actions is a bit sluggish tonight. I've confirmed that dolt main includes the fix for this bug and 1.42.18 should unblock you. Let us know if you see any other problems!

**Comment by glennmatthews** [comment]
1.42.18 looks to get our tests back to 100% passing. Thank you!

**Comment by timsehn** [comment]
Sorry for the regressions. We are optimizing join performance and missed some edge cases it seems. Thanks for enhancing our test suite!
