### ISSUE TITLE
mysql-connector-python fails to connect to `dolt sql-sever`

### ISSUE THREAD

**Issue by zhangysh1995** [dolthub/dolt#833]
I could use `mysql-client` to log into the server, however, I cannot do it with `mysql-connector-python`:

``` Bash
# okay with the client
xxx:~/test$ mysql -P 4000 -D test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3619
Server version: 5.7.31 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

# fail with the connector
xxx:~$ time python3 testcon.py
^Z
[8]+  Stopped                 python3 testcon.py

real    0m34.996s
user    0m0.000s
sys     0m0.001s
````

Set up:

```` Bash
mkdir test; cd test
dolt init --name zhangys --email zhangysh1995@gmail.com 
dolt sql-server -P 4000 -u zhangys
````

Test script:
```` Python3
import mysql.connector

config = {
    "port": "4000",
    "user": "zhangys",
    "database": "test"
}

try:
    conn = mysql.connector.connect(**config)
    cu = conn.connect()
except Exception as e:
    print(e)

````

Environment:
```` Bash
xxx:~/remote/randgen$ uname -r
4.15.0-72-generic
xxx:~/remote/randgen$ cat /etc/os-release | grep VERSION
VERSION="18.04.3 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
xxx:~/remote/randgen$ mysql --version
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper
xxx:~/remote/randgen$ pip3 freeze | grep mysql
mysql==0.0.2
mysql-connector-python==8.0.19
mysqlclient==1.4.6
````

**Comment by oscarbatori** [comment]
@zhangysh1995 I don't seem to be able to replicate this locally. I was confused when I saw this because all of our Python library uses `mysql-connector` (underneath SQL Alchemy).

@andrew-wm-arthur can you sanity check me on this? 

Have you seen [Doltpy[(https://github.com/liquidata-inc/doltpy)? This provides much of the tooling needed for working with Dolt.

**Comment by zhangysh1995** [comment]
> Have you seen [Doltpy[(https://github.com/liquidata-inc/doltpy)? This provides much of the tooling needed for working with Dolt.

Good to know it. But I have a code base to use so it may be not easy to move to a new driver.

**Comment by zhangysh1995** [comment]
> @zhangysh1995 I don't seem to be able to replicate this locally. I was confused when I saw this because all of our Python library uses `mysql-connector` (underneath SQL Alchemy).

Yeah it was a typo, the package is `mysql-connector-python`.

**Comment by oscarbatori** [comment]
We are using `mysql-connector-python`, check out [`setup.py`](https://github.com/liquidata-inc/doltpy/blob/master/setup.py) to see our dependency.

All of our tooling uses this driver, and I could not replicate your issue locally on my Mac. 

Can I ask you a bit more about what you are trying to to do?

**Comment by zhangysh1995** [comment]
> We are using `mysql-connector-python`, check out [`setup.py`](https://github.com/liquidata-inc/doltpy/blob/master/setup.py) to see our dependency.

Think one dependency on my machine maybe missing. I will try again.


> Can I ask you a bit more about what you are trying to to do?

Normal connection with normal queries, nothing special.

**Comment by oscarbatori** [comment]
If you could show me the exception you are seeing that would help? I just can't replicate it locally and we have made such extensive use of this connector that I'd like to see the exception before digging in further.

**Comment by zhangysh1995** [comment]
> If you could show me the exception you are seeing that would help? I just can't replicate it locally and we have made such extensive use of this connector that I'd like to see the exception before digging in further.

There was no private data related to this issue. I just saw the program get stuck and nothing happened, so I used the command `time` to demo the hang. I ran the provided test case for more than 30s without any exception, crash and no output. I will try to replicate it with a docker container if possible.

**Comment by zhangysh1995** [comment]
I found a way to reproduce the problem:

````
1. Follow the test case to set up the sql-server
2. Use ctrl-z to kill the server (stdout: killed + stopped, however it is sleeping which is correct on Linux)
3. Run the script to connect, the program will sleep (reproduced)
````
`ctril-z` sends sleep to the server, however, the connector is also stuck. 
I think it is `mysql-connector-python` has a problem with handling the conenction (?) rather than `dolt`?

**Comment by zachmu** [comment]
@zhangysh1995 I'm going to close this out owing to the age and lack of a solid repro. We definitely have come a long way on SQL server connectivity, including with various python connectors, since you filed this. So give another try if you're still interested. Please do let us know if you have the same issue or new problems.
