### ISSUE TITLE
Dolt clone on tag name results in multiple issues

### ISSUE THREAD

**Issue by farhanhubble** [dolthub/dolt#8377]
**Reproduction**:
1. On doltlab create a new tag via the "Create Release" flow, say "tag-01"
2. Clone only this tag `dolt clone origin "tag-01" <doltlab_url>`
3. Try `dolt status`
4. Try `dolt branch -v`
5. Try `dolt log`
6. Try `dolt sql -q 'select * from dolt_branches'`

**Current behavior:**
Commands 3,4 result in `unexpectedly received non-string column in 'SELECT active_branch()': %!s(<nil>)`. Command 5 results in `this operation is not supported while in a detached head state` while command 6 results in no branch data.

**Expected behavior:**
Either dolt clone should not work with tag names or it should leave the repo in a state where basic commands work

**Dolt version**: 1.43.0

**Comment by timsehn** [comment]
Thanks. We need to copy some of the Git behavior here.

**Comment by jycor** [comment]
Hey @farhanhubble, thanks for reporting this issue.

We've improved our error handling for tags. You shouldn't be able to reference a tag in `dolt clone`.
```
dolt clone --branch tag1 <dolt-repo-url> db
```
Should throw an error.

We'll have a release with these changes out later this week!
