### ISSUE TITLE
Parquet dump type for decimal is binary, not decimal

### ISSUE THREAD

**Issue by jeregrine** [dolthub/dolt#8384]
The Parquet format [supports decimal types](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal) 

[Here](https://github.com/dolthub/dolt/blob/a63bf91ca42085153a6c435eaacaa68c095675ee/go/libraries/doltcore/table/typed/parquet/writer.go#L147C1-L149C1) it is set as a utf-8 binary instead of decimal.

**Comment by fulghum** [comment]
Hi @jeregrine, thanks for taking the time to report this. Sorry we didn't get you a response faster. Looks like we need to revisit the parquet serialization of decimal types. 

Does this cause exported parquet files to not load correctly for you in other systems? Just curious to understand the impact, particularly whether this results in a broken data import or if it's an optimization for the data import from the Dolt-produced parquet file. That'll help us understand how to prioritize the work.

**Comment by timsehn** [comment]
Seems like this might be as simple as adding another case statement for DECIMAL types. Might not be worth waiting for the customer response. @jycor will get this done today.

**Comment by jycor** [comment]
Hey @jeregrine, thanks for reporting this issue!

Dolt parquet exports are now stored as `BYTE_ARRAY` with converted type set to `DECIMAL`.
This should result in slightly better compression. A release with this should come out later this week.

Let us know how it works for you.
