### ISSUE TITLE
dolt can restore individual or specified files up to the specified commit record

### ISSUE THREAD

**Issue by Donxiaohao** [dolthub/dolt#8442]
The git checkout command can restore a single file to the location of the specified commit record, like the following command：git checkout  commitId -- filepath Does

My requirement is that when operating on a single table, I want to perform data recovery without affecting the data in other tables.

For example, Table A submitted 10 pieces of data, which was recorded as the first submission, Table B submitted 5 pieces of data, and was recorded as the second submission, and Table A modified 5 pieces of data, which was recorded as the third submission. At this time, I want to Restoring table A data to the first submission is currently not supported. If you use the reset or revert command, the data in table B will be lost.  I hope that only the status of table A is changed, without any modifications to table B.

**Comment by timsehn** [comment]
Someone will pick this up today. @jycor for visibility.

**Comment by Donxiaohao** [comment]
> Someone will pick this up today. @jycor for visibility.

thanks a lot

**Comment by jycor** [comment]
Hey @Donxiaohao, thanks for the feature request!
I'm working on this now, and am aiming to support this feature sometime early next week.

**Comment by zachmu** [comment]
I have this mostly implemented, will cut a release in a bit.

**Comment by zachmu** [comment]
This is going out in release 1.43.5, which should be out in about an hour. Please reopen if the issue is not resolved.

**Comment by Donxiaohao** [comment]
> This is going out in release 1.43.5, which should be out in about an hour. Please reopen if the issue is not resolved.

okey  thanks
