### ISSUE TITLE
The following is the log, it has been stuck at pulling..... for about one day. Is there any way to see if it is running normally?

### ISSUE THREAD

**Issue by berisfu** [dolthub/dolt#8452]
+ cd /dolt/investment_data
+ dolt pull
- Pulling...Updating 7qpb0e2v4sqe1qanlggmcisn10h6vj20..bec1m9b6vqaveln0u34aafqodek5jtog
/ Pulling...commit 1d4i7c0r4db01gfi3qvii8ooctmc132v (HEAD -> master)
Merge: 7qpb0e2v4sqe1qanlggmcisn10h6vj20 8ipl4abccin6iqlqf5uvgadohl1o9amn
Author: root <root@localhost>
Date:  Mon Oct 14 23:43:38 +0000 2024

        Merge branch 'master' of https://doltremoteapi.dolthub.com/chenditc/investment_data into master
/ Pulling...

**Comment by timsehn** [comment]
This is almost certainly some sort of infinite loop. I would kill it and try again. 

If it gets stuck again, you can, delete the `investment_data` directory and reclone it with `dolt clone chenditc/investment/data`.

Are you using the latest version of Dolt? When did you originally clone the database? I wonder if it's some sort of version compatibility thing.

**Comment by timsehn** [comment]
No response. Please re-open if the recurs.
