### ISSUE TITLE
excessive memory usage during `SELECT DISTINCT` query

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#8488]
Dolt `v1.43.7`

```
dolt clone post-no-preference/options
cd options
dolt sql -q 'SELECT DISTINCT `act_symbol` FROM `option_chain` ORDER BY `act_symbol`;'
```

Executing this query uses almost 80GBs of memory locally and takes a long time to complete (if it completes at all)

**Comment by zachmu** [comment]
@jycor I think this is probably due to some loop in GMS (or possibly dolt) not checking for context cancelation
