### ISSUE TITLE
Dolt question

### ISSUE THREAD

**Issue by AngryRocket** [dolthub/dolt#8537]
Dolt will crash when writing a large amount of SQL？
At present, I have configured the mode of 1 primary and 2 backup, but the host crashed while writing data frantically. What is the reason?

**Comment by timsehn** [comment]
We are discussing this on Discord. It sounds like you are using an old version. Can you upgrade to the latest? This will be easier to fix with a back and forth on Discord.

Dolt should not crash ever and can handle many concurrent writes.
