### ISSUE TITLE
Potential TUI tool like Lazygit

### ISSUE THREAD

**Issue by Mickychen00** [dolthub/dolt#8572]
Hi,

I am an avid user of TUI git tools like Lazygit (https://github.com/jesseduffield/lazygit). I've discovered that many commands and procedures in Dolt are more efficiently executed using hotkeys rather than a GUI. Since Lazygit is built with Go, perhaps we could see a LazyDolt in the future.

**Comment by fulghum** [comment]
Hi @Mickychen00, thanks for the sharing the feature idea. LazyGit looks like a cool tool! We're currently focused on improvements to the SQL engine, but it would be cool to see someone in the community contribute a TUI app for Dolt. Thanks for the enhancement suggestion!

**Comment by Mickychen00** [comment]
Hi. Thanks a lot. Just some thoughts: For the people who use Dolt well, I think most of them know Git well. I think compared to the Dolt workbench, a combination of the functions of Lazygit and Visidata (https://www.visidata.org/) would be more promising. This LazyDolt tool would appeal to more people who know TUI well but would not like to use a premature GUI tool.

@timsehn @fulghum

**Comment by timsehn** [comment]
Thanks for the feedback. This is unlikely to get on our radar any time soon. I'll have @liuliu-dev the owner of the workbench see if there is anything in these tools we can crib for the workbench. We only really have time/resources for one GUI interface :-)

**Comment by aspiers** [comment]
I have just vibe-coded this yesterday:

https://github.com/aspiers/lazydolt

It's just an MVP at this point but already beginning to be useful.

I also vibe-coded the beginnings of an emacs mode with very similar design to magit:

https://github.com/aspiers/madolt

**Comment by Mickychen00** [comment]
Hi. Great to hear that! Thanks to AI, everyone can make their dreams come true. I will give it a try!

**Comment by aspiers** [comment]
I definitely recommend trying madolt as I've put more effort into it than into lazydolt, and it's getting pretty nice.

**Comment by Mickychen00** [comment]
> I definitely recommend trying madolt as I've put more effort into it than into lazydolt, and it's getting pretty nice.

thanks for recommending. I'll try it despite I am a Vim user without Emac knowledge. Is Emac hard to learn?

**Comment by aspiers** [comment]
There's definitely a learning curve, but if you only want to use it for this it shouldn't be too bad.  Plus these days AI can answer any question easily if you get stuck.  "How do I quit emacs?" used to be the most popular question but no reason to struggle with that any more 😆
