### ISSUE TITLE
Erroneous output with unique constraint on TEXT or TINYTEXT

### ISSUE THREAD

**Issue by rjosephwright** [dolthub/dolt#8629]
When I create a column with a unique constraint on TEXT or TINYTEXT I get garbled output for the error.

Example:

```
mysql> create table test_error ( thing TINYTEXT UNIQUE );
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test_error (thing) values ('hello');
Query OK, 1 row affected (0.01 sec)

mysql> insert into test_error (thing) values ('hello');
ERROR 1062 (HY000): duplicate unique key given: [?~<$???#????a׃᫛]
```

If I replace TINYTEXT with VARCHAR I get the expected error output:

```
mysql> create table test_error ( thing VARCHAR(255) UNIQUE );

... lines omitted ...

mysql> insert into test_error (thing) values ('hello');
ERROR 1062 (HY000): duplicate unique key given: [hello]
```

The issue occurs on the latest release (1.43.19).

**Comment by timsehn** [comment]
Thanks for the report. We will get this fixed today.

**Comment by jycor** [comment]
Hey @rjosephwright, thanks for reporting this issue.
The fix has been merged to dolt main and we'll have a release out for you later this week

**Comment by rjosephwright** [comment]
Thanks for such a quick response @jycor.

**Comment by bpf120** [comment]
@rjosephwright , thanks for the issue. We'd love to learn about your use case.  You can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.
