### ISSUE TITLE
Getting error for `select * from dolt_procedures` for repo used in dolt docs

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#8642]
This repo is used in the embedded dolthub console in the `dolt_procedure` [dolt docs](https://docs.dolthub.com/sql-reference/version-control/dolt-system-tables#dolt_procedures)
Here's the query that fails:
https://www.dolthub.com/repositories/dolthub/first-hour-db/query/main?active=Tables&q=SELECT+*+FROM+dolt_procedures%0A

Confirmed that this is not a dolthub-only error and it is not an error on all databases with procedures
Potentially only an issue for older databases since additional columns were added

**Comment by macneale4** [comment]
Migrating the table by doing a `select * from dolt_procedures` results in some downstream issues where we would be updating read-only databases. So I decided to punt, and manually upgrade the `first-hour-db` database so that the documentation would render correctly.
