### ISSUE TITLE
LOAD DATA INFILE syntax error on different order of params 'starting by' and 'terminated by'

### ISSUE THREAD

**Issue by uroborosq** [dolthub/dolt#8706]
Env:
Docker image -  dolthub/dolt-sql-server:latest
```
root@c0ca5804a5c6:/var/lib/dolt# dolt version
dolt version 1.45.0
```
Host OS: arch linux, amd64

---

Steps:
create a csv file for import:
```bash
echo -e '1;"test1"\n2;"test2"' > example.csv
```
try to import data with firstly 'STARTING BY'  then 'TERMINATED BY':
 ```sql
LOAD DATA LOCAL INFILE '/var/lib/dolt/example.csv' INTO TABLE `test_load_data` CHARACTER SET binary FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES STARTING BY '' TERMINATED BY '\n' (id,value);
```
Such query works perfectly.

Then, swap 'TERMINATED BY' and 'STARTING BY':
```sql
test/main*> LOAD DATA LOCAL INFILE '/var/lib/dolt/example.csv' INTO TABLE `test_load_data` CHARACTER SET binary FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' STARTING BY '' (id,value);
Error parsing SQL: 
syntax error at position 208 near 'STARTING'
CLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' STARTING BY '' (id,value)
                                                                ^
```
No problems with MySQL (9) when order is reversed.

Originally, problem was faced with usage of [sqlc](https://sqlc.dev/) for Go, which uses such order from in external lib - https://github.com/hexon/mysqltsv/blob/main/mysqltsv.go#L17, so there is no visible way to override it.

**Comment by timsehn** [comment]
Good bug and repro. @jycor will fix this tomorrow

**Comment by timsehn** [comment]
@jycor was sick yesterday but I see this in our fork of Vitess

https://github.com/dolthub/vitess/pull/393

**Comment by jycor** [comment]
Hey @uroborosq, thanks for filing this issue!
The fix for this has been merged to Vitess and is making its way to Dolt main.
We can have a release with the fix out later this week!

**Comment by bpf120** [comment]
@uroborosq , we'd love to learn about your Dolt use case too. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

**Comment by uroborosq** [comment]
big thanks everyone for quick reaction, will be waiting for the fix become available!
