### ISSUE TITLE
Dolt allows changing primary key column order

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#872]
This should either be disallowed, or should rewrite all the rows in the table to match the new key column order.

**Comment by zachmu** [comment]
This happens via `ALTER TABLE` statements

**Comment by zachmu** [comment]
This needs to be accounted for in your work related to supporting primary key changes

**Comment by VinaiRachakonda** [comment]
We support the following operation by dropping a Primary Key and readding it with the new order.
