### ISSUE TITLE
Strange queryable diff behavior

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#881]
I took [this](https://www.dolthub.com/repositories/open-elections/voting-data) repo, which is fairly large, and ran the following query, plucking the `HEAD` of `master`:
```
$ dolt diff -q 'select state from national_voting_data'  oglus4uu3sk3nd4dbrh1u3821n68hunp oglus4uu3sk3nd4dbrh1u3821n68hunp
```

It's clearly a no-op but in fact it takes a rather long time to run (around 10 minutes). It appears that this corner case prompts some strange behavior under the hood.

**Comment by andrew-wm-arthur** [comment]
We're not very smart about using storage layer diffs at this point. The possibility is there, but it's not implemented

**Comment by zachmu** [comment]
Closing this for now, we don't have any immediate plans to make query diff faster in the way you need.
