### ISSUE TITLE
diff query returns error when nulls in column

### ISSUE THREAD

**Issue by s0rbus** [dolthub/dolt#882]
Working through the employees example under samples in the repo I got as far as adding start dates in a branch and running 'dolt diff' This presented a table showing the rows and the diffs in the 'start date' column. However trying the query option of diff, dolt diff -q 'select \`start date\` from employees' I get:

~~~~
No rows written, cannot write footer
column <start date> received nil but is non-nullable
~~~~

**Comment by zachmu** [comment]
Andy, can you look into why this is happening?

**Comment by andrew-wm-arthur** [comment]
After some deliberation, we decided to remove the `dolt diff -q` feature. It's implementation proved to be unmaintainable alongside our current sql server developement
