### ISSUE TITLE
push to google storage gives me a strange error 

### ISSUE THREAD

**Issue by zzztimbo** [dolthub/dolt#893]
What am I to make of this? 

```
➜  dolt push --set-upstream sesame_pricebooks_dolt_gs master
Counted chunks: 158110, Buffered chunks: 158110)

error: push failed
cause: manifest
```

**Comment by zachmu** [comment]
Brian, any ideas what the cause of the error is here?

**Comment by VinaiRachakonda** [comment]
Closing this for now. We've had people successfully push to gcs recently who have had no issues. There's been some good work on this done
