### ISSUE TITLE
Cannot create index on top of column with foreign key constraint

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#895]
From Balint:

dolt_migration> 
             -> 
             -> CREATE TABLE node_definition(
             ->   id VARCHAR(24) NOT NULL,
             -> 
             ->   node_type_id VARCHAR(24) NOT NULL,

(...)

             -> 
             ->   PRIMARY KEY (id),
             ->   FOREIGN KEY (node_type_id) REFERENCES node_type (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
             ->   FOREIGN KEY (gene_id) REFERENCES gene (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
             ->   FOREIGN KEY (node_mutation_annotation_id) REFERENCES node_mutation_annotation (id) ON UPDATE RESTRICT ON DELETE RESTRICT
             -> );
dolt_migration> CREATE UNIQUE INDEX unique_node_definition_turbine_node_name ON node_definition(turbine_node_name);
dolt_migration> CREATE UNIQUE INDEX unique_node_definition_enst ON node_definition(enst);
dolt_migration> 
             -> 

(...)

dolt_migration> 
             -> 
             -> CREATE TABLE readout_node(
             ->   id VARCHAR(24) NOT NULL,
             -> 
             ->   node_definition_id VARCHAR(24) NOT NULL,
             ->   readout_type VARCHAR(100) NOT NULL,
             -> 
             ->   PRIMARY KEY (id),
             ->   FOREIGN KEY (node_definition_id) REFERENCES node_definition (id) ON UPDATE RESTRICT ON DELETE RESTRICT
             -> );
dolt_migration> CREATE UNIQUE INDEX unique_readout_node_node_definition_id ON readout_node(node_definition_id);

cannot create a duplicate index on this table

It works in MySQL and does what we need. Some FK-s must be UNIQUE, some not. In Dolt we can not get the same result because of this error message.

**Comment by Hydrocharged** [comment]
Fixed in https://github.com/dolthub/dolt/pull/939
