### ISSUE TITLE
Automatically update winget and chocolatey versions of dolt on every release

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#936]
Dolt releases for windows are currently MSI. In addition, we should support other windows installation options:

* WinGet
* chocolatey
* scoop

**Comment by tiksn** [comment]
For [WinGet](https://github.com/microsoft/winget-cli) here is the [PR](https://github.com/microsoft/winget-pkgs/pull/7696) that adds dolt version 0.23.2

**Comment by zachmu** [comment]
We now support winget and chocolatey, but we need to automate releases to keep these package managers up to date, the way we do for homebrew.

**Comment by zachmu** [comment]
@coffeegoddd do you have an idea how much work it would be to update chocolatey at release time?

**Comment by zachmu** [comment]
Verification of project ownership for David Gardiner

**Comment by timsehn** [comment]
Looks like from the comments, this is resolved.
