### ISSUE TITLE
I dolt push but i can't see anything in the repo

### ISSUE THREAD

**Issue by Emekaborisama** [dolthub/dolt#940]
I did dolt push origin master to my repo but i can't see any data on my repo

**Comment by oscarbatori** [comment]
Can you provide a link to your repo?

**Comment by Emekaborisama** [comment]
https://www.dolthub.com/repositories/emekaboris/EndSars

**Comment by Emekaborisama** [comment]
Why can't i manually upload the dataset? @oscarbatori

**Comment by andrew-wm-arthur** [comment]
@Emekaborisama do you want to chat with us on our Discord server? I might be easier to solve your issue over chat
https://discord.com/invite/RFwfYpu

**Comment by timsehn** [comment]
Did you run `dolt login` to authenticate? Did you set your remote? What
does `dolt push` output?

**Comment by Emekaborisama** [comment]
Yes, i did

**Comment by zachmu** [comment]
For posterity, this was caused by the repo being empty -- needed to add tables to the repo before pushing.
