### ISSUE TITLE
[Windows] Files left open after clone

### ISSUE THREAD

**Issue by gigi81** [dolthub/dolt#943]
If I run this series of commands on windows

```bash
dolt clone gigi81/test-configuration
rmdir test-configuration /s /q
```

I get this error:
The process cannot access the file because it is being used by another process.

Seems like some files are left open by dolt after the clone command.

If I try the same thing in Linux, I cannot reproduce, so it seems to be Windows specific:
dolt clone gigi81/test-configuration &&  rm -r test-configuration

I'm using the latest release available dolt version 0.21.0

**Comment by zachmu** [comment]
Hi @gigi81,

We can't reproduce this, either with cmd.exe or with powershell. It shouldn't be possible -- the `dolt clone` process terminates when the `dolt clone` command finishes, so it can't have any open file handles.

Are you sure there isn't another process with these files open? An instance of explorer.exe examining that directory will prevent it from being deleted. Same is true if you have another instance of e.g. `dolt sql` running in that directory.

Zach

**Comment by gigi81** [comment]
I just tried again. I got a little bit more details this time...

```
Microsoft Windows [Version 10.0.19042.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\luigi>dolt clone gigi81/test-configuration
cloning https://doltremoteapi.dolthub.com/gigi81/test-configuration
30 of 30 chunks complete. 0 chunks being downloaded currently.

C:\Users\luigi>rmdir test-configuration /s /q
test-configuration\DOLT~1\noms\0eu14p8u8oj56ni62oec52ds366d4vs6 - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\1d9duh2k3h4qequh72v8qfthu67mg20v - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\2ihifvaigfp25j9usi50n0k5ja0mrra5 - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\62etkmk2ndpotearm90en568h56ag80e - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\k9agcjj1627ma4ljpo5584qvequ3rvcg - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\q08adih8nl073oifpj0kp6j8ekavrrpu - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\sb4og3mf6llcdod9q6c3ne2ue7sqh2ub - The process cannot access the file because it is being used by another process.
test-configuration\DOLT~1\noms\uj2qif9ggeghs3j2ueganorqaam1lek5 - The process cannot access the file because it is being used by another process.
The process cannot access the file because it is being used by another process.
```

If I wait a couple of seconds the rmdir command works fine. I don't have anything special running on the box...

Anyway, not a big deal.
