### ISSUE TITLE
Editing database in a separate process with server running causes weird ODBC connection error

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#964]
Repro steps:

1. Use Windows. Install: https://dev.mysql.com/downloads/connector/odbc/
2. Start a `dolt sql-server --loglevel trace` in a shell
3. In another shell, edit the dolt database (ie. add a table)
4. Attempt to connect to the database with MySQL ODBC driver (I did this using "Get Data" in Excel)
5. Database ODBC connection times out
6. Navigate to the running sql-server shell, no log messages
7. `Ctrl-C` in that shell. These errors appear:
```
INFO: NewConnection: client 7
ERROR: Cannot send HandshakeV10 packet to client 7 (127.0.0.1:57639): write tcp 127.0.0.1:3306->127.0.0.1:57639: wsasend: An established connection was aborted by the software in your host machine.
Write(header) failed
conn 7
```
8. Server is still running

**Comment by zachmu** [comment]
The version of ODBC used by excel seems to be doing something antatgonistic to dolt. I spent an afternoon looking into it and didn't find anything obvious that should make it so slow.
