### ISSUE TITLE
Dolt SQL select order is inconsistent on larger tables

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#984]
This is due the non-deterministic nature of the exchange nodes. While technically the order of a select without an `order by` clause is undefined, it would be better to return a consistent order for the same query executed repeatedly.

**Comment by timsehn** [comment]
Fixed for simple plans. Open a new issue with a specific repro.

**Comment by zachmu** [comment]
Now that we have the new storage format, parallel table scans are no faster than single-threaded and may in fact be slower. We should address this.

Working on a simple repro.

**Comment by zachmu** [comment]
Clone this database:

`dolt clone zachmu/tablescan_order`

Then run this command over and over, get different output:

```bash
% dolt sql -q "select * from t1 limit 100"
```

**Comment by andy-wm-arthur** [comment]
#5396 fixes this for databases with format `__DOLT__` by turning off query parallelism for scans
