### ISSUE TITLE
Excel Query Broken

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#991]
# Reproduction steps stolen from Docs

The first thing you have to do is start a Dolt SQL Server. To do this navigate to the Dolt repository directory you want to read from and run `dolt sql-server`. This command starts a MySQL compatible server on port 3306 with a user named `root`. It exposes a database named after the Dolt repository directory with dashes (`-`) changed to underscores (`_`). Thus, `dolt-test` directory name becomes `dolt_test` database name. For the purposes of this example I am running a database named `dolt_test` with user `dolt`.

Now you must install the [MySQL ODBC Connector](https://dev.mysql.com/downloads/connector/odbc/) on your computer. Downloading the appropriate one and running it opens a standard Windows Installer. Once complete, navigate to `Control Panel` > `Administrative Tools` > `ODBC Data Sources` or just search for `ODBC Data Sources`. You'll be greeted by this window:

![odbc-data-sources](https://user-images.githubusercontent.com/5376236/98180437-bb95c280-1eb5-11eb-9491-40f470a93536.png)

Click `Add...` and you should see `MySQL ODBC 8.0 ANSI Driver` and `MySQL ODBC 8.0 Unicode Driver`, select the `MySQL ODBC 8.0 Unicode Driver` and click `Finish`. Now you need to enter your connection information. We call the data source Dolt Test, leave the server on TCP and enter `localhost` as the server name, enter the user `dolt`, and the database as `dolt_test`. After entering that information, clicking `Test` should result in a `Connection Successful` dialog. Click `OK` and the new Dolt Test ODBC connector will appear in the list.

![mysql-odbc-config](https://user-images.githubusercontent.com/5376236/98180425-b2a4f100-1eb5-11eb-8a24-35ed955868ff.png)

Now it's time to read the data into Excel over that connection. Go back to Excel and navigate to `Data` > `Get Data` > `From Other Sources` > `From ODBC`. Pick `Dolt Test` from the drop down and click `OK`. This will bring up the following preview screen where you can navigate to and pick the table you want to import. The test table is in the `dolt_test` database. Clicking load will load the data into the selected sheet.

![excel-get-data-odbc](https://user-images.githubusercontent.com/5376236/98180415-ad47a680-1eb5-11eb-9ca2-f78ce48f2426.png)

If you want to return the results of a query instead of a whole table, navigate to `Data` > `Get Data` > `From Other Sources` > `From ODBC`. Pick `Dolt Test` from the drop down and click `Advanced` instead of `OK`. Enter the SQL query you would like to run in the text box. I used `select * from test where pk=1`.

The results preview loads correctly but when you get `Load`, it spins for a while and you get the following on the client and server.

This breaks right now with a weird handshake error.

```
INFO: NewConnection: client 4
ERROR: Cannot send HandshakeV10 packet to client 4 (127.0.0.1:52444): write tcp 127.0.0.1:3306->127.0.0.1:52444: wsasend: An established connection was aborted by the software in your host machine.
Write(packet) failed
conn 4
INFO: ConnectionClosed: client 4
```

Client side sees this:

![](https://cdn.discordapp.com/attachments/746418211184050346/773692085001650206/unknown.png)

**Comment by timsehn** [comment]
Tried:

1. 32-bit vs 64-bit ODBC - Same behavior
2. ANSI vs UNICODE MySQL connector - Same behavior
3. Excel version: Version 2010 13328.20292

**Comment by timsehn** [comment]
This is the set up for Dolt:
```
PS C:\Users\timse\dolthub\dolt> cd .\excelbug\
PS C:\Users\timse\dolthub\dolt\excelbug> dolt init
Successfully initialized dolt data repository.
PS C:\Users\timse\dolthub\dolt\excelbug> dolt sql -q "create table excel (pk int, c1 int, primary key(pk))"
PS C:\Users\timse\dolthub\dolt\excelbug> dolt sql -q "insert into excel values (0,0), (1,1), (2,2)"
Query OK, 3 rows affected
PS C:\Users\timse\dolthub\dolt\excelbug> dolt sql-server -loglevel trace
Starting server with Config HP="localhost:3306"|U="root"|P=""|T="30000"|R="false"|L="trace"
```

**Comment by timsehn** [comment]
Port 3306 vs 3307. Same behavior.

**Comment by timsehn** [comment]
Andy has it working no issue on his machine 32bit ANSI MySQL connector

**Comment by timsehn** [comment]
@zachmu reproduced as well

**Comment by andrew-wm-arthur** [comment]
Standard workflow is working for me all the way through loading to a spreadsheet. 

Using the advanced options and providing the optional SQL statement works through the preview menu, but fails after clicking the "load" button:
`[DataFormat.Error] We cannot return the data produced by this query because of its complexity`

**Comment by zachmu** [comment]
Duplicate: https://github.com/dolthub/dolt/issues/964
